//------------------------------------------------------------------------------
// The confidential and proprietary information contained in this file may
// only be used by a person authorised under and to the extent permitted
// by a subsisting licensing agreement from Arm Limited or its affiliates.
//
//            (C) COPYRIGHT 2019-2021 Arm Limited or its affiliates.
//                ALL RIGHTS RESERVED
//
// This entire notice must be reproduced on all copies of this file
// and copies of this file may only be made by a person if such person is
// permitted to do so under the terms of a subsisting license agreement
// from Arm Limited or its affiliates.
//
//
//      Release Information : SSE710-r0p0-00eac0
//
//------------------------------------------------------------------------------
// Verilog-2001 (IEEE Std 1364-2001)
//------------------------------------------------------------------------------

`undef RS_REGD
`undef RS_FWD_REG
`undef RS_REV_REG
`undef RS_STATIC_BYPASS


`undef AWFIFO_BYPASS
`undef AWFIFO_SIZE
`undef AWFIFO_ADDR
`undef AWFIFO_MASK
`undef AWFIFO_WRAP_FITS


`undef ARDATA_SIZE
`undef ARDATA_BYPASS
`undef ARDATA_ADDR
`undef ARDATA_MASK
`undef ARDATA_END
`undef ARDATA_ID
`undef ARDATA_TWO
`undef ARDATA_WRAP_FITS


  
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_0_0
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_0_1
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_0_2
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_0_3
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_0_4
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_0_5
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_0_6
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_0_7
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_0_8
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_0_9
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_0_10
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_0_11
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_1_0
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_1_1
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_1_2
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_1_3
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_1_4
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_1_5
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_1_6
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_1_7
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_1_8
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_1_9
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_1_10
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_1_11
`undef NIC400_IB_HOSTCPU_AXIS_IB_AW_FIFO_x_x



  
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_0_0
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_0_1
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_0_2
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_0_3
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_0_4
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_0_5
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_0_6
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_0_7
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_0_8
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_0_9
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_0_10
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_0_11
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_1_0
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_1_1
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_1_2
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_1_3
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_1_4
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_1_5
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_1_6
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_1_7
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_1_8
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_1_9
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_1_10
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_1_11
`undef NIC400_IB_HOSTCPU_AXIS_IB_AR_FIFO_x_x



  
`undef NIC400_IB_HOSTCPU_AXIS_IB_R_FIFO_0_0
`undef NIC400_IB_HOSTCPU_AXIS_IB_R_FIFO_0_1
`undef NIC400_IB_HOSTCPU_AXIS_IB_R_FIFO_0_2
`undef NIC400_IB_HOSTCPU_AXIS_IB_R_FIFO_0_3
`undef NIC400_IB_HOSTCPU_AXIS_IB_R_FIFO_1_0
`undef NIC400_IB_HOSTCPU_AXIS_IB_R_FIFO_1_1
`undef NIC400_IB_HOSTCPU_AXIS_IB_R_FIFO_1_2
`undef NIC400_IB_HOSTCPU_AXIS_IB_R_FIFO_1_3
`undef NIC400_IB_HOSTCPU_AXIS_IB_R_FIFO_x_x



  
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_0_0
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_0_1
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_0_2
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_0_3
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_0_4
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_0_5
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_0_6
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_0_7
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_0_8
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_0_9
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_0_10
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_0_11
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_1_0
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_1_1
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_1_2
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_1_3
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_1_4
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_1_5
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_1_6
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_1_7
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_1_8
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_1_9
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_1_10
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_1_11
`undef NIC400_IB_HOSTCPU_AXIS_IB_W_FIFO_x_x



  
`undef NIC400_IB_HOSTCPU_AXIS_IB_B_FIFO_0_0
`undef NIC400_IB_HOSTCPU_AXIS_IB_B_FIFO_0_1
`undef NIC400_IB_HOSTCPU_AXIS_IB_B_FIFO_0_2
`undef NIC400_IB_HOSTCPU_AXIS_IB_B_FIFO_0_3
`undef NIC400_IB_HOSTCPU_AXIS_IB_B_FIFO_1_0
`undef NIC400_IB_HOSTCPU_AXIS_IB_B_FIFO_1_1
`undef NIC400_IB_HOSTCPU_AXIS_IB_B_FIFO_1_2
`undef NIC400_IB_HOSTCPU_AXIS_IB_B_FIFO_1_3
`undef NIC400_IB_HOSTCPU_AXIS_IB_B_FIFO_x_x





