//-----------------------------------------------------------------------------
// The confidential and proprietary information contained in this file may
// only be used by a person authorised under and to the extent permitted
// by a subsisting licensing agreement from ARM Limited.
//
//            (C) COPYRIGHT 2012-2015 ARM Limited.
//                ALL RIGHTS RESERVED
//
// This entire notice must be reproduced on all copies of this file
// and copies of this file may only be made by a person if such person is
// permitted to do so under the terms of a subsisting license agreement
// from ARM Limited.
//
//      SVN Information
//
//      Checked In          : $Date: 2014-07-02 16:52:21 +0100 (Wed, 02 Jul 2014) $
//
//      Revision            : $Revision: 283836 $
//
//      Release Information : CORTEXA53-r0p4-51rel0
//
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Description: Top level of the CortexA53 L2 memory system (with RAMs)
//-----------------------------------------------------------------------------

`include "ca53scu_defs.v"
`include "ca53_ace_defs.v"
`include "cortexa53params.v"

module ca53_l2 `CA53_L2_PARAM_DECL (
  // Inputs
  input  wire                                   CLKIN,
  input  wire                                   DFTSE,
  input  wire                                   DFTRSTDISABLE,
  input  wire                                   DFTRAMHOLD,
  input  wire                                   DFTMCPHOLD,
  input  wire [NUM_CPUS-1:0]                    ncpuporeset,
  input  wire [NUM_CPUS-1:0]                    ncorereset,
  input  wire                                   nl2reset,
  input  wire                                   nmbistreset,
  input  wire                                   l2rstdisable_i,
  input  wire [NUM_CPUS-1:0]                    cfgend_i,
  input  wire [NUM_CPUS-1:0]                    vinithi_i,
  input  wire [NUM_CPUS-1:0]                    cfgte_i,
  input  wire [NUM_CPUS-1:0]                    cp15sdisable_i,
  input  wire [  7:0]                           clusteridaff1_i,
  input  wire [  7:0]                           clusteridaff2_i,
  input  wire [NUM_CPUS-1:0]                    etm_oslock_i,
  input  wire [NUM_CPUS-1:0]                    aa64naa32_i,
  input  wire [(`CA53_RVBARADDR_PKDED_W-1):0]   rvbaraddr_i,
  input  wire [NUM_CPUS-1:0]                    cryptodisable_i,
  input  wire [NUM_CPUS-1:0]                    nfiq_i,
  input  wire [NUM_CPUS-1:0]                    nirq_i,
  input  wire [NUM_CPUS-1:0]                    nsei_i,
  input  wire [NUM_CPUS-1:0]                    nrei_i,
  input  wire [NUM_CPUS-1:0]                    nvfiq_i,
  input  wire [NUM_CPUS-1:0]                    nvirq_i,
  input  wire [NUM_CPUS-1:0]                    nvsei_i,
  input  wire [ 39:18]                          periphbase_i,
  input  wire                                   giccdisable_i,
  input  wire                                   icdtvalid_i,
  input  wire [ 15:0]                           icdtdata_i,
  input  wire                                   icdtlast_i,
  input  wire [  1:0]                           icdtdest_i,
  input  wire                                   icctready_i,
  input  wire [ 63:0]                           cntvalueb_i,
  input  wire                                   cntclken_i,
  input  wire [ 63:0]                           tsvalueb_i,
  input  wire                                   clrexmonreq_i,
  input  wire                                   eventi_i,
  input  wire                                   l2flushreq_i,
  input  wire [NUM_CPUS-1:0]                    cpuqreqn_i,
  input  wire [NUM_CPUS-1:0]                    neonqreqn_i,
  input  wire                                   l2qreqn_i,
  input  wire                                   broadcastcachemaint_i,
  input  wire                                   broadcastinner_i,
  input  wire                                   broadcastouter_i,
  input  wire                                   aclkenm_i,
  input  wire                                   acinactm_i,
  input  wire                                   sysbardisable_i,
  input  wire                                   awreadym_i,
  input  wire                                   wreadym_i,
  input  wire                                   bvalidm_i,
  input  wire [`CA53_SCU_EXT_WID_W-1:0]         bidm_i,
  input  wire [`CA53_ACE_BRESP_W-1:0]           brespm_i,
  input  wire                                   arreadym_i,
  input  wire                                   rvalidm_i,
  input  wire [`CA53_SCU_EXT_RID_W-1:0]         ridm_i,
  input  wire [`CA53_SCU_EXT_DATA_W-1:0]        rdatam_i,
  input  wire [`CA53_ACE_RRESP_W-1:0]           rrespm_i,
  input  wire                                   rlastm_i,
  input  wire                                   acvalidm_i,
  input  wire [`CA53_SCU_EXT_ADDR_W-1:0]        acaddrm_i,
  input  wire [`CA53_ACE_ACPROT_W-1:0]          acprotm_i,
  input  wire [`CA53_ACE_ACSNOOP_W-1:0]         acsnoopm_i,
  input  wire                                   crreadym_i,
  input  wire                                   cdreadym_i,
  input  wire                                   sclken_i,
  input  wire                                   sinact_i,
  input  wire [6:0]                             nodeid_i,
  input  wire                                   rxsactive_i,
  input  wire                                   rxlinkactivereq_i,
  input  wire                                   txlinkactiveack_i,
  input  wire                                   txreqlcrdv_i,
  input  wire                                   txrsplcrdv_i,
  input  wire                                   txdatlcrdv_i,
  input  wire                                   rxsnpflitpend_i,
  input  wire                                   rxsnpflitv_i,
  input  wire [64:0]                            rxsnpflit_i,
  input  wire                                   rxrspflitpend_i,
  input  wire                                   rxrspflitv_i,
  input  wire [44:0]                            rxrspflit_i,
  input  wire                                   rxdatflitpend_i,
  input  wire                                   rxdatflitv_i,
  input  wire [193:0]                           rxdatflit_i,
  input  wire [1:0]                             samaddrmap0_i,
  input  wire [1:0]                             samaddrmap1_i,
  input  wire [1:0]                             samaddrmap2_i,
  input  wire [1:0]                             samaddrmap3_i,
  input  wire [1:0]                             samaddrmap4_i,
  input  wire [1:0]                             samaddrmap5_i,
  input  wire [1:0]                             samaddrmap6_i,
  input  wire [1:0]                             samaddrmap7_i,
  input  wire [1:0]                             samaddrmap8_i,
  input  wire [1:0]                             samaddrmap9_i,
  input  wire [1:0]                             samaddrmap10_i,
  input  wire [1:0]                             samaddrmap11_i,
  input  wire [1:0]                             samaddrmap12_i,
  input  wire [1:0]                             samaddrmap13_i,
  input  wire [1:0]                             samaddrmap14_i,
  input  wire [1:0]                             samaddrmap15_i,
  input  wire [39:24]                           sammnbase_i,
  input  wire [6:0]                             sammnnodeid_i,
  input  wire [6:0]                             samhni0nodeid_i,
  input  wire [6:0]                             samhni1nodeid_i,
  input  wire [6:0]                             samhnf0nodeid_i,
  input  wire [6:0]                             samhnf1nodeid_i,
  input  wire [6:0]                             samhnf2nodeid_i,
  input  wire [6:0]                             samhnf3nodeid_i,
  input  wire [6:0]                             samhnf4nodeid_i,
  input  wire [6:0]                             samhnf5nodeid_i,
  input  wire [6:0]                             samhnf6nodeid_i,
  input  wire [6:0]                             samhnf7nodeid_i,
  input  wire [2:0]                             samhnfmode_i,
  input  wire                                   aclkens_i,
  input  wire                                   ainacts_i,
  input  wire                                   awvalids_i,
  input  wire [  4:0]                           awids_i,
  input  wire [ 39:0]                           awaddrs_i,
  input  wire [  7:0]                           awlens_i,
  input  wire [  3:0]                           awcaches_i,
  input  wire [  1:0]                           awusers_i,
  input  wire [  2:0]                           awprots_i,
  input  wire                                   wvalids_i,
  input  wire [127:0]                           wdatas_i,
  input  wire [ 15:0]                           wstrbs_i,
  input  wire                                   wlasts_i,
  input  wire                                   breadys_i,
  input  wire                                   arvalids_i,
  input  wire [  4:0]                           arids_i,
  input  wire [ 39:0]                           araddrs_i,
  input  wire [  7:0]                           arlens_i,
  input  wire [  3:0]                           arcaches_i,
  input  wire [  1:0]                           arusers_i,
  input  wire [  2:0]                           arprots_i,
  input  wire                                   rreadys_i,
  input  wire                                   npresetdbg_i,
  input  wire                                   pclkendbg_i,
  input  wire                                   pseldbg_i,
  input  wire [ 21: 2]                          paddrdbg_i,
  input  wire                                   paddrdbg31_i,
  input  wire                                   penabledbg_i,
  input  wire                                   pwritedbg_i,
  input  wire [ 31:0]                           pwdatadbg_i,
  input  wire [(`CA53_PRDATADBG_PKDED_W-1):0]   dpu_prdatadbg_i,
  input  wire [NUM_CPUS-1: 0]                   dpu_preadydbg_i,
  input  wire [NUM_CPUS-1: 0]                   dpu_pslverrdbg_i,
  input  wire [(`CA53_PRDATADBG_PKDED_W-1):0]   etm_prdatadbg_i,
  input  wire [NUM_CPUS-1: 0]                   etm_preadydbg_i,
  input  wire [(`CA53_ETMEXT_PKDED_W-1):0]      etm_extout_i,
  input  wire [NUM_CPUS-1: 0]                   dcu_excl_mon_cleared_i,
  input  wire [(`CA53_CPADDR_PKDED_W-1):0]      dcu_cp_gov_addr_i,
  input  wire [NUM_CPUS-1: 0]                   dcu_cp_gov_ns_i,
  input  wire [NUM_CPUS-1: 0]                   dcu_cp_gov_req_i,
  input  wire [(`CA53_CPSEL_PKDED_W-1):0]       dcu_cp_gov_sel_i,
  input  wire [(`CA53_CPDATA_PKDED_W-1):0]      dcu_cp_gov_wdata_i,
  input  wire [NUM_CPUS-1: 0]                   dcu_cp_gov_wenable_i,
  input  wire [ 39:12]                          dbgromaddr_i,
  input  wire                                   dbgromaddrv_i,
  input  wire [NUM_CPUS-1:0]                    edbgrq_i,
  input  wire [NUM_CPUS-1:0]                    dbgen_i,
  input  wire [NUM_CPUS-1:0]                    spiden_i,
  input  wire [NUM_CPUS-1:0]                    niden_i,
  input  wire [NUM_CPUS-1:0]                    spniden_i,
  input  wire [NUM_CPUS-1:0]                    dbgpwrdup_i,
  input  wire                                   dbgl1rstdisable_i,
  input  wire                                   atclken_i,
  input  wire [(`CA53_ATREADYM_PKDED_W-1):0]    atreadym_i,
  input  wire [(`CA53_AFVALIDM_PKDED_W-1):0]    afvalidm_i,
  input  wire [(`CA53_ATDATAM_PKDED_W-1):0]     etm_atdatam_i,
  input  wire [(`CA53_ATVALIDM_PKDED_W-1):0]    etm_atvalidm_i,
  input  wire [(`CA53_ATBYTESM_PKDED_W-1):0]    etm_atbytesm_i,
  input  wire [(`CA53_AFREADYM_PKDED_W-1):0]    etm_afreadym_i,
  input  wire [(`CA53_ATIDM_PKDED_W-1):0]       etm_atidm_i,
  input  wire [(`CA53_SYNCREQM_PKDED_W-1):0]    syncreqm_i,
  input  wire [3:0]                             ctichin_i,
  input  wire [3:0]                             ctichoutack_i,
  input  wire [NUM_CPUS-1:0]                    ctiirqack_i,
  input  wire                                   cisbypass_i,
  input  wire [3:0]                             cihsbypass_i,
  input  wire [NUM_CPUS-1:0]                    dpu_warmrstreq_i,
  input  wire [NUM_CPUS-1:0]                    dpu_dbgtrigger_i,
  input  wire [NUM_CPUS-1:0]                    dpu_dbgack_i,
  input  wire [NUM_CPUS-1:0]                    dpu_commrx_i,
  input  wire [NUM_CPUS-1:0]                    dpu_commtx_i,
  input  wire [NUM_CPUS-1:0]                    dpu_ncommirq_i,
  input  wire [NUM_CPUS-1:0]                    dpu_dbgrstreq_i,
  input  wire [NUM_CPUS-1:0]                    dpu_dbgnopwrdwn_i,
  input  wire [NUM_CPUS-1:0]                    dpu_clr_event_register_i,
  input  wire [(`CA53_EXCP_LEV_PKDED_W-1):0]    dpu_exception_level_i,
  input  wire [NUM_CPUS-1:0]                    dpu_aarch64_at_el3_i,
  input  wire [NUM_CPUS-1:0]                    dpu_dscr_halted_i,
  input  wire [NUM_CPUS-1:0]                    dpu_hcr_el2_fmo_i,
  input  wire [NUM_CPUS-1:0]                    dpu_hcr_el2_imo_i,
  input  wire [NUM_CPUS-1:0]                    dpu_hcr_el2_amo_i,
  input  wire [NUM_CPUS-1:0]                    dpu_monitor_mode_i,
  input  wire [NUM_CPUS-1:0]                    dpu_rei_level_ack_i,
  input  wire [NUM_CPUS-1:0]                    dpu_scr_el3_fiq_i,
  input  wire [NUM_CPUS-1:0]                    dpu_scr_el3_irq_i,
  input  wire [NUM_CPUS-1:0]                    dpu_scr_el3_ns_i,
  input  wire [NUM_CPUS-1:0]                    dpu_sei_level_ack_i,
  input  wire [NUM_CPUS-1:0]                    dpu_vsei_level_ack_i,
  input  wire [NUM_CPUS-1:0]                    dpu_wfi_req_i,
  input  wire [NUM_CPUS-1:0]                    dpu_wfe_req_i,
  input  wire [NUM_CPUS-1:0]                    dpu_irq_pended_i,
  input  wire [NUM_CPUS-1:0]                    dpu_fiq_pended_i,
  input  wire [NUM_CPUS-1:0]                    dpu_sei_pended_i,
  input  wire [NUM_CPUS-1:0]                    dpu_irq_masked_i,
  input  wire [NUM_CPUS-1:0]                    dpu_fiq_masked_i,
  input  wire [NUM_CPUS-1:0]                    dpu_sei_masked_i,
  input  wire [NUM_CPUS-1:0]                    dpu_virq_pended_i,
  input  wire [NUM_CPUS-1:0]                    dpu_vfiq_pended_i,
  input  wire [NUM_CPUS-1:0]                    dpu_vsei_pended_i,
  input  wire [NUM_CPUS-1:0]                    dpu_virq_masked_i,
  input  wire [NUM_CPUS-1:0]                    dpu_vfiq_masked_i,
  input  wire [NUM_CPUS-1:0]                    dpu_vsei_masked_i,
  input  wire [NUM_CPUS-1:0]                    dpu_dbg_double_lock_set_i,
  input  wire [NUM_CPUS-1:0]                    dpu_ns_state_i,
  input  wire [NUM_CPUS-1:0]                    stb_wfx_ready_i,
  input  wire [NUM_CPUS-1:0]                    biu_wfx_ready_i,
  input  wire [NUM_CPUS-1:0]                    dcu_wfx_ready_i,
  input  wire [NUM_CPUS-1:0]                    ifu_wfx_ready_i,
  input  wire [NUM_CPUS-1:0]                    tlb_wfx_ready_i,
  input  wire [NUM_CPUS-1:0]                    etm_wfx_ready_i,
  input  wire [NUM_CPUS-1:0]                    dpu_imp_abort_pending_i,
  input  wire [(`CA53_RET_CTL_PKDED_W-1):0]     dpu_cpuectlr_cpu_ret_delay_i,
  input  wire [(`CA53_RET_CTL_PKDED_W-1):0]     dpu_cpuectlr_neon_ret_delay_i,
  input  wire [NUM_CPUS-1: 0]                   dpu_neon_active_i,
  input  wire [NUM_CPUS-1:0]                    dpu_npmuirq_i,
  input  wire [(`CA53_PMUEVNT_CPU_PKDED_W-1):0] dpu_pmuevent_i,
  input  wire [NUM_CPUS-1:0]                    dpu_smp_en_i,
  input  wire [NUM_CPUS-1:0]                    dpu_sev_req_i,
  input  wire [(`CA53_ARACTIVE_PKDED_W-1):0]    biu_ar_active_i,
  input  wire [(`CA53_ARVALID_PKDED_W-1):0]     biu_ar_valid_i,
  input  wire [(`CA53_ARID_PKDED_W-1):0]        biu_ar_id_i,
  input  wire [(`CA53_ARTYPE_PKDED_W-1):0]      biu_ar_type_i,
  input  wire [(`CA53_ARATTRS_PKDED_W-1):0]     biu_ar_attrs_i,
  input  wire [(`CA53_ARWAY_PKDED_W-1):0]       biu_ar_way_i,
  input  wire [(`CA53_ARADDR_PKDED_W-1):0]      biu_ar_addr_i,
  input  wire [(`CA53_ARLEN_PKDED_W-1):0]       biu_ar_len_i,
  input  wire [(`CA53_ARSIZE_PKDED_W-1):0]      biu_ar_size_i,
  input  wire [(`CA53_ARLOCK_PKDED_W-1):0]      biu_ar_lock_i,
  input  wire [(`CA53_ARPRIV_PKDED_W-1):0]      biu_ar_priv_i,
  input  wire [(`CA53_DRCREDIT_PKDED_W-1):0]    biu_dr_credit_i,
  input  wire [(`CA53_DWVALID_PKDED_W-1):0]     biu_dw_valid_i,
  input  wire [(`CA53_DWL2DB_PKDED_W-1):0]      biu_dw_l2db_id_i,
  input  wire [(`CA53_DWCHUNKS_PKDED_W-1):0]    biu_dw_chunks_valid_i,
  input  wire [(`CA53_DWLAST_PKDED_W-1):0]      biu_dw_last_i,
  input  wire [(`CA53_DWSTRB_PKDED_W-1):0]      biu_dw_strb_i,
  input  wire [(`CA53_DWDATA_PKDED_W-1):0]      biu_dw_data_i,
  input  wire [(`CA53_DWERR_PKDED_W-1):0]       biu_dw_err_i,
  input  wire [(`CA53_DWFATAL_PKDED_W-1):0]     biu_dw_fatal_i,
  input  wire [(`CA53_ACREADY_PKDED_W-1):0]     dcu_ac_ready_i,
  input  wire [(`CA53_CRVALID_PKDED_W-1):0]     dcu_cr_valid_i,
  input  wire [(`CA53_CRID_PKDED_W-1):0]        dcu_cr_id_i,
  input  wire [(`CA53_CRDIRTY_PKDED_W-1):0]     dcu_cr_dirty_i,
  input  wire [(`CA53_CRAGE_PKDED_W-1):0]       dcu_cr_age_i,
  input  wire [(`CA53_CRALLOC_PKDED_W-1):0]     dcu_cr_alloc_i,
  input  wire [(`CA53_CRMIG_PKDED_W-1):0]       dcu_cr_migratory_i,
  input  wire [(`CA53_DVM_COMP_PKDED_W-1):0]    dcu_dvm_complete_i,
  input  wire                                   mbistreq_i,
  input  wire [(`CA53_MBIST0_ADDR_W-1): 0]      mbistaddr0_i,
  input  wire [(`CA53_MBIST1_ADDR_W-1): 0]      mbistaddr1_i,
  input  wire [(`CA53_MBIST0_DATA_W-1): 0]      mbistindata0_i,
  input  wire [(`CA53_MBIST1_DATA_W-1): 0]      mbistindata1_i,
  input  wire                                   mbistwriteen0_i,
  input  wire                                   mbistwriteen1_i,
  input  wire                                   mbistreaden0_i,
  input  wire                                   mbistreaden1_i,
  input  wire [(`CA53_MBIST0_RAMARRAY_W-1):0]   mbistarray0_i,
  input  wire [(`CA53_MBIST1_RAMARRAY_W-1):0]   mbistarray1_i,
  input  wire [(`CA53_MBIST0_BE_W-1):0]         mbistbe0_i,
  input  wire [(`CA53_MBIST1_BE_W-1):0]         mbistbe1_i,
  input  wire                                   mbistcfg0_i,
  input  wire                                   mbistcfg1_i,
  input  wire [(`CA53_L1DC_SIZE_W-1):0]         l1_dc_size_i,
  // Outputs
  output wire [NUM_CPUS-1:0]                    clk_cpu,
  output wire [NUM_CPUS-1:0]                    reset_n_cpu,
  output wire [NUM_CPUS-1:0]                    po_reset_n_cpu,
  output wire [NUM_CPUS-1:0]                    warmrstreq_o,
  output wire [NUM_CPUS-1:0]                    gov_cfgend_o,
  output wire [NUM_CPUS-1:0]                    gov_vinithi_o,
  output wire [NUM_CPUS-1:0]                    gov_cfgte_o,
  output wire [NUM_CPUS-1:0]                    gov_cp15sdisable_o,
  output wire [  7:0]                           gov_clusteridaff1_o,
  output wire [  7:0]                           gov_clusteridaff2_o,
  output wire [NUM_CPUS-1:0]                    gov_aa64naa32_o,
  output wire [(`CA53_RVBARADDR_PKDED_W-1):0]   gov_rvbaraddr_o,
  output wire [NUM_CPUS-1:0]                    gov_cryptodisable_o,
  output wire [NUM_CPUS-1:0]                    gov_stall_neon_o,
  output wire [NUM_CPUS-1:0]                    gic_irq_o,
  output wire [NUM_CPUS-1:0]                    gic_fiq_o,
  output wire [NUM_CPUS-1:0]                    gic_virq_o,
  output wire [NUM_CPUS-1:0]                    gic_vfiq_o,
  output wire [NUM_CPUS-1:0]                    gov_sei_level_req_o,
  output wire [NUM_CPUS-1:0]                    gov_vsei_level_req_o,
  output wire [NUM_CPUS-1:0]                    gov_rei_level_req_o,
  output wire [NUM_CPUS-1:0]                    gov_int_active_o,
  output wire [NUM_CPUS-1: 0]                   gic_icc_sre_el1_ns_sre_o,
  output wire [NUM_CPUS-1: 0]                   gic_icc_sre_el1_s_sre_o,
  output wire [NUM_CPUS-1: 0]                   gic_icc_sre_el2_enable_o,
  output wire [NUM_CPUS-1: 0]                   gic_icc_sre_el2_sre_o,
  output wire [NUM_CPUS-1: 0]                   gic_icc_sre_el3_enable_o,
  output wire [NUM_CPUS-1: 0]                   gic_icc_sre_el3_sre_o,
  output wire [NUM_CPUS-1: 0]                   gic_ich_hcr_el2_tall0_o,
  output wire [NUM_CPUS-1: 0]                   gic_ich_hcr_el2_tall1_o,
  output wire [NUM_CPUS-1: 0]                   gic_ich_hcr_el2_tc_o,
  output wire [NUM_CPUS-1:0]                    nvcpumntirq_o,
  output wire [ 39:18]                          gov_periphbase_o,
  output wire                                   gov_giccdisable_o,
  output wire                                   icdtready_o,
  output wire                                   icctvalid_o,
  output wire [ 15:0]                           icctdata_o,
  output wire                                   icctlast_o,
  output wire [  1:0]                           icctid_o,
  output wire [NUM_CPUS-1:0]                    gov_standbywfi_o,
  output wire [NUM_CPUS-1:0]                    gov_standbywfe_o,
  output wire [NUM_CPUS-1:0]                    standbywfi_o,
  output wire [NUM_CPUS-1:0]                    standbywfe_o,
  output wire                                   standbywfil2_o,
  output wire [NUM_CPUS-1:0]                    gov_wfx_drain_req_o,
  output wire [NUM_CPUS-1:0]                    gov_wfx_wake_o,
  output wire                                   clrexmonack_o,
  output wire                                   evento_o,
  output wire [NUM_CPUS-1:0]                    gov_mbistreq_cpu_o,
  output wire [NUM_CPUS-1:0]                    gov_event_reg_o,
  output wire [NUM_CPUS-1:0]                    ncntpsirq_o,
  output wire [NUM_CPUS-1:0]                    ncntpnsirq_o,
  output wire [NUM_CPUS-1:0]                    ncnthpirq_o,
  output wire [NUM_CPUS-1:0]                    ncntvirq_o,
  output wire [NUM_CPUS-1:0]                    gov_smpen_o,
  output wire [NUM_CPUS-1:0]                    cpuqactive_o,
  output wire [NUM_CPUS-1:0]                    cpuqdeny_o,
  output wire [NUM_CPUS-1:0]                    cpuqacceptn_o,
  output wire [NUM_CPUS-1:0]                    neonqactive_o,
  output wire [NUM_CPUS-1:0]                    neonqdeny_o,
  output wire [NUM_CPUS-1:0]                    neonqacceptn_o,
  output wire                                   l2qactive_o,
  output wire                                   l2qdeny_o,
  output wire                                   l2qacceptn_o,
  output wire                                   l2flushdone_o,
  output wire                                   nexterrirq_o,
  output wire                                   ninterrirq_o,
  output wire [NUM_CPUS-1:0]                    scu_broadcastinner_o,
  output wire                                   scu_ext_ar_valid_o,
  output wire [(`CA53_SCU_EXT_ADDR_W-1):0]      scu_ext_ar_addr_o,
  output wire [(`CA53_ACE_ARLEN_W-1):0]         scu_ext_ar_len_o,
  output wire [(`CA53_ACE_ARSIZE_W-1):0]        scu_ext_ar_size_o,
  output wire [(`CA53_ACE_ARBURST_W-1):0]       scu_ext_ar_burst_o,
  output wire                                   scu_ext_ar_lock_o,
  output wire [(`CA53_ACE_ARCACHE_W-1):0]       scu_ext_ar_cache_o,
  output wire [(`CA53_ACE_ARPROT_W-1):0]        scu_ext_ar_prot_o,
  output wire [(`CA53_ACE_ARDOMAIN_W-1):0]      scu_ext_ar_domain_o,
  output wire [(`CA53_ACE_ARSNOOP_W-1):0]       scu_ext_ar_snoop_o,
  output wire [(`CA53_ACE_ARBAR_W-1):0]         scu_ext_ar_bar_o,
  output wire [(`CA53_SCU_EXT_RID_W-1):0]       scu_ext_ar_id_o,
  output wire [7:0]                             scu_ext_rdmemattr_o,
  output wire                                   scu_ext_dr_ready_o,
  output wire                                   scu_ext_aw_valid_o,
  output wire [(`CA53_SCU_EXT_ADDR_W-1):0]      scu_ext_aw_addr_o,
  output wire [(`CA53_ACE_AWLEN_W-1):0]         scu_ext_aw_len_o,
  output wire [(`CA53_ACE_AWSIZE_W-1):0]        scu_ext_aw_size_o,
  output wire [(`CA53_ACE_AWBURST_W-1):0]       scu_ext_aw_burst_o,
  output wire                                   scu_ext_aw_lock_o,
  output wire [(`CA53_ACE_AWCACHE_W-1):0]       scu_ext_aw_cache_o,
  output wire [(`CA53_ACE_AWPROT_W-1):0]        scu_ext_aw_prot_o,
  output wire [(`CA53_SCU_EXT_WID_W-1):0]       scu_ext_aw_id_o,
  output wire [(`CA53_ACE_AWDOMAIN_W-1):0]      scu_ext_aw_domain_o,
  output wire [(`CA53_ACE_AWSNOOP_W-1):0]       scu_ext_aw_snoop_o,
  output wire [(`CA53_ACE_AWBAR_W-1):0]         scu_ext_aw_bar_o,
  output wire                                   scu_ext_aw_unique_o,
  output wire [7:0]                             scu_ext_wrmemattr_o,
  output wire [(`CA53_SCU_EXT_STRB_W-1):0]      scu_ext_dw_strb_o,
  output wire [(`CA53_SCU_EXT_DATA_W-1):0]      scu_ext_dw_data_o,
  output wire [(`CA53_SCU_EXT_WID_W-1):0]       scu_ext_dw_id_o,
  output wire                                   scu_ext_dw_last_o,
  output wire                                   scu_ext_dw_valid_o,
  output wire                                   scu_ext_db_ready_o,
  output wire                                   scu_ext_ac_ready_o,
  output wire                                   scu_ext_cr_valid_o,
  output wire [(`CA53_ACE_CRRESP_W-1):0]        scu_ext_cr_resp_o,
  output wire                                   scu_ext_cd_valid_o,
  output wire [(`CA53_SCU_EXT_DATA_W-1):0]      scu_ext_cd_data_o,
  output wire                                   scu_ext_cd_last_o,
  output wire                                   scu_ext_rack_o,
  output wire                                   scu_ext_wack_o,
  output wire                                   scu_txsactive_o,
  output wire                                   scu_rxlinkactiveack_o,
  output wire                                   scu_txlinkactivereq_o,
  output wire                                   scu_txreqflitpend_o,
  output wire                                   scu_txreqflitv_o,
  output wire [99:0]                            scu_txreqflit_o,
  output wire [7:0]                             scu_reqmemattr_o,
  output wire                                   scu_txrspflitpend_o,
  output wire                                   scu_txrspflitv_o,
  output wire [44:0]                            scu_txrspflit_o,
  output wire                                   scu_txdatflitpend_o,
  output wire                                   scu_txdatflitv_o,
  output wire [193:0]                           scu_txdatflit_o,
  output wire                                   scu_rxsnplcrdv_o,
  output wire                                   scu_rxrsplcrdv_o,
  output wire                                   scu_rxdatlcrdv_o,
  output wire [NUM_CPUS-1:0]                    gov_pseldbg_dbg_o,
  output wire [NUM_CPUS-1:0]                    gov_pseldbg_pmu_o,
  output wire [NUM_CPUS-1:0]                    gov_pseldbg_etm_o,
  output wire [(`CA53_PADDRDBG_PKDED_W-1):0]    gov_paddrdbg_o,
  output wire [NUM_CPUS-1:0]                    gov_paddrdbg31_o,
  output wire [NUM_CPUS-1:0]                    gov_penabledbg_o,
  output wire [NUM_CPUS-1:0]                    gov_pwritedbg_o,
  output wire [(`CA53_PWDATADBG_PKDED_W-1):0]   gov_pwdatadbg_o,
  output wire                                   scu_acp_awready_o,
  output wire                                   scu_acp_wready_o,
  output wire                                   scu_acp_bvalid_o,
  output wire [  4:0]                           scu_acp_bid_o,
  output wire [  1:0]                           scu_acp_bresp_o,
  output wire                                   scu_acp_arready_o,
  output wire                                   scu_acp_rvalid_o,
  output wire [  4:0]                           scu_acp_rid_o,
  output wire [127:0]                           scu_acp_rdata_o,
  output wire [  1:0]                           scu_acp_rresp_o,
  output wire                                   scu_acp_rlast_o,
  output wire [ 31:0]                           prdatadbg_o,
  output wire                                   preadydbg_o,
  output wire                                   pslverrdbg_o,
  output wire [NUM_CPUS-1:0]                    ncommirq_o,
  output wire [NUM_CPUS-1:0]                    dbgack_o,
  output wire [NUM_CPUS-1:0]                    commrx_o,
  output wire [NUM_CPUS-1:0]                    commtx_o,
  output wire [NUM_CPUS-1:0]                    dbgrstreq_o,
  output wire [NUM_CPUS-1:0]                    dbgnopwrdwn_o,
  output wire [NUM_CPUS-1:0]                    gov_dbgpwrupreq_o,
  output wire [NUM_CPUS-1:0]                    dbgpwrupreq_o,
  output wire [NUM_CPUS-1:0]                    gov_dbgl1rstdisable_o,
  output wire [(`CA53_ETMEXT_PKDED_W-1):0]      gov_extin_o,
  output wire [NUM_CPUS-1:0]                    gov_edecr_osuce_o,
  output wire [NUM_CPUS-1:0]                    gov_edecr_rce_o,
  output wire [NUM_CPUS-1:0]                    gov_edecr_ss_o,
  output wire [NUM_CPUS-1:0]                    gov_edlsr_slk_o,
  output wire [NUM_CPUS-1:0]                    gov_pmlsr_slk_o,
  output wire [NUM_CPUS-1:0]                    gov_etmpdsr_rd_o,
  output wire [ 39:12]                          gov_dbgromaddr_o,
  output wire                                   gov_dbgromaddrv_o,
  output wire [NUM_CPUS-1:0]                    gov_edbgrq_o,
  output wire [NUM_CPUS-1:0]                    gov_dbgen_o,
  output wire [NUM_CPUS-1:0]                    gov_spiden_o,
  output wire [NUM_CPUS-1:0]                    gov_niden_o,
  output wire [NUM_CPUS-1:0]                    gov_spniden_o,
  output wire [NUM_CPUS-1:0]                    gov_dbgrestart_o,
  output wire [NUM_CPUS-1:0]                    gov_stall_dsb_o,
  output wire [NUM_CPUS-1:0]                    gov_cp_ack_o,
  output wire [(`CA53_CPDATA_PKDED_W-1):0]      gov_cp_rdata_o,
  output wire [NUM_CPUS-1:0]                    gov_pcnt_kernel_access_o,
  output wire [NUM_CPUS-1:0]                    gov_pcnt_usr_access_o,
  output wire [NUM_CPUS-1:0]                    gov_vcnt_usr_access_o,
  output wire [NUM_CPUS-1:0]                    gov_cntp_usr_access_o,
  output wire [NUM_CPUS-1:0]                    gov_cntv_usr_access_o,
  output wire [NUM_CPUS-1:0]                    gov_cntp_kernel_access_o,
  output wire [63:0]                            gov_tsvalueb_o,
  output wire [NUM_CPUS-1: 0]                   gov_atclken_o,
  output wire [(`CA53_ATREADYM_PKDED_W-1):0]    gov_atreadym_o,
  output wire [(`CA53_AFVALIDM_PKDED_W-1):0]    gov_afvalidm_o,
  output wire [(`CA53_ATDATAM_PKDED_W-1):0]     atdatam_o,
  output wire [(`CA53_ATVALIDM_PKDED_W-1):0]    atvalidm_o,
  output wire [(`CA53_ATBYTESM_PKDED_W-1):0]    atbytesm_o,
  output wire [(`CA53_AFREADYM_PKDED_W-1):0]    afreadym_o,
  output wire [(`CA53_ATIDM_PKDED_W-1):0]       atidm_o,
  output wire [(`CA53_SYNCREQM_PKDED_W-1):0]    gov_syncreqm_o,
  output wire [NUM_CPUS-1:0]                    npmuirq_o,
  output wire [(`CA53_PMUEVNT_PKDED_W-1):0]     pmuevent_o,
  output wire [(`CA53_ARCREDIT_PKDED_W-1):0]    scu_ar_credit_o,
  output wire [(`CA53_ARBLOCK_PKDED_W-1):0]     scu_ar_block_o,
  output wire [(`CA53_DRVALID_PKDED_W-1):0]     scu_dr_valid_o,
  output wire [(`CA53_DRID_PKDED_W-1):0]        scu_dr_id_o,
  output wire [(`CA53_DRRESP_PKDED_W-1):0]      scu_dr_resp_o,
  output wire [(`CA53_DRCHUNK_PKDED_W-1):0]     scu_dr_chunk_o,
  output wire [(`CA53_DRDATA_PKDED_W-1):0]      scu_dr_data_o,
  output wire [(`CA53_RRVALID_PKDED_W-1):0]     scu_rr_valid_o,
  output wire [(`CA53_RRID_PKDED_W-1):0]        scu_rr_id_o,
  output wire [(`CA53_RRRESP_PKDED_W-1):0]      scu_rr_resp_o,
  output wire [(`CA53_RRL2DB_PKDED_W-1):0]      scu_rr_l2db_id_o,
  output wire [(`CA53_EVDONE_PKDED_W-1):0]      scu_ev_done_o,
  output wire [(`CA53_DBEXCLVAL_PKDED_W-1):0]   scu_db_excl_valid_o,
  output wire [(`CA53_DBEXCLRSP_PKDED_W-1):0]   scu_db_excl_resp_o,
  output wire [(`CA53_DBDECERR_PKDED_W-1):0]    scu_db_decerr_o,
  output wire [(`CA53_DBSLVERR_PKDED_W-1):0]    scu_db_slverr_o,
  output wire [(`CA53_LEAVERAM_PKDED_W-1):0]    scu_leave_ramode_o,
  output wire [(`CA53_ACVALID_PKDED_W-1):0]     scu_ac_valid_o,
  output wire [(`CA53_ACID_PKDED_W-1):0]        scu_ac_id_o,
  output wire [(`CA53_ACL2DB_PKDED_W-1):0]      scu_ac_l2db_id_o,
  output wire [(`CA53_ACSNOOP_PKDED_W-1):0]     scu_ac_snoop_o,
  output wire [(`CA53_ACADDR_PKDED_W-1):0]      scu_ac_addr_o,
  output wire [(`CA53_ACWAY_PKDED_W-1):0]       scu_ac_way_o,
  output wire [(`CA53_DVM_COMP_PKDED_W-1):0]    scu_dvm_complete_o,
  output wire [(`CA53_REQBUFS_BUSY_PKDED_W-1):0]scu_reqbufs_busy_o,
  output wire [(`CA53_DRAIN_STB_PKDED_W-1):0]   scu_drain_stb_o,
  output wire [NUM_CPUS-1:0]                    scu_evnt_l2_access_o,
  output wire [NUM_CPUS-1:0]                    scu_evnt_l2_refill_o,
  output wire [NUM_CPUS-1:0]                    scu_evnt_l2_wb_o,
  output wire [NUM_CPUS-1:0]                    scu_evnt_snooped_data_o,
  output wire [NUM_CPUS-1:0]                    scu_evnt_bus_cycle_o,
  output wire [NUM_CPUS-1:0]                    scu_evnt_bus_acc_rd_o,
  output wire [NUM_CPUS-1:0]                    scu_evnt_bus_acc_wr_o,
  output wire [NUM_CPUS-1:0]                    scu_evnt_eviction_o,
  output wire [`CA53_L2_SIZE_W-1:0]             l2_size_o,
  output wire [3:0]                             ctichout_o,
  output wire [3:0]                             ctichinack_o,
  output wire [NUM_CPUS-1: 0]                   ctiirq_o,
  output wire                                   mbistack0_o,
  output wire                                   mbistack1_o,
  output wire [(`CA53_MBIST0_DATA_W-1): 0]      mbistoutdata0_o,
  output wire [(`CA53_MBIST1_DATA_W-1): 0]      mbistoutdata1_o
);

  // -----------------------------
  // Wire declarations
  // -----------------------------

  /*ARMAUTO*/
  // The following wires were automatically generated
  // to interconnect instantiations where appropriate.
  wire                                       clk;
  wire                                       l1d_tagram_clken;
  wire     [`CA53_SCU_L1D_TAGRAM_ADDR_W-1:0] l1d_tagram_cpu0_addr;
  wire             [`CA53_SCU_L1D_ASSOC-1:0] l1d_tagram_cpu0_en;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu0_way0_rdata;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu0_way1_rdata;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu0_way2_rdata;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu0_way3_rdata;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu0_wdata;
  wire                                       l1d_tagram_cpu0_wr;
  wire     [`CA53_SCU_L1D_TAGRAM_ADDR_W-1:0] l1d_tagram_cpu1_addr;
  wire             [`CA53_SCU_L1D_ASSOC-1:0] l1d_tagram_cpu1_en;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu1_way0_rdata;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu1_way1_rdata;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu1_way2_rdata;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu1_way3_rdata;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu1_wdata;
  wire                                       l1d_tagram_cpu1_wr;
  wire     [`CA53_SCU_L1D_TAGRAM_ADDR_W-1:0] l1d_tagram_cpu2_addr;
  wire             [`CA53_SCU_L1D_ASSOC-1:0] l1d_tagram_cpu2_en;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu2_way0_rdata;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu2_way1_rdata;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu2_way2_rdata;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu2_way3_rdata;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu2_wdata;
  wire                                       l1d_tagram_cpu2_wr;
  wire     [`CA53_SCU_L1D_TAGRAM_ADDR_W-1:0] l1d_tagram_cpu3_addr;
  wire             [`CA53_SCU_L1D_ASSOC-1:0] l1d_tagram_cpu3_en;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu3_way0_rdata;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu3_way1_rdata;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu3_way2_rdata;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu3_way3_rdata;
  wire     [`CA53_SCU_L1D_TAGRAM_DATA_W-1:0] l1d_tagram_cpu3_wdata;
  wire                                       l1d_tagram_cpu3_wr;
  wire     [`CA53_SCU_L2_DATARAM_ADDR_W-1:0] l2_dataram_addr;
  wire       [`CA53_SCU_L2_DATARAM_EN_W-1:0] l2_dataram_clken;
  wire       [`CA53_SCU_L2_DATARAM_EN_W-1:0] l2_dataram_en;
  wire                                       l2_dataram_no_acc_next_cycle;
  wire     [`CA53_SCU_L2_DATARAM_DATA_W-1:0] l2_dataram_rdata0;
  wire     [`CA53_SCU_L2_DATARAM_DATA_W-1:0] l2_dataram_rdata1;
  wire     [`CA53_SCU_L2_DATARAM_DATA_W-1:0] l2_dataram_rdata2;
  wire     [`CA53_SCU_L2_DATARAM_DATA_W-1:0] l2_dataram_rdata3;
  wire     [`CA53_SCU_L2_DATARAM_DATA_W-1:0] l2_dataram_rdata4;
  wire     [`CA53_SCU_L2_DATARAM_DATA_W-1:0] l2_dataram_rdata5;
  wire     [`CA53_SCU_L2_DATARAM_DATA_W-1:0] l2_dataram_rdata6;
  wire     [`CA53_SCU_L2_DATARAM_DATA_W-1:0] l2_dataram_rdata7;
  wire     [`CA53_SCU_L2_DATARAM_DATA_W-1:0] l2_dataram_wdata0;
  wire     [`CA53_SCU_L2_DATARAM_DATA_W-1:0] l2_dataram_wdata1;
  wire     [`CA53_SCU_L2_DATARAM_DATA_W-1:0] l2_dataram_wdata2;
  wire     [`CA53_SCU_L2_DATARAM_DATA_W-1:0] l2_dataram_wdata3;
  wire     [`CA53_SCU_L2_DATARAM_DATA_W-1:0] l2_dataram_wdata4;
  wire     [`CA53_SCU_L2_DATARAM_DATA_W-1:0] l2_dataram_wdata5;
  wire     [`CA53_SCU_L2_DATARAM_DATA_W-1:0] l2_dataram_wdata6;
  wire     [`CA53_SCU_L2_DATARAM_DATA_W-1:0] l2_dataram_wdata7;
  wire                                       l2_dataram_wr;
  wire                 [`CA53_L2_SIZE_W-1:0] l2_size;
  wire      [`CA53_SCU_L2_TAGRAM_ADDR_W-1:0] l2_tagram_addr;
  wire                                       l2_tagram_clken;
  wire              [`CA53_SCU_L2_ASSOC-1:0] l2_tagram_en;
  wire      [`CA53_SCU_L2_TAGRAM_DATA_W-1:0] l2_tagram_way0_rdata;
  wire      [`CA53_SCU_L2_TAGRAM_DATA_W-1:0] l2_tagram_way10_rdata;
  wire      [`CA53_SCU_L2_TAGRAM_DATA_W-1:0] l2_tagram_way11_rdata;
  wire      [`CA53_SCU_L2_TAGRAM_DATA_W-1:0] l2_tagram_way12_rdata;
  wire      [`CA53_SCU_L2_TAGRAM_DATA_W-1:0] l2_tagram_way13_rdata;
  wire      [`CA53_SCU_L2_TAGRAM_DATA_W-1:0] l2_tagram_way14_rdata;
  wire      [`CA53_SCU_L2_TAGRAM_DATA_W-1:0] l2_tagram_way15_rdata;
  wire      [`CA53_SCU_L2_TAGRAM_DATA_W-1:0] l2_tagram_way1_rdata;
  wire      [`CA53_SCU_L2_TAGRAM_DATA_W-1:0] l2_tagram_way2_rdata;
  wire      [`CA53_SCU_L2_TAGRAM_DATA_W-1:0] l2_tagram_way3_rdata;
  wire      [`CA53_SCU_L2_TAGRAM_DATA_W-1:0] l2_tagram_way4_rdata;
  wire      [`CA53_SCU_L2_TAGRAM_DATA_W-1:0] l2_tagram_way5_rdata;
  wire      [`CA53_SCU_L2_TAGRAM_DATA_W-1:0] l2_tagram_way6_rdata;
  wire      [`CA53_SCU_L2_TAGRAM_DATA_W-1:0] l2_tagram_way7_rdata;
  wire      [`CA53_SCU_L2_TAGRAM_DATA_W-1:0] l2_tagram_way8_rdata;
  wire      [`CA53_SCU_L2_TAGRAM_DATA_W-1:0] l2_tagram_way9_rdata;
  wire      [`CA53_SCU_L2_TAGRAM_DATA_W-1:0] l2_tagram_wdata;
  wire                                       l2_tagram_wr;
  wire   [`CA53_SCU_L2_VICTIMRAM_ADDR_W-1:0] l2_victimram_addr;
  wire                                       l2_victimram_clken;
  wire                                       l2_victimram_en;
  wire                                       l2_victimram_no_acc_next_cycle;
  wire   [`CA53_SCU_L2_VICTIMRAM_DATA_W-1:0] l2_victimram_rdata;
  wire   [`CA53_SCU_L2_VICTIMRAM_STRB_W-1:0] l2_victimram_strb;
  wire   [`CA53_SCU_L2_VICTIMRAM_DATA_W-1:0] l2_victimram_wdata;
  wire                                       l2_victimram_wr;
  /*END*/

  //
  // ---------------------------------------------------------
  // Main Code
  // ---------------------------------------------------------
  //

  // ------------------------------------------------------
  // Unpack buses
  // ------------------------------------------------------



  // ------------------------------------------------------
  // L2
  // ------------------------------------------------------

  ca53_l2noram `CA53_L2_PARAM_INST u_ca53_l2noram (
    /*ARMAUTO*/
    // Inputs
    .CLKIN                            (CLKIN),
    .DFTSE                            (DFTSE),
    .DFTRSTDISABLE                    (DFTRSTDISABLE),
    .DFTRAMHOLD                       (DFTRAMHOLD),
    .DFTMCPHOLD                       (DFTMCPHOLD),
    .ncpuporeset                      (ncpuporeset[NUM_CPUS-1:0]),
    .ncorereset                       (ncorereset[NUM_CPUS-1:0]),
    .nl2reset                         (nl2reset),
    .nmbistreset                      (nmbistreset),
    .l2rstdisable_i                   (l2rstdisable_i),
    .cfgend_i                         (cfgend_i[NUM_CPUS-1:0]),
    .vinithi_i                        (vinithi_i[NUM_CPUS-1:0]),
    .cfgte_i                          (cfgte_i[NUM_CPUS-1:0]),
    .cp15sdisable_i                   (cp15sdisable_i[NUM_CPUS-1:0]),
    .clusteridaff1_i                  (clusteridaff1_i[ 7:0]),
    .clusteridaff2_i                  (clusteridaff2_i[ 7:0]),
    .etm_oslock_i                     (etm_oslock_i[NUM_CPUS-1: 0]),
    .aa64naa32_i                      (aa64naa32_i[NUM_CPUS-1:0]),
    .rvbaraddr_i                      (rvbaraddr_i[(`CA53_RVBARADDR_PKDED_W-1):0]),
    .cryptodisable_i                  (cryptodisable_i[NUM_CPUS-1:0]),
    .nfiq_i                           (nfiq_i[NUM_CPUS-1:0]),
    .nirq_i                           (nirq_i[NUM_CPUS-1:0]),
    .nsei_i                           (nsei_i[NUM_CPUS-1:0]),
    .nrei_i                           (nrei_i[NUM_CPUS-1:0]),
    .nvfiq_i                          (nvfiq_i[NUM_CPUS-1:0]),
    .nvirq_i                          (nvirq_i[NUM_CPUS-1:0]),
    .nvsei_i                          (nvsei_i[NUM_CPUS-1:0]),
    .periphbase_i                     (periphbase_i[ 39:18]),
    .giccdisable_i                    (giccdisable_i),
    .icdtvalid_i                      (icdtvalid_i),
    .icdtdata_i                       (icdtdata_i[ 15:0]),
    .icdtlast_i                       (icdtlast_i),
    .icdtdest_i                       (icdtdest_i[ 1:0]),
    .icctready_i                      (icctready_i),
    .cntvalueb_i                      (cntvalueb_i[ 63:0]),
    .cntclken_i                       (cntclken_i),
    .tsvalueb_i                       (tsvalueb_i[ 63:0]),
    .clrexmonreq_i                    (clrexmonreq_i),
    .eventi_i                         (eventi_i),
    .l2flushreq_i                     (l2flushreq_i),
    .cpuqreqn_i                       (cpuqreqn_i[NUM_CPUS-1:0]),
    .neonqreqn_i                      (neonqreqn_i[NUM_CPUS-1:0]),
    .l2qreqn_i                        (l2qreqn_i),
    .broadcastcachemaint_i            (broadcastcachemaint_i),
    .broadcastinner_i                 (broadcastinner_i),
    .broadcastouter_i                 (broadcastouter_i),
    .aclkenm_i                        (aclkenm_i),
    .acinactm_i                       (acinactm_i),
    .sysbardisable_i                  (sysbardisable_i),
    .awreadym_i                       (awreadym_i),
    .wreadym_i                        (wreadym_i),
    .bvalidm_i                        (bvalidm_i),
    .bidm_i                           (bidm_i[`CA53_SCU_EXT_WID_W-1:0]),
    .brespm_i                         (brespm_i[`CA53_ACE_BRESP_W-1:0]),
    .arreadym_i                       (arreadym_i),
    .rvalidm_i                        (rvalidm_i),
    .ridm_i                           (ridm_i[`CA53_SCU_EXT_RID_W-1:0]),
    .rdatam_i                         (rdatam_i[`CA53_SCU_EXT_DATA_W-1:0]),
    .rrespm_i                         (rrespm_i[`CA53_ACE_RRESP_W-1:0]),
    .rlastm_i                         (rlastm_i),
    .acvalidm_i                       (acvalidm_i),
    .acaddrm_i                        (acaddrm_i[`CA53_SCU_EXT_ADDR_W-1:0]),
    .acprotm_i                        (acprotm_i[`CA53_ACE_ACPROT_W-1:0]),
    .acsnoopm_i                       (acsnoopm_i[`CA53_ACE_ACSNOOP_W-1:0]),
    .crreadym_i                       (crreadym_i),
    .cdreadym_i                       (cdreadym_i),
    .sclken_i                         (sclken_i),
    .sinact_i                         (sinact_i),
    .nodeid_i                         (nodeid_i[6:0]),
    .rxsactive_i                      (rxsactive_i),
    .rxlinkactivereq_i                (rxlinkactivereq_i),
    .txlinkactiveack_i                (txlinkactiveack_i),
    .txreqlcrdv_i                     (txreqlcrdv_i),
    .txrsplcrdv_i                     (txrsplcrdv_i),
    .txdatlcrdv_i                     (txdatlcrdv_i),
    .rxsnpflitpend_i                  (rxsnpflitpend_i),
    .rxsnpflitv_i                     (rxsnpflitv_i),
    .rxsnpflit_i                      (rxsnpflit_i[64:0]),
    .rxrspflitpend_i                  (rxrspflitpend_i),
    .rxrspflitv_i                     (rxrspflitv_i),
    .rxrspflit_i                      (rxrspflit_i[44:0]),
    .rxdatflitpend_i                  (rxdatflitpend_i),
    .rxdatflitv_i                     (rxdatflitv_i),
    .rxdatflit_i                      (rxdatflit_i[193:0]),
    .samaddrmap0_i                    (samaddrmap0_i[1:0]),
    .samaddrmap1_i                    (samaddrmap1_i[1:0]),
    .samaddrmap2_i                    (samaddrmap2_i[1:0]),
    .samaddrmap3_i                    (samaddrmap3_i[1:0]),
    .samaddrmap4_i                    (samaddrmap4_i[1:0]),
    .samaddrmap5_i                    (samaddrmap5_i[1:0]),
    .samaddrmap6_i                    (samaddrmap6_i[1:0]),
    .samaddrmap7_i                    (samaddrmap7_i[1:0]),
    .samaddrmap8_i                    (samaddrmap8_i[1:0]),
    .samaddrmap9_i                    (samaddrmap9_i[1:0]),
    .samaddrmap10_i                   (samaddrmap10_i[1:0]),
    .samaddrmap11_i                   (samaddrmap11_i[1:0]),
    .samaddrmap12_i                   (samaddrmap12_i[1:0]),
    .samaddrmap13_i                   (samaddrmap13_i[1:0]),
    .samaddrmap14_i                   (samaddrmap14_i[1:0]),
    .samaddrmap15_i                   (samaddrmap15_i[1:0]),
    .sammnbase_i                      (sammnbase_i[39:24]),
    .sammnnodeid_i                    (sammnnodeid_i[6:0]),
    .samhni0nodeid_i                  (samhni0nodeid_i[6:0]),
    .samhni1nodeid_i                  (samhni1nodeid_i[6:0]),
    .samhnf0nodeid_i                  (samhnf0nodeid_i[6:0]),
    .samhnf1nodeid_i                  (samhnf1nodeid_i[6:0]),
    .samhnf2nodeid_i                  (samhnf2nodeid_i[6:0]),
    .samhnf3nodeid_i                  (samhnf3nodeid_i[6:0]),
    .samhnf4nodeid_i                  (samhnf4nodeid_i[6:0]),
    .samhnf5nodeid_i                  (samhnf5nodeid_i[6:0]),
    .samhnf6nodeid_i                  (samhnf6nodeid_i[6:0]),
    .samhnf7nodeid_i                  (samhnf7nodeid_i[6:0]),
    .samhnfmode_i                     (samhnfmode_i[2:0]),
    .aclkens_i                        (aclkens_i),
    .ainacts_i                        (ainacts_i),
    .awvalids_i                       (awvalids_i),
    .awids_i                          (awids_i[ 4:0]),
    .awaddrs_i                        (awaddrs_i[ 39:0]),
    .awlens_i                         (awlens_i[ 7:0]),
    .awcaches_i                       (awcaches_i[ 3:0]),
    .awusers_i                        (awusers_i[ 1:0]),
    .awprots_i                        (awprots_i[ 2:0]),
    .wvalids_i                        (wvalids_i),
    .wdatas_i                         (wdatas_i[127:0]),
    .wstrbs_i                         (wstrbs_i[ 15:0]),
    .wlasts_i                         (wlasts_i),
    .breadys_i                        (breadys_i),
    .arvalids_i                       (arvalids_i),
    .arids_i                          (arids_i[ 4:0]),
    .araddrs_i                        (araddrs_i[ 39:0]),
    .arlens_i                         (arlens_i[ 7:0]),
    .arcaches_i                       (arcaches_i[ 3:0]),
    .arusers_i                        (arusers_i[ 1:0]),
    .arprots_i                        (arprots_i[ 2:0]),
    .rreadys_i                        (rreadys_i),
    .npresetdbg_i                     (npresetdbg_i),
    .pclkendbg_i                      (pclkendbg_i),
    .pseldbg_i                        (pseldbg_i),
    .paddrdbg_i                       (paddrdbg_i[ 21: 2]),
    .paddrdbg31_i                     (paddrdbg31_i),
    .penabledbg_i                     (penabledbg_i),
    .pwritedbg_i                      (pwritedbg_i),
    .pwdatadbg_i                      (pwdatadbg_i[ 31:0]),
    .dpu_prdatadbg_i                  (dpu_prdatadbg_i[(`CA53_PRDATADBG_PKDED_W-1):0]),
    .dpu_preadydbg_i                  (dpu_preadydbg_i[NUM_CPUS-1:0]),
    .dpu_pslverrdbg_i                 (dpu_pslverrdbg_i[NUM_CPUS-1:0]),
    .etm_prdatadbg_i                  (etm_prdatadbg_i[(`CA53_PRDATADBG_PKDED_W-1):0]),
    .etm_preadydbg_i                  (etm_preadydbg_i[NUM_CPUS-1:0]),
    .etm_extout_i                     (etm_extout_i[(`CA53_ETMEXT_PKDED_W-1):0]),
    .dcu_excl_mon_cleared_i           (dcu_excl_mon_cleared_i[NUM_CPUS-1:0]),
    .dcu_cp_gov_addr_i                (dcu_cp_gov_addr_i[(`CA53_CPADDR_PKDED_W-1):0]),
    .dcu_cp_gov_ns_i                  (dcu_cp_gov_ns_i[NUM_CPUS-1:0]),
    .dcu_cp_gov_req_i                 (dcu_cp_gov_req_i[NUM_CPUS-1:0]),
    .dcu_cp_gov_sel_i                 (dcu_cp_gov_sel_i[(`CA53_CPSEL_PKDED_W-1):0]),
    .dcu_cp_gov_wdata_i               (dcu_cp_gov_wdata_i[(`CA53_CPDATA_PKDED_W-1):0]),
    .dcu_cp_gov_wenable_i             (dcu_cp_gov_wenable_i[NUM_CPUS-1:0]),
    .dbgromaddr_i                     (dbgromaddr_i[ 39:12]),
    .dbgromaddrv_i                    (dbgromaddrv_i),
    .edbgrq_i                         (edbgrq_i[NUM_CPUS-1:0]),
    .dbgen_i                          (dbgen_i[NUM_CPUS-1:0]),
    .spiden_i                         (spiden_i[NUM_CPUS-1:0]),
    .niden_i                          (niden_i[NUM_CPUS-1:0]),
    .spniden_i                        (spniden_i[NUM_CPUS-1:0]),
    .dbgpwrdup_i                      (dbgpwrdup_i[NUM_CPUS-1:0]),
    .dbgl1rstdisable_i                (dbgl1rstdisable_i),
    .atclken_i                        (atclken_i),
    .atreadym_i                       (atreadym_i[(`CA53_ATREADYM_PKDED_W-1):0]),
    .afvalidm_i                       (afvalidm_i[(`CA53_AFVALIDM_PKDED_W-1):0]),
    .etm_atdatam_i                    (etm_atdatam_i[(`CA53_ATDATAM_PKDED_W-1):0]),
    .etm_atvalidm_i                   (etm_atvalidm_i[(`CA53_ATVALIDM_PKDED_W-1):0]),
    .etm_atbytesm_i                   (etm_atbytesm_i[(`CA53_ATBYTESM_PKDED_W-1):0]),
    .etm_afreadym_i                   (etm_afreadym_i[(`CA53_AFREADYM_PKDED_W-1):0]),
    .etm_atidm_i                      (etm_atidm_i[(`CA53_ATIDM_PKDED_W-1):0]),
    .syncreqm_i                       (syncreqm_i[(`CA53_SYNCREQM_PKDED_W-1):0]),
    .ctichin_i                        (ctichin_i[3:0]),
    .ctichoutack_i                    (ctichoutack_i[3:0]),
    .ctiirqack_i                      (ctiirqack_i[NUM_CPUS-1:0]),
    .cisbypass_i                      (cisbypass_i),
    .cihsbypass_i                     (cihsbypass_i[3:0]),
    .dpu_warmrstreq_i                 (dpu_warmrstreq_i[NUM_CPUS-1:0]),
    .dpu_dbgtrigger_i                 (dpu_dbgtrigger_i[NUM_CPUS-1:0]),
    .dpu_dbgack_i                     (dpu_dbgack_i[NUM_CPUS-1:0]),
    .dpu_commrx_i                     (dpu_commrx_i[NUM_CPUS-1:0]),
    .dpu_commtx_i                     (dpu_commtx_i[NUM_CPUS-1:0]),
    .dpu_ncommirq_i                   (dpu_ncommirq_i[NUM_CPUS-1:0]),
    .dpu_dbgrstreq_i                  (dpu_dbgrstreq_i[NUM_CPUS-1:0]),
    .dpu_dbgnopwrdwn_i                (dpu_dbgnopwrdwn_i[NUM_CPUS-1:0]),
    .dpu_clr_event_register_i         (dpu_clr_event_register_i[NUM_CPUS-1:0]),
    .dpu_exception_level_i            (dpu_exception_level_i[(`CA53_EXCP_LEV_PKDED_W-1):0]),
    .dpu_aarch64_at_el3_i             (dpu_aarch64_at_el3_i[NUM_CPUS-1:0]),
    .dpu_hcr_el2_fmo_i                (dpu_hcr_el2_fmo_i[NUM_CPUS-1:0]),
    .dpu_hcr_el2_imo_i                (dpu_hcr_el2_imo_i[NUM_CPUS-1:0]),
    .dpu_hcr_el2_amo_i                (dpu_hcr_el2_amo_i[NUM_CPUS-1:0]),
    .dpu_monitor_mode_i               (dpu_monitor_mode_i[NUM_CPUS-1:0]),
    .dpu_rei_level_ack_i              (dpu_rei_level_ack_i[NUM_CPUS-1:0]),
    .dpu_scr_el3_fiq_i                (dpu_scr_el3_fiq_i[NUM_CPUS-1:0]),
    .dpu_scr_el3_irq_i                (dpu_scr_el3_irq_i[NUM_CPUS-1:0]),
    .dpu_scr_el3_ns_i                 (dpu_scr_el3_ns_i[NUM_CPUS-1:0]),
    .dpu_sei_level_ack_i              (dpu_sei_level_ack_i[NUM_CPUS-1:0]),
    .dpu_vsei_level_ack_i             (dpu_vsei_level_ack_i[NUM_CPUS-1:0]),
    .dpu_wfi_req_i                    (dpu_wfi_req_i[NUM_CPUS-1:0]),
    .dpu_wfe_req_i                    (dpu_wfe_req_i[NUM_CPUS-1:0]),
    .dpu_irq_pended_i                 (dpu_irq_pended_i[NUM_CPUS-1:0]),
    .dpu_fiq_pended_i                 (dpu_fiq_pended_i[NUM_CPUS-1:0]),
    .dpu_sei_pended_i                 (dpu_sei_pended_i[NUM_CPUS-1:0]),
    .dpu_irq_masked_i                 (dpu_irq_masked_i[NUM_CPUS-1:0]),
    .dpu_fiq_masked_i                 (dpu_fiq_masked_i[NUM_CPUS-1:0]),
    .dpu_sei_masked_i                 (dpu_sei_masked_i[NUM_CPUS-1:0]),
    .dpu_virq_pended_i                (dpu_virq_pended_i[NUM_CPUS-1:0]),
    .dpu_vfiq_pended_i                (dpu_vfiq_pended_i[NUM_CPUS-1:0]),
    .dpu_vsei_pended_i                (dpu_vsei_pended_i[NUM_CPUS-1:0]),
    .dpu_virq_masked_i                (dpu_virq_masked_i[NUM_CPUS-1:0]),
    .dpu_vfiq_masked_i                (dpu_vfiq_masked_i[NUM_CPUS-1:0]),
    .dpu_vsei_masked_i                (dpu_vsei_masked_i[NUM_CPUS-1:0]),
    .dpu_dbg_double_lock_set_i        (dpu_dbg_double_lock_set_i[NUM_CPUS-1:0]),
    .dpu_ns_state_i                   (dpu_ns_state_i[NUM_CPUS-1:0]),
    .dpu_dscr_halted_i                (dpu_dscr_halted_i[NUM_CPUS-1:0]),
    .stb_wfx_ready_i                  (stb_wfx_ready_i[NUM_CPUS-1:0]),
    .biu_wfx_ready_i                  (biu_wfx_ready_i[NUM_CPUS-1:0]),
    .dcu_wfx_ready_i                  (dcu_wfx_ready_i[NUM_CPUS-1:0]),
    .ifu_wfx_ready_i                  (ifu_wfx_ready_i[NUM_CPUS-1:0]),
    .tlb_wfx_ready_i                  (tlb_wfx_ready_i[NUM_CPUS-1:0]),
    .etm_wfx_ready_i                  (etm_wfx_ready_i[NUM_CPUS-1:0]),
    .dpu_imp_abort_pending_i          (dpu_imp_abort_pending_i[NUM_CPUS-1:0]),
    .dpu_cpuectlr_cpu_ret_delay_i     (dpu_cpuectlr_cpu_ret_delay_i[(`CA53_RET_CTL_PKDED_W-1):0]),
    .dpu_cpuectlr_neon_ret_delay_i    (dpu_cpuectlr_neon_ret_delay_i[(`CA53_RET_CTL_PKDED_W-1):0]),
    .dpu_neon_active_i                (dpu_neon_active_i[NUM_CPUS-1: 0]),
    .dpu_npmuirq_i                    (dpu_npmuirq_i[NUM_CPUS-1:0]),
    .dpu_pmuevent_i                   (dpu_pmuevent_i[(`CA53_PMUEVNT_CPU_PKDED_W-1):0]),
    .dpu_smp_en_i                     (dpu_smp_en_i[NUM_CPUS-1:0]),
    .dpu_sev_req_i                    (dpu_sev_req_i[NUM_CPUS-1:0]),
    .biu_ar_active_i                  (biu_ar_active_i[(`CA53_ARACTIVE_PKDED_W-1):0]),
    .biu_ar_valid_i                   (biu_ar_valid_i[(`CA53_ARVALID_PKDED_W-1):0]),
    .biu_ar_id_i                      (biu_ar_id_i[(`CA53_ARID_PKDED_W-1):0]),
    .biu_ar_type_i                    (biu_ar_type_i[(`CA53_ARTYPE_PKDED_W-1):0]),
    .biu_ar_attrs_i                   (biu_ar_attrs_i[(`CA53_ARATTRS_PKDED_W-1):0]),
    .biu_ar_way_i                     (biu_ar_way_i[(`CA53_ARWAY_PKDED_W-1):0]),
    .biu_ar_addr_i                    (biu_ar_addr_i[(`CA53_ARADDR_PKDED_W-1):0]),
    .biu_ar_len_i                     (biu_ar_len_i[(`CA53_ARLEN_PKDED_W-1):0]),
    .biu_ar_size_i                    (biu_ar_size_i[(`CA53_ARSIZE_PKDED_W-1):0]),
    .biu_ar_lock_i                    (biu_ar_lock_i[(`CA53_ARLOCK_PKDED_W-1):0]),
    .biu_ar_priv_i                    (biu_ar_priv_i[(`CA53_ARPRIV_PKDED_W-1):0]),
    .biu_dr_credit_i                  (biu_dr_credit_i[(`CA53_DRCREDIT_PKDED_W-1):0]),
    .biu_dw_valid_i                   (biu_dw_valid_i[(`CA53_DWVALID_PKDED_W-1):0]),
    .biu_dw_l2db_id_i                 (biu_dw_l2db_id_i[(`CA53_DWL2DB_PKDED_W-1):0]),
    .biu_dw_chunks_valid_i            (biu_dw_chunks_valid_i[(`CA53_DWCHUNKS_PKDED_W-1):0]),
    .biu_dw_last_i                    (biu_dw_last_i[(`CA53_DWLAST_PKDED_W-1):0]),
    .biu_dw_strb_i                    (biu_dw_strb_i[(`CA53_DWSTRB_PKDED_W-1):0]),
    .biu_dw_data_i                    (biu_dw_data_i[(`CA53_DWDATA_PKDED_W-1):0]),
    .biu_dw_err_i                     (biu_dw_err_i[(`CA53_DWERR_PKDED_W-1):0]),
    .biu_dw_fatal_i                   (biu_dw_fatal_i[(`CA53_DWFATAL_PKDED_W-1):0]),
    .dcu_ac_ready_i                   (dcu_ac_ready_i[(`CA53_ACREADY_PKDED_W-1):0]),
    .dcu_cr_valid_i                   (dcu_cr_valid_i[(`CA53_CRVALID_PKDED_W-1):0]),
    .dcu_cr_id_i                      (dcu_cr_id_i[(`CA53_CRID_PKDED_W-1):0]),
    .dcu_cr_dirty_i                   (dcu_cr_dirty_i[(`CA53_CRDIRTY_PKDED_W-1):0]),
    .dcu_cr_age_i                     (dcu_cr_age_i[(`CA53_CRAGE_PKDED_W-1):0]),
    .dcu_cr_alloc_i                   (dcu_cr_alloc_i[(`CA53_CRALLOC_PKDED_W-1):0]),
    .dcu_cr_migratory_i               (dcu_cr_migratory_i[(`CA53_CRMIG_PKDED_W-1):0]),
    .dcu_dvm_complete_i               (dcu_dvm_complete_i[(`CA53_DVM_COMP_PKDED_W-1):0]),
    .mbistreq_i                       (mbistreq_i),
    .mbistaddr0_i                     (mbistaddr0_i[(`CA53_MBIST0_ADDR_W-1): 0]),
    .mbistaddr1_i                     (mbistaddr1_i[(`CA53_MBIST1_ADDR_W-1): 0]),
    .mbistindata0_i                   (mbistindata0_i[(`CA53_MBIST0_DATA_W-1): 0]),
    .mbistindata1_i                   (mbistindata1_i[(`CA53_MBIST1_DATA_W-1): 0]),
    .mbistwriteen0_i                  (mbistwriteen0_i),
    .mbistwriteen1_i                  (mbistwriteen1_i),
    .mbistreaden0_i                   (mbistreaden0_i),
    .mbistreaden1_i                   (mbistreaden1_i),
    .mbistarray0_i                    (mbistarray0_i[(`CA53_MBIST0_RAMARRAY_W-1):0]),
    .mbistarray1_i                    (mbistarray1_i[(`CA53_MBIST1_RAMARRAY_W-1):0]),
    .mbistbe0_i                       (mbistbe0_i[(`CA53_MBIST0_BE_W-1):0]),
    .mbistbe1_i                       (mbistbe1_i[(`CA53_MBIST1_BE_W-1):0]),
    .mbistcfg0_i                      (mbistcfg0_i),
    .mbistcfg1_i                      (mbistcfg1_i),
    .l1_dc_size_i                     (l1_dc_size_i[(`CA53_L1DC_SIZE_W-1):0]),
    .l1d_tagram_cpu0_way0_rdata_i     (l1d_tagram_cpu0_way0_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu0_way1_rdata_i     (l1d_tagram_cpu0_way1_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu0_way2_rdata_i     (l1d_tagram_cpu0_way2_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu0_way3_rdata_i     (l1d_tagram_cpu0_way3_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu1_way0_rdata_i     (l1d_tagram_cpu1_way0_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu1_way1_rdata_i     (l1d_tagram_cpu1_way1_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu1_way2_rdata_i     (l1d_tagram_cpu1_way2_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu1_way3_rdata_i     (l1d_tagram_cpu1_way3_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu2_way0_rdata_i     (l1d_tagram_cpu2_way0_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu2_way1_rdata_i     (l1d_tagram_cpu2_way1_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu2_way2_rdata_i     (l1d_tagram_cpu2_way2_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu2_way3_rdata_i     (l1d_tagram_cpu2_way3_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu3_way0_rdata_i     (l1d_tagram_cpu3_way0_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu3_way1_rdata_i     (l1d_tagram_cpu3_way1_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu3_way2_rdata_i     (l1d_tagram_cpu3_way2_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu3_way3_rdata_i     (l1d_tagram_cpu3_way3_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l2_size_i                        (l2_size[`CA53_L2_SIZE_W-1:0]),
    .l2_tagram_way0_rdata_i           (l2_tagram_way0_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
    .l2_tagram_way1_rdata_i           (l2_tagram_way1_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
    .l2_tagram_way2_rdata_i           (l2_tagram_way2_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
    .l2_tagram_way3_rdata_i           (l2_tagram_way3_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
    .l2_tagram_way4_rdata_i           (l2_tagram_way4_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
    .l2_tagram_way5_rdata_i           (l2_tagram_way5_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
    .l2_tagram_way6_rdata_i           (l2_tagram_way6_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
    .l2_tagram_way7_rdata_i           (l2_tagram_way7_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
    .l2_tagram_way8_rdata_i           (l2_tagram_way8_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
    .l2_tagram_way9_rdata_i           (l2_tagram_way9_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
    .l2_tagram_way10_rdata_i          (l2_tagram_way10_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
    .l2_tagram_way11_rdata_i          (l2_tagram_way11_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
    .l2_tagram_way12_rdata_i          (l2_tagram_way12_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
    .l2_tagram_way13_rdata_i          (l2_tagram_way13_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
    .l2_tagram_way14_rdata_i          (l2_tagram_way14_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
    .l2_tagram_way15_rdata_i          (l2_tagram_way15_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
    .l2_victimram_rdata_i             (l2_victimram_rdata[`CA53_SCU_L2_VICTIMRAM_DATA_W-1:0]),
    .l2_dataram_rdata0_i              (l2_dataram_rdata0[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
    .l2_dataram_rdata1_i              (l2_dataram_rdata1[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
    .l2_dataram_rdata2_i              (l2_dataram_rdata2[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
    .l2_dataram_rdata3_i              (l2_dataram_rdata3[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
    .l2_dataram_rdata4_i              (l2_dataram_rdata4[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
    .l2_dataram_rdata5_i              (l2_dataram_rdata5[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
    .l2_dataram_rdata6_i              (l2_dataram_rdata6[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
    .l2_dataram_rdata7_i              (l2_dataram_rdata7[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
    // Outputs
    .clk_cpu                          (clk_cpu[NUM_CPUS-1:0]),
    .clk                              (clk),
    .reset_n_cpu                      (reset_n_cpu[NUM_CPUS-1:0]),
    .po_reset_n_cpu                   (po_reset_n_cpu[NUM_CPUS-1:0]),
    .warmrstreq_o                     (warmrstreq_o[NUM_CPUS-1:0]),
    .gov_cfgend_o                     (gov_cfgend_o[NUM_CPUS-1:0]),
    .gov_vinithi_o                    (gov_vinithi_o[NUM_CPUS-1:0]),
    .gov_cfgte_o                      (gov_cfgte_o[NUM_CPUS-1:0]),
    .gov_cp15sdisable_o               (gov_cp15sdisable_o[NUM_CPUS-1:0]),
    .gov_clusteridaff1_o              (gov_clusteridaff1_o[ 7:0]),
    .gov_clusteridaff2_o              (gov_clusteridaff2_o[ 7:0]),
    .gov_aa64naa32_o                  (gov_aa64naa32_o[NUM_CPUS-1:0]),
    .gov_rvbaraddr_o                  (gov_rvbaraddr_o[(`CA53_RVBARADDR_PKDED_W-1):0]),
    .gov_cryptodisable_o              (gov_cryptodisable_o[NUM_CPUS-1:0]),
    .gov_stall_neon_o                 (gov_stall_neon_o[NUM_CPUS-1:0]),
    .gic_irq_o                        (gic_irq_o[NUM_CPUS-1:0]),
    .gic_fiq_o                        (gic_fiq_o[NUM_CPUS-1:0]),
    .gic_virq_o                       (gic_virq_o[NUM_CPUS-1:0]),
    .gic_vfiq_o                       (gic_vfiq_o[NUM_CPUS-1:0]),
    .gov_sei_level_req_o              (gov_sei_level_req_o[NUM_CPUS-1:0]),
    .gov_vsei_level_req_o             (gov_vsei_level_req_o[NUM_CPUS-1:0]),
    .gov_rei_level_req_o              (gov_rei_level_req_o[NUM_CPUS-1:0]),
    .gov_int_active_o                 (gov_int_active_o[NUM_CPUS-1:0]),
    .gic_icc_sre_el1_ns_sre_o         (gic_icc_sre_el1_ns_sre_o[NUM_CPUS-1:0]),
    .gic_icc_sre_el1_s_sre_o          (gic_icc_sre_el1_s_sre_o[NUM_CPUS-1:0]),
    .gic_icc_sre_el2_enable_o         (gic_icc_sre_el2_enable_o[NUM_CPUS-1:0]),
    .gic_icc_sre_el2_sre_o            (gic_icc_sre_el2_sre_o[NUM_CPUS-1:0]),
    .gic_icc_sre_el3_enable_o         (gic_icc_sre_el3_enable_o[NUM_CPUS-1:0]),
    .gic_icc_sre_el3_sre_o            (gic_icc_sre_el3_sre_o[NUM_CPUS-1:0]),
    .gic_ich_hcr_el2_tall0_o          (gic_ich_hcr_el2_tall0_o[NUM_CPUS-1:0]),
    .gic_ich_hcr_el2_tall1_o          (gic_ich_hcr_el2_tall1_o[NUM_CPUS-1:0]),
    .gic_ich_hcr_el2_tc_o             (gic_ich_hcr_el2_tc_o[NUM_CPUS-1:0]),
    .nvcpumntirq_o                    (nvcpumntirq_o[NUM_CPUS-1:0]),
    .gov_periphbase_o                 (gov_periphbase_o[ 39:18]),
    .gov_giccdisable_o                (gov_giccdisable_o),
    .icdtready_o                      (icdtready_o),
    .icctvalid_o                      (icctvalid_o),
    .icctdata_o                       (icctdata_o[ 15:0]),
    .icctlast_o                       (icctlast_o),
    .icctid_o                         (icctid_o[ 1:0]),
    .gov_standbywfi_o                 (gov_standbywfi_o[NUM_CPUS-1:0]),
    .gov_standbywfe_o                 (gov_standbywfe_o[NUM_CPUS-1:0]),
    .standbywfi_o                     (standbywfi_o[NUM_CPUS-1:0]),
    .standbywfe_o                     (standbywfe_o[NUM_CPUS-1:0]),
    .standbywfil2_o                   (standbywfil2_o),
    .gov_wfx_drain_req_o              (gov_wfx_drain_req_o[NUM_CPUS-1: 0]),
    .gov_wfx_wake_o                   (gov_wfx_wake_o[NUM_CPUS-1: 0]),
    .clrexmonack_o                    (clrexmonack_o),
    .evento_o                         (evento_o),
    .gov_mbistreq_cpu_o               (gov_mbistreq_cpu_o[NUM_CPUS-1:0]),
    .gov_event_reg_o                  (gov_event_reg_o[NUM_CPUS-1:0]),
    .ncntpsirq_o                      (ncntpsirq_o[NUM_CPUS-1:0]),
    .ncntpnsirq_o                     (ncntpnsirq_o[NUM_CPUS-1:0]),
    .ncnthpirq_o                      (ncnthpirq_o[NUM_CPUS-1:0]),
    .ncntvirq_o                       (ncntvirq_o[NUM_CPUS-1:0]),
    .gov_smpen_o                      (gov_smpen_o[NUM_CPUS-1:0]),
    .cpuqactive_o                     (cpuqactive_o[NUM_CPUS-1:0]),
    .cpuqdeny_o                       (cpuqdeny_o[NUM_CPUS-1:0]),
    .cpuqacceptn_o                    (cpuqacceptn_o[NUM_CPUS-1:0]),
    .neonqactive_o                    (neonqactive_o[NUM_CPUS-1:0]),
    .neonqdeny_o                      (neonqdeny_o[NUM_CPUS-1:0]),
    .neonqacceptn_o                   (neonqacceptn_o[NUM_CPUS-1:0]),
    .l2qactive_o                      (l2qactive_o),
    .l2qdeny_o                        (l2qdeny_o),
    .l2qacceptn_o                     (l2qacceptn_o),
    .l2flushdone_o                    (l2flushdone_o),
    .nexterrirq_o                     (nexterrirq_o),
    .ninterrirq_o                     (ninterrirq_o),
    .scu_broadcastinner_o             (scu_broadcastinner_o[NUM_CPUS-1:0]),
    .scu_ext_ar_valid_o               (scu_ext_ar_valid_o),
    .scu_ext_ar_addr_o                (scu_ext_ar_addr_o[(`CA53_SCU_EXT_ADDR_W-1):0]),
    .scu_ext_ar_len_o                 (scu_ext_ar_len_o[(`CA53_ACE_ARLEN_W-1):0]),
    .scu_ext_ar_size_o                (scu_ext_ar_size_o[(`CA53_ACE_ARSIZE_W-1):0]),
    .scu_ext_ar_burst_o               (scu_ext_ar_burst_o[(`CA53_ACE_ARBURST_W-1):0]),
    .scu_ext_ar_lock_o                (scu_ext_ar_lock_o),
    .scu_ext_ar_cache_o               (scu_ext_ar_cache_o[(`CA53_ACE_ARCACHE_W-1):0]),
    .scu_ext_ar_prot_o                (scu_ext_ar_prot_o[(`CA53_ACE_ARPROT_W-1):0]),
    .scu_ext_ar_domain_o              (scu_ext_ar_domain_o[(`CA53_ACE_ARDOMAIN_W-1):0]),
    .scu_ext_ar_snoop_o               (scu_ext_ar_snoop_o[(`CA53_ACE_ARSNOOP_W-1):0]),
    .scu_ext_ar_bar_o                 (scu_ext_ar_bar_o[(`CA53_ACE_ARBAR_W-1):0]),
    .scu_ext_ar_id_o                  (scu_ext_ar_id_o[(`CA53_SCU_EXT_RID_W-1):0]),
    .scu_ext_rdmemattr_o              (scu_ext_rdmemattr_o[7:0]),
    .scu_ext_dr_ready_o               (scu_ext_dr_ready_o),
    .scu_ext_aw_valid_o               (scu_ext_aw_valid_o),
    .scu_ext_aw_addr_o                (scu_ext_aw_addr_o[(`CA53_SCU_EXT_ADDR_W-1):0]),
    .scu_ext_aw_len_o                 (scu_ext_aw_len_o[(`CA53_ACE_AWLEN_W-1):0]),
    .scu_ext_aw_size_o                (scu_ext_aw_size_o[(`CA53_ACE_AWSIZE_W-1):0]),
    .scu_ext_aw_burst_o               (scu_ext_aw_burst_o[(`CA53_ACE_AWBURST_W-1):0]),
    .scu_ext_aw_lock_o                (scu_ext_aw_lock_o),
    .scu_ext_aw_cache_o               (scu_ext_aw_cache_o[(`CA53_ACE_AWCACHE_W-1):0]),
    .scu_ext_aw_prot_o                (scu_ext_aw_prot_o[(`CA53_ACE_AWPROT_W-1):0]),
    .scu_ext_aw_id_o                  (scu_ext_aw_id_o[(`CA53_SCU_EXT_WID_W-1):0]),
    .scu_ext_aw_domain_o              (scu_ext_aw_domain_o[(`CA53_ACE_AWDOMAIN_W-1):0]),
    .scu_ext_aw_snoop_o               (scu_ext_aw_snoop_o[(`CA53_ACE_AWSNOOP_W-1):0]),
    .scu_ext_aw_bar_o                 (scu_ext_aw_bar_o[(`CA53_ACE_AWBAR_W-1):0]),
    .scu_ext_aw_unique_o              (scu_ext_aw_unique_o),
    .scu_ext_wrmemattr_o              (scu_ext_wrmemattr_o[7:0]),
    .scu_ext_dw_strb_o                (scu_ext_dw_strb_o[(`CA53_SCU_EXT_STRB_W-1):0]),
    .scu_ext_dw_data_o                (scu_ext_dw_data_o[(`CA53_SCU_EXT_DATA_W-1):0]),
    .scu_ext_dw_id_o                  (scu_ext_dw_id_o[(`CA53_SCU_EXT_WID_W-1):0]),
    .scu_ext_dw_last_o                (scu_ext_dw_last_o),
    .scu_ext_dw_valid_o               (scu_ext_dw_valid_o),
    .scu_ext_db_ready_o               (scu_ext_db_ready_o),
    .scu_ext_ac_ready_o               (scu_ext_ac_ready_o),
    .scu_ext_cr_valid_o               (scu_ext_cr_valid_o),
    .scu_ext_cr_resp_o                (scu_ext_cr_resp_o[(`CA53_ACE_CRRESP_W-1):0]),
    .scu_ext_cd_valid_o               (scu_ext_cd_valid_o),
    .scu_ext_cd_data_o                (scu_ext_cd_data_o[(`CA53_SCU_EXT_DATA_W-1):0]),
    .scu_ext_cd_last_o                (scu_ext_cd_last_o),
    .scu_ext_rack_o                   (scu_ext_rack_o),
    .scu_ext_wack_o                   (scu_ext_wack_o),
    .gov_pseldbg_dbg_o                (gov_pseldbg_dbg_o[NUM_CPUS-1:0]),
    .gov_pseldbg_pmu_o                (gov_pseldbg_pmu_o[NUM_CPUS-1:0]),
    .gov_pseldbg_etm_o                (gov_pseldbg_etm_o[NUM_CPUS-1:0]),
    .gov_paddrdbg_o                   (gov_paddrdbg_o[(`CA53_PADDRDBG_PKDED_W-1):0]),
    .gov_paddrdbg31_o                 (gov_paddrdbg31_o[NUM_CPUS-1:0]),
    .gov_penabledbg_o                 (gov_penabledbg_o[NUM_CPUS-1:0]),
    .gov_pwritedbg_o                  (gov_pwritedbg_o[NUM_CPUS-1:0]),
    .gov_pwdatadbg_o                  (gov_pwdatadbg_o[(`CA53_PWDATADBG_PKDED_W-1):0]),
    .scu_txsactive_o                  (scu_txsactive_o),
    .scu_rxlinkactiveack_o            (scu_rxlinkactiveack_o),
    .scu_txlinkactivereq_o            (scu_txlinkactivereq_o),
    .scu_txreqflitpend_o              (scu_txreqflitpend_o),
    .scu_txreqflitv_o                 (scu_txreqflitv_o),
    .scu_txreqflit_o                  (scu_txreqflit_o[99:0]),
    .scu_reqmemattr_o                 (scu_reqmemattr_o[7:0]),
    .scu_txrspflitpend_o              (scu_txrspflitpend_o),
    .scu_txrspflitv_o                 (scu_txrspflitv_o),
    .scu_txrspflit_o                  (scu_txrspflit_o[44:0]),
    .scu_txdatflitpend_o              (scu_txdatflitpend_o),
    .scu_txdatflitv_o                 (scu_txdatflitv_o),
    .scu_txdatflit_o                  (scu_txdatflit_o[193:0]),
    .scu_rxsnplcrdv_o                 (scu_rxsnplcrdv_o),
    .scu_rxrsplcrdv_o                 (scu_rxrsplcrdv_o),
    .scu_rxdatlcrdv_o                 (scu_rxdatlcrdv_o),
    .scu_acp_awready_o                (scu_acp_awready_o),
    .scu_acp_wready_o                 (scu_acp_wready_o),
    .scu_acp_bvalid_o                 (scu_acp_bvalid_o),
    .scu_acp_bid_o                    (scu_acp_bid_o[ 4:0]),
    .scu_acp_bresp_o                  (scu_acp_bresp_o[ 1:0]),
    .scu_acp_arready_o                (scu_acp_arready_o),
    .scu_acp_rvalid_o                 (scu_acp_rvalid_o),
    .scu_acp_rid_o                    (scu_acp_rid_o[ 4:0]),
    .scu_acp_rdata_o                  (scu_acp_rdata_o[127:0]),
    .scu_acp_rresp_o                  (scu_acp_rresp_o[ 1:0]),
    .scu_acp_rlast_o                  (scu_acp_rlast_o),
    .prdatadbg_o                      (prdatadbg_o[ 31:0]),
    .preadydbg_o                      (preadydbg_o),
    .pslverrdbg_o                     (pslverrdbg_o),
    .ncommirq_o                       (ncommirq_o[NUM_CPUS-1:0]),
    .dbgack_o                         (dbgack_o[NUM_CPUS-1:0]),
    .commrx_o                         (commrx_o[NUM_CPUS-1:0]),
    .commtx_o                         (commtx_o[NUM_CPUS-1:0]),
    .dbgrstreq_o                      (dbgrstreq_o[NUM_CPUS-1:0]),
    .dbgnopwrdwn_o                    (dbgnopwrdwn_o[NUM_CPUS-1:0]),
    .gov_dbgpwrupreq_o                (gov_dbgpwrupreq_o[NUM_CPUS-1:0]),
    .dbgpwrupreq_o                    (dbgpwrupreq_o[NUM_CPUS-1:0]),
    .gov_dbgl1rstdisable_o            (gov_dbgl1rstdisable_o[NUM_CPUS-1:0]),
    .gov_extin_o                      (gov_extin_o[(`CA53_ETMEXT_PKDED_W-1):0]),
    .gov_edecr_osuce_o                (gov_edecr_osuce_o[NUM_CPUS-1:0]),
    .gov_edecr_rce_o                  (gov_edecr_rce_o[NUM_CPUS-1:0]),
    .gov_edecr_ss_o                   (gov_edecr_ss_o[NUM_CPUS-1:0]),
    .gov_edlsr_slk_o                  (gov_edlsr_slk_o[NUM_CPUS-1:0]),
    .gov_pmlsr_slk_o                  (gov_pmlsr_slk_o[NUM_CPUS-1:0]),
    .gov_etmpdsr_rd_o                 (gov_etmpdsr_rd_o[NUM_CPUS-1:0]),
    .gov_dbgromaddr_o                 (gov_dbgromaddr_o[ 39:12]),
    .gov_dbgromaddrv_o                (gov_dbgromaddrv_o),
    .gov_edbgrq_o                     (gov_edbgrq_o[NUM_CPUS-1:0]),
    .gov_dbgen_o                      (gov_dbgen_o[NUM_CPUS-1:0]),
    .gov_spiden_o                     (gov_spiden_o[NUM_CPUS-1:0]),
    .gov_niden_o                      (gov_niden_o[NUM_CPUS-1:0]),
    .gov_spniden_o                    (gov_spniden_o[NUM_CPUS-1:0]),
    .gov_dbgrestart_o                 (gov_dbgrestart_o[NUM_CPUS-1:0]),
    .gov_stall_dsb_o                  (gov_stall_dsb_o[NUM_CPUS-1:0]),
    .gov_cp_ack_o                     (gov_cp_ack_o[NUM_CPUS-1:0]),
    .gov_cp_rdata_o                   (gov_cp_rdata_o[(`CA53_CPDATA_PKDED_W-1):0]),
    .gov_pcnt_kernel_access_o         (gov_pcnt_kernel_access_o[NUM_CPUS-1:0]),
    .gov_pcnt_usr_access_o            (gov_pcnt_usr_access_o[NUM_CPUS-1:0]),
    .gov_vcnt_usr_access_o            (gov_vcnt_usr_access_o[NUM_CPUS-1:0]),
    .gov_cntp_usr_access_o            (gov_cntp_usr_access_o[NUM_CPUS-1:0]),
    .gov_cntv_usr_access_o            (gov_cntv_usr_access_o[NUM_CPUS-1:0]),
    .gov_cntp_kernel_access_o         (gov_cntp_kernel_access_o[NUM_CPUS-1:0]),
    .gov_tsvalueb_o                   (gov_tsvalueb_o[63:0]),
    .gov_atclken_o                    (gov_atclken_o[NUM_CPUS-1: 0]),
    .gov_atreadym_o                   (gov_atreadym_o[(`CA53_ATREADYM_PKDED_W-1):0]),
    .gov_afvalidm_o                   (gov_afvalidm_o[(`CA53_AFVALIDM_PKDED_W-1):0]),
    .atdatam_o                        (atdatam_o[(`CA53_ATDATAM_PKDED_W-1):0]),
    .atvalidm_o                       (atvalidm_o[(`CA53_ATVALIDM_PKDED_W-1):0]),
    .atbytesm_o                       (atbytesm_o[(`CA53_ATBYTESM_PKDED_W-1):0]),
    .afreadym_o                       (afreadym_o[(`CA53_AFREADYM_PKDED_W-1):0]),
    .atidm_o                          (atidm_o[(`CA53_ATIDM_PKDED_W-1):0]),
    .gov_syncreqm_o                   (gov_syncreqm_o[(`CA53_SYNCREQM_PKDED_W-1):0]),
    .npmuirq_o                        (npmuirq_o[NUM_CPUS-1:0]),
    .pmuevent_o                       (pmuevent_o[(`CA53_PMUEVNT_PKDED_W-1):0]),
    .scu_ar_credit_o                  (scu_ar_credit_o[(`CA53_ARCREDIT_PKDED_W-1):0]),
    .scu_ar_block_o                   (scu_ar_block_o[(`CA53_ARBLOCK_PKDED_W-1):0]),
    .scu_dr_valid_o                   (scu_dr_valid_o[(`CA53_DRVALID_PKDED_W-1):0]),
    .scu_dr_id_o                      (scu_dr_id_o[(`CA53_DRID_PKDED_W-1):0]),
    .scu_dr_resp_o                    (scu_dr_resp_o[(`CA53_DRRESP_PKDED_W-1):0]),
    .scu_dr_chunk_o                   (scu_dr_chunk_o[(`CA53_DRCHUNK_PKDED_W-1):0]),
    .scu_dr_data_o                    (scu_dr_data_o[(`CA53_DRDATA_PKDED_W-1):0]),
    .scu_rr_valid_o                   (scu_rr_valid_o[(`CA53_RRVALID_PKDED_W-1):0]),
    .scu_rr_id_o                      (scu_rr_id_o[(`CA53_RRID_PKDED_W-1):0]),
    .scu_rr_resp_o                    (scu_rr_resp_o[(`CA53_RRRESP_PKDED_W-1):0]),
    .scu_rr_l2db_id_o                 (scu_rr_l2db_id_o[(`CA53_RRL2DB_PKDED_W-1):0]),
    .scu_ev_done_o                    (scu_ev_done_o[(`CA53_EVDONE_PKDED_W-1):0]),
    .scu_db_excl_valid_o              (scu_db_excl_valid_o[(`CA53_DBEXCLVAL_PKDED_W-1):0]),
    .scu_db_excl_resp_o               (scu_db_excl_resp_o[(`CA53_DBEXCLRSP_PKDED_W-1):0]),
    .scu_db_decerr_o                  (scu_db_decerr_o[(`CA53_DBDECERR_PKDED_W-1):0]),
    .scu_db_slverr_o                  (scu_db_slverr_o[(`CA53_DBSLVERR_PKDED_W-1):0]),
    .scu_leave_ramode_o               (scu_leave_ramode_o[(`CA53_LEAVERAM_PKDED_W-1):0]),
    .scu_ac_valid_o                   (scu_ac_valid_o[(`CA53_ACVALID_PKDED_W-1):0]),
    .scu_ac_id_o                      (scu_ac_id_o[(`CA53_ACID_PKDED_W-1):0]),
    .scu_ac_l2db_id_o                 (scu_ac_l2db_id_o[(`CA53_ACL2DB_PKDED_W-1):0]),
    .scu_ac_snoop_o                   (scu_ac_snoop_o[(`CA53_ACSNOOP_PKDED_W-1):0]),
    .scu_ac_addr_o                    (scu_ac_addr_o[(`CA53_ACADDR_PKDED_W-1):0]),
    .scu_ac_way_o                     (scu_ac_way_o[(`CA53_ACWAY_PKDED_W-1):0]),
    .scu_dvm_complete_o               (scu_dvm_complete_o[(`CA53_DVM_COMP_PKDED_W-1):0]),
    .scu_reqbufs_busy_o               (scu_reqbufs_busy_o[(`CA53_REQBUFS_BUSY_PKDED_W-1):0]),
    .scu_drain_stb_o                  (scu_drain_stb_o[(`CA53_DRAIN_STB_PKDED_W-1):0]),
    .scu_evnt_l2_access_o             (scu_evnt_l2_access_o[NUM_CPUS-1:0]),
    .scu_evnt_l2_refill_o             (scu_evnt_l2_refill_o[NUM_CPUS-1:0]),
    .scu_evnt_l2_wb_o                 (scu_evnt_l2_wb_o[NUM_CPUS-1:0]),
    .scu_evnt_snooped_data_o          (scu_evnt_snooped_data_o[NUM_CPUS-1:0]),
    .scu_evnt_bus_cycle_o             (scu_evnt_bus_cycle_o[NUM_CPUS-1:0]),
    .scu_evnt_bus_acc_rd_o            (scu_evnt_bus_acc_rd_o[NUM_CPUS-1:0]),
    .scu_evnt_bus_acc_wr_o            (scu_evnt_bus_acc_wr_o[NUM_CPUS-1:0]),
    .scu_evnt_eviction_o              (scu_evnt_eviction_o[NUM_CPUS-1:0]),
    .ctichout_o                       (ctichout_o[3:0]),
    .ctichinack_o                     (ctichinack_o[3:0]),
    .ctiirq_o                         (ctiirq_o[NUM_CPUS-1:0]),
    .mbistack0_o                      (mbistack0_o),
    .mbistack1_o                      (mbistack1_o),
    .mbistoutdata0_o                  (mbistoutdata0_o[(`CA53_MBIST0_DATA_W-1): 0]),
    .mbistoutdata1_o                  (mbistoutdata1_o[(`CA53_MBIST1_DATA_W-1): 0]),
    .l1d_tagram_clken_o               (l1d_tagram_clken),
    .l1d_tagram_cpu0_en_o             (l1d_tagram_cpu0_en[`CA53_SCU_L1D_ASSOC-1:0]),
    .l1d_tagram_cpu0_wr_o             (l1d_tagram_cpu0_wr),
    .l1d_tagram_cpu0_addr_o           (l1d_tagram_cpu0_addr[`CA53_SCU_L1D_TAGRAM_ADDR_W-1:0]),
    .l1d_tagram_cpu0_wdata_o          (l1d_tagram_cpu0_wdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu1_en_o             (l1d_tagram_cpu1_en[`CA53_SCU_L1D_ASSOC-1:0]),
    .l1d_tagram_cpu1_wr_o             (l1d_tagram_cpu1_wr),
    .l1d_tagram_cpu1_addr_o           (l1d_tagram_cpu1_addr[`CA53_SCU_L1D_TAGRAM_ADDR_W-1:0]),
    .l1d_tagram_cpu1_wdata_o          (l1d_tagram_cpu1_wdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu2_en_o             (l1d_tagram_cpu2_en[`CA53_SCU_L1D_ASSOC-1:0]),
    .l1d_tagram_cpu2_wr_o             (l1d_tagram_cpu2_wr),
    .l1d_tagram_cpu2_addr_o           (l1d_tagram_cpu2_addr[`CA53_SCU_L1D_TAGRAM_ADDR_W-1:0]),
    .l1d_tagram_cpu2_wdata_o          (l1d_tagram_cpu2_wdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu3_en_o             (l1d_tagram_cpu3_en[`CA53_SCU_L1D_ASSOC-1:0]),
    .l1d_tagram_cpu3_wr_o             (l1d_tagram_cpu3_wr),
    .l1d_tagram_cpu3_addr_o           (l1d_tagram_cpu3_addr[`CA53_SCU_L1D_TAGRAM_ADDR_W-1:0]),
    .l1d_tagram_cpu3_wdata_o          (l1d_tagram_cpu3_wdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l2_tagram_clken_o                (l2_tagram_clken),
    .l2_tagram_en_o                   (l2_tagram_en[`CA53_SCU_L2_ASSOC-1:0]),
    .l2_tagram_wr_o                   (l2_tagram_wr),
    .l2_tagram_addr_o                 (l2_tagram_addr[`CA53_SCU_L2_TAGRAM_ADDR_W-1:0]),
    .l2_tagram_wdata_o                (l2_tagram_wdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
    .l2_victimram_no_acc_next_cycle_o (l2_victimram_no_acc_next_cycle),
    .l2_victimram_clken_o             (l2_victimram_clken),
    .l2_victimram_en_o                (l2_victimram_en),
    .l2_victimram_wr_o                (l2_victimram_wr),
    .l2_victimram_strb_o              (l2_victimram_strb[`CA53_SCU_L2_VICTIMRAM_STRB_W-1:0]),
    .l2_victimram_addr_o              (l2_victimram_addr[`CA53_SCU_L2_VICTIMRAM_ADDR_W-1:0]),
    .l2_victimram_wdata_o             (l2_victimram_wdata[`CA53_SCU_L2_VICTIMRAM_DATA_W-1:0]),
    .l2_dataram_no_acc_next_cycle_o   (l2_dataram_no_acc_next_cycle),
    .l2_dataram_clken_o               (l2_dataram_clken[`CA53_SCU_L2_DATARAM_EN_W-1:0]),
    .l2_dataram_en_o                  (l2_dataram_en[`CA53_SCU_L2_DATARAM_EN_W-1:0]),
    .l2_dataram_wr_o                  (l2_dataram_wr),
    .l2_dataram_addr_o                (l2_dataram_addr[`CA53_SCU_L2_DATARAM_ADDR_W-1:0]),
    .l2_dataram_wdata0_o              (l2_dataram_wdata0[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
    .l2_dataram_wdata1_o              (l2_dataram_wdata1[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
    .l2_dataram_wdata2_o              (l2_dataram_wdata2[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
    .l2_dataram_wdata3_o              (l2_dataram_wdata3[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
    .l2_dataram_wdata4_o              (l2_dataram_wdata4[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
    .l2_dataram_wdata5_o              (l2_dataram_wdata5[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
    .l2_dataram_wdata6_o              (l2_dataram_wdata6[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
    .l2_dataram_wdata7_o              (l2_dataram_wdata7[`CA53_SCU_L2_DATARAM_DATA_W-1:0])
  );  // u_ca53_l2noram

  // ------------------------------------------------------
  // SCU snoop filter RAMs
  // ------------------------------------------------------

  ca53scu_l1d_tagrams `CA53_L1D_RAM_PARAM_INST u_ca53scu_l1d_tagrams (
    /*ARMAUTO*/
    // Inputs
    .clk                          (clk),
    .DFTSE                        (DFTSE),
    .l1_dc_size_i                 (l1_dc_size_i[`CA53_L1DC_SIZE_W-1:0]),
    .l1d_tagram_clken_i           (l1d_tagram_clken),
    .l1d_tagram_cpu0_en_i         (l1d_tagram_cpu0_en[`CA53_SCU_L1D_ASSOC-1:0]),
    .l1d_tagram_cpu0_wr_i         (l1d_tagram_cpu0_wr),
    .l1d_tagram_cpu0_addr_i       (l1d_tagram_cpu0_addr[`CA53_SCU_L1D_TAGRAM_ADDR_W-1:0]),
    .l1d_tagram_cpu0_wdata_i      (l1d_tagram_cpu0_wdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu1_en_i         (l1d_tagram_cpu1_en[`CA53_SCU_L1D_ASSOC-1:0]),
    .l1d_tagram_cpu1_wr_i         (l1d_tagram_cpu1_wr),
    .l1d_tagram_cpu1_addr_i       (l1d_tagram_cpu1_addr[`CA53_SCU_L1D_TAGRAM_ADDR_W-1:0]),
    .l1d_tagram_cpu1_wdata_i      (l1d_tagram_cpu1_wdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu2_en_i         (l1d_tagram_cpu2_en[`CA53_SCU_L1D_ASSOC-1:0]),
    .l1d_tagram_cpu2_wr_i         (l1d_tagram_cpu2_wr),
    .l1d_tagram_cpu2_addr_i       (l1d_tagram_cpu2_addr[`CA53_SCU_L1D_TAGRAM_ADDR_W-1:0]),
    .l1d_tagram_cpu2_wdata_i      (l1d_tagram_cpu2_wdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu3_en_i         (l1d_tagram_cpu3_en[`CA53_SCU_L1D_ASSOC-1:0]),
    .l1d_tagram_cpu3_wr_i         (l1d_tagram_cpu3_wr),
    .l1d_tagram_cpu3_addr_i       (l1d_tagram_cpu3_addr[`CA53_SCU_L1D_TAGRAM_ADDR_W-1:0]),
    .l1d_tagram_cpu3_wdata_i      (l1d_tagram_cpu3_wdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    // Outputs
    .l1d_tagram_cpu0_way0_rdata_o (l1d_tagram_cpu0_way0_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu0_way1_rdata_o (l1d_tagram_cpu0_way1_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu0_way2_rdata_o (l1d_tagram_cpu0_way2_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu0_way3_rdata_o (l1d_tagram_cpu0_way3_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu1_way0_rdata_o (l1d_tagram_cpu1_way0_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu1_way1_rdata_o (l1d_tagram_cpu1_way1_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu1_way2_rdata_o (l1d_tagram_cpu1_way2_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu1_way3_rdata_o (l1d_tagram_cpu1_way3_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu2_way0_rdata_o (l1d_tagram_cpu2_way0_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu2_way1_rdata_o (l1d_tagram_cpu2_way1_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu2_way2_rdata_o (l1d_tagram_cpu2_way2_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu2_way3_rdata_o (l1d_tagram_cpu2_way3_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu3_way0_rdata_o (l1d_tagram_cpu3_way0_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu3_way1_rdata_o (l1d_tagram_cpu3_way1_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu3_way2_rdata_o (l1d_tagram_cpu3_way2_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0]),
    .l1d_tagram_cpu3_way3_rdata_o (l1d_tagram_cpu3_way3_rdata[`CA53_SCU_L1D_TAGRAM_DATA_W-1:0])
  );  // u_ca53scu_l1d_tagrams

  // ------------------------------------------------------
  // L2 RAMs
  // ------------------------------------------------------

generate if (L2_CACHE) begin : g_l2_rams
    ca53_l2_tagrams `CA53_L2_RAM_PARAM_INST u_ca53_l2_tagrams (
      /*ARMAUTO*/
      // Inputs
      .clk                              (clk),
      .DFTSE                            (DFTSE),
      .l2_tagram_clken_i                (l2_tagram_clken),
      .l2_tagram_en_i                   (l2_tagram_en[`CA53_SCU_L2_ASSOC-1:0]),
      .l2_tagram_wr_i                   (l2_tagram_wr),
      .l2_tagram_addr_i                 (l2_tagram_addr[`CA53_SCU_L2_TAGRAM_ADDR_W-1:0]),
      .l2_tagram_wdata_i                (l2_tagram_wdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
      .l2_victimram_no_acc_next_cycle_i (l2_victimram_no_acc_next_cycle),
      .l2_victimram_clken_i             (l2_victimram_clken),
      .l2_victimram_en_i                (l2_victimram_en),
      .l2_victimram_wr_i                (l2_victimram_wr),
      .l2_victimram_strb_i              (l2_victimram_strb[`CA53_SCU_L2_VICTIMRAM_STRB_W-1:0]),
      .l2_victimram_addr_i              (l2_victimram_addr[`CA53_SCU_L2_VICTIMRAM_ADDR_W-1:0]),
      .l2_victimram_wdata_i             (l2_victimram_wdata[`CA53_SCU_L2_VICTIMRAM_DATA_W-1:0]),
      // Outputs
      .l2_size_o                        (l2_size[`CA53_L2_SIZE_W-1:0]),
      .l2_tagram_way0_rdata_o           (l2_tagram_way0_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
      .l2_tagram_way1_rdata_o           (l2_tagram_way1_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
      .l2_tagram_way2_rdata_o           (l2_tagram_way2_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
      .l2_tagram_way3_rdata_o           (l2_tagram_way3_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
      .l2_tagram_way4_rdata_o           (l2_tagram_way4_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
      .l2_tagram_way5_rdata_o           (l2_tagram_way5_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
      .l2_tagram_way6_rdata_o           (l2_tagram_way6_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
      .l2_tagram_way7_rdata_o           (l2_tagram_way7_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
      .l2_tagram_way8_rdata_o           (l2_tagram_way8_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
      .l2_tagram_way9_rdata_o           (l2_tagram_way9_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
      .l2_tagram_way10_rdata_o          (l2_tagram_way10_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
      .l2_tagram_way11_rdata_o          (l2_tagram_way11_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
      .l2_tagram_way12_rdata_o          (l2_tagram_way12_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
      .l2_tagram_way13_rdata_o          (l2_tagram_way13_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
      .l2_tagram_way14_rdata_o          (l2_tagram_way14_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
      .l2_tagram_way15_rdata_o          (l2_tagram_way15_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]),
      .l2_victimram_rdata_o             (l2_victimram_rdata[`CA53_SCU_L2_VICTIMRAM_DATA_W-1:0])
    );  // u_ca53_l2_tagrams

    ca53_l2_datarams `CA53_L2_RAM_PARAM_INST u_ca53_l2_datarams (
      /*ARMAUTO*/
      // Inputs
      .clk                            (clk),
      .DFTSE                          (DFTSE),
      .l2_size_i                      (l2_size[`CA53_L2_SIZE_W-1:0]),
      .l2_dataram_no_acc_next_cycle_i (l2_dataram_no_acc_next_cycle),
      .l2_dataram_clken_i             (l2_dataram_clken[`CA53_SCU_L2_DATARAM_EN_W-1:0]),
      .l2_dataram_en_i                (l2_dataram_en[`CA53_SCU_L2_DATARAM_EN_W-1:0]),
      .l2_dataram_wr_i                (l2_dataram_wr),
      .l2_dataram_addr_i              (l2_dataram_addr[`CA53_SCU_L2_DATARAM_ADDR_W-1:0]),
      .l2_dataram_wdata0_i            (l2_dataram_wdata0[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
      .l2_dataram_wdata1_i            (l2_dataram_wdata1[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
      .l2_dataram_wdata2_i            (l2_dataram_wdata2[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
      .l2_dataram_wdata3_i            (l2_dataram_wdata3[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
      .l2_dataram_wdata4_i            (l2_dataram_wdata4[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
      .l2_dataram_wdata5_i            (l2_dataram_wdata5[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
      .l2_dataram_wdata6_i            (l2_dataram_wdata6[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
      .l2_dataram_wdata7_i            (l2_dataram_wdata7[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
      // Outputs
      .l2_dataram_rdata0_o            (l2_dataram_rdata0[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
      .l2_dataram_rdata1_o            (l2_dataram_rdata1[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
      .l2_dataram_rdata2_o            (l2_dataram_rdata2[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
      .l2_dataram_rdata3_o            (l2_dataram_rdata3[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
      .l2_dataram_rdata4_o            (l2_dataram_rdata4[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
      .l2_dataram_rdata5_o            (l2_dataram_rdata5[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
      .l2_dataram_rdata6_o            (l2_dataram_rdata6[`CA53_SCU_L2_DATARAM_DATA_W-1:0]),
      .l2_dataram_rdata7_o            (l2_dataram_rdata7[`CA53_SCU_L2_DATARAM_DATA_W-1:0])
    );  // u_ca53_l2_datarams

end else begin : g_l2_ram_stubs

    /*ARMSTUB u_ca53_l2_tagrams*/
    assign l2_size[`CA53_L2_SIZE_W-1:0]                          = {`CA53_L2_SIZE_W{1'b0}};
    assign l2_tagram_way0_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]  = {`CA53_SCU_L2_TAGRAM_DATA_W{1'b0}};
    assign l2_tagram_way1_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]  = {`CA53_SCU_L2_TAGRAM_DATA_W{1'b0}};
    assign l2_tagram_way2_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]  = {`CA53_SCU_L2_TAGRAM_DATA_W{1'b0}};
    assign l2_tagram_way3_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]  = {`CA53_SCU_L2_TAGRAM_DATA_W{1'b0}};
    assign l2_tagram_way4_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]  = {`CA53_SCU_L2_TAGRAM_DATA_W{1'b0}};
    assign l2_tagram_way5_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]  = {`CA53_SCU_L2_TAGRAM_DATA_W{1'b0}};
    assign l2_tagram_way6_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]  = {`CA53_SCU_L2_TAGRAM_DATA_W{1'b0}};
    assign l2_tagram_way7_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]  = {`CA53_SCU_L2_TAGRAM_DATA_W{1'b0}};
    assign l2_tagram_way8_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]  = {`CA53_SCU_L2_TAGRAM_DATA_W{1'b0}};
    assign l2_tagram_way9_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0]  = {`CA53_SCU_L2_TAGRAM_DATA_W{1'b0}};
    assign l2_tagram_way10_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0] = {`CA53_SCU_L2_TAGRAM_DATA_W{1'b0}};
    assign l2_tagram_way11_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0] = {`CA53_SCU_L2_TAGRAM_DATA_W{1'b0}};
    assign l2_tagram_way12_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0] = {`CA53_SCU_L2_TAGRAM_DATA_W{1'b0}};
    assign l2_tagram_way13_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0] = {`CA53_SCU_L2_TAGRAM_DATA_W{1'b0}};
    assign l2_tagram_way14_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0] = {`CA53_SCU_L2_TAGRAM_DATA_W{1'b0}};
    assign l2_tagram_way15_rdata[`CA53_SCU_L2_TAGRAM_DATA_W-1:0] = {`CA53_SCU_L2_TAGRAM_DATA_W{1'b0}};
    assign l2_victimram_rdata[`CA53_SCU_L2_VICTIMRAM_DATA_W-1:0] = {`CA53_SCU_L2_VICTIMRAM_DATA_W{1'b0}};
    /*END*/
    /*ARMSTUB u_ca53_l2_datarams*/
    assign l2_dataram_rdata0[`CA53_SCU_L2_DATARAM_DATA_W-1:0] = {`CA53_SCU_L2_DATARAM_DATA_W{1'b0}};
    assign l2_dataram_rdata1[`CA53_SCU_L2_DATARAM_DATA_W-1:0] = {`CA53_SCU_L2_DATARAM_DATA_W{1'b0}};
    assign l2_dataram_rdata2[`CA53_SCU_L2_DATARAM_DATA_W-1:0] = {`CA53_SCU_L2_DATARAM_DATA_W{1'b0}};
    assign l2_dataram_rdata3[`CA53_SCU_L2_DATARAM_DATA_W-1:0] = {`CA53_SCU_L2_DATARAM_DATA_W{1'b0}};
    assign l2_dataram_rdata4[`CA53_SCU_L2_DATARAM_DATA_W-1:0] = {`CA53_SCU_L2_DATARAM_DATA_W{1'b0}};
    assign l2_dataram_rdata5[`CA53_SCU_L2_DATARAM_DATA_W-1:0] = {`CA53_SCU_L2_DATARAM_DATA_W{1'b0}};
    assign l2_dataram_rdata6[`CA53_SCU_L2_DATARAM_DATA_W-1:0] = {`CA53_SCU_L2_DATARAM_DATA_W{1'b0}};
    assign l2_dataram_rdata7[`CA53_SCU_L2_DATARAM_DATA_W-1:0] = {`CA53_SCU_L2_DATARAM_DATA_W{1'b0}};
    /*END*/

end endgenerate

  /*ARMASSIGN*/
  assign l2_size_o = l2_size[`CA53_L2_SIZE_W-1:0];
  /*END*/

endmodule // ca53_l2

/*ARMAUTO_UNDEF*/
`define CA53_UNDEFINE
`include "cortexa53params.v"
`include "ca53_ace_defs.v"
`include "ca53scu_defs.v"
`undef CA53_UNDEFINE
/*END*/
