/******************************************************************
*
* qspi_hclk_gen controller C MACRO generated by ezchip
*
******************************************************************/

#ifndef _QSPI_HCLK_GEN_MACRO_H_
#define _QSPI_HCLK_GEN_MACRO_H_

#ifdef VIRTUAL_ADDR
#else //VIRTUAL_ADDR
#endif //VIRTUAL_ADDR
#define _ENABLE_CLOCK_hclk_ {}

#endif //_QSPI_HCLK_GEN_MACRO_H_
