/****************************************************************
*
* module ez_clk_div_buf for sim generated by ezchip
* 
*
*****************************************************************/
module ez_clk_div_buf (
	input I,
	output Z
);
//ez_ckbuf U_EZ_CKBUF (
//	.O(Z),
//	.I(I)
//);
assign Z = I;
endmodule
