/******************************************************************
*
* module QSPI generated by ezchip
* 
*
******************************************************************/
// IC-Studio Root Head Start
// Please DO NOT modify by hand
module QSPI (
	 input qspi_psel_s
	,input [31:0] qspi_paddr_s
	,input qspi_penable_s
	,input [31:0] qspi_pwdata_s
	,input qspi_pwrite_s
	,input systop_warmresetn_s
	,input qspi_pclk
	,input qspi_presetn
	,input qspi_rx_dma_ack
	,input qspi_tx_dma_ack
	,output [31:0] qspi_prdata_s
	,output qspi_pready_s
	,output qspi_boot_intr
	,output qspi_rx_dma_req
	,output qspi_tx_dma_req
	,inout X_qspi_holdn
	,inout X_qspi_wpn
	,inout X_qspi_clk
	,inout X_qspi_csn
	,inout X_qspi_miso
	,inout X_qspi_mosi
	,input [31:0] xnvm_araddr
	,input [1:0] xnvm_arburst
	,input [3:0] xnvm_arcache
	,input [11:0] xnvm_arid
	,input [7:0] xnvm_arlen
	,input xnvm_arlock
	,input [2:0] xnvm_arprot
	,input [2:0] xnvm_arsize
	,input xnvm_arvalid
	,input [31:0] xnvm_awaddr
	,input [1:0] xnvm_awburst
	,input [3:0] xnvm_awcache
	,input [11:0] xnvm_awid
	,input [7:0] xnvm_awlen
	,input xnvm_awlock
	,input [2:0] xnvm_awprot
	,input [2:0] xnvm_awsize
	,input xnvm_awvalid
	,input xnvm_bready
	,input xnvm_rready
	,input [63:0] xnvm_wdata
	,input xnvm_wlast
	,input [7:0] xnvm_wstrb
	,input xnvm_wvalid
	,input aclkout
	,output xnvm_arready
	,output xnvm_awready
	,output [11:0] xnvm_bid
	,output [1:0] xnvm_bresp
	,output xnvm_bvalid
	,output [63:0] xnvm_rdata
	,output [11:0] xnvm_rid
	,output xnvm_rlast
	,output [1:0] xnvm_rresp
	,output xnvm_rvalid
	,output xnvm_wready
);


`ifdef __QSPI_EMPTY__
	assign qspi_prdata_s = 32'h0;
	assign qspi_pready_s = 1'h0;
	assign xnvm_arready = 1'h0;
	assign xnvm_awready = 1'h0;
	assign xnvm_bid = 12'h0;
	assign xnvm_bresp = 2'h0;
	assign xnvm_bvalid = 1'h0;
	assign xnvm_rdata = 64'h0;
	assign xnvm_rid = 12'h0;
	assign xnvm_rlast = 1'h0;
	assign xnvm_rresp = 2'h0;
	assign xnvm_rvalid = 1'h0;
	assign xnvm_wready = 1'h0;
	assign qspi_boot_intr = 1'h0;
	assign qspi_rx_dma_req = 1'h0;
	assign qspi_tx_dma_req = 1'h0;
`else
wire ez_QSPI_0_qspi_psel_s_w;
wire [31:0] ez_QSPI_0_qspi_paddr_s_w;
wire ez_QSPI_0_qspi_penable_s_w;
wire [31:0] ez_QSPI_0_qspi_pwdata_s_w;
wire ez_QSPI_0_qspi_pwrite_s_w;
wire [31:0] ez_u0_atcspi200_103_prdata_w;
wire ez_u0_atcspi200_103_pready_w;
wire ez_QSPI_0_systop_warmresetn_s_w;
wire ez_spi_holdn_pad_105_O_w;
wire ez_u0_atcspi200_103_spi_hold_n_out_w;
wire ez_u0_atcspi200_103_spi_hold_n_oe_w;
wire ez_u0_atcspi200_103_spi_wp_n_oe_w;
wire ez_u0_atcspi200_103_spi_wp_n_out_w;
wire ez_spi_wpn_pad_106_O_w;
wire ez_u0_atcspi200_103_spi_clk_oe_w;
wire ez_u0_atcspi200_103_spi_clk_out_w;
wire ez_spi_clk_pad_107_O_w;
wire ez_u0_atcspi200_103_spi_cs_n_oe_w;
wire ez_u0_atcspi200_103_spi_cs_n_out_w;
wire ez_spi_csn_pad_108_O_w;
wire ez_u0_atcspi200_103_spi_miso_oe_w;
wire ez_u0_atcspi200_103_spi_miso_out_w;
wire ez_spi_miso_pad_109_O_w;
wire ez_u0_atcspi200_103_spi_mosi_oe_w;
wire ez_u0_atcspi200_103_spi_mosi_out_w;
wire ez_spi_mosi_pad_110_O_w;
wire ez_u0_atcspi200_103_spi_boot_intr_w;
wire ez_QSPI_0_qspi_pclk_w;
wire ez_QSPI_0_qspi_presetn_w;
wire ez_QSPI_0_qspi_rx_dma_ack_w;
wire ez_u0_atcspi200_103_spi_rx_dma_req_w;
wire ez_QSPI_0_qspi_tx_dma_ack_w;
wire ez_u0_atcspi200_103_spi_tx_dma_req_w;
wire ez_spi_holdn_pad_105_IO_w;
wire ez_spi_wpn_pad_106_IO_w;
wire ez_spi_clk_pad_107_IO_w;
wire ez_spi_csn_pad_108_IO_w;
wire ez_spi_miso_pad_109_IO_w;
wire ez_spi_mosi_pad_110_IO_w;
wire ez_u0_DW_axi_x2h_114_awready_w;
wire ez_u0_nic400_sse710_integration_example_f0_flash_113_awvalid_xnvm_axi_m_w;
wire [11:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_awid_xnvm_axi_m_w;
wire [31:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_awaddr_xnvm_axi_m_w;
wire [7:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_awlen_xnvm_axi_m_w;
wire [2:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_awsize_xnvm_axi_m_w;
wire [1:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_awburst_xnvm_axi_m_w;
wire ez_u0_nic400_sse710_integration_example_f0_flash_113_awlock_xnvm_axi_m_w;
wire [3:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_awcache_xnvm_axi_m_w;
wire [2:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_awprot_xnvm_axi_m_w;
wire ez_u0_DW_axi_x2h_114_wready_w;
wire ez_u0_nic400_sse710_integration_example_f0_flash_113_wvalid_xnvm_axi_m_w;
wire [127:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_wdata_xnvm_axi_m_w;
wire [15:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_wstrb_xnvm_axi_m_w;
wire ez_u0_nic400_sse710_integration_example_f0_flash_113_wlast_xnvm_axi_m_w;
wire ez_u0_nic400_sse710_integration_example_f0_flash_113_bready_xnvm_axi_m_w;
wire ez_u0_DW_axi_x2h_114_bvalid_w;
wire [11:0] ez_u0_DW_axi_x2h_114_bid_w;
wire [1:0] ez_u0_DW_axi_x2h_114_bresp_w;
wire ez_u0_DW_axi_x2h_114_arready_w;
wire ez_u0_nic400_sse710_integration_example_f0_flash_113_arvalid_xnvm_axi_m_w;
wire [11:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_arid_xnvm_axi_m_w;
wire [31:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_araddr_xnvm_axi_m_w;
wire [7:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_arlen_xnvm_axi_m_w;
wire [2:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_arsize_xnvm_axi_m_w;
wire [1:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_arburst_xnvm_axi_m_w;
wire ez_u0_nic400_sse710_integration_example_f0_flash_113_arlock_xnvm_axi_m_w;
wire [3:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_arcache_xnvm_axi_m_w;
wire [2:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_arprot_xnvm_axi_m_w;
wire ez_u0_nic400_sse710_integration_example_f0_flash_113_rready_xnvm_axi_m_w;
wire ez_u0_DW_axi_x2h_114_rvalid_w;
wire [11:0] ez_u0_DW_axi_x2h_114_rid_w;
wire [127:0] ez_u0_DW_axi_x2h_114_rdata_w;
wire [1:0] ez_u0_DW_axi_x2h_114_rresp_w;
wire ez_u0_DW_axi_x2h_114_rlast_w;
wire [31:0] ez_u0_DW_axi_x2h_114_mhaddr_w;
wire ez_u0_DW_axi_x2h_114_mhwrite_w;
wire [1:0] ez_u0_DW_axi_x2h_114_mhtrans_w;
wire [31:0] ez_u0_atcspi200_103_hrdata_mem_w;
wire [1:0] ez_u0_atcspi200_103_hresp_mem_w;
wire ez_u0_atcspi200_103_hreadyout_mem_w;
wire ez_QSPI_0_xnvm_wvalid_w;
wire [7:0] ez_QSPI_0_xnvm_wstrb_w;
wire ez_u0_nic400_sse710_integration_example_f0_flash_113_wready_xnvm_axi_s_w;
wire ez_QSPI_0_xnvm_wlast_w;
wire [63:0] ez_QSPI_0_xnvm_wdata_w;
wire ez_u0_nic400_sse710_integration_example_f0_flash_113_rvalid_xnvm_axi_s_w;
wire [1:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_rresp_xnvm_axi_s_w;
wire ez_QSPI_0_xnvm_rready_w;
wire ez_u0_nic400_sse710_integration_example_f0_flash_113_rlast_xnvm_axi_s_w;
wire [11:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_rid_xnvm_axi_s_w;
wire [63:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_rdata_xnvm_axi_s_w;
wire ez_u0_nic400_sse710_integration_example_f0_flash_113_bvalid_xnvm_axi_s_w;
wire [1:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_bresp_xnvm_axi_s_w;
wire ez_QSPI_0_xnvm_bready_w;
wire [11:0] ez_u0_nic400_sse710_integration_example_f0_flash_113_bid_xnvm_axi_s_w;
wire ez_QSPI_0_xnvm_awvalid_w;
wire [2:0] ez_QSPI_0_xnvm_awsize_w;
wire ez_u0_nic400_sse710_integration_example_f0_flash_113_awready_xnvm_axi_s_w;
wire [2:0] ez_QSPI_0_xnvm_awprot_w;
wire ez_QSPI_0_xnvm_awlock_w;
wire [7:0] ez_QSPI_0_xnvm_awlen_w;
wire [11:0] ez_QSPI_0_xnvm_awid_w;
wire [3:0] ez_QSPI_0_xnvm_awcache_w;
wire [1:0] ez_QSPI_0_xnvm_awburst_w;
wire [31:0] ez_QSPI_0_xnvm_awaddr_w;
wire ez_QSPI_0_xnvm_arvalid_w;
wire [2:0] ez_QSPI_0_xnvm_arsize_w;
wire ez_u0_nic400_sse710_integration_example_f0_flash_113_arready_xnvm_axi_s_w;
wire [2:0] ez_QSPI_0_xnvm_arprot_w;
wire ez_QSPI_0_xnvm_arlock_w;
wire [7:0] ez_QSPI_0_xnvm_arlen_w;
wire [11:0] ez_QSPI_0_xnvm_arid_w;
wire [3:0] ez_QSPI_0_xnvm_arcache_w;
wire [1:0] ez_QSPI_0_xnvm_arburst_w;
wire [31:0] ez_QSPI_0_xnvm_araddr_w;
wire ez_QSPI_0_aclkout_w;
wire ez_u0_qspi_hclk_gen_116_hclk_w;


assign qspi_prdata_s = ez_u0_atcspi200_103_prdata_w;
assign qspi_pready_s = ez_u0_atcspi200_103_pready_w;
assign xnvm_arready = ez_u0_nic400_sse710_integration_example_f0_flash_113_arready_xnvm_axi_s_w;
assign xnvm_awready = ez_u0_nic400_sse710_integration_example_f0_flash_113_awready_xnvm_axi_s_w;
assign xnvm_bid = ez_u0_nic400_sse710_integration_example_f0_flash_113_bid_xnvm_axi_s_w;
assign xnvm_bresp = ez_u0_nic400_sse710_integration_example_f0_flash_113_bresp_xnvm_axi_s_w;
assign xnvm_bvalid = ez_u0_nic400_sse710_integration_example_f0_flash_113_bvalid_xnvm_axi_s_w;
assign xnvm_rdata = ez_u0_nic400_sse710_integration_example_f0_flash_113_rdata_xnvm_axi_s_w;
assign xnvm_rid = ez_u0_nic400_sse710_integration_example_f0_flash_113_rid_xnvm_axi_s_w;
assign xnvm_rlast = ez_u0_nic400_sse710_integration_example_f0_flash_113_rlast_xnvm_axi_s_w;
assign xnvm_rresp = ez_u0_nic400_sse710_integration_example_f0_flash_113_rresp_xnvm_axi_s_w;
assign xnvm_rvalid = ez_u0_nic400_sse710_integration_example_f0_flash_113_rvalid_xnvm_axi_s_w;
assign xnvm_wready = ez_u0_nic400_sse710_integration_example_f0_flash_113_wready_xnvm_axi_s_w;
assign qspi_boot_intr = ez_u0_atcspi200_103_spi_boot_intr_w;
assign qspi_rx_dma_req = ez_u0_atcspi200_103_spi_rx_dma_req_w;
assign qspi_tx_dma_req = ez_u0_atcspi200_103_spi_tx_dma_req_w;
assign ez_QSPI_0_qspi_psel_s_w = qspi_psel_s;
assign ez_QSPI_0_qspi_paddr_s_w = qspi_paddr_s;
assign ez_QSPI_0_qspi_penable_s_w = qspi_penable_s;
assign ez_QSPI_0_qspi_pwdata_s_w = qspi_pwdata_s;
assign ez_QSPI_0_qspi_pwrite_s_w = qspi_pwrite_s;
assign ez_QSPI_0_xnvm_araddr_w = xnvm_araddr;
assign ez_QSPI_0_xnvm_arburst_w = xnvm_arburst;
assign ez_QSPI_0_xnvm_arcache_w = xnvm_arcache;
assign ez_QSPI_0_xnvm_arid_w = xnvm_arid;
assign ez_QSPI_0_xnvm_arlen_w = xnvm_arlen;
assign ez_QSPI_0_xnvm_arlock_w = xnvm_arlock;
assign ez_QSPI_0_xnvm_arprot_w = xnvm_arprot;
assign ez_QSPI_0_xnvm_arsize_w = xnvm_arsize;
assign ez_QSPI_0_xnvm_arvalid_w = xnvm_arvalid;
assign ez_QSPI_0_xnvm_awaddr_w = xnvm_awaddr;
assign ez_QSPI_0_xnvm_awburst_w = xnvm_awburst;
assign ez_QSPI_0_xnvm_awcache_w = xnvm_awcache;
assign ez_QSPI_0_xnvm_awid_w = xnvm_awid;
assign ez_QSPI_0_xnvm_awlen_w = xnvm_awlen;
assign ez_QSPI_0_xnvm_awlock_w = xnvm_awlock;
assign ez_QSPI_0_xnvm_awprot_w = xnvm_awprot;
assign ez_QSPI_0_xnvm_awsize_w = xnvm_awsize;
assign ez_QSPI_0_xnvm_awvalid_w = xnvm_awvalid;
assign ez_QSPI_0_xnvm_bready_w = xnvm_bready;
assign ez_QSPI_0_xnvm_rready_w = xnvm_rready;
assign ez_QSPI_0_xnvm_wdata_w = xnvm_wdata;
assign ez_QSPI_0_xnvm_wlast_w = xnvm_wlast;
assign ez_QSPI_0_xnvm_wstrb_w = xnvm_wstrb;
assign ez_QSPI_0_xnvm_wvalid_w = xnvm_wvalid;
assign ez_QSPI_0_aclkout_w =aclkout;
assign ez_QSPI_0_systop_warmresetn_s_w =systop_warmresetn_s;
assign ez_QSPI_0_qspi_pclk_w =qspi_pclk;
assign ez_QSPI_0_qspi_presetn_w = qspi_presetn;
assign ez_QSPI_0_qspi_rx_dma_ack_w = qspi_rx_dma_ack;
assign ez_QSPI_0_qspi_tx_dma_ack_w = qspi_tx_dma_ack;


`ifndef _EMPTY_INST_103_   //QSPI.u0_atcspi200
atcspi200 u0_atcspi200
(
	.apb2ahb_clken( 1'h1 ),
	.haddr_mem( ez_u0_DW_axi_x2h_114_mhaddr_w ),
	.hclk( ez_QSPI_0_qspi_pclk_w ),
	.hrdata_mem( ez_u0_atcspi200_103_hrdata_mem_w ),
	.hreadyin_mem( ez_u0_atcspi200_103_hreadyout_mem_w ),
	.hreadyout_mem( ez_u0_atcspi200_103_hreadyout_mem_w ),
	.hresetn( ez_QSPI_0_systop_warmresetn_s_w ),
	.hresp_mem( ez_u0_atcspi200_103_hresp_mem_w ),
	.hsel_mem( 1'h1 ),
	.htrans_mem( ez_u0_DW_axi_x2h_114_mhtrans_w ),
	.hwrite_mem( ez_u0_DW_axi_x2h_114_mhwrite_w ),
	.paddr( ez_QSPI_0_qspi_paddr_s_w ),
	.pclk( ez_QSPI_0_qspi_pclk_w ),
	.penable( ez_QSPI_0_qspi_penable_s_w ),
	.prdata( ez_u0_atcspi200_103_prdata_w ),
	.pready( ez_u0_atcspi200_103_pready_w ),
	.presetn( ez_QSPI_0_qspi_presetn_w ),
	.psel( ez_QSPI_0_qspi_psel_s_w ),
	.pwdata( ez_QSPI_0_qspi_pwdata_s_w ),
	.pwrite( ez_QSPI_0_qspi_pwrite_s_w ),
	.scan_enable( 1'h0 ),
	.scan_test( 1'h0 ),
	.spi_boot_intr( ez_u0_atcspi200_103_spi_boot_intr_w ),
	.spi_clk_in( ez_spi_clk_pad_107_O_w ),
	.spi_clk_oe( ez_u0_atcspi200_103_spi_clk_oe_w ),
	.spi_clk_out( ez_u0_atcspi200_103_spi_clk_out_w ),
	.spi_clock( ez_u0_qspi_hclk_gen_116_hclk_w ),
	.spi_cs_n_in( ez_spi_csn_pad_108_O_w ),
	.spi_cs_n_oe( ez_u0_atcspi200_103_spi_cs_n_oe_w ),
	.spi_cs_n_out( ez_u0_atcspi200_103_spi_cs_n_out_w ),
	.spi_default_as_slave( 1'h0 ),
	.spi_default_mode3( 1'h0 ),
	.spi_hold_n_in( ez_spi_holdn_pad_105_O_w ),
	.spi_hold_n_oe( ez_u0_atcspi200_103_spi_hold_n_oe_w ),
	.spi_hold_n_out( ez_u0_atcspi200_103_spi_hold_n_out_w ),
	.spi_miso_in( ez_spi_miso_pad_109_O_w ),
	.spi_miso_oe( ez_u0_atcspi200_103_spi_miso_oe_w ),
	.spi_miso_out( ez_u0_atcspi200_103_spi_miso_out_w ),
	.spi_mosi_in( ez_spi_mosi_pad_110_O_w ),
	.spi_mosi_oe( ez_u0_atcspi200_103_spi_mosi_oe_w ),
	.spi_mosi_out( ez_u0_atcspi200_103_spi_mosi_out_w ),
	.spi_rstn( ez_QSPI_0_systop_warmresetn_s_w ),
	.spi_rx_dma_ack( ez_QSPI_0_qspi_rx_dma_ack_w ),
	.spi_rx_dma_req( ez_u0_atcspi200_103_spi_rx_dma_req_w ),
	.spi_tx_dma_ack( ez_QSPI_0_qspi_tx_dma_ack_w ),
	.spi_tx_dma_req( ez_u0_atcspi200_103_spi_tx_dma_req_w ),
	.spi_wp_n_in( ez_spi_wpn_pad_106_O_w ),
	.spi_wp_n_oe( ez_u0_atcspi200_103_spi_wp_n_oe_w ),
	.spi_wp_n_out( ez_u0_atcspi200_103_spi_wp_n_out_w )
);

`else
assign hrdata_mem = 32'b0;
assign hreadyout_mem = 1'b0;
assign hresp_mem = 2'b0;
assign prdata = 32'b0;
assign pready = 1'b0;
assign spi_boot_intr = 1'b0;
assign spi_clk_oe = 1'b0;
assign spi_clk_out = 1'b0;
assign spi_cs_n_oe = 1'b0;
assign spi_cs_n_out = 1'b0;
assign spi_hold_n_oe = 1'b0;
assign spi_hold_n_out = 1'b0;
assign spi_miso_oe = 1'b0;
assign spi_miso_out = 1'b0;
assign spi_mosi_oe = 1'b0;
assign spi_mosi_out = 1'b0;
assign spi_rx_dma_req = 1'b0;
assign spi_tx_dma_req = 1'b0;
assign spi_wp_n_oe = 1'b0;
assign spi_wp_n_out = 1'b0;
`endif
spi_inout_pad u0_spi_pad
(
	.ez_spi_holdn_pad_105_O_w( ez_spi_holdn_pad_105_O_w ),
	.ez_u0_atcspi200_103_spi_hold_n_out_w( ez_u0_atcspi200_103_spi_hold_n_out_w ),
	.ez_u0_atcspi200_103_spi_hold_n_oe_w( ez_u0_atcspi200_103_spi_hold_n_oe_w ),
	.ez_u0_atcspi200_103_spi_wp_n_oe_w( ez_u0_atcspi200_103_spi_wp_n_oe_w ),
	.ez_u0_atcspi200_103_spi_wp_n_out_w( ez_u0_atcspi200_103_spi_wp_n_out_w ),
	.ez_spi_wpn_pad_106_O_w( ez_spi_wpn_pad_106_O_w ),
	.ez_u0_atcspi200_103_spi_clk_oe_w( ez_u0_atcspi200_103_spi_clk_oe_w ),
	.ez_u0_atcspi200_103_spi_clk_out_w( ez_u0_atcspi200_103_spi_clk_out_w ),
	.ez_spi_clk_pad_107_O_w( ez_spi_clk_pad_107_O_w ),
	.ez_u0_atcspi200_103_spi_cs_n_oe_w( ez_u0_atcspi200_103_spi_cs_n_oe_w ),
	.ez_u0_atcspi200_103_spi_cs_n_out_w( ez_u0_atcspi200_103_spi_cs_n_out_w ),
	.ez_spi_csn_pad_108_O_w( ez_spi_csn_pad_108_O_w ),
	.ez_u0_atcspi200_103_spi_miso_oe_w( ez_u0_atcspi200_103_spi_miso_oe_w ),
	.ez_u0_atcspi200_103_spi_miso_out_w( ez_u0_atcspi200_103_spi_miso_out_w ),
	.ez_spi_miso_pad_109_O_w( ez_spi_miso_pad_109_O_w ),
	.ez_u0_atcspi200_103_spi_mosi_oe_w( ez_u0_atcspi200_103_spi_mosi_oe_w ),
	.ez_u0_atcspi200_103_spi_mosi_out_w( ez_u0_atcspi200_103_spi_mosi_out_w ),
	.ez_spi_mosi_pad_110_O_w( ez_spi_mosi_pad_110_O_w ),
	.ez_spi_holdn_pad_105_IO_w( X_qspi_holdn ),
	.ez_spi_wpn_pad_106_IO_w( X_qspi_wpn ),
	.ez_spi_clk_pad_107_IO_w( X_qspi_clk ),
	.ez_spi_csn_pad_108_IO_w( X_qspi_csn ),
	.ez_spi_miso_pad_109_IO_w( X_qspi_miso ),
	.ez_spi_mosi_pad_110_IO_w( X_qspi_mosi )
);

`ifndef _EMPTY_INST_113_   //QSPI.u0_nic400_sse710_integration_example_f0_flash
nic400_sse710_integration_example_f0_flash u0_nic400_sse710_integration_example_f0_flash
(
	.aclkoutclk( ez_QSPI_0_aclkout_w ),
	.aclkoutresetn( ez_QSPI_0_systop_warmresetn_s_w ),
	.araddr_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_araddr_xnvm_axi_m_w ),
	.araddr_xnvm_axi_s( ez_QSPI_0_xnvm_araddr_w ),
	.arburst_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_arburst_xnvm_axi_m_w ),
	.arburst_xnvm_axi_s( ez_QSPI_0_xnvm_arburst_w ),
	.arcache_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_arcache_xnvm_axi_m_w ),
	.arcache_xnvm_axi_s( ez_QSPI_0_xnvm_arcache_w ),
	.arid_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_arid_xnvm_axi_m_w ),
	.arid_xnvm_axi_s( ez_QSPI_0_xnvm_arid_w ),
	.arlen_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_arlen_xnvm_axi_m_w ),
	.arlen_xnvm_axi_s( ez_QSPI_0_xnvm_arlen_w ),
	.arlock_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_arlock_xnvm_axi_m_w ),
	.arlock_xnvm_axi_s( ez_QSPI_0_xnvm_arlock_w ),
	.arprot_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_arprot_xnvm_axi_m_w ),
	.arprot_xnvm_axi_s( ez_QSPI_0_xnvm_arprot_w ),
	.arready_xnvm_axi_m( ez_u0_DW_axi_x2h_114_arready_w ),
	.arready_xnvm_axi_s( ez_u0_nic400_sse710_integration_example_f0_flash_113_arready_xnvm_axi_s_w ),
	.arsize_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_arsize_xnvm_axi_m_w ),
	.arsize_xnvm_axi_s( ez_QSPI_0_xnvm_arsize_w ),
	.arvalid_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_arvalid_xnvm_axi_m_w ),
	.arvalid_xnvm_axi_s( ez_QSPI_0_xnvm_arvalid_w ),
	.awaddr_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_awaddr_xnvm_axi_m_w ),
	.awaddr_xnvm_axi_s( ez_QSPI_0_xnvm_awaddr_w ),
	.awburst_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_awburst_xnvm_axi_m_w ),
	.awburst_xnvm_axi_s( ez_QSPI_0_xnvm_awburst_w ),
	.awcache_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_awcache_xnvm_axi_m_w ),
	.awcache_xnvm_axi_s( ez_QSPI_0_xnvm_awcache_w ),
	.awid_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_awid_xnvm_axi_m_w ),
	.awid_xnvm_axi_s( ez_QSPI_0_xnvm_awid_w ),
	.awlen_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_awlen_xnvm_axi_m_w ),
	.awlen_xnvm_axi_s( ez_QSPI_0_xnvm_awlen_w ),
	.awlock_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_awlock_xnvm_axi_m_w ),
	.awlock_xnvm_axi_s( ez_QSPI_0_xnvm_awlock_w ),
	.awprot_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_awprot_xnvm_axi_m_w ),
	.awprot_xnvm_axi_s( ez_QSPI_0_xnvm_awprot_w ),
	.awready_xnvm_axi_m( ez_u0_DW_axi_x2h_114_awready_w ),
	.awready_xnvm_axi_s( ez_u0_nic400_sse710_integration_example_f0_flash_113_awready_xnvm_axi_s_w ),
	.awsize_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_awsize_xnvm_axi_m_w ),
	.awsize_xnvm_axi_s( ez_QSPI_0_xnvm_awsize_w ),
	.awvalid_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_awvalid_xnvm_axi_m_w ),
	.awvalid_xnvm_axi_s( ez_QSPI_0_xnvm_awvalid_w ),
	.bid_xnvm_axi_m( ez_u0_DW_axi_x2h_114_bid_w ),
	.bid_xnvm_axi_s( ez_u0_nic400_sse710_integration_example_f0_flash_113_bid_xnvm_axi_s_w ),
	.bready_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_bready_xnvm_axi_m_w ),
	.bready_xnvm_axi_s( ez_QSPI_0_xnvm_bready_w ),
	.bresp_xnvm_axi_m( ez_u0_DW_axi_x2h_114_bresp_w ),
	.bresp_xnvm_axi_s( ez_u0_nic400_sse710_integration_example_f0_flash_113_bresp_xnvm_axi_s_w ),
	.bvalid_xnvm_axi_m( ez_u0_DW_axi_x2h_114_bvalid_w ),
	.bvalid_xnvm_axi_s( ez_u0_nic400_sse710_integration_example_f0_flash_113_bvalid_xnvm_axi_s_w ),
	.rdata_xnvm_axi_m( ez_u0_DW_axi_x2h_114_rdata_w ),
	.rdata_xnvm_axi_s( ez_u0_nic400_sse710_integration_example_f0_flash_113_rdata_xnvm_axi_s_w ),
	.rid_xnvm_axi_m( ez_u0_DW_axi_x2h_114_rid_w ),
	.rid_xnvm_axi_s( ez_u0_nic400_sse710_integration_example_f0_flash_113_rid_xnvm_axi_s_w ),
	.rlast_xnvm_axi_m( ez_u0_DW_axi_x2h_114_rlast_w ),
	.rlast_xnvm_axi_s( ez_u0_nic400_sse710_integration_example_f0_flash_113_rlast_xnvm_axi_s_w ),
	.rready_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_rready_xnvm_axi_m_w ),
	.rready_xnvm_axi_s( ez_QSPI_0_xnvm_rready_w ),
	.rresp_xnvm_axi_m( ez_u0_DW_axi_x2h_114_rresp_w ),
	.rresp_xnvm_axi_s( ez_u0_nic400_sse710_integration_example_f0_flash_113_rresp_xnvm_axi_s_w ),
	.rvalid_xnvm_axi_m( ez_u0_DW_axi_x2h_114_rvalid_w ),
	.rvalid_xnvm_axi_s( ez_u0_nic400_sse710_integration_example_f0_flash_113_rvalid_xnvm_axi_s_w ),
	.wdata_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_wdata_xnvm_axi_m_w ),
	.wdata_xnvm_axi_s( ez_QSPI_0_xnvm_wdata_w ),
	.wlast_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_wlast_xnvm_axi_m_w ),
	.wlast_xnvm_axi_s( ez_QSPI_0_xnvm_wlast_w ),
	.wready_xnvm_axi_m( ez_u0_DW_axi_x2h_114_wready_w ),
	.wready_xnvm_axi_s( ez_u0_nic400_sse710_integration_example_f0_flash_113_wready_xnvm_axi_s_w ),
	.wstrb_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_wstrb_xnvm_axi_m_w ),
	.wstrb_xnvm_axi_s( ez_QSPI_0_xnvm_wstrb_w ),
	.wvalid_xnvm_axi_m( ez_u0_nic400_sse710_integration_example_f0_flash_113_wvalid_xnvm_axi_m_w ),
	.wvalid_xnvm_axi_s( ez_QSPI_0_xnvm_wvalid_w )
);

`else
assign araddr_xnvm_axi_m = 32'b0;
assign arburst_xnvm_axi_m = 2'b0;
assign arcache_xnvm_axi_m = 4'b0;
assign arid_xnvm_axi_m = 12'b0;
assign arlen_xnvm_axi_m = 8'b0;
assign arlock_xnvm_axi_m = 1'b0;
assign arprot_xnvm_axi_m = 3'b0;
assign arready_xnvm_axi_s = 1'b0;
assign arsize_xnvm_axi_m = 3'b0;
assign arvalid_xnvm_axi_m = 1'b0;
assign awaddr_xnvm_axi_m = 32'b0;
assign awburst_xnvm_axi_m = 2'b0;
assign awcache_xnvm_axi_m = 4'b0;
assign awid_xnvm_axi_m = 12'b0;
assign awlen_xnvm_axi_m = 8'b0;
assign awlock_xnvm_axi_m = 1'b0;
assign awprot_xnvm_axi_m = 3'b0;
assign awready_xnvm_axi_s = 1'b0;
assign awsize_xnvm_axi_m = 3'b0;
assign awvalid_xnvm_axi_m = 1'b0;
assign bid_xnvm_axi_s = 12'b0;
assign bready_xnvm_axi_m = 1'b0;
assign bresp_xnvm_axi_s = 2'b0;
assign bvalid_xnvm_axi_s = 1'b0;
assign rdata_xnvm_axi_s = 64'b0;
assign rid_xnvm_axi_s = 12'b0;
assign rlast_xnvm_axi_s = 1'b0;
assign rready_xnvm_axi_m = 1'b0;
assign rresp_xnvm_axi_s = 2'b0;
assign rvalid_xnvm_axi_s = 1'b0;
assign wdata_xnvm_axi_m = 128'b0;
assign wlast_xnvm_axi_m = 1'b0;
assign wready_xnvm_axi_s = 1'b0;
assign wstrb_xnvm_axi_m = 16'b0;
assign wvalid_xnvm_axi_m = 1'b0;
`endif
`ifndef _EMPTY_INST_114_   //QSPI.u0_DW_axi_x2h
DW_axi_x2h u0_DW_axi_x2h
(
	.aclk( ez_QSPI_0_aclkout_w ),
	.araddr( ez_u0_nic400_sse710_integration_example_f0_flash_113_araddr_xnvm_axi_m_w ),
	.arburst( ez_u0_nic400_sse710_integration_example_f0_flash_113_arburst_xnvm_axi_m_w ),
	.arcache( ez_u0_nic400_sse710_integration_example_f0_flash_113_arcache_xnvm_axi_m_w ),
	.aresetn( ez_QSPI_0_systop_warmresetn_s_w ),
	.arid( ez_u0_nic400_sse710_integration_example_f0_flash_113_arid_xnvm_axi_m_w ),
	.arlen( ez_u0_nic400_sse710_integration_example_f0_flash_113_arlen_xnvm_axi_m_w ),
	.arlock( ez_u0_nic400_sse710_integration_example_f0_flash_113_arlock_xnvm_axi_m_w ),
	.arprot( ez_u0_nic400_sse710_integration_example_f0_flash_113_arprot_xnvm_axi_m_w ),
	.arready( ez_u0_DW_axi_x2h_114_arready_w ),
	.arsize( ez_u0_nic400_sse710_integration_example_f0_flash_113_arsize_xnvm_axi_m_w ),
	.arvalid( ez_u0_nic400_sse710_integration_example_f0_flash_113_arvalid_xnvm_axi_m_w ),
	.awaddr( ez_u0_nic400_sse710_integration_example_f0_flash_113_awaddr_xnvm_axi_m_w ),
	.awburst( ez_u0_nic400_sse710_integration_example_f0_flash_113_awburst_xnvm_axi_m_w ),
	.awcache( ez_u0_nic400_sse710_integration_example_f0_flash_113_awcache_xnvm_axi_m_w ),
	.awid( ez_u0_nic400_sse710_integration_example_f0_flash_113_awid_xnvm_axi_m_w ),
	.awlen( ez_u0_nic400_sse710_integration_example_f0_flash_113_awlen_xnvm_axi_m_w ),
	.awlock( ez_u0_nic400_sse710_integration_example_f0_flash_113_awlock_xnvm_axi_m_w ),
	.awprot( ez_u0_nic400_sse710_integration_example_f0_flash_113_awprot_xnvm_axi_m_w ),
	.awready( ez_u0_DW_axi_x2h_114_awready_w ),
	.awsize( ez_u0_nic400_sse710_integration_example_f0_flash_113_awsize_xnvm_axi_m_w ),
	.awvalid( ez_u0_nic400_sse710_integration_example_f0_flash_113_awvalid_xnvm_axi_m_w ),
	.bid( ez_u0_DW_axi_x2h_114_bid_w ),
	.bready( ez_u0_nic400_sse710_integration_example_f0_flash_113_bready_xnvm_axi_m_w ),
	.bresp( ez_u0_DW_axi_x2h_114_bresp_w ),
	.bvalid( ez_u0_DW_axi_x2h_114_bvalid_w ),
	.mhaddr( ez_u0_DW_axi_x2h_114_mhaddr_w ),
	.mhburst(  ),
	.mhclk( ez_QSPI_0_qspi_pclk_w ),
	.mhlock(  ),
	.mhprot(  ),
	.mhrdata( ez_u0_atcspi200_103_hrdata_mem_w ),
	.mhready( ez_u0_atcspi200_103_hreadyout_mem_w ),
	.mhresetn( ez_QSPI_0_systop_warmresetn_s_w ),
	.mhresp( ez_u0_atcspi200_103_hresp_mem_w ),
	.mhsize(  ),
	.mhtrans( ez_u0_DW_axi_x2h_114_mhtrans_w ),
	.mhwdata(  ),
	.mhwrite( ez_u0_DW_axi_x2h_114_mhwrite_w ),
	.rdata( ez_u0_DW_axi_x2h_114_rdata_w ),
	.rid( ez_u0_DW_axi_x2h_114_rid_w ),
	.rlast( ez_u0_DW_axi_x2h_114_rlast_w ),
	.rready( ez_u0_nic400_sse710_integration_example_f0_flash_113_rready_xnvm_axi_m_w ),
	.rresp( ez_u0_DW_axi_x2h_114_rresp_w ),
	.rvalid( ez_u0_DW_axi_x2h_114_rvalid_w ),
	.wdata( ez_u0_nic400_sse710_integration_example_f0_flash_113_wdata_xnvm_axi_m_w ),
	.wlast( ez_u0_nic400_sse710_integration_example_f0_flash_113_wlast_xnvm_axi_m_w ),
	.wready( ez_u0_DW_axi_x2h_114_wready_w ),
	.wstrb( ez_u0_nic400_sse710_integration_example_f0_flash_113_wstrb_xnvm_axi_m_w ),
	.wvalid( ez_u0_nic400_sse710_integration_example_f0_flash_113_wvalid_xnvm_axi_m_w )
);

`else
assign arready = 1'b0;
assign awready = 1'b0;
assign bid = 12'b0;
assign bresp = 2'b0;
assign bvalid = 1'b0;
assign mhaddr = 32'b0;
assign mhtrans = 2'b0;
assign mhwrite = 1'b0;
assign rdata = 128'b0;
assign rid = 12'b0;
assign rlast = 1'b0;
assign rresp = 2'b0;
assign rvalid = 1'b0;
assign wready = 1'b0;
`endif
`ifndef _EMPTY_INST_116_   //QSPI.u0_qspi_hclk_gen
qspi_hclk_gen_top u0_qspi_hclk_gen
(
	.hclk( ez_u0_qspi_hclk_gen_116_hclk_w ),
	.aclk( ez_QSPI_0_aclkout_w ),
	.hclk_div( 4'h4 ),
	.test_en( 1'h0 ),
	.scan_en( 1'h0 ),
	.resetn( ez_QSPI_0_systop_warmresetn_s_w )
);

`else
assign hclk = 1'b0;
`endif

`endif


endmodule