/******************************************************************
*
* module spi_inout_pad generated by ezchip
* 
*
******************************************************************/
// IC-Studio Root Head Start
// Please DO NOT modify by hand
module spi_inout_pad (
inout ez_spi_clk_pad_107_IO_w,
inout ez_spi_csn_pad_108_IO_w,
inout ez_spi_holdn_pad_105_IO_w,
inout ez_spi_miso_pad_109_IO_w,
inout ez_spi_mosi_pad_110_IO_w,
inout ez_spi_wpn_pad_106_IO_w,
input ez_u0_atcspi200_103_spi_clk_oe_w,
input ez_u0_atcspi200_103_spi_clk_out_w,
input ez_u0_atcspi200_103_spi_cs_n_oe_w,
input ez_u0_atcspi200_103_spi_cs_n_out_w,
input ez_u0_atcspi200_103_spi_hold_n_oe_w,
input ez_u0_atcspi200_103_spi_hold_n_out_w,
input ez_u0_atcspi200_103_spi_miso_oe_w,
input ez_u0_atcspi200_103_spi_miso_out_w,
input ez_u0_atcspi200_103_spi_mosi_oe_w,
input ez_u0_atcspi200_103_spi_mosi_out_w,
input ez_u0_atcspi200_103_spi_wp_n_oe_w,
input ez_u0_atcspi200_103_spi_wp_n_out_w,
output ez_spi_clk_pad_107_O_w,
output ez_spi_csn_pad_108_O_w,
output ez_spi_holdn_pad_105_O_w,
output ez_spi_miso_pad_109_O_w,
output ez_spi_mosi_pad_110_O_w,
output ez_spi_wpn_pad_106_O_w
);


`ifdef __SPI_INOUT_PAD_EMPTY__
	assign ez_spi_holdn_pad_105_O_w = 1'h0;
	assign ez_spi_wpn_pad_106_O_w = 1'h0;
	assign ez_spi_clk_pad_107_O_w = 1'h0;
	assign ez_spi_csn_pad_108_O_w = 1'h0;
	assign ez_spi_miso_pad_109_O_w = 1'h0;
	assign ez_spi_mosi_pad_110_O_w = 1'h0;
`else


`ifndef _EMPTY_INST_105_   //QSPI.u0_spi_pad.spi_holdn_pad
nds_inout_pad spi_holdn_pad
(
	.E( ez_u0_atcspi200_103_spi_hold_n_oe_w ),
	.I( ez_u0_atcspi200_103_spi_hold_n_out_w ),
	.IO( ez_spi_holdn_pad_105_IO_w ),
	.O( ez_spi_holdn_pad_105_O_w ),
	.PD( 1'h0 ),
	.PU( 1'h0 )
);

`else
assign O = 1'b0;
`endif
`ifndef _EMPTY_INST_106_   //QSPI.u0_spi_pad.spi_wpn_pad
nds_inout_pad spi_wpn_pad
(
	.E( ez_u0_atcspi200_103_spi_wp_n_oe_w ),
	.I( ez_u0_atcspi200_103_spi_wp_n_out_w ),
	.IO( ez_spi_wpn_pad_106_IO_w ),
	.O( ez_spi_wpn_pad_106_O_w ),
	.PD( 1'h0 ),
	.PU( 1'h0 )
);

`else
assign O = 1'b0;
`endif
`ifndef _EMPTY_INST_107_   //QSPI.u0_spi_pad.spi_clk_pad
nds_inout_pad spi_clk_pad
(
	.E( ez_u0_atcspi200_103_spi_clk_oe_w ),
	.I( ez_u0_atcspi200_103_spi_clk_out_w ),
	.IO( ez_spi_clk_pad_107_IO_w ),
	.O( ez_spi_clk_pad_107_O_w ),
	.PD( 1'h0 ),
	.PU( 1'h0 )
);

`else
assign O = 1'b0;
`endif
`ifndef _EMPTY_INST_108_   //QSPI.u0_spi_pad.spi_csn_pad
nds_inout_pad spi_csn_pad
(
	.E( ez_u0_atcspi200_103_spi_cs_n_oe_w ),
	.I( ez_u0_atcspi200_103_spi_cs_n_out_w ),
	.IO( ez_spi_csn_pad_108_IO_w ),
	.O( ez_spi_csn_pad_108_O_w ),
	.PD( 1'h0 ),
	.PU( 1'h0 )
);

`else
assign O = 1'b0;
`endif
`ifndef _EMPTY_INST_109_   //QSPI.u0_spi_pad.spi_miso_pad
nds_inout_pad spi_miso_pad
(
	.E( ez_u0_atcspi200_103_spi_miso_oe_w ),
	.I( ez_u0_atcspi200_103_spi_miso_out_w ),
	.IO( ez_spi_miso_pad_109_IO_w ),
	.O( ez_spi_miso_pad_109_O_w ),
	.PD( 1'h0 ),
	.PU( 1'h0 )
);

`else
assign O = 1'b0;
`endif
`ifndef _EMPTY_INST_110_   //QSPI.u0_spi_pad.spi_mosi_pad
nds_inout_pad spi_mosi_pad
(
	.E( ez_u0_atcspi200_103_spi_mosi_oe_w ),
	.I( ez_u0_atcspi200_103_spi_mosi_out_w ),
	.IO( ez_spi_mosi_pad_110_IO_w ),
	.O( ez_spi_mosi_pad_110_O_w ),
	.PD( 1'h0 ),
	.PU( 1'h0 )
);

`else
assign O = 1'b0;
`endif

`endif


endmodule