//------------------------------------------------------------------------------
// The confidential and proprietary information contained in this file may
// only be used by a person authorised under and to the extent permitted
// by a subsisting licensing agreement from Arm Limited or its affiliates.
//
//            (C) COPYRIGHT 2019-2021 Arm Limited or its affiliates.
//                ALL RIGHTS RESERVED
//
// This entire notice must be reproduced on all copies of this file
// and copies of this file may only be made by a person if such person is
// permitted to do so under the terms of a subsisting license agreement
// from Arm Limited or its affiliates.
//
//
//      Release Information : SSE710-r0p0-00eac0
//
//------------------------------------------------------------------------------
// Verilog-2001 (IEEE Std 1364-2001)
//------------------------------------------------------------------------------

module firewall_f0_comp_dp #(
  parameter FC_MST_ID_SINGLE_MST = 0,
  parameter FC_TE_LVL           = 0,
  parameter FC_RSE_LVL          = 0,
  parameter FC_PE_LVL           = 2,
  parameter FC_ME_LVL           = 0,
  parameter FW_SE_LVL           = 1,
  parameter FC_INST_SPT         = 0,
  parameter FC_ADDR_WIDTH       = 64,
  parameter FC_AXIDATA_WIDTH    = 64,
  parameter FC_AXIID_WIDTH      = 9 ,
  parameter FC_MST_ID_WIDTH     = 8,
  parameter FC_AXIUSER_AR_WIDTH = 2,
  parameter FC_AXIUSER_R_WIDTH  = 2,
  parameter FC_AXIUSER_AW_WIDTH = 2,
  parameter FC_AXIUSER_W_WIDTH  = 2,
  parameter FC_AXIUSER_B_WIDTH  = 2,
  parameter TRACKER_PAYLOAD_WIDTH_AR = 2,
  parameter TRACKER_PAYLOAD_WIDTH_AW = 2,
  parameter FC_NUM_RGN          = 4,
  parameter LOG2_FC_NUM_RGN     = 2,
  parameter FC_NUM_MPE          = 4,
  parameter FC_MNRS             = 7'h0, 
  parameter FC_MXRS             = 7'h8,  
  parameter FC_SINGLE_MST       = 1,
  parameter FC_NUM_MST_ID       = 4,
  parameter FC_ID               = 1,
  parameter [FC_MST_ID_WIDTH*FC_NUM_MST_ID-1:0] FC_MST_ID_VAL = {FC_NUM_MST_ID*FC_MST_ID_WIDTH{1'b0}},
  parameter [FC_AXIDATA_WIDTH*FC_NUM_MST_ID-1:0] FC_ERR_RESP_PER_MST_ID = {FC_NUM_MST_ID*FC_AXIDATA_WIDTH{1'b0}},
  parameter [FC_AXIDATA_WIDTH-1:0] FC_ERR_RESP_DEF = {FC_AXIDATA_WIDTH{1'b0}},
  parameter FC_PRIV_SPT        = 0,
  parameter FC_SEC_SPT         = 1,
  parameter FC_NUM_READ_OS     = 4,
  parameter FC_NUM_WRITE_OS    = 4,
  parameter FC_AXI_READ_RESP_INTRLV  = 1,
  `include "firewall_f0_reg_width_params.vh"

) (
    input  wire                       clk,
    input  wire                       reset_n,

    input  wire [FC_AXIID_WIDTH-1:0]              arid_s_i    ,
    input  wire [FC_ADDR_WIDTH-1:0]               araddr_s_i  ,
    input  wire [7:0]                             arlen_s_i   ,
    input  wire [2:0]                             arsize_s_i  ,
    input  wire [1:0]                             arburst_s_i ,
    input  wire                                   arlock_s_i  ,
    input  wire [3:0]                             arcache_s_i ,
    input  wire [2:0]                             arprot_s_i  ,
    input  wire [3:0]                             arqos_s_i   ,
    input  wire [3:0]                             arregion_s_i,
    input  wire [FC_AXIUSER_AR_WIDTH-1:0]         aruser_s_i  ,
    input  wire                                   arvalid_s_i ,
    output wire                                   arready_s_o ,
    input  wire [FC_MST_ID_WIDTH-1:0]             armmusid_s_i,

    input  wire [FC_AXIID_WIDTH-1:0]              awid_s_i    ,
    input  wire [FC_ADDR_WIDTH-1:0]               awaddr_s_i  ,
    input  wire [7:0]                             awlen_s_i   ,
    input  wire [2:0]                             awsize_s_i  ,
    input  wire [1:0]                             awburst_s_i ,
    input  wire                                   awlock_s_i  ,
    input  wire [3:0]                             awcache_s_i ,
    input  wire [2:0]                             awprot_s_i  ,
    input  wire [3:0]                             awqos_s_i   ,
    input  wire [3:0]                             awregion_s_i,
    input  wire [FC_AXIUSER_AW_WIDTH-1:0]         awuser_s_i  ,
    input  wire                                   awvalid_s_i ,
    output wire                                   awready_s_o ,
    input  wire [FC_MST_ID_WIDTH-1:0]             awmmusid_s_i,

    input  wire [FC_AXIDATA_WIDTH-1:0]            wdata_s_i   ,
    input  wire [FC_AXIDATA_WIDTH/8-1:0]          wstrb_s_i   ,
    input  wire                                   wlast_s_i   ,
    input  wire [FC_AXIUSER_W_WIDTH-1:0]          wuser_s_i   ,
    input  wire                                   wvalid_s_i  ,
    output wire                                   wready_s_o  ,

    output wire [FC_AXIID_WIDTH-1:0]              bid_s_o     ,
    output wire [1:0]                             bresp_s_o   ,
    output wire [FC_AXIUSER_B_WIDTH-1:0]          buser_s_o   ,
    output wire                                   bvalid_s_o  ,
    input  wire                                   bready_s_i  ,

    output wire [FC_AXIID_WIDTH-1:0]              rid_s_o     ,
    output wire [FC_AXIDATA_WIDTH-1:0]            rdata_s_o   ,
    output wire [1:0]                             rresp_s_o   ,
    output wire                                   rlast_s_o   ,
    output wire [FC_AXIUSER_R_WIDTH-1:0]          ruser_s_o   ,
    output wire                                   rvalid_s_o  ,
    input  wire                                   rready_s_i  ,

    input  wire                                   awakeup_s_i  ,

    output wire [FC_AXIID_WIDTH-1:0]              arid_m_o    ,
    output wire [FC_ADDR_WIDTH-1:0]               araddr_m_o  ,
    output wire [7:0]                             arlen_m_o   ,
    output wire [2:0]                             arsize_m_o  ,
    output wire [1:0]                             arburst_m_o ,
    output wire                                   arlock_m_o  ,
    output wire [3:0]                             arcache_m_o ,
    output wire [2:0]                             arprot_m_o  ,
    output wire [3:0]                             arqos_m_o   ,
    output wire [3:0]                             arregion_m_o,
    output wire [FC_AXIUSER_AR_WIDTH-1:0]         aruser_m_o  ,
    output wire                                   arvalid_m_o ,
    input  wire                                   arready_m_i ,
    output wire [FC_MST_ID_WIDTH-1:0]             armmusid_m_o,

    output wire [FC_AXIID_WIDTH-1:0]              awid_m_o    ,
    output wire [FC_ADDR_WIDTH-1:0]               awaddr_m_o  ,
    output wire [7:0]                             awlen_m_o   ,
    output wire [2:0]                             awsize_m_o  ,
    output wire [1:0]                             awburst_m_o ,
    output wire                                   awlock_m_o  ,
    output wire [3:0]                             awcache_m_o ,
    output wire [2:0]                             awprot_m_o  ,
    output wire [3:0]                             awqos_m_o   ,
    output wire [3:0]                             awregion_m_o,
    output wire [FC_AXIUSER_AW_WIDTH-1:0]         awuser_m_o  ,
    output wire                                   awvalid_m_o ,
    input  wire                                   awready_m_i ,
    output wire [FC_MST_ID_WIDTH-1:0]             awmmusid_m_o,

    output wire [FC_AXIDATA_WIDTH-1:0]            wdata_m_o   ,
    output wire [FC_AXIDATA_WIDTH/8-1:0]          wstrb_m_o   ,
    output wire                                   wlast_m_o   ,
    output wire [FC_AXIUSER_W_WIDTH-1:0]          wuser_m_o   ,
    output wire                                   wvalid_m_o  ,
    input  wire                                   wready_m_i  ,

    input  wire [FC_AXIID_WIDTH-1:0]              bid_m_i     ,
    input  wire [1:0]                             bresp_m_i   ,
    input  wire [FC_AXIUSER_B_WIDTH-1:0]          buser_m_i   ,
    input  wire                                   bvalid_m_i  ,
    output wire                                   bready_m_o  ,

    input  wire [FC_AXIID_WIDTH-1:0]              rid_m_i     ,
    input  wire [FC_AXIDATA_WIDTH-1:0]            rdata_m_i   ,
    input  wire [1:0]                             rresp_m_i   ,
    input  wire                                   rlast_m_i   ,
    input  wire [FC_AXIUSER_R_WIDTH-1:0]          ruser_m_i   ,
    input  wire                                   rvalid_m_i  ,
    output wire                                   rready_m_o  ,

    output wire                                   awakeup_m_o ,

    input  wire                                   tracker_al_empty_rd_i,
    input  wire                                   tracker_al_empty_wr_i,
    input  wire                                   tracker_empty_rd_i,
    input  wire                                   tracker_empty_wr_i,

    output wire [FC_AXIID_WIDTH-1:0]              tracker_id_rd_ch_o,
    output wire [FC_AXIID_WIDTH-1:0]              tracker_id_wr_ch_o,
    output wire                                   tracker_read_rd_ch_o,
    output wire                                   tracker_read_wr_ch_o,
    input  wire [TRACKER_PAYLOAD_WIDTH_AR-1:0]    tracker_dout_rd_ch_i,
    input  wire [TRACKER_PAYLOAD_WIDTH_AW-1:0]    tracker_dout_wr_ch_i,
    input wire                                    tracker_dout_rd_ch_vld_i,
    input wire                                    tracker_dout_wr_ch_vld_i,


    input  wire                                    rb_me_st_rdum_i ,
    input  wire                                    rb_pe_st_err_i , 
    input  wire [1:0]                              rb_pe_st_err_raz_i , 
    input  wire [1:0]                              rb_pe_st_flt_cfg_i, 
    input  wire                                    rb_pe_st_en_i,

    output wire [FE_TAL_WIDTH-1:0]                 rb_fe_rd_tal_o,
    output wire [FE_TAU_WIDTH-1:0]                 rb_fe_rd_tau_o,
    output wire [FE_TP_WIDTH-1:0]                  rb_fe_rd_tp_o,
    output wire [FC_MST_ID_WIDTH-1:0]              rb_fe_rd_mid_o,
    output wire                                    rb_fe_rd_valid_o,
    output wire                                    rb_fe_rd_type_o,  
    output wire                                    rb_tmp_reg_err_rd,

    output wire [FE_TAL_WIDTH-1:0]                 rb_fe_wr_tal_o,
    output wire [FE_TAU_WIDTH-1:0]                 rb_fe_wr_tau_o,
    output wire [FE_TP_WIDTH-1:0]                  rb_fe_wr_tp_o,
    output wire [FC_MST_ID_WIDTH-1:0]              rb_fe_wr_mid_o,
    output wire                                    rb_fe_wr_valid_o,
    output wire                                    rb_fe_wr_type_o,  
    output wire                                    rb_tmp_reg_err_wr,

    input  wire [PROT_SIZE_WIDTH-1:0]              rb_prot_size_i,
    input  wire                                    rb_bypass_i,
    input  wire                                    rb_sram_rdy_i,
    input  wire [1:0]                              rb_fw_st_i,

    input  wire                                    rb_st_me_en_i,
    output wire                                    rd_edr_wen_o,       
    output wire [31:0]                             rd_edr_addr_lwr_o,  
    output wire [31:0]                             rd_edr_addr_uppr_o, 
    output wire [FC_MST_ID_WIDTH+4-1:0]            rd_edr_prop_o,      
    output wire                                    wr_edr_wen_o,       
    output wire [31:0]                             wr_edr_addr_lwr_o,  
    output wire [31:0]                             wr_edr_addr_uppr_o, 
    output wire [FC_MST_ID_WIDTH+4-1:0]            wr_edr_prop_o,      
    input  wire [(FC_NUM_RGN*RGN_TCFG0_WIDTH)-1:0] rb_cfg_rgn_tcfg0_i,
    input  wire [(FC_NUM_RGN*RGN_TCFG1_WIDTH)-1:0] rb_cfg_rgn_tcfg1_i,
    input  wire [(FC_NUM_RGN*RGN_TCFG2_WIDTH)-1:0] rb_cfg_rgn_tcfg2_i,

    input  wire [(FC_NUM_RGN*RGN_ST_WIDTH)-1:0]    rb_rgn_st_i,
    input  wire [(FC_NUM_RGN*RGN_SIZE_WIDTH)-1:0]  rb_rgn_size_i,
    input  wire [(FC_NUM_RGN*FC_MXRS)-1:0]         rb_rgn_base_addr_i,
    input  wire [(FC_NUM_RGN*FC_MXRS)-1:0]         rb_rgn_upper_addr_i,

    input  wire [(FC_NUM_RGN*FC_MST_ID_WIDTH)-1:0]  rb_rgn_mid0_i,
    input  wire [(FC_NUM_RGN*FC_MST_ID_WIDTH)-1:0]  rb_rgn_mid1_i,
    input  wire [(FC_NUM_RGN*FC_MST_ID_WIDTH)-1:0]  rb_rgn_mid2_i,
    input  wire [(FC_NUM_RGN*FC_MST_ID_WIDTH)-1:0]  rb_rgn_mid3_i,

    input  wire [(FC_NUM_RGN*RGN_MPL0_WIDTH)-1:0]  rb_rgn_mpl0_i,
    input  wire [(FC_NUM_RGN*RGN_MPL1_WIDTH)-1:0]  rb_rgn_mpl1_i,
    input  wire [(FC_NUM_RGN*RGN_MPL2_WIDTH)-1:0]  rb_rgn_mpl2_i,
    input  wire [(FC_NUM_RGN*RGN_MPL3_WIDTH)-1:0]  rb_rgn_mpl3_i,

    input  wire [FC_AXIID_WIDTH-1:0]               bid_pchk_i     ,
    input  wire [1:0]                              bresp_pchk_i   ,
    input  wire [FC_AXIUSER_B_WIDTH-1:0]           buser_pchk_i   ,
    input  wire                                    bvalid_pchk_i  ,
    output wire                                    bready_pchk_o  ,

    input  wire [FC_AXIID_WIDTH-1:0]               bid_cfg_i     ,
    input  wire [1:0]                              bresp_cfg_i   ,
    input  wire [FC_AXIUSER_B_WIDTH-1:0]           buser_cfg_i   ,
    input  wire                                    bvalid_cfg_i  ,
    output wire                                    bready_cfg_o  ,

    input  wire [FC_AXIID_WIDTH-1:0]               rid_pchk_i     ,
    input  wire [FC_AXIDATA_WIDTH-1:0]             rdata_pchk_i   ,
    input  wire [1:0]                              rresp_pchk_i   ,
    input  wire                                    rlast_pchk_i   ,
    input  wire [FC_AXIUSER_R_WIDTH-1:0]           ruser_pchk_i   ,
    input  wire                                    rvalid_pchk_i  ,
    input  wire [FC_MST_ID_WIDTH-1:0]              mst_id_pchk_i  ,
    output wire                                    rready_pchk_o  ,

    input  wire [FC_AXIID_WIDTH-1:0]               rid_cfg_i     ,
    input  wire [FC_AXIDATA_WIDTH-1:0]             rdata_cfg_i   ,
    input  wire [1:0]                              rresp_cfg_i   ,
    input  wire                                    rlast_cfg_i   ,
    input  wire [FC_AXIUSER_R_WIDTH-1:0]           ruser_cfg_i   ,
    input  wire                                    rvalid_cfg_i  ,
    input  wire [FC_MST_ID_WIDTH-1:0]              mst_id_cfg_i  ,
    output wire                                    rready_cfg_o

);


assign awakeup_m_o = awakeup_s_i;

firewall_f0_comp_dp_write #(
  .FC_MST_ID_SINGLE_MST     (FC_MST_ID_SINGLE_MST),
  .FC_SINGLE_MST            (FC_SINGLE_MST),
  .FC_ME_LVL                (FC_ME_LVL),
  .FW_SE_LVL                (FW_SE_LVL  ),
  .FC_INST_SPT              (FC_INST_SPT),
  .FC_PRIV_SPT              (FC_PRIV_SPT),
  .FC_TE_LVL                (FC_TE_LVL),
  .FC_RSE_LVL               (FC_RSE_LVL),
  .FC_PE_LVL                (FC_PE_LVL),
  .FC_ADDR_WIDTH            (FC_ADDR_WIDTH),
  .FC_AXIDATA_WIDTH         (FC_AXIDATA_WIDTH),
  .FC_AXIID_WIDTH           (FC_AXIID_WIDTH),
  .FC_MST_ID_WIDTH          (FC_MST_ID_WIDTH),
  .FC_AXIUSER_AW_WIDTH      (FC_AXIUSER_AW_WIDTH),
  .FC_AXIUSER_W_WIDTH       (FC_AXIUSER_W_WIDTH),
  .FC_AXIUSER_B_WIDTH       (FC_AXIUSER_B_WIDTH),
  .TRACKER_PAYLOAD_WIDTH_AW (TRACKER_PAYLOAD_WIDTH_AW),
  .FC_NUM_RGN               (FC_NUM_RGN),
  .LOG2_FC_NUM_RGN          (LOG2_FC_NUM_RGN),
  .FC_NUM_MPE               (FC_NUM_MPE),
  .RGN_ST_WIDTH             (RGN_ST_WIDTH),
  .FC_MNRS                  (FC_MNRS),
  .FC_MXRS                  (FC_MXRS),
  .FC_ID                    (FC_ID),
  .FC_SEC_SPT               (FC_SEC_SPT)

)
u_comp_dpf_write(
    .clk                   (clk                ),
    .reset_n               (reset_n            ),
    .awid_s_i              (awid_s_i           ),
    .awaddr_s_i            (awaddr_s_i         ),
    .awlen_s_i             (awlen_s_i          ),
    .awsize_s_i            (awsize_s_i         ),
    .awburst_s_i           (awburst_s_i        ),
    .awlock_s_i            (awlock_s_i         ),
    .awcache_s_i           (awcache_s_i        ),
    .awprot_s_i            (awprot_s_i         ),
    .awqos_s_i             (awqos_s_i          ),
    .awregion_s_i          (awregion_s_i       ),
    .awuser_s_i            (awuser_s_i         ),
    .awvalid_s_i           (awvalid_s_i        ),
    .awready_s_o           (awready_s_o        ),
    .awmmusid_s_i          (awmmusid_s_i       ),
    .wdata_s_i             (wdata_s_i          ),
    .wstrb_s_i             (wstrb_s_i          ),
    .wlast_s_i             (wlast_s_i          ),
    .wuser_s_i             (wuser_s_i          ),
    .wvalid_s_i            (wvalid_s_i         ),
    .wready_s_o            (wready_s_o         ),
    .bid_s_o               (bid_s_o            ),
    .bresp_s_o             (bresp_s_o          ),
    .buser_s_o             (buser_s_o          ),
    .bvalid_s_o            (bvalid_s_o         ),
    .bready_s_i            (bready_s_i         ),
    .awid_m_o              (awid_m_o           ),
    .awaddr_m_o            (awaddr_m_o         ),
    .awlen_m_o             (awlen_m_o          ),
    .awsize_m_o            (awsize_m_o         ),
    .awburst_m_o           (awburst_m_o        ),
    .awlock_m_o            (awlock_m_o         ),
    .awcache_m_o           (awcache_m_o        ),
    .awprot_m_o            (awprot_m_o         ),
    .awqos_m_o             (awqos_m_o          ),
    .awregion_m_o          (awregion_m_o       ),
    .awuser_m_o            (awuser_m_o         ),
    .awvalid_m_o           (awvalid_m_o        ),
    .awready_m_i           (awready_m_i        ),
    .awmmusid_m_o          (awmmusid_m_o       ),
    .wdata_m_o             (wdata_m_o          ),
    .wstrb_m_o             (wstrb_m_o          ),
    .wlast_m_o             (wlast_m_o          ),
    .wuser_m_o             (wuser_m_o          ),
    .wvalid_m_o            (wvalid_m_o         ),
    .wready_m_i            (wready_m_i         ),
    .bid_m_i               (bid_m_i            ),
    .bresp_m_i             (bresp_m_i          ),
    .buser_m_i             (buser_m_i          ),
    .bvalid_m_i            (bvalid_m_i         ),
    .bready_m_o            (bready_m_o         ),
    .tracker_al_empty_wr_i (tracker_al_empty_wr_i),
    .tracker_empty_wr_i    (tracker_empty_wr_i   ),
    .tracker_id_wr_ch_o    (tracker_id_wr_ch_o   ),
    .tracker_read_wr_ch_o  (tracker_read_wr_ch_o ),
    .tracker_dout_wr_ch_i  (tracker_dout_wr_ch_i ),
    .tracker_dout_wr_ch_vld_i (tracker_dout_wr_ch_vld_i),

    .rb_pe_st_err_i        (rb_pe_st_err_i    ),
    .rb_pe_st_flt_cfg_i    (rb_pe_st_flt_cfg_i),
    .rb_pe_st_en_i         (rb_pe_st_en_i     ),
    .rb_fe_tal_o           (rb_fe_wr_tal_o    ),
    .rb_fe_tau_o           (rb_fe_wr_tau_o    ),
    .rb_fe_tp_o            (rb_fe_wr_tp_o     ),
    .rb_fe_mid_o           (rb_fe_wr_mid_o    ),
    .rb_fe_valid_o         (rb_fe_wr_valid_o  ),
    .rb_fe_type_o          (rb_fe_wr_type_o   ),
    .rb_tmp_reg_err        (rb_tmp_reg_err_wr ),
    .rb_prot_size_i        (rb_prot_size_i    ),
    .rb_bypass_i           (rb_bypass_i       ),
    .rb_sram_rdy_i         (rb_sram_rdy_i     ),
    .rb_fw_st_i            (rb_fw_st_i[0]     ),
    .rb_st_me_en_i         (rb_st_me_en_i     ),
    .rb_cfg_rgn_tcfg0_i    (rb_cfg_rgn_tcfg0_i),
    .rb_cfg_rgn_tcfg1_i    (rb_cfg_rgn_tcfg1_i),
    .rb_cfg_rgn_tcfg2_i    (rb_cfg_rgn_tcfg2_i),

    .rb_rgn_st_i           (rb_rgn_st_i        ),
    .rb_rgn_size_i         (rb_rgn_size_i      ),
    .rb_rgn_base_addr_i    (rb_rgn_base_addr_i ),
    .rb_rgn_upper_addr_i   (rb_rgn_upper_addr_i),

    .rb_rgn_mid0_i         (rb_rgn_mid0_i      ),
    .rb_rgn_mid1_i         (rb_rgn_mid1_i      ),
    .rb_rgn_mid2_i         (rb_rgn_mid2_i      ),
    .rb_rgn_mid3_i         (rb_rgn_mid3_i      ),

    .rb_rgn_mpl0_i         (rb_rgn_mpl0_i      ),
    .rb_rgn_mpl1_i         (rb_rgn_mpl1_i      ),
    .rb_rgn_mpl2_i         (rb_rgn_mpl2_i      ),
    .rb_rgn_mpl3_i         (rb_rgn_mpl3_i      ),

    .wr_edr_wen_o          (wr_edr_wen_o      ), 
    .wr_edr_addr_lwr_o     (wr_edr_addr_lwr_o ),  
    .wr_edr_addr_uppr_o    (wr_edr_addr_uppr_o), 
    .wr_edr_prop_o         (wr_edr_prop_o     ), 

    .bid_pchk_i            (bid_pchk_i   ),
    .bresp_pchk_i          (bresp_pchk_i ),
    .buser_pchk_i          (buser_pchk_i ),
    .bvalid_pchk_i         (bvalid_pchk_i),
    .bready_pchk_o         (bready_pchk_o),

    .bid_cfg_i             (bid_cfg_i    ),
    .bresp_cfg_i           (bresp_cfg_i  ),
    .buser_cfg_i           (buser_cfg_i  ),
    .bvalid_cfg_i          (bvalid_cfg_i ),
    .bready_cfg_o          (bready_cfg_o )
);

firewall_f0_comp_dp_read #(
  .FC_MST_ID_SINGLE_MST     (FC_MST_ID_SINGLE_MST),
  .FC_SINGLE_MST            (FC_SINGLE_MST),
  .FC_ME_LVL                (FC_ME_LVL),
  .FC_TE_LVL                (FC_TE_LVL),
  .FC_RSE_LVL               (FC_RSE_LVL),
  .FW_SE_LVL                (FW_SE_LVL),
  .FC_PE_LVL                (FC_PE_LVL),
  .FC_INST_SPT              (FC_INST_SPT),
  .FC_ADDR_WIDTH            (FC_ADDR_WIDTH),
  .FC_AXIDATA_WIDTH         (FC_AXIDATA_WIDTH),
  .FC_AXIID_WIDTH           (FC_AXIID_WIDTH),
  .FC_MST_ID_WIDTH          (FC_MST_ID_WIDTH),
  .FC_AXIUSER_AR_WIDTH      (FC_AXIUSER_AR_WIDTH),
  .FC_AXIUSER_R_WIDTH       (FC_AXIUSER_R_WIDTH),
  .TRACKER_PAYLOAD_WIDTH_AR (TRACKER_PAYLOAD_WIDTH_AR),
  .FC_NUM_RGN               (FC_NUM_RGN),
  .LOG2_FC_NUM_RGN          (LOG2_FC_NUM_RGN),
  .FC_NUM_MPE               (FC_NUM_MPE),
  .RGN_ST_WIDTH             (RGN_ST_WIDTH),
  .FC_MNRS                  (FC_MNRS),
  .FC_MXRS                  (FC_MXRS),
  .FC_NUM_MST_ID            (FC_NUM_MST_ID),
  .FC_ID                    (FC_ID),
  .FC_MST_ID_VAL            (FC_MST_ID_VAL),
  .FC_ERR_RESP_PER_MST_ID   (FC_ERR_RESP_PER_MST_ID),
  .FC_ERR_RESP_DEF          (FC_ERR_RESP_DEF),
  .FC_PRIV_SPT              (FC_PRIV_SPT),
  .FC_SEC_SPT               (FC_SEC_SPT),
  .FC_NUM_READ_OS           (FC_NUM_READ_OS),
  .FC_AXI_READ_RESP_INTRLV  (FC_AXI_READ_RESP_INTRLV)
)
u_comp_dpf_read(
    .clk                    (clk                ),
    .reset_n                (reset_n            ),
    .arid_s_i               (arid_s_i           ),
    .araddr_s_i             (araddr_s_i         ),
    .arlen_s_i              (arlen_s_i          ),
    .arsize_s_i             (arsize_s_i         ),
    .arburst_s_i            (arburst_s_i        ),
    .arlock_s_i             (arlock_s_i         ),
    .arcache_s_i            (arcache_s_i        ),
    .arprot_s_i             (arprot_s_i         ),
    .arqos_s_i              (arqos_s_i          ),
    .arregion_s_i           (arregion_s_i       ),
    .aruser_s_i             (aruser_s_i         ),
    .arvalid_s_i            (arvalid_s_i        ),
    .arready_s_o            (arready_s_o        ),
    .armmusid_s_i           (armmusid_s_i       ),
    .rid_s_o                (rid_s_o            ),
    .rdata_s_o              (rdata_s_o          ),
    .rresp_s_o              (rresp_s_o          ),
    .rlast_s_o              (rlast_s_o          ),
    .ruser_s_o              (ruser_s_o          ),
    .rvalid_s_o             (rvalid_s_o         ),
    .rready_s_i             (rready_s_i         ),
    .arid_m_o               (arid_m_o           ),
    .araddr_m_o             (araddr_m_o         ),
    .arlen_m_o              (arlen_m_o          ),
    .arsize_m_o             (arsize_m_o         ),
    .arburst_m_o            (arburst_m_o        ),
    .arlock_m_o             (arlock_m_o         ),
    .arcache_m_o            (arcache_m_o        ),
    .arprot_m_o             (arprot_m_o         ),
    .arqos_m_o              (arqos_m_o          ),
    .arregion_m_o           (arregion_m_o       ),
    .aruser_m_o             (aruser_m_o         ),
    .arvalid_m_o            (arvalid_m_o        ),
    .arready_m_i            (arready_m_i        ),
    .armmusid_m_o           (armmusid_m_o       ),
    .rid_m_i                (rid_m_i            ),
    .rdata_m_i              (rdata_m_i          ),
    .rresp_m_i              (rresp_m_i          ),
    .rlast_m_i              (rlast_m_i          ),
    .ruser_m_i              (ruser_m_i          ),
    .rvalid_m_i             (rvalid_m_i         ),
    .rready_m_o             (rready_m_o         ),
    .tracker_al_empty_rd_i  (tracker_al_empty_rd_i),
    .tracker_empty_rd_i     (tracker_empty_rd_i   ),
    .tracker_id_rd_ch_o     (tracker_id_rd_ch_o   ),
    .tracker_read_rd_ch_o   (tracker_read_rd_ch_o ),
    .tracker_dout_rd_ch_i   (tracker_dout_rd_ch_i ),
    .tracker_dout_rd_ch_vld_i (tracker_dout_rd_ch_vld_i),

    .rb_me_st_rdum_i       (rb_me_st_rdum_i    ),
    .rb_pe_st_err_raz_i    (rb_pe_st_err_raz_i ),
    .rb_pe_st_flt_cfg_i    (rb_pe_st_flt_cfg_i ),
    .rb_pe_st_en_i         (rb_pe_st_en_i      ),
    .rb_fe_tal_o           (rb_fe_rd_tal_o     ),
    .rb_fe_tau_o           (rb_fe_rd_tau_o     ),
    .rb_fe_tp_o            (rb_fe_rd_tp_o      ),
    .rb_fe_mid_o           (rb_fe_rd_mid_o     ),
    .rb_fe_valid_o         (rb_fe_rd_valid_o   ),
    .rb_fe_type_o          (rb_fe_rd_type_o    ),
    .rb_tmp_reg_err        (rb_tmp_reg_err_rd  ),
    .rb_prot_size_i        (rb_prot_size_i     ),
    .rb_bypass_i           (rb_bypass_i        ),
    .rb_sram_rdy_i         (rb_sram_rdy_i      ),
    .rb_fw_st_i            (rb_fw_st_i         ),
    .rb_st_me_en_i         (rb_st_me_en_i      ),
    .rb_cfg_rgn_tcfg0_i    (rb_cfg_rgn_tcfg0_i),
    .rb_cfg_rgn_tcfg1_i    (rb_cfg_rgn_tcfg1_i),
    .rb_cfg_rgn_tcfg2_i    (rb_cfg_rgn_tcfg2_i),

    .rb_rgn_st_i           (rb_rgn_st_i        ),
    .rb_rgn_size_i         (rb_rgn_size_i      ),
    .rb_rgn_base_addr_i    (rb_rgn_base_addr_i ),
    .rb_rgn_upper_addr_i   (rb_rgn_upper_addr_i),

    .rb_rgn_mid0_i         (rb_rgn_mid0_i      ),
    .rb_rgn_mid1_i         (rb_rgn_mid1_i      ),
    .rb_rgn_mid2_i         (rb_rgn_mid2_i      ),
    .rb_rgn_mid3_i         (rb_rgn_mid3_i      ),

    .rb_rgn_mpl0_i         (rb_rgn_mpl0_i      ),
    .rb_rgn_mpl1_i         (rb_rgn_mpl1_i      ),
    .rb_rgn_mpl2_i         (rb_rgn_mpl2_i      ),
    .rb_rgn_mpl3_i         (rb_rgn_mpl3_i      ),

    .rd_edr_wen_o          (rd_edr_wen_o       ), 
    .rd_edr_addr_lwr_o     (rd_edr_addr_lwr_o  ), 
    .rd_edr_addr_uppr_o    (rd_edr_addr_uppr_o ), 
    .rd_edr_prop_o         (rd_edr_prop_o      ), 

    .rid_pchk_i            (rid_pchk_i         ),
    .rdata_pchk_i          (rdata_pchk_i       ),
    .rresp_pchk_i          (rresp_pchk_i       ),
    .rlast_pchk_i          (rlast_pchk_i       ),
    .ruser_pchk_i          (ruser_pchk_i       ),
    .rvalid_pchk_i         (rvalid_pchk_i      ),
    .rready_pchk_o         (rready_pchk_o      ),
    .mst_id_pchk_i         (mst_id_pchk_i      ),

    .rid_cfg_i             (rid_cfg_i          ),
    .rdata_cfg_i           (rdata_cfg_i        ),
    .rresp_cfg_i           (rresp_cfg_i        ),
    .rlast_cfg_i           (rlast_cfg_i        ),
    .ruser_cfg_i           (ruser_cfg_i        ),
    .rvalid_cfg_i          (rvalid_cfg_i       ),
    .rready_cfg_o          (rready_cfg_o       ),
    .mst_id_cfg_i          (mst_id_cfg_i       )
);

endmodule
