//------------------------------------------------------------------------------
// The confidential and proprietary information contained in this file may
// only be used by a person authorised under and to the extent permitted
// by a subsisting licensing agreement from Arm Limited or its affiliates.
//
//            (C) COPYRIGHT 2019-2021 Arm Limited or its affiliates.
//                ALL RIGHTS RESERVED
//
// This entire notice must be reproduced on all copies of this file
// and copies of this file may only be made by a person if such person is
// permitted to do so under the terms of a subsisting license agreement
// from Arm Limited or its affiliates.
//
//
//      Release Information : SSE710-r0p0-00eac0
//
//------------------------------------------------------------------------------
// Verilog-2001 (IEEE Std 1364-2001)
//------------------------------------------------------------------------------


`include "firewall_f0_comp_user_cfg_sse710_host_cpu.vh"
localparam [7:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID0_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID0_VAL;
localparam [7:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID1_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID1_VAL;
localparam [7:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID2_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID2_VAL;
localparam [7:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID3_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID3_VAL;
localparam [7:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID4_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID4_VAL;
localparam [7:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID5_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID5_VAL;
localparam [7:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID6_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID6_VAL;
localparam [7:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID7_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID7_VAL;
localparam [7:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID8_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID8_VAL;

localparam [127:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID0 = {4{FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID0_VAL}}; 
localparam [127:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID1 = {4{FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID1_VAL}}; 
localparam [127:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID2 = {4{FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID2_VAL}}; 
localparam [127:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID3 = {4{FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID3_VAL}}; 
localparam [127:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID4 = {4{FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID4_VAL}}; 
localparam [127:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID5 = {4{FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID5_VAL}}; 
localparam [127:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID6 = {4{FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID6_VAL}}; 
localparam [127:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID7 = {4{FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID7_VAL}}; 
localparam [127:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID8 = {4{FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID8_VAL}}; 

localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_PE_LVL            = 0; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_TE_LVL            = 0; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_RSE_LVL           = 0; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ME_LVL            = 2; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_NUM_RGN           = 1; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MNRS              = 0; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MXRS              = 5; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_NUM_MPE           = 1; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ID                = 6; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_SINGLE_MST        = 1; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ADDR_WIDTH        = 40; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FW_NUM_FC            = 14; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_LOG2_FW_NUM_FC       = $clog2(FIREWALL_F0_CFG_SSE710_HOST_CPU_FW_NUM_FC); 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_AXIDATA_WIDTH     = 128; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_AXIID_WIDTH       = 8; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID_WIDTH      = 8; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID_SINGLE_MST = 1; 

localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FW_SRE_LVL       =  1;     
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FW_LDE_LVL       =  2;     
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FW_MAX_MST_ID_WIDTH  =  8 ;     


localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FW_SE_LVL           = 1;            
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_NUM_FE           = 1;            
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_NUM_EDR          = 1;            
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_SEC_SPT          = 1;            
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MA_SPT           = 1;            
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_SH_SPT           = 0;            
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_INST_SPT         = 1;            
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_PRIV_SPT         = 1;            
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_CFG_DATA_W       = 32;           




localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_NUM_READ_OS      = 32; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_NUM_WRITE_OS     = 32; 

localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_AW_REG_SLC_S  = 3; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_W_REG_SLC_S   = 3; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_B_REG_SLC_S   = 3; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_AR_REG_SLC_S  = 3; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_R_REG_SLC_S   = 3; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_AW_REG_SLC_M  = 3; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_W_REG_SLC_M   = 3; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_B_REG_SLC_M   = 3; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_AR_REG_SLC_M  = 3; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_R_REG_SLC_M   = 3; 
localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_BAS_REG_SLC   = 0; 

localparam   FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_AXIUSER_AR_WIDTH = 2; 
localparam   FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_AXIUSER_AW_WIDTH = 2; 
localparam   FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_AXIUSER_W_WIDTH  = 1; 
localparam   FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_AXIUSER_R_WIDTH  = 1; 
localparam   FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_AXIUSER_B_WIDTH  = 1; 

localparam FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_NUM_MST_ID = 9; 

localparam [71:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID_VAL  = {
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID8_VAL,
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID7_VAL,
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID6_VAL,
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID5_VAL,
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID4_VAL,
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID3_VAL,
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID2_VAL,
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID1_VAL,
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_MST_ID0_VAL
};

localparam [1151:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID  = {
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID8,
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID7,
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID6,
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID5,
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID4,
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID3,
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID2,
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID1,
    FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_PER_MST_ID0
};

localparam [127:0] FIREWALL_F0_CFG_SSE710_HOST_CPU_FC_ERR_RESP_DEF = 128'hec00ec00ec00ec00ec00ec00ec00ec00;  
