//------------------------------------------------------------------------------
// The confidential and proprietary information contained in this file may
// only be used by a person authorised under and to the extent permitted
// by a subsisting licensing agreement from Arm Limited or its affiliates.
//
//            (C) COPYRIGHT 2019-2021 Arm Limited or its affiliates.
//                ALL RIGHTS RESERVED
//
// This entire notice must be reproduced on all copies of this file
// and copies of this file may only be made by a person if such person is
// permitted to do so under the terms of a subsisting license agreement
// from Arm Limited or its affiliates.
//
//
//      Release Information : SSE710-r0p0-00eac0
//
//------------------------------------------------------------------------------
// Verilog-2001 (IEEE Std 1364-2001)
//------------------------------------------------------------------------------


`include "firewall_f0_comp_user_cfg_sse710_aonperiph.vh"
localparam [7:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID0_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID0_VAL;
localparam [7:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID1_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID1_VAL;
localparam [7:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID2_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID2_VAL;
localparam [7:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID3_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID3_VAL;
localparam [7:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID4_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID4_VAL;
localparam [7:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID5_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID5_VAL;
localparam [7:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID6_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID6_VAL;
localparam [7:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID7_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID7_VAL;
localparam [7:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID8_VAL = FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID8_VAL;

localparam [31:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID0 = FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID0_VAL; 
localparam [31:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID1 = FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID1_VAL; 
localparam [31:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID2 = FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID2_VAL; 
localparam [31:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID3 = FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID3_VAL; 
localparam [31:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID4 = FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID4_VAL; 
localparam [31:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID5 = FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID5_VAL; 
localparam [31:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID6 = FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID6_VAL; 
localparam [31:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID7 = FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID7_VAL; 
localparam [31:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID8 = FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID8_VAL; 

localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_PE_LVL            = 1; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_TE_LVL            = 0; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RSE_LVL           = 0; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ME_LVL            = 0; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_NUM_RGN           = 40; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MNRS              = 7; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MXRS              = 23; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_NUM_MPE           = 1; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ID                = 3; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_SINGLE_MST        = 0; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ADDR_WIDTH        = 32; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FW_NUM_FC            = 14; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_LOG2_FW_NUM_FC       = $clog2(FIREWALL_F0_CFG_SSE710_AONPERIPH_FW_NUM_FC); 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_AXIDATA_WIDTH     = 32; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_AXIID_WIDTH       = 12; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID_WIDTH      = 8; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID_SINGLE_MST = 0; 

localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FW_SRE_LVL       =  1;     
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FW_LDE_LVL       =  2;     
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FW_MAX_MST_ID_WIDTH  =  8 ;     


localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FW_SE_LVL           = 1;            
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_NUM_FE           = 1;            
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_NUM_EDR          = 1;            
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_SEC_SPT          = 1;            
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MA_SPT           = 1;            
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_SH_SPT           = 0;            
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_INST_SPT         = 1;            
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_PRIV_SPT         = 1;            
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_CFG_DATA_W       = 32;           



localparam [919:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN_BASE_ADDR = {
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN39_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN38_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN37_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN36_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN35_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN34_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN33_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN32_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN31_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN30_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN29_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN28_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN27_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN26_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN25_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN24_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN23_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN22_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN21_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN20_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN19_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN18_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN17_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN16_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN15_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN14_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN13_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN12_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN11_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN10_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN9_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN8_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN7_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN6_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN5_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN4_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN3_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN2_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN1_BASE_ADDR ,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN0_BASE_ADDR 
};

localparam [919:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN_UPR_ADDR  = {
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN39_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN38_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN37_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN36_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN35_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN34_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN33_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN32_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN31_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN30_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN29_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN28_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN27_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN26_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN25_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN24_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN23_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN22_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN21_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN20_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN19_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN18_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN17_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN16_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN15_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN14_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN13_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN12_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN11_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN10_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN9_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN8_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN7_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN6_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN5_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN4_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN3_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN2_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN1_UPR_ADDR,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN0_UPR_ADDR
};

localparam [319:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN_SIZE  = {
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN39_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN38_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN37_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN36_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN35_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN34_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN33_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN32_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN31_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN30_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN29_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN28_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN27_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN26_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN25_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN24_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN23_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN22_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN21_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN20_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN19_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN18_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN17_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN16_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN15_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN14_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN13_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN12_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN11_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN10_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN9_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN8_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN7_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN6_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN5_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN4_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN3_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN2_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN1_SIZE,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN0_SIZE
};

localparam [39:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN_MULNPO2  = {
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN39_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN38_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN37_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN36_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN35_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN34_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN33_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN32_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN31_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN30_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN29_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN28_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN27_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN26_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN25_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN24_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN23_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN22_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN21_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN20_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN19_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN18_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN17_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN16_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN15_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN14_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN13_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN12_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN11_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN10_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN9_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN8_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN7_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN6_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN5_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN4_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN3_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN2_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN1_MULNPO2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN0_MULNPO2
};


localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_NUM_READ_OS      = 8; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_NUM_WRITE_OS     = 8; 

localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_AW_REG_SLC_S  = 3; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_W_REG_SLC_S   = 3; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_B_REG_SLC_S   = 3; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_AR_REG_SLC_S  = 3; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_R_REG_SLC_S   = 3; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_AW_REG_SLC_M  = 3; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_W_REG_SLC_M   = 3; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_B_REG_SLC_M   = 3; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_AR_REG_SLC_M  = 3; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_R_REG_SLC_M   = 3; 
localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_BAS_REG_SLC   = 0; 

localparam   FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_AXIUSER_AR_WIDTH = 2; 
localparam   FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_AXIUSER_AW_WIDTH = 2; 
localparam   FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_AXIUSER_W_WIDTH  = 1; 
localparam   FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_AXIUSER_R_WIDTH  = 1; 
localparam   FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_AXIUSER_B_WIDTH  = 1; 

localparam FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_NUM_MST_ID = 9; 

localparam [71:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID_VAL  = {
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID8_VAL,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID7_VAL,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID6_VAL,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID5_VAL,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID4_VAL,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID3_VAL,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID2_VAL,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID1_VAL,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_MST_ID0_VAL
};

localparam [287:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID  = {
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID8,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID7,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID6,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID5,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID4,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID3,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID2,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID1,
    FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_PER_MST_ID0
};

localparam [31:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_ERR_RESP_DEF = 32'hdeaddead;  
