/******************************************************************
*
* qspi_hclk_gen controller JS MACRO generated by ezchip
*
******************************************************************/

import { signal_posedge,sim_log,sim_assert_fail,signal_polling,sim_async_finish,ma_inw,ma_outw,mem_read,mem_write,sim_wait,sim_time,signal_write,signal_read } from "js_sim.so";
import * as os from "os"
import * as std from "std"
import {get_period,polling_bit,Log} from "sim_lib.js"

