#! /usr/bin/env perl
BEGIN { $^W = 1 }
#******************************************************************************
#   The confidential and proprietary information contained in this file may
#   only be used by a person authorised under and to the extent permitted
#   by a subsisting licensing agreement from Arm Limited or its affiliates.
#
#          (C) COPYRIGHT 2010-2018 Arm Limited or its affiliates.
#              ALL RIGHTS RESERVED
#
#   This entire notice must be reproduced on all copies of this file
#   and copies of this file may only be made by a person if such person is
#   permitted to do so under the terms of a subsisting license agreement
#   from Arm Limited or its affiliates.
#******************************************************************************
#
#               Build Component
#               ===============
#
#******************************************************************************
#
#       RCS Information
#
#       RCS Filename        : Build_Component
#       Release             : $State$
#
#******************************************************************************
# This is a configurator script for ARM IP-XACT files. It uses a helper library
# called IP-XACT_lib.pm
#
# Control of configuration space for a component is managed within a component's
# IP-XACT file only. Once all the appropriate user parameters are entered (either
# on the command line, a file or as prompted during execution), generators
# specified within the IP-XACT file are called. Following execution of the
# generators, a configured IP-XACT file (the original plus all the user values
# "fixed" with dependency equations solved) is saved back to the same location
# as the original IP-XACT file but with an appropriate unique name.
#
#******************************************************************************

######## KNOWN LIMITATIONS ########
# - when using configuration files, it does not save or load a unique string name

use warnings;

use XML::LibXML;
if (not(XML::LibXML::LIBXML_VERSION =~ /^\d+$/)) {
  die 'The Perl XML::LibXML module could not be found';
}
if (not(XML::LibXML::LIBXML_RUNTIME_VERSION =~ /^\d+$/)) {
  die 'The Perl XML::LibXML module could not find the libxml2 runtime library';
}

# On a system with improperly installed libxml, the identifiers count as
# barewords so can generate Perl syntax errors with 'use strict'. Therefore
# we only turn on strict checks after we know libxml is properly installed

use strict;
use Cwd;
use File::Basename;

# point to where IPXACT_lib is located (Assumes IPXACT_lib.pm is adjacent to this script)
BEGIN { my $ipxact_lib = dirname(Cwd::abs_path($0)); chomp($ipxact_lib);  push @INC, $ipxact_lib};

use CGI qw(:standard);
use IPXACT_lib;


my $version = '$Revision: 4048 $';
$IPXACT_lib::debug = 0;

# Get name of program
my $prog;
chop($prog = `basename $0`);

#
# Usage statement
#
my $usage = "
This program uses the information stored within an IP-XACT component description to configure it through user-resolved parameters.
It creates a temporary new name (either through the command line or as a hash of supplied parameters) should any generator require a unique name when running generator processes. Should the files associated with the IP-XACT (e.g. the component's Verilog RTL) require modification, as a consequence of parameter options specified, then this is assumed to be done as part of the component's generator flow that is referenced within the IP-XACT file.

Usage:   $prog <filename.xml> [<uniquifier>] [-config <config_file> | -adconfig <adconfig_file> | <parameter_name>=<parameter_value> [...further name=value pairs]] [-output_dir <output_directory>] [-module_name <component_name>] [-rename_top_rtl] [-no_gen] [-keepdepends] [-default_ipxact_dir] [-overwrite] [-h]

Where: <filename.xml>
          IP-XACT file to base configuration on

       <uniquifier>
          A unique string to potentially append to the configured component filename.
          If a uniquifier is not required then specifying a string has no effect.
          If a uniquifier is required and you do not specify it the script will generate a string based on your specified configuration.

       <config_file>
          A file that contains a list of all the <parameter_name> = <parameter_value> pairs required to build a specific configuration of the component.
          Each name and value pair must be on a different line.
          Use this option if you have saved a configuration from a previous script invocation.

       <adconfig_file>
          A file that contains the AMBA Designer data required to build a specific configuration of the component.
          Use this option if you have saved a configuration file from the AMBA Designer tool.

       <parameter_name>=<parameter_value>
          A set of parameter name and value pairs (multiple sets can be specified) required to build a specific configuration of the component.
          Names must match the user resolved parameters in the IP-XACT. All parameters must be specified for the component to be configured.

       <output_directory>
          overrides any of -default_ipxact_dir and TARGET_IPXACT_DIRECTORY to define the output directory.

       <component_name>
          overrides the spirit:modelName

       -rename_top_rtl
          locates and renames the top-level file declaration with the overriden component name (must be used only when -module_name is used too)

       -no_gen
          Do not run any generator routines

       -keepdepends
          When creating the configured IP-XACT, maintain the original expression dependency. Default is to resolve everything to immediates.

       -default_ipxact_dir
          Ignore TARGET_IPXACT_DIRECTORY parameters and write configured IP-XACT on the same dir as <filename.xml>

       -h
          Display help information

       -overwrite
          Overwrite any existing generated component defintion

NOTE

If any config file, adconfig file or parameter=value pairs on the command line are specified, the script will prompt for required values (with option to save to a suitable configuration file).

If both -adconfig and -config are specified the script will return an error.
";

exit Main();

##############
# SUBROUTINE #
##############
sub Main {

  my $IPXACT_doc;                               # ultimately contains the XML parser opened IP-XACT document
  my $okay                = 1;                  # if zero, an error has occured
  my %cmd_line_params     = ();                 # used to store name/value pairs from the command line
  my $run_gen             = 1;                  # default to run generators unless "-no_gen" is specified
  my $config_file         = "not_defined_file"; # set to one if a configuration file is being supplied
  my $adconfig_file       = "not_defined_file"; # set to one if a configuration file is being supplied
  my $output_dir          = "not_defined_dir";  # set to one if a configuration file is being supplied
  my $module_name         = "not_defined_name"; # set to one if a configuration file is being supplied
  my $rename_top_rtl      = 0;                  # set to one if a configuration file is being supplied
  my $keep_depends        = 0;                  # by default, change all resolve=depends to resolve=immediate
  my $default_ipxact_dir  = 0;                  # Use the default IPXACT target directory
  my $overwrite           = 0;                  # If the output file already exists, enable overwrite.
  my $no_fix_path         = 0;                  # Force BC to maintain the original file paths

  # parse command line
  my $IPXACT_file;
  my $uniq_ext = "";

  foreach my $argnum (0 .. $#ARGV) {
    debugMsg("MAIN Found ARG ".$argnum." = ".$ARGV[$argnum]);
    # test if -h is present on the command line with portable search thru a list (could be using ~~ with perl 5.10+)
    my %argv_hash = map { $_, 1 } @ARGV;
    if( $argv_hash{ '-h' } ){ 
      print_info($usage); 
      exit 0;
    }
    if ($argnum == 0) {
      debugMsg("MAIN ...Found file");
      # first argument *must be the file*
      $IPXACT_file = $ARGV[$argnum];
    } elsif ($config_file eq "1") {
      $config_file = $ARGV[$argnum]; # we shouldn't hit this again
    } elsif ($adconfig_file eq "1") {
      $adconfig_file = $ARGV[$argnum]; # we shouldn't hit this again
    } elsif ($output_dir eq "1") {
      $output_dir = $ARGV[$argnum]; # we shouldn't hit this again
    } elsif ($module_name eq "1") {
      $module_name = $ARGV[$argnum]; # we shouldn't hit this again
    } elsif ($ARGV[$argnum] =~ /(.*)=(.*)/) {
      # matches a name/value pair where $1 is the name and $2 is the value
      debugMsg("MAIN ...name/value pair: $1=$2");
      $cmd_line_params{$1} = $2;
    } elsif ($ARGV[$argnum] =~ /^-(.*)/) {
      # parameter
      debugMsg("MAIN ...parameter found $1");
      SWITCH: {
        if ($1 eq "keepdepends") {$keep_depends = 1; last SWITCH}
        if ($1 eq "no_gen") { $run_gen = 0; last SWITCH}
        if ($1 eq "config") { $config_file = "1"; last SWITCH}
        if ($1 eq "adconfig") { $adconfig_file = "1"; last SWITCH}
        if ($1 eq "output_dir") { $output_dir = "1"; last SWITCH}
        if ($1 eq "module_name") { $module_name = "1"; last SWITCH}
        if ($1 eq "rename_top_rtl") { $rename_top_rtl = "1"; last SWITCH}
        if ($1 eq "debug") { $IPXACT_lib::debug = 1; last SWITCH}
        if ($1 eq "default_ipxact_dir") { $default_ipxact_dir = 1; last SWITCH}
        if ($1 eq "overwrite") { $overwrite = 1; last SWITCH}
        if ($1 eq "no_fix_path") { $no_fix_path = 1; last SWITCH}
        $okay = 0; # unknown option
        print "Unknown option: $1 \n";
      }
    } elsif ($argnum == 1) {
      # not a name/value pair in the second argument, must be uniquifier
      $uniq_ext = $ARGV[$argnum];
      debugMsg("MAIN ...uniquifier value: $uniq_ext");
    } else {
      # No idea what the argument is
      $okay = 0; # unknown option
      print "Unknown option: $ARGV[$argnum]\n";
    }
  }

  if ($rename_top_rtl and $module_name eq "not_defined_name") {
      print_error("option -rename_top_rtl can only be used when -module_name is used too");
      exit 1;
  }

  # check XML file is IP-XACT (and open)
  if (defined $IPXACT_file) {
    $IPXACT_doc = check_XML($IPXACT_file);
    if ($IPXACT_doc) {
      debugMsg("MAIN opened file successfully: $IPXACT_file");
      # check it's a spirit:component
      if ($IPXACT_doc->find('/spirit:component')) {
        print "Opening $IPXACT_file for reading.\n";
      } else {
        $okay = 0;
        print_error("$IPXACT_file does not contain a spirit:component.");
      }
    } else {
      $okay = 0;
    }
  } else {
    $okay = 0;
  }

  # check only one config file is present
  unless ($config_file eq "not_defined_file" | $adconfig_file eq "not_defined_file") {
    $okay = 0;
    print_error("Two configuration files are present $config_file and $adconfig_file. Only one is allowed.");
  }

  ## Parse_parameters()
  # Go through IP-XACT file answering parameters with spirit:resolve=user using the command line ones were applicable otherwise prompt the user.
  # - send pointer to IP-XACT document
  # - hash of command line name=value pairs
  if ($okay == 1) {
    my @parse_return;
    
    if ($adconfig_file ne "not_defined_file") {
  
      # If AD File is specified
      debugMsg("Using ad configuration file: ".$adconfig_file);
      @parse_return = parse_parameters($IPXACT_doc, \%cmd_line_params, $adconfig_file,"adconfig");

    } else {
      
      # If config file is specified, or cmdline params,
      debugMsg("Using configuration file: ".$config_file) if($config_file ne "not_defined_file");
      @parse_return = parse_parameters($IPXACT_doc, \%cmd_line_params, $config_file,"config");

    }
    
    $okay = $parse_return[0];
    if (defined $parse_return[1]) {
      if ($uniq_ext =~ /^\s*$/) {$uniq_ext = $parse_return[1];}
      debugMsg("Uniquifier retrieved from parse parameter: ".$parse_return[1])
    }
  }

  # if new spirit:name specified then update that field
  # may have been passed as spirit:name in the param=value or as <uniquifier>
  # (otherwise make a hash of parameters as the uniqifier)
  if ($okay == 1) {

    my $orig_name = $IPXACT_doc->findvalue("spirit:component/spirit:name");
    my $orig_instance_name = $IPXACT_doc->findvalue("spirit:component/spirit:model/spirit:views/spirit:view/spirit:modelName");
    debugMsg("MAIN Original name: ".$orig_name);
    debugMsg("MAIN Original instance name: ".$orig_instance_name);

    my $new_name = $orig_name;
    
    # VLNV Name is the instance uniquifier
    if (defined $cmd_line_params{"spirit:name"}) {
      $new_name = $cmd_line_params{"spirit:name"};
      debugMsg("MAIN name defined on command line: ".$new_name);
 
    } elsif ($uniq_ext !~ /^\s*$/) {
 
      $new_name = $orig_name."_".$uniq_ext;
      debugMsg("MAIN name defined by uniquifier: ".$new_name);
 
    } else {
      # nothing specified, try creating a hash of the params
      print_info("No unique string found, creating a temporary name based upon the chosen parameters\n");
      $uniq_ext = "";
      foreach my $param (sort keys %cmd_line_params) {
        $uniq_ext = $uniq_ext."_".$cmd_line_params{$param};
        debugMsg("MAIN unique is now: ".$uniq_ext);
      }
      $uniq_ext =~ s/(?:\\|\/|\s+|\?|\.|\!|\"|\')//g;
      $uniq_ext =~ s/(^_|\s+|)//;
      $uniq_ext =~ s/_$//;
      if ($uniq_ext =~ /^\s*$/) {
        print_error("Could find nor create a uniquifier, please provide one");
        exit 1;
      }
 
      $new_name = $orig_name."_".$uniq_ext;
 
    }

    if($new_name ne $orig_name) {
      # update the VLNV Name and modelName
      debugMsg("Renaming Component VLNV Name (".$new_name.")\n");
      rename_component($IPXACT_doc,$new_name);
    } else {
      debugMsg("Leaving Component VLNV Name (".$orig_name.") untouched\n");
    }
  
    # modelName is the RTL Module declaration
    if ($module_name !~ /^not_defined_name$/) {
      # update the VLNV Name and modelName
      rename_component_instance($IPXACT_doc,$module_name);
      update_top_level_file_reference($IPXACT_doc, $orig_name, $module_name) if($rename_top_rtl);
      debugMsg("Renaming Component modelName (".$module_name.")\n");
    } else {
      debugMsg("Leaving Component modelName (".$orig_instance_name.") untouched\n");
    }

  }

  ## call generators
  # go through IP-XACT running any generators specified
  if ($okay == 1) {
    $okay = call_generators($IPXACT_doc, $run_gen, $IPXACT_file);
  }

  ## resolve dependencies in the entire document
  # go through IP-XACT solving all the XPath expressions
  if ($okay == 1) {
    $okay = resolve_doc($IPXACT_doc, $IPXACT_file);
  }

  ## Remove of resolve=user to stop any possible changes
  if ($okay == 1) {
    $okay = solidify_doc($IPXACT_doc, $IPXACT_file, $keep_depends);
  }

  ## attempt to save the new IP-XACT file
  if ($okay == 1) {
    my $target_ipxact_dir = dirname($IPXACT_file);
    if($output_dir !~ /not_defined_dir/) {
      debugMsg("Output dir specified on command line.\n$output_dir\n");
      $target_ipxact_dir = $output_dir;
      print "-output_dir <<$target_ipxact_dir>> has been specified on command line.\n";
      fix_path($IPXACT_doc, $target_ipxact_dir, $IPXACT_file) if(!$no_fix_path);
    } else {      
      my $TARGET_IPXACT_DIRECTORY = $IPXACT_doc->findvalue('spirit:component/spirit:parameters/spirit:parameter[spirit:name="TARGET_IPXACT_DIRECTORY"]/spirit:value');
      if ($TARGET_IPXACT_DIRECTORY ne "" and (!$default_ipxact_dir)) {
        if ($TARGET_IPXACT_DIRECTORY =~ /^\//) {
          $target_ipxact_dir = $TARGET_IPXACT_DIRECTORY;
          print_info("Saving to Absolute path <<$target_ipxact_dir>> as defined by parameter TARGET_IPXACT_DIRECTORY.\n");
        } else {
          $target_ipxact_dir = "$target_ipxact_dir/$TARGET_IPXACT_DIRECTORY";
        }
        debugMsg("An option for ipxact file location was found: ".$target_ipxact_dir);
      } else {
        debugMsg("Ipxact file will be saved in default location");
      }
    }
    $okay = save_doc($IPXACT_doc, $target_ipxact_dir, $overwrite);
  }
  if ($okay == 0) {
    print_error($usage);
    print_error("An error occurred\n");
  } else {
    print_info("completed.\n");
  }

  # if everything has worked we want to return 0 to quit cleanly
  return !$okay

};

#################################################################################
# Routine : rename_component
#    Stuff
#
# Arguments :
#    XMLDOC pre-opened XML document (the IP-XACT file)
#    new name
#
# Returns : new name
#################################################################################
sub rename_component($$) {
  my $XML_doc = shift;
  my $new_name   = shift;

  # param=value specified, replaces the entire name
  debugMsg("MAIN got a new name: ".$new_name);
  $XML_doc->find("spirit:component/spirit:name")->get_node(0)->firstChild->setData($new_name);
  debugMsg("MAIN new name = ".$XML_doc->findvalue("spirit:component/spirit:name"));

  return $new_name;
}

#################################################################################
# Routine : rename_component
#    Stuff
#
# Arguments :
#    XMLDOC pre-opened XML document (the IP-XACT file)
#    new name
#
# Returns : new name
#################################################################################
sub rename_component_instance($$) {
  my $XML_doc = shift;
  my $new_name   = shift;

  # param=value specified, replaces the entire name
  debugMsg("MAIN got a new name: ".$new_name);
  $XML_doc->find("spirit:component/spirit:model/spirit:views/spirit:view/spirit:modelName")->get_node(0)->firstChild->setData($new_name);
  debugMsg("MAIN new modelName = ".$XML_doc->findvalue("spirit:component/spirit:model/spirit:views/spirit:view/spirit:modelName"));

  return $new_name;
}

#################################################################################
# Routine : update top level file name
#    Stuff
#
# Arguments :
#    XMLDOC pre-opened XML document (the IP-XACT file)
#    original name
#    new name
#
# Returns : 0 - Pass, 1 - No replacements made
#################################################################################
sub update_top_level_file_reference($$$) {

  my $XML_doc    = shift;
  my $orig_name  = shift;
  my $new_name   = shift;

  my $rtl_file_name = $XML_doc->findvalue('spirit:component/spirit:fileSets/spirit:fileSet/spirit:file[spirit:isIncludeFile/@spirit:externalDeclarations="true" and spirit:isIncludeFile = "false"]/spirit:name');
  $rtl_file_name =~ s/$orig_name/$new_name/;
  $XML_doc->find('spirit:component/spirit:fileSets/spirit:fileSet/spirit:file[spirit:isIncludeFile/@spirit:externalDeclarations="true" and spirit:isIncludeFile = "false"]/spirit:name')->get_node(0)->firstChild->setData($rtl_file_name);
  return 0;
}
#################################################################################
# Routine : strip unused
#    Removes temporary attributes that are in the IP-XACT file
#
# Arguments :
#    XMLDOC pre-opened XML document (the IP-XACT file)
#
# Returns : <none>
#################################################################################
sub strip_unused($) {

  my $XML_doc = shift;

  # find all parameters in IP-XACT Doc (XMLDOC)
  my @userParams      = ();
  my $p_userParams    = $XML_doc->find('spirit:component/spirit:parameters/spirit:parameter');
  my $p_userModParams = $XML_doc->find('spirit:component/spirit:model/spirit:modelParameters/spirit:modelParameter');
  push @userParams, $p_userParams->get_nodelist;
  push @userParams, $p_userModParams->get_nodelist;
  foreach my $Param_node (@userParams) {

    # Assert an arbitrary ordering if spirit:order is not defined
    $Param_node->find("spirit:value")->get_node(0)->removeAttribute("spirit:order");
    # Assert a default rangeType if it is not defined
    $Param_node->find("spirit:value")->get_node(0)->removeAttribute("spirit:rangeType");
  }
  
  return;
  
}
#################################################################################
# Routine : parse_parameters
#    resolves parameters that are in the IP-XACT file
#
# Arguments :
#    XMLDOC pre-opened XML document (the IP-XACT file)
#    pointer to hash of name=value pairs
#    file containing parameters
#
# Returns : status (1 = okay), $uniq_ext (empty or with unique string)
#################################################################################
sub parse_parameters($$$$) {
  #my $XML_doc = shift;
  #my $p_hash_name_value = shift;
  #my %hash_name_value = %$p_hash_name_value;
  #my $config_file = shift;
  my $XML_doc = $_[0];
  #my $p_hash_name_value = $_[0];
  my %hash_name_value = %{$_[1]};
  my $config_file = $_[2];
  my $config_type = $_[3]; #0  config : 1 adconfig
  my $check = 1;
  my $uniq_ext;
  # have a hash of parameters from the command line, need to also get parameters from the IP-XACT file and cross-update
  # checks if a parameter is needed due following arm:presence evaluation
  # if any parameters passed, assume all required (DIE if not)
  # if no parameters passed, prompt the user for them

  debugMsg("parse_parameters running");

  # find all parameters in IP-XACT Doc (XMLDOC)
  my @userParams      = ();
  my $p_userParams    = $XML_doc->find('spirit:component/spirit:parameters/spirit:parameter[spirit:value/@spirit:resolve="user"]');
  my $p_userModParams = $XML_doc->find('spirit:component/spirit:model/spirit:modelParameters/spirit:modelParameter[spirit:value/@spirit:resolve="user"]');
  push @userParams, $p_userParams->get_nodelist;
  push @userParams, $p_userModParams->get_nodelist;
  
  my %XML_Params; # hash of params in IP-XACT

  # make sure there are some params
  if (scalar(@userParams) == 0) {
    $check = 0;
    print_error("No user configurable parameters present in the component.");
  }

  # check what has been done:
  # - no file, no command line => query user (allow save!)
  # -    file, no command line => use file (error on missing)
  # - no file,    command line => use command line (error on missing)
  # -    file,    command line => error
  my $parse = ($config_file eq "not_defined_file");
  my $ask   = ($parse && ((keys %hash_name_value) == 0));
  if(not($parse)) {
    die "ERROR: Unable to process IP-XACT file. Please only supply configuration file OR command line parameters (not both).\n" if( ( (keys %hash_name_value) >= 1) );
    die "ERROR: Unable to locate the file $config_file" if(not(check_file($config_file)));
  }
  if ($config_file ne "not_defined_file") {
    if ($config_type eq "config") {
      open (FILE, $config_file);
      while (<FILE>) {
        chomp;
        my $line = $_;
        # use NAME identifier for the first bit and then eat up everything until the first space (or end of line)
        if ($line =~ /\s*#.*/ ) {
          # commented out line
          debugMsg("parse_parameters: found commented out line: $line");
        } elsif ($line =~ /([a-zA-Z_]{1}[a-zA-Z0-9_\-.]*) *= *([^ ]*)/ ) {
          # valid line
          debugMsg("parse_parameters: found $1=$2 in file $config_file");
          $hash_name_value{$1} = $2;
        }
      }
    close (FILE);
    } else { # AD Config file
      my $adcfg_doc = check_XML($config_file);
      my $cfgnodes = $adcfg_doc->find('/periph/*');
      foreach my $node ($cfgnodes->get_nodelist) {
        if ($node->nodeName() eq "xmlcfg") {
          #uniquifier found
          $uniq_ext = $adcfg_doc->findvalue($node->nodePath);
          debugMsg("parse_parameters: found uniquifier <".$node->nodeName().">".$adcfg_doc->findvalue($node->nodePath)."<\/".$node->nodeName()."> in file $config_file");
        } elsif ($node->nodeName() ne "parcfg") {
          #ordinary parameters
          debugMsg("parse_parameters: found <".$node->nodeName().">".$adcfg_doc->findvalue($node->nodePath)."<\/".$node->nodeName()."> in file $config_file");
          $hash_name_value{$node->nodeName()} = $adcfg_doc->findvalue($node->nodePath);
        } # elsif node parcfg
      } # foreach node/cfgnodes
    } # else
  } # if config_file ne not_defined_file

  # catch empty files
  if (keys %hash_name_value) {
    $parse = 1;
  } else {
    print_error("ERROR: Unable to locate any valid name=value pairs within the file $config_file");
  }

  if ($parse == 1) {

    # sort through the nodes and stick them into an ordered list (use spirit:order)
    my %ordered_params;

    my $sub_order = 0;
    my $order_count++;
    
    foreach my $Param_node (@userParams) { # ($userParams->get_nodelist) {
      my $param_name = $Param_node->findvalue("spirit:name");
      my $param_value= $Param_node->findvalue("spirit:value");
      debugMsg("parse_parameters: found in IPXACT (name=value): $param_name=$param_value");

      my $param_value_node = $Param_node->find("spirit:value")->get_node(0);

      # Assert an arbitrary ordering if spirit:order is not defined
      $Param_node->find("spirit:value")->get_node(0)->setAttribute("spirit:order", $order_count++) if not($Param_node->find("spirit:value")->get_node(0)->hasAttribute('spirit:order'));
      # Assert a default rangeType if it is not defined
      $Param_node->find("spirit:value")->get_node(0)->setAttribute("spirit:rangeType", "float") if (not($Param_node->find("spirit:value")->get_node(0)->hasAttribute('spirit:rangeType')) and $Param_node->find("spirit:value")->get_node(0)->hasAttribute('spirit:maximum'));
      
      if (check_configuration( $param_value_node )) {
        # if the node is okay add it to the stack

        # get the spirit:order, if there isn't one, assume zero (first)
        my $this_order = 0;
        if ($Param_node->find("spirit:value")->get_node(0)->hasAttribute('spirit:order')) {
          $this_order = $Param_node->find("spirit:value")->get_node(0)->getAttribute('spirit:order');
        }

        # construct a potential key
        my $this_key = $this_order + $sub_order;
        # check if it exists
        if (defined $ordered_params{$this_key}) {
          # one already exists, increment the fraction of the (sub) order
          $sub_order += 0.001; # good for 1000 options!
          $this_key = $this_order + $sub_order;
        }

        # store away the node
        debugMsg("parse_parameters: storing parameter #$this_key");
        $ordered_params{$this_key} = $Param_node;
      } else {
        print_error("An error occured within the spirit:parameter $param_name\n");
        $check = 0;
      }
    }

    # now have all the parameter nodes in an hash that can be ordered

    foreach my $key (sort sort_numerical keys %ordered_params) {
      debugMsg("parse_parameters: examining parameter #$key");
      my $arm_presence = ();
      my $name = $ordered_params{$key}->findvalue("spirit:name");
      if($XML_doc->find("/spirit:component")->get_node(0)->hasAttribute("xmlns:arm")) {
        $arm_presence = $XML_doc->find('/spirit:component/spirit:parameters/spirit:parameter[spirit:name="'.$name.'"]/spirit:vendorExtensions/arm:presence');
      } else {
        debugMsg("parse_parameters: No arm namespace");
      }
      ## evaluate if they have arm:presence
      if ((defined $arm_presence) and ($arm_presence->size() == 1)) {
        debugMsg("parse_parameters: arm:presence detected for parameter = $name");
        # get the value
        my $presence_result = solve_dependency($arm_presence->get_node(0));

        # store value down
        $arm_presence->get_node(0)->firstChild->setData($presence_result);

      } elsif ((defined $arm_presence) and ($arm_presence->size() > 1)) {
        print_error("parse_parameters: multiple arm:presence tags detected on parameter $name");
      } else {
        debugMsg("parse_parameters: no arm:presence detected");
      }

      if (defined $arm_presence) {
        # copy over arm_presence variable with evaluated tag (either 'true', 'false' or not defined).
        $arm_presence = $XML_doc->findvalue('/spirit:component/spirit:parameters/spirit:parameter[spirit:name="'.$name.'"]/spirit:vendorExtensions/arm:presence');
      } else {
        debugMsg("parse_parameters: no arm:presence detected");
        $arm_presence = 'true';
      }
      ## decide where to get a value for it from
      if (($ask == 1)&&($arm_presence !~ /false/ )) {
        # prompt the user for a value
        my $param = $ordered_params{$key};

        # - show name
        # - show description
        # - if not choice
        #   - define type (integer, string, bitString, float)
        #   - define bounds (min/max, if a bitString then length)
        # - if choice (find choice)
        #   - foreach enumeration (spirit:enumeration)
        #     - display value (@spirit:text) with meanings (@spirit:help) and required entry value (.)
        # - while not valid (or enter for default/original)
        #   - prompt for value
        #   - check_parameter

        if ($param->find('./spirit:name')) {
          print "Please enter value for the configuration parameter '".$param->findvalue('./spirit:name')."' [".$name."]\n";
        } else {
          print_error("parse_parameters: No spirit:name present for parameter: ".$name);
          $check = 0;
        }

        if ($param->find('./spirit:description')) {
          # remove any techpub markup and convert "&lt;"/"&gt;"
          my $description = remove_TPmarkup($param->findvalue('./spirit:description'));
          print "Description for this parameter:\n ".$description."\n";
        } else {
          print_error("parse_parameters: No spirit:description present for parameter: ".$name);
          $check = 0;
        }

        if ($param->find('./spirit:value/@spirit:choiceRef')) {
          # it's part of a choiceRef - go find and display that
          my $config_path = '/spirit:component/spirit:choices/spirit:choice[spirit:name="'.$param->findvalue('./spirit:value/@spirit:choiceRef').'"]';
          debugMsg("parse_parameters: Finding config: $config_path");
          my $config_node = $XML_doc->find($config_path)->get_node(0);

          print "\nSelect from one of the following options:\n";

          foreach my $enum ($config_node->find('./spirit:enumeration')->get_nodelist()) {
            my $enum_text;
            my $enum_description;
            my $enum_value = $enum->textContent();
            if ($enum->hasAttribute('spirit:text')) {
              $enum_text = $enum->getAttribute('spirit:text');
            } else {
              debugMsg("parse_parameters: No spirit:text defined");
            }
            if ($enum->hasAttribute('spirit:help')) {
              $enum_description = remove_TPmarkup($enum->getAttribute('spirit:help'));
            } else {
              debugMsg("parse_parameters: No spirit:description defined");
            }

            if ($enum_text) {
              print "For a value of '".$enum_text."', enter: ".$enum_value."\n";
            } else {
              print "Enter: ".$enum_value."\n";
            }
            if ($enum_description) {
              print " ".$enum_description."\n";
            }

          }

        } else {
          # not a choice, just display what we can find out...

          # type of value
          print "Require a value of type: ".$param->findvalue('./spirit:value/@spirit:format')."\n";

          # min/max of value
          if ($param->find('./spirit:value/@spirit:minimum')) {
            print "The value must be greater than or equal to: ".$param->findvalue('./spirit:value/@spirit:minimum')."\n";
          }
          if ($param->find('./spirit:value/@spirit:maximum')) {
            print "The value must be less than or equal to: ".$param->findvalue('./spirit:value/@spirit:maximum')."\n";
          }

          # bitString
          if ($param->find('./spirit:value/@spirit:bitStringLength')) {
            print "The bitString is required to be a string ".$param->findvalue('./spirit:value/@spirit:bitStringLength')." characters long\n";
          }
        }

        # prompt the user until they get it right (!)
        my $valid = 0;
        my $default_val = $param->findvalue('./spirit:value');
        while ($valid == 0) {
          my $user_val;
          print "Enter value [enter for default=".$default_val."] : ";
          chomp ($user_val = <STDIN>);

          if ($user_val ne '') {
          } else {
            # no defined, copy the default
            $user_val = $default_val;
          }

          # store value down
          my $node_path = 'spirit:component/spirit:parameters/spirit:parameter[spirit:name="'.$name.'"]/spirit:value';
          if($XML_doc->find($node_path)) {
            $XML_doc->find($node_path)->get_node(0)->firstChild->setData($user_val);
          } else {
            $node_path = '//spirit:modelParameter[spirit:name="'.$name.'"]/spirit:value';
            $XML_doc->find($node_path)->get_node(0)->firstChild->setData($user_val);
          }
          $valid = check_configuration($ordered_params{$key}->find("spirit:value")->get_node(1));
          if ($valid == 0) {
            print "Invalid option entered. Please try again.\n";
          }
        }

      } elsif (((defined $arm_presence) and ($arm_presence !~ /false/ )) or (not(defined $arm_presence))){ # if ($ask != 1)
        # copy from the stored hash
        if (defined $hash_name_value{$name}) {
          # parameter in IP-XACT matches one passed in the command line
          # copy value across (to IP-XACT)

          my $node_path = '//spirit:parameter[spirit:name="'.$name.'"]/spirit:value';
          if($XML_doc->find($node_path)) {
            $XML_doc->find($node_path)->get_node(0)->firstChild->setData($hash_name_value{$name});
          } else {
            $node_path = '//spirit:modelParameter[spirit:name="'.$name.'"]/spirit:value';
            $XML_doc->find($node_path)->get_node(0)->firstChild->setData($hash_name_value{$name});
          }
          my $param_value = $XML_doc->findvalue($node_path);
          debugMsg("parse_parameters: updated XML: $name=$param_value");

          # make sure the value supplied is okay to be used
          if (check_configuration($ordered_params{$key}->find("spirit:value")->get_node(1)) == 0) {
            $check = 0;
          }

        } else {
          # error, value not supplied but was expected!
          print "ERROR: missing value for the spirit:parameter/spirit:modelParameter $name\n";
          $check = 0;
        }

        # do a final grab of the value
        my $value = $ordered_params{$key}->findvalue("spirit:value");
        print "Have value of '".$value."' for attribute: ".$name."\n";

      } else {
        # parameter not required as arm:presence evaluated to false
        if ($ordered_params{$key}->find('./spirit:name')) {
          print "Value for the configuration parameter '".$ordered_params{$key}->findvalue('./spirit:name')."' [".$name."] is not required.\n";
        } else {
          print_error("parse_parameters: No spirit:name present for parameter: ".$name);
          $check = 0;
        }
        # delete from the parameter hash if it's there
        if (exists $hash_name_value{$key}) {
          delete (${$_[1]}{$key});
        }
        # don't forget to delete the parameter from the search list
        delete ($ordered_params{$key});
      }

    }

    # all values updated
    if (($ask == 1) && scalar(@userParams)) { #$userParams) {
      # ask if they want to save it ***uses same format as config input***
      # - prompt y/n
      # - until possible to create
      #   - ask for filename (default= "spirit:name"_config)
      # - store contents of hash_name_value to file.
      print "Do you wish to save this configuration?\n Enter 'yes' to save (anything else to skip): ";
      my $save;
      chomp ($save = <STDIN>);
      if ($save eq "yes") {

        my $valid_file = 0;
        while ($valid_file == 0) {
          print "Please enter a filename (including path) to continue: ";
          chomp ($save = <STDIN>);

          if (-e $save) {
            print "Cannot save to $save. File already exists.\n";
          } elsif (open CONFIG, "> $save") {
            debugMsg("parse_parameters: successfully opened file $save");
            $valid_file = 1;

            print CONFIG "# Configuration file for ".$XML_doc->findvalue('spirit:component/spirit:name')."\n";

            foreach my $pkey (keys %ordered_params) {
              my $line = $ordered_params{$pkey}->findvalue("spirit:name")." = ".$ordered_params{$pkey}->findvalue("spirit:value")."\n";
              print CONFIG $line;
            }

            print CONFIG "# End of configuration file.\n";

          } else {
            print "An error occured opening the file $save ".$!."\n";
          }


        }

      }

    }

    # params updated, copy them back to the hash
    if (($ask == 1) && scalar(@userParams)) { #$userParams) {
      foreach my $pkey (keys %ordered_params) {
        my $param_name = $ordered_params{$pkey}->findvalue("spirit:name");
        my $param_val = $ordered_params{$pkey}->findvalue("spirit:value");
        ${$_[1]}{$param_name} = $param_val;
        debugMsg("parse_parameters: adding ".$param_name." as ".${$_[1]}{$param_name});
      }
    }

    # now delete any element in the passed hash that doesn't exist
    foreach my $nameval (keys %hash_name_value) {
      if (exists $ordered_params{$nameval}) {
        # is present in original hash - leave it!
      } else {
        # extra value - delete it! (unless it was spirit:name)
        delete ($hash_name_value{$nameval});
      }
    }


  } else {     # if ($parse != 1)
    $check = 0;
  }

  my @return_var;
  push(@return_var, $check);
  if (defined $uniq_ext) {push(@return_var, $uniq_ext)};

  return @return_var;

}


#################################################################################
# Routine : call_generators
#    calls all the generators specified in IP-XACT doc (assumes parameters have been updated)
#
# Arguments :
#    XMLDOC pre-opened XML document (the IP-XACT file)
#
# Returns : status (1 = okay)
#################################################################################
sub call_generators() {
  my $XML_doc = shift;
  my $do_run = shift;
  my $filename = shift;
  my $status = 1;

  debugMsg("call_generators running");

  # find all parameters in IP-XACT Doc (XMLDOC)
  my $GeneratorList = $XML_doc->find('spirit:component/spirit:componentGenerators/spirit:componentGenerator');
  my %Gen_phases;
  foreach my $Gen_node ($GeneratorList->get_nodelist) {
    # get generator name
    my $Gen_name = $Gen_node->findvalue("spirit:name");
    # get phase_number
    my $Gen_phase_element = $Gen_node->find("spirit:phase")->get_node(0);
    my $Gen_phase = "999999999";
    if (defined $Gen_phase_element) {
      $Gen_phase = $Gen_phase_element->getFirstChild->getValue();
    }

    debugMsg("call_generators: found Generator: $Gen_name ($Gen_phase)");

    # check apiType, transportMethods before adding
    my $check_node = $Gen_node->find("spirit:apiType")->get_node(0);
    if ((defined $check_node) && ($check_node->getFirstChild->getValue() eq "none")) {
      # right api type
      # check transport
      $check_node = $Gen_node->find("spirit:transportMethods/spirit:transportMethod")->get_node(0);
      if (defined $check_node) {
        # success!
        $Gen_phases{$Gen_name} = $Gen_phase;
      } else {
        # erp! wrong transport (or missing)
        print_error("spirit:transportMethods for generator name=$Gen_name is not supported\n");
        $status = 0;
      }
    } else {
      # erp! wrong api (or missing)
      print_error("spirit:apiType for generator name=$Gen_name is not supported\n");
      $status = 0;
    }
  }

  # run through them in sequence
  foreach my $key (sort { $Gen_phases{$a} <=> $Gen_phases{$b} } keys %Gen_phases) {

    my $Gen_name = $key;
    my $Gen_phase = $Gen_phases{$key};
    debugMsg("call_generators: running $Gen_name in sequence: $Gen_phase");

    my $Gen_node_path = 'spirit:component/spirit:componentGenerators/spirit:componentGenerator[spirit:name="'.$Gen_name.'"]';

    my $Gen_exe = $XML_doc->findvalue($Gen_node_path."/spirit:generatorExe");

    # fetch list of parameters to call alongside the generator
    my $param_list = $XML_doc->find($Gen_node_path."/spirit:parameters/spirit:parameter");
    my $param_string = ""; # string to store the options in
    foreach my $Gen_param ($param_list->get_nodelist) {
      my $Gen_param_name = $Gen_param->findvalue("spirit:name");
      my $Gen_param_value_element = $Gen_param->find("spirit:value")->get_node(0);
      my $Gen_param_value;

      debugMsg("call_generators: topnode=".$Gen_param_value_element->toString);

      # need to check the param value as it may be a XPath defined
      check_configuration($Gen_param_value_element);
      $Gen_param_value = solve_dependency($Gen_param_value_element);
      # store the value to the string
      $param_string = "$param_string ".$Gen_param_name."=".$Gen_param_value;

    } # foreach param

    # now have all the parameters on the string, call the generator
    # Need to get the correct path (Gen_exe is relative to the IP-XACT file)
    # get the location of IP-XACT file to cd to before calling generator

    my $run_location = dirname($filename);

    # check the Gen_exe exists...
    if (-e $run_location."/".$Gen_exe) {
      debugMsg("call_generators: Generator found...");
    } else {
      print_error("Could not find the generator: $Gen_exe \n");
      $do_run = 0;
      $status = 0;
    }

    print "> $Gen_exe $param_string\n";

    if ($do_run == 1) {
      my $result;
      eval { $result = `cd $run_location; $Gen_exe $param_string`};
      if ( $@ ) {
        print "\nAn error occurred within the generator\n";
        $status = 0;
      }
      print "Generator output: \n$result\n";
    } else {
      print "WARNING: calling of generator disabled\n";
    }


  }

  return $status;

}

#################################################################################
# Routine : resolve_doc
#    find all the XPath expressions and solve them
#
# Arguments :
#    XMLDOC pre-opened XML document (the IP-XACT file)
#    filename of this file
#
# Returns : status (1 = okay)
#################################################################################
sub resolve_doc($$) {
  my $XML_doc = shift;
  my $filename = shift;
  my $status = 1;

  debugMsg("resolve_doc running");

  # find all nodes that have a @spirit:resolve="dependent"
  my $nodes_to_solve = $XML_doc->find('//*[@spirit:resolve="dependent"]');

  my $found_number = $nodes_to_solve->size();
  debugMsg("resolve_doc: found ".$found_number." nodes that have dependency to solve.");

  foreach my $curr_node ($nodes_to_solve->get_nodelist) {
    debugMsg("resolve_doc: found node @ ".$curr_node->nodePath());

    # solve the expression
    my $new_value = solve_dependency($curr_node);

    # save the value
    my $tmp_result = $XML_doc->find($curr_node->nodePath());
    my $tmp_result2 = $curr_node->nodePath();
    debugMsg(" Searching for node: ".$tmp_result2);
    if ($tmp_result->size() == 1) {
       $tmp_result->get_node(0)->firstChild->setData($new_value);
    } else {
       print_error(" Didn't find the right number of nodes to replace -got:".$tmp_result->size());
    }

    # load it back to check
    my $param_value = $XML_doc->findvalue($curr_node->nodePath());
    debugMsg("resolve_doc: updated XML: $param_value");

  }

  # delete anything that had arm:presence evaluate to false
  # or just delete the arm:presence tag if it was true (after)
  if($XML_doc->find("/spirit:component")->get_node(0)->hasAttribute("xmlns:arm")) {

    my $arm_nodes = $XML_doc->find('//*[spirit:vendorExtensions/arm:presence="false"]');
    $found_number = $arm_nodes->size();
    debugMsg("resolve_doc: found ".$found_number." nodes that have an arm:presence tag set to false.");
    foreach my $arm_node ($arm_nodes->get_nodelist) {
      debugMsg("resolve_doc: found arm node @ ".$arm_node->nodePath());
      # delete the node!
      my $this_node = $arm_node->nodeName();
      my $parent_node = $arm_node->parentNode;
      $parent_node->removeChild($arm_node);
    }
  
    # ...delete the arm:presence tag if it was true
    $arm_nodes = $XML_doc->find('//arm:presence[.="true"]');
    $found_number = $arm_nodes->size();
    debugMsg("resolve_doc: found ".$found_number." nodes that have an arm:presence tag set to true.");
    foreach my $arm_node ($arm_nodes->get_nodelist) {
      debugMsg("resolve_doc: found arm node @ ".$arm_node->nodePath());
      # delete the node!
      my $this_node = $arm_node->nodeName();
      my $parent_node = $arm_node->parentNode;
      $parent_node->removeChild($arm_node);
  
      # check if there are any children present on the node (see if any other
      # vendorExtensions present)
      my $children = $parent_node->hasChildNodes();
      debugMsg("resolve_doc: children on this node? $children");
      my $elements_present = 0;
      if ($children) {
        my $childs = $parent_node->childNodes();
        foreach my $this_child ($childs->get_nodelist) {
          if ($this_child->nodeType == XML::LibXML::XML_ELEMENT_NODE) {
            # An element is present
            $elements_present++;
          }
        }
      }
      # if no more elements are nested within the vendorExtension then delete the
      # vendorExtension element as well
      if ($elements_present == 0) {
        $this_node = $parent_node;
        debugMsg("resolve_doc: deleting".$this_node->nodePath());
        $parent_node = $this_node->parentNode;
        $parent_node->removeChild($this_node);
      }
  
    }
  } else {
    debugMsg("resolve_doc: No arm namespace");
  }

  return $status;

}

#################################################################################
# Routine : solidify_doc
#    Removes of any ability to change the document (changes resolve=user to immediate)
#
# Arguments :
#    XMLDOC pre-opened XML document (the IP-XACT file)
#    filename of this file
#    flag for skipping changing resolve=depends
#
# Returns : status (1 = okay)
#################################################################################
sub solidify_doc($$) {
  my $XML_doc = shift;
  my $filename = shift;
  my $skip_depends = shift;
  my $status = 1;

  debugMsg("solidify_doc running");

  # find all nodes that have a @spirit:resolve="user"
  my $nodes_to_solve = $XML_doc->find('//*[@spirit:resolve="user"]');

  my $found_number = $nodes_to_solve->size();
  debugMsg("solidify_doc: found ".$found_number." user resolve nodes.");

  foreach my $curr_node ($nodes_to_solve->get_nodelist) {
    debugMsg("solidify_doc: fixing node @ ".$curr_node->nodePath());

    # change it to immediate
    $XML_doc->find($curr_node->nodePath())->get_node(0)->setAttribute("spirit:resolve", "immediate");
  }

  if ($skip_depends == 0) {
    # repeat process for spirit:resolve=dependent nodes *and* delete dependency (illegal otherwise)

    # find all nodes that have a @spirit:resolve="dependent"
    $nodes_to_solve = $XML_doc->find('//*[@spirit:resolve="dependent"]');

    $found_number = $nodes_to_solve->size();
    debugMsg("solidify_doc: found ".$found_number." nodes with resolve=dependent.");

    foreach my $curr_node ($nodes_to_solve->get_nodelist) {
      debugMsg("solidify_doc: fixing node @ ".$curr_node->nodePath());

      # change it to immediate
      $XML_doc->find($curr_node->nodePath())->get_node(0)->setAttribute("spirit:resolve", "immediate");

      # delete the dependency (XPath) expression
      $XML_doc->find($curr_node->nodePath())->get_node(0)->removeAttribute("spirit:dependency");
    }
  }

  return $status;

}

#################################################################################
# Routine : save_doc
#    find all the XPath expressions and solve them
#
# Arguments :
#    XMLDOC pre-opened XML document (the IP-XACT file)
#    filename of original IP-XACT doc (need path to the file as base)
#
# Returns : status (1 = okay)
#################################################################################
sub save_doc($$$) {
  my $XML_doc = shift;
  my $directory = shift;
  my $overwrite = shift;
  my $status = 1;

  debugMsg("save_doc running");
  strip_unused($XML_doc);

  my $name = $XML_doc->findvalue("spirit:component/spirit:name");
  my $save_to = $directory."/".$name.".xml";

  if (-e $save_to) {
    if ($overwrite) {
      print "Warning: File already exists with the same name: << $save_to >>, deleting it as the flag -overwrite is been used\n";
      unlink $save_to;
    } else {
      print "Error: File already exists with the same name: << $save_to >>, please consider adding the optional flag -overwrite to the command line\n";
      $status = 0;
    }
  }

  system("mkdir -p $directory") == 0 or die "Failed to create a directory at this location : << $directory >>, please make sure you have write access to it.";
  my $state = $XML_doc->toFile($save_to);
  if ($state) {
    print "IP-XACT component has been successfully saved to $save_to !\n";
  } else {
    print "An error occured when writing the file $save_to .\n";
    $status = 0;
  }

  return $status;
}

#################################################################################
# Routine : sort_numerical
#    Numerical sorting routine (for use with sorting hash keys)
#################################################################################
sub sort_numerical { $a <=> $b }

#################################################################################
# Routine : fix_path
#    fix path in the xml doc, when TARGET_DIRECTORY or TARGET_IPXACT_DIRECTORY is present
#
# Arguments :
#    XMLDOC pre-opened XML document (the IP-XACT file), $default_ipxact_dir
##
# Returns : none
#################################################################################
sub fix_path() {
  my $XML_doc = shift;
  my $ipxact_dir = shift;
  my $file_name = shift;
  # get absolute paths from relative paths
  $ipxact_dir = `readlink -m $ipxact_dir`;
  chomp($ipxact_dir);
  $ipxact_dir = strip_dots($ipxact_dir);
  debugMsg("fix_path: ipxact dir is: ".$ipxact_dir);

  # search for file names
  my $target_dir = $XML_doc->findvalue('spirit:component/spirit:parameters/spirit:parameter[spirit:name="TARGET_DIRECTORY"]/spirit:value');
  if ($target_dir ne "") {print "target directory is $target_dir\n";}
  my $nodes = $XML_doc->find('/spirit:component/spirit:fileSets/spirit:fileSet/spirit:file/spirit:name');
  foreach my $node ($nodes->get_nodelist) {
    my $node_val = $XML_doc->findvalue($node->nodePath);
    if ($target_dir !~ /^\//) {
      $node_val = dirname($file_name);
      $node_val = $node_val."/".$XML_doc->findvalue($node->nodePath);
    }
    # get absolute path to file
    $node_val = `readlink -m $node_val`;
    chomp($node_val);
    debugMsg("fix_path: file were : ".$node_val);
    # calculate relative path
    $node_val = strip_dots($node_val);
    my $new_node_val = rel_path($ipxact_dir,$node_val);
    debugMsg("fix_path: file will be: ".$new_node_val);
    #find node and insert corrected value
    my $node_path = $XML_doc->find($node->nodePath());
    $node_path->get_node(0)->firstChild->setData($new_node_val);
    # load it back to check
    $new_node_val = $XML_doc->findvalue($node->nodePath());
    debugMsg("fix_path: file is: ".$new_node_val);
  }

  # Dependencies
  $nodes = $XML_doc->find('/spirit:component/spirit:fileSets/spirit:fileSet/spirit:dependency');
  foreach my $node ($nodes->get_nodelist) {
    my $node_val = $XML_doc->findvalue($node->nodePath);
    if ($target_dir !~ /^\//) {
      $node_val = dirname($file_name);
      $node_val = $node_val."/".$XML_doc->findvalue($node->nodePath);
    }
    # get absolute path to file
    $node_val = `readlink -m $node_val`;
    chomp($node_val);
    debugMsg("fix_path: dir were : ".$node_val);
    # calculate relative path
    $node_val = strip_dots($node_val);
    my $new_node_val = rel_path($ipxact_dir,$node_val);
    debugMsg("fix_path: dir will be: ".$new_node_val);
    #find node and insert corrected value
    my $node_path = $XML_doc->find($node->nodePath());
    $node_path->get_node(0)->firstChild->setData($new_node_val);
    # load it back to check
    $new_node_val = $XML_doc->findvalue($node->nodePath());
    debugMsg("fix_path: dir is: ".$new_node_val);
  }
}

#################################################################################
# Routine : strip_dots
#    erase dots in the middle of file paths, when the path do not begin with
#    dots, calculating the path correctly without the dots
#
# Arguments :
#    some file path
##
# Returns : path without dots in the middle
#################################################################################
sub strip_dots ($) {
  my $path = shift;
  while ($path =~ /\/\.\.\//)  {
    $path =~ s/([^ \r\t\n\f\/]+)\/\.\.\///;
    print "$path\n";
  }
  return $path;
}

#################################################################################
# Routine : rel_path
#    calculate the relative path from one location to another
#
# Arguments :
#    two directories or file paths
##
# Returns : relative path from first argument to second argument
#################################################################################
sub rel_path ($$){
  my $start = shift;
  my $end = shift;
  # separate each path level
  my @start_ = split("\/", $start);
  my @end_ = split("\/", $end);
  my $i = 0;
  # keep erasing the begining of each path untill they are different
  while ($start_[$i] eq $end_[$i]) {
    $end =~ s/${end_[$i]}(\/)*//;
    $start =~ s/${start_[$i]}(\/)*//;
    $i = $i + 1;
    if ($i > $#start_ or $i > $#end_) {last;}
  }
  # transform remaining $start content into ..
  if ($start ne "") {
    $start =~ s/([^ \r\t\n\f\/]+)/\.\./g;
    $end = $start."\/".$end;
  }
  return $end;
}
