/****************************************************************
*
* module qspi_hclk_gen_top generated by ezchip
* 
*
*****************************************************************/
`timescale 1ns/1ps

module qspi_hclk_gen_top (
//output signal
	output hclk,




//input signal
`ifdef _XILINX_FPGA_
	input _ez_fpga_clk_src_,
`else
	input aclk,
`endif //_XILINX_FPGA_


	input test_en,
	input scan_en,
	input resetn,



	input [3:0] hclk_div);

`ifdef __QSPI_HCLK_GEN_EMPTY__
//output signal
	assign hclk = 1'h0;






`else


qspi_hclk_gen qspi_hclk_gen_instance (
	.hclk(hclk),
	.hclk_div(hclk_div),
	.test_en(test_en),
	.scan_en(scan_en),
	.resetn(resetn),
	`ifdef _XILINX_FPGA_
	._ez_fpga_clk_src_(_ez_fpga_clk_src_)
`else
	.aclk(aclk)
`endif //
);


`endif

endmodule
