/****************************************************************
*
* module qspi_hclk_gen generated by ezchip
* 
*
*****************************************************************/
`timescale 1ns/1ps

module qspi_hclk_gen (
//output signal
	output hclk,
//input signal
	input [3:0] hclk_div,
`ifdef _XILINX_FPGA_
	input _ez_fpga_clk_src_,
`else
	input aclk,
`endif //_XILINX_FPGA_
	input test_en,
	input scan_en,
	input resetn
);
//internal clock

/****************************************************************
*
* clock hclk
*
*****************************************************************/
wire hclk_stp1;
`ifdef _XILINX_FPGA_
assign hclk_stp1 = _ez_fpga_clk_src_;
`else
assign hclk_stp1 = aclk;
`endif //_XILINX_FPGA_

wire hclk_stp2;
`ifdef _XILINX_FPGA_
assign hclk_stp2 = hclk_stp1;
`else
assign hclk_stp2 = hclk_stp1;
`endif //_XILINX_FPGA_

wire hclk_stp3;
wire [2:0] hclk_div_sync;
wire hclk_stp3_unbuf;
assign hclk_div_sync = hclk_div;
divideModule #(.DIV_WIDTH(4)) hclk_div_inst_ (
	.SE(scan_en),
	.resetn(resetn),
	.clk_in(hclk_stp2),
	.divisor(hclk_div_sync),
	.out_clk(hclk_stp3_unbuf)
);
ez_clk_div_buf dont_touch_hclk_div_obuf_inst_ (
	.Z(hclk_stp3),
	.I(hclk_stp3_unbuf)
);

wire hclk_stp4;
assign hclk_stp4 = hclk_stp3;

wire hclk_stp5;
assign hclk_stp5 = hclk_stp4;

wire hclk_stp6;
assign hclk_stp6 = hclk_stp5;

`ifdef _XILINX_FPGA_
assign hclk = hclk_stp6;
`else
assign hclk = hclk_stp6;
`endif //_XILINX_FPGA_


endmodule
