// --========================================================================--
//   The confidential and proprietary information contained in this file may
//   only be used by a person authorised under and to the extent permitted
//   by a subsisting licensing agreement from ARM Limited.
//    (C) COPYRIGHT 2000-2001, 2007 ARM Limited
//        ALL RIGHTS RESERVED
//   This entire notice must be reproduced on all copies of this file
//   and copies of this file may only be made by a person if such person is
//   permitted to do so under the terms of a subsisting license agreement
//   from ARM Limited.
//------------------------------------------------------------------------------
//
//  Version and Release Control Information:
//
//  File Name              : UartBaudCntr.v.rca
//  File Revision          : 23277
//
//  Release Information    : PL011-r1p5-00rel0
//
//------------------------------------------------------------------------------
// Purpose     : This block contains the 16 bit down counter used to
//               generate the Baud16 signal
// --=========================================================================--

`timescale 1ns/1ps

module UartBaudCntr (
                     UARTCLK,
                     nUARTRST,
                     LCRUpdateSync,
                     ILPRUpdateSync,
                     FBRDUpdateSync,
		     SIRENSync,
		     SIRLPSync,
		     CharTxComp,
		     CharRxComp,
                     StopBaudCnt,
                     FracValue,
                     UARTLCRHInt,
                     UARTLCRM,
                     UARTLCRL,
                     UARTILPR,
                     Baud16,
                     IrLPBaud16,
                     LCRH,
                     Abort,
		     LoadValue,
                     Zerobaud
                    );

input        UARTCLK;         // Main UART Clock
input        nUARTRST;        // Muxed Reset (from nUARTRST)
input        LCRUpdateSync;   // Sync control for LCR
input        ILPRUpdateSync;  // Sync control for ILPR
input        FBRDUpdateSync;  // Sync control for FBRD
input        SIRENSync;       // SIR Enable
input        SIRLPSync;       // SIR Low power Enable
input        CharTxComp;      // Character Tx complete                   
input        CharRxComp;      // Character Rx complete                   
input        StopBaudCnt;     // Stop baud count
input  [5:0] FracValue;       // Fractional part of baud rate divisor
input  [6:0] UARTLCRHInt;     // 1st stage
input  [7:0] UARTLCRM;        // 1st stage
input  [7:0] UARTLCRL;        // 1st stage
input  [7:0] UARTILPR;        // 1st stage

output        Baud16;         // Stream of UARTCLK-wide pulses
output        IrLPBaud16;     // For Low power IrDA
output  [6:1] LCRH;           // 2nd buffer
output        Abort;          // TX Abort
output        Zerobaud;       // Illegal divisor value
output [15:0] LoadValue;      // Baud16 divisor value

//------------------------------------------------------------------------------
// Purpose     : This block contains the 16 bit down counter used to
//               generate the Baud16 signal
//------------------------------------------------------------------------------
//
//------------------------------------------------------------------------------
//
//                   UartBaudCntr
//                   ============
//
//------------------------------------------------------------------------------
//
// Overview
// ========
//
// This block generates the Baud16 signal by dividing down the input clock
// UARTCLK. It contains a 16-bit down-counter, which reloads to either the
// LoadValue or (LoadValue + 1) every time it reaches one. The value loaded
// depends on the carry part of an adder. This adder combined with the different
// load values is used to generate a Fractional divider as well.
//
// When the count reaches one, a one UARTCLK clock wide pulse is created
// on the Baud16 signal.  This signal is used to add a fractional part to a
// 6-bit adder and the carry output from this adder is used to control the load
// value of the 16-bit counter described earlier.
//
// This block also generates the IrLPBaud16 signal by dividing the
// input UARTCLK by the value (IrDA Low Power Divisor). The 
// SIRLPC counter that generates this signal is an 8-bit wide
// down counter.
//
// This module contains the second stage buffers for the LCR
// registers (UARTLCRH, UARTLCRM and UARTLCRL) and the UARTILPR
// register. Data on the corresponding first stage inputs are
// clocked into the second stage buffers when the LCRStg2WrEn
// signal or the ILPRStg2WrEn signal is asserted. 
// The LCRStg2WrEn signal is generated by XORing the UpdateLCRSync
// input with the internal delayed version of that signal. The
// delayed version is only updated at the end of the character
// being transmitted or received, so that the registers do not get
// updated during transmission or reception.
// The ILPRStg2WrEn signal is also generated in a similar manner.
//
//------------------------------------------------------------------------------

`define FBRDAdderValue 6'b011111
  
//------------------------------------------------------------------------------
// Wire declaration
//------------------------------------------------------------------------------
wire        UARTCLK;
// Main UART Clock                                     (Module Input)

wire        nUARTRST;
// Muxed Reset (from nUARTRST)                         (Module Input)

wire  [6:0] UARTLCRHInt;
// 1st stage                                           (Module Input)

wire  [7:0] UARTLCRM;
// 1st stage                                           (Module Input)

wire  [7:0] UARTLCRL;
// 1st stage                                           (Module Input)

wire  [7:0] UARTILPR;
// 1st stage                                           (Module Input)

wire        LCRUpdateSync;
// Sync control for LCR                                (Module Input)

wire        ILPRUpdateSync;
// Sync control for ILPR                               (Module Input)

wire        SIRENSync;
// SIR Enable                                          (Module Input)

wire        SIRLPSync;
// SIR Low power Enable                                (Module Input)

wire        CharTxComp;
// Character Tx Complete                               (Module Input)

wire        CharRxComp;
// Character Rx Complete                               (Module Input)

wire        StopBaudCnt;
// Stop baud count                                     (Module Input)

wire  [5:0] FracValue;
// Fractional part of baud rate divisor                (Module Input)

wire        LCRStg2WrEn;
// Load signal for 2nd stage LCR buffers

wire        ILPRStg2WrEn;
// Load signal for 2nd stage ILPR buffer

wire [15:0] iLoadValue;
// Counter that is used to generate the Baud16 signal
// Internal version of LoadValue signal

wire        iBaud16;
// Internal version of Baud16 signal

wire        iIrLPBaud16;
// Internal version of IrLPBaud16 signal

wire        FBRDStg2WrEn;
// Delayed version of load signal for 2nd stage of FBRD buffer

wire  [6:0] FBRDadd1;
// Concatenation of 0 and FBRDadd for 1st part of addition

wire  [6:0] FBRDadd2;
// Concatenation of 0 and FBRD for 2nd part of addition

//------------------------------------------------------------------------------
// Register declaration
//------------------------------------------------------------------------------
reg  [6:0] iLCRH;
// 2nd stage buffer for UARTLCRH

reg  [6:0] NextLCRH;
// D-input for LCRH

reg  [7:0] LCRM;
// 2nd stage buffer for UARTLCRM

reg  [7:0] NextLCRM;
// D-input for LCRH

reg  [7:0] LCRL;
// 2nd stage buffer for UARTLCRL

reg  [7:0] NextLCRL;
// D-input for LCRL

reg  [7:0] ILPR;
// 2nd stage buffer for UARTILPR

reg  [7:0] NextILPR;
// D-input for ILPR

reg  [5:0] FBRD;
// 2nd stage buffer for UARTFBRD

reg  [5:0] NextFBRD;
// D-input for FBRD

reg [15:0] CountBaud16;
//  Counter that is used to generate the Baud16 signal

reg [15:0] NextCountBaud16;
// D-input of CountBaud16

reg  [7:0] iSIRLPC;
// Internal version of SIRLPC counter that is used to generate the IrLPBaud16
// signal

reg  [7:0] NextSIRLPC;
// D-input of iSIRLPC
  
reg        LstCntBaud16Bit1;
// Delayed version of Bit 0 of CountBaud16

reg        LstSIRLPCBit0;
// Delayed version of Bit 0 of SIRLPC

reg        DelLCRUpdate;
// Delayed version of LCRUpdateSync

reg        DelILPRUpdate;
// Delayed version of ILPRUpdateSync

reg        DelFBRDUpdate;
// Delayed version of FBRDUpdateSync

reg        NextDelLCRUpdate;
// D-input of LCRUpdate

reg        NextDelILPRUpdate;
// D-input of ILPRUpdate

reg        NextDelFBRDUpdate;
// D-input of FBRDUpdate

reg        DelLCRStg2WrEn;
// Delayed version of load signal for 2nd stage of LCR buffers

reg        DelILPRStg2WrEn;
// Delayed version of load signal for 2nd stage of ILPR buffer

reg        iZerobaud;
// internal version of Illegal divisor signal

reg        UARTFBRDCarry;
// Carry from Fractional baud rate counter

reg        NextUARTFBRDCarry;
// Carry from Fractional baud rate counter, next value

reg  [6:0] NextUARTFBRDadd;
// Output of addition for UARTFBRDadd

reg  [5:0] UARTFBRDadd;
// Sum for fractional baud rate divider

reg 	   StopLPCntr;
// Stop Low power IrDa counter

reg 	   NextStopLPCntr;
// D-input of StopLPCntr 

//------------------------------------------------------------------------------
//
// Main Verilog code
// =================
//
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Generation of delayed versions of the Update trigger inputs. The
// Delayed Update signals can only change once the current character has
// completed.
//------------------------------------------------------------------------------
always @ (posedge UARTCLK or negedge nUARTRST)
begin : p_DelSeq
  if (nUARTRST == 1'b0)
    begin
      DelLCRUpdate  <= 1'b0;
      DelILPRUpdate <= 1'b0;
      DelFBRDUpdate <= 1'b0;
    end
  else
    begin
      DelLCRUpdate  <= NextDelLCRUpdate;
      DelILPRUpdate <= NextDelILPRUpdate;
      DelFBRDUpdate <= NextDelFBRDUpdate;
    end
end // block: p_DelSeq
  

always @ (CharRxComp or CharTxComp or LCRUpdateSync or ILPRUpdateSync or
          FBRDUpdateSync or DelLCRUpdate or DelILPRUpdate or DelFBRDUpdate)
begin: p_DelComb
  if((CharRxComp == 1'b1) && (CharTxComp == 1'b1))
    begin
      NextDelLCRUpdate  = LCRUpdateSync;
      NextDelILPRUpdate = ILPRUpdateSync;
      NextDelFBRDUpdate = FBRDUpdateSync;
    end
  else
    begin
      NextDelLCRUpdate  = DelLCRUpdate;
      NextDelILPRUpdate = DelILPRUpdate;
      NextDelFBRDUpdate = DelFBRDUpdate;
    end        
end // block: p_DelComb
  
//------------------------------------------------------------------------------
// Generation of load signals for second stage buffers.
//------------------------------------------------------------------------------
assign LCRStg2WrEn  = (LCRUpdateSync ^ DelLCRUpdate) && (CharRxComp && CharTxComp);
assign ILPRStg2WrEn = (ILPRUpdateSync ^ DelILPRUpdate) && (CharRxComp && CharTxComp);
assign FBRDStg2WrEn = (FBRDUpdateSync ^ DelFBRDUpdate) && (CharRxComp && CharTxComp);


//------------------------------------------------------------------------------
// Write into LCRH , LCRM , LCRL and IrLPR registers
//------------------------------------------------------------------------------
always @(LCRStg2WrEn or ILPRStg2WrEn or FBRDStg2WrEn or iLCRH or LCRM or 
         LCRL or ILPR or FBRD or  UARTLCRHInt or UARTLCRM or UARTLCRL or 
         UARTILPR or FracValue)
begin : p_RegWrComb
  NextLCRH = iLCRH;
  NextLCRM = LCRM;
  NextLCRL = LCRL;
  NextILPR = ILPR;
  NextFBRD = FBRD;
  if (LCRStg2WrEn == 1'b1)
    begin
      NextLCRH = UARTLCRHInt;
      NextLCRM = UARTLCRM;
      NextLCRL = UARTLCRL;
    end

  if (ILPRStg2WrEn == 1'b1)
    begin
      NextILPR = UARTILPR;
    end

  if (FBRDStg2WrEn == 1'b1) 
    begin
      NextFBRD = FracValue;
    end

end // p_RegWrComb;

//------------------------------------------------------------------------------
// Sequential process for write
//------------------------------------------------------------------------------
always @(posedge UARTCLK or negedge nUARTRST)
begin : p_RegWrSeq
  if(nUARTRST == 1'b0)
    begin
      iLCRH <= 7'b0000000;
      LCRM  <= 8'b00000000;
      LCRL  <= 8'b00000000;
      ILPR  <= 8'b00000000;
      FBRD  <= 6'b000000;
    end
  else
    begin
      iLCRH <= NextLCRH;
      LCRM  <= NextLCRM;
      LCRL  <= NextLCRL;
      ILPR  <= NextILPR;
      FBRD  <= NextFBRD;
    end
end // p_RegWrSeq;

//------------------------------------------------------------------------------
// Assignment of the local copy to port
//------------------------------------------------------------------------------
assign  LCRH = iLCRH[6:1];

//------------------------------------------------------------------------------
// Delayed version of LCRStg2WrEn and IrLPRStg2WrEn
//------------------------------------------------------------------------------
always @ (posedge UARTCLK or negedge nUARTRST)
begin : p_DelWrEn
  if(nUARTRST == 1'b0)
    begin
      DelLCRStg2WrEn   <= 1'b0;
      DelILPRStg2WrEn  <= 1'b0;
    end
  else
    begin
      DelLCRStg2WrEn  <= LCRStg2WrEn;
      DelILPRStg2WrEn <= ILPRStg2WrEn;
    end
end // p_DelWrEn;

//------------------------------------------------------------------------------
// Combining LCRM and LCRL registers
//------------------------------------------------------------------------------
assign  iLoadValue = {LCRM, LCRL};

//------------------------------------------------------------------------------
// Divide by n+1/n counter:
// Reset the counter to its reload value whenever the StopBaudCnt signal is
// asserted or when the count reaches one or when the reloadvalue has been
// updated with a write to the MUBRLCR/LUBRLCR registers. When the count reaches
// one, the counter will be reloaded with either n or n+1 depending on the state
// of the carry signal from the adder.
//------------------------------------------------------------------------------

always @ (CountBaud16 or DelLCRStg2WrEn or iLoadValue or StopBaudCnt or
          UARTFBRDCarry or iZerobaud)
begin : p_X16CntComb
  NextCountBaud16 = CountBaud16;
  if ((StopBaudCnt == 1'b1) || (DelLCRStg2WrEn == 1'b1) || (iZerobaud == 1'b1))
    begin
      NextCountBaud16 = iLoadValue;
    end
  else
    begin
      if (CountBaud16 == 16'b0000000000000001)
        begin
          if (UARTFBRDCarry == 1'b0)
            begin
              NextCountBaud16 = iLoadValue;
            end // if (UARTFBRDCarry == 1'b0)
          else
            begin
              NextCountBaud16 = (iLoadValue + 1'b1);
            end     
        end // if (CountBaud16 == 16'b0000000000000001)
      else
        begin
          NextCountBaud16 = (CountBaud16 - 1'b1);
        end // else: !if(CountBaud16 == 16'b0000000000000001)
    end
end // p_X16CntComb;

//------------------------------------------------------------------------------
// Clock in the LSBit of the count to facilitate detection of a zero-to-one
// transition.  LstCntBaud16Bit1 is generated from the divide by n/n+1 counter
// and used to generate the Baud16 signal (high for 1 UARTCLK cycle).
//------------------------------------------------------------------------------
always @ (posedge UARTCLK  or negedge nUARTRST)
begin : p_X16CntSeq
  if (nUARTRST == 1'b0)
    begin
      LstCntBaud16Bit1 <= 1'b0;
      CountBaud16      <= 16'b0000000000000000;
    end
  else
    begin
      LstCntBaud16Bit1 <= CountBaud16[0];
      CountBaud16      <= NextCountBaud16;
    end
end // p_X16CntSeq;

//------------------------------------------------------------------------------
// For the divide by n/n+1 counter:
// Detect the counter counting down to one by seeing if the
// counter has reached one and the previous value of the
// LSBit is zero.
//------------------------------------------------------------------------------
assign iBaud16 = (((LstCntBaud16Bit1 == 1'b0) && (CountBaud16 == 16'b0000000000000001)) ||
                ((iLoadValue == 16'b0000000000000001) && (CountBaud16 == 16'b0000000000000001)));
  
//------------------------------------------------------------------------------
// When the Baud16 signal is high, the adder is loaded with the fractional part.
// Otherwise the adder retains it value. Also, at reset, the adder is
// initialised with the value in FBRDAdderValue. This can be set to a non-zero
// value to average out the pulse spread between /n and /(n+1).
//------------------------------------------------------------------------------
always @(posedge UARTCLK or negedge nUARTRST)
begin : p_AdderSeq
  if(nUARTRST == 1'b0)
    UARTFBRDadd   <= `FBRDAdderValue;
  else
    UARTFBRDadd   <= NextUARTFBRDadd[5:0];
end // block: p_AdderSeq

// Define the two values to add: M + CurrentAdderValue : Note that the MSB
// (Carry) in both is set to zero always.
assign  FBRDadd1 = {1'b0,UARTFBRDadd};
assign  FBRDadd2 = {1'b0,FBRD};

always @ (FBRDadd1 or FBRDadd2 or StopBaudCnt or iBaud16)
begin : p_AdderComb
  if (StopBaudCnt == 1'b1)
    NextUARTFBRDadd = {1'b0, `FBRDAdderValue};      // including carry
  else
    begin
      if (iBaud16 == 1'b1)
        NextUARTFBRDadd = FBRDadd1 + FBRDadd2;
      else
        NextUARTFBRDadd = FBRDadd1;
    end // else: !if(StopBaudCnt == 1'b1)
end // block: p_AdderComb
  
// Once Carry is asserted, it should be held high for one UARTCLK cycle, so that
// it can be used to load the 16-bit counter with n+1 (because it will have
// counted down to one). When carry is low and the counter has counted down,
// it should be loaded with n.
  always @ (posedge UARTCLK or negedge nUARTRST)
  begin : p_CarrySeq
    if(nUARTRST == 1'b0)
      UARTFBRDCarry <= 1'b0;
    else
      UARTFBRDCarry <= NextUARTFBRDCarry;
  end // block: p_CarrySeq

  always @ (StopBaudCnt or iBaud16 or NextUARTFBRDadd or UARTFBRDCarry)
  begin : p_CarryComb
    if (StopBaudCnt == 1'b1)
      NextUARTFBRDCarry = 1'b0;
    else if (iBaud16 == 1'b1)
      NextUARTFBRDCarry = NextUARTFBRDadd[6];
    else
      NextUARTFBRDCarry = UARTFBRDCarry;
  end // block: p_CarryComb

//------------------------------------------------------------------------------
// If the Load value is 0 and the Fractional divisor value is 0, then
// pull the Zerobaud output continuously  high, else Zerobaud is 0.
//------------------------------------------------------------------------------
always @ (iLoadValue or FBRD)
begin : p_ZeroBaud
  if ((iLoadValue == 16'b0000000000000000) || ((iLoadValue == 16'b1111111111111111)
        && (FBRD != 6'b000000)))
    begin
      iZerobaud = 1'b1;
    end
  else
    begin
      iZerobaud = 1'b0;
    end
end // p_ZeroBaud;

//------------------------------------------------------------------------------
// Assignment of the local copy to port
//------------------------------------------------------------------------------
assign Zerobaud = iZerobaud;

//------------------------------------------------------------------------------
// Generation of StopLPCntr signal.
// StopLPCntr is asserted when SIRENSync and SIRLPSync are both
// deasserted and CharTxComp and CharRxComp are asserted. This signal
// is used to stop the low power IrDa counter when the Uart is
// operating in normal mode. The current character completes
// transmission or reception before the counter stops.
//------------------------------------------------------------------------------

always @ (StopLPCntr or SIRENSync or SIRLPSync or CharTxComp or CharRxComp)
begin : p_StopLPCntrSeqComb
  NextStopLPCntr = StopLPCntr;
    if ((SIRENSync == 1'b0) && (SIRLPSync == 1'b0) &&
           (CharTxComp == 1'b1) && (CharRxComp == 1'b1))  
      NextStopLPCntr = 1'b1;
    else if ((SIRENSync == 1'b1) || (SIRLPSync == 1'b1)) 
      NextStopLPCntr = 1'b0;     
end // block: p_StopLPCntrSeqComb

  
always @ (posedge UARTCLK or negedge nUARTRST)
begin : p_StopLPCntrSeq
  if(nUARTRST == 1'b0)
    StopLPCntr <= 1'b1;
  else
    StopLPCntr <= NextStopLPCntr;
end // block: p_StopLPCntrSeq
  

//------------------------------------------------------------------------------
// IrLPBaud16 generation
// The counter is reloaded with it's initial value when any of the
// following occur:
//   - the IrDa modes are both disabled and the current character has
//   - finished being transmitted or received.
//   - StopBaudCnt is asserted.
//   - the counter has counted down to 1.
//   - a new value has been written to the low power divisor register(ILPR) 
//------------------------------------------------------------------------------
always @(iSIRLPC or DelILPRStg2WrEn or ILPR or StopBaudCnt or SIRENSync or 
         SIRLPSync or StopLPCntr)
begin : p_SIRLPCComb
  NextSIRLPC = iSIRLPC;
  if ((StopBaudCnt == 1'b1) || (DelILPRStg2WrEn == 1'b1) || ((StopLPCntr == 1'b1) &&
                                (SIRENSync == 1'b0) && (SIRLPSync == 1'b0)))
    begin
      NextSIRLPC = ILPR;
    end
  else
    begin
      if (iSIRLPC == 8'b00000001)
        begin
          NextSIRLPC = ILPR;
        end
      else
        begin
          NextSIRLPC = (iSIRLPC - 1'b1);
        end
    end
end // p_SIRLPCComb;
  
//------------------------------------------------------------------------------
// Sequential process for the SIRLPC counter.
//------------------------------------------------------------------------------
always @(posedge UARTCLK or negedge  nUARTRST)
begin : p_SIRLPCSeq
  if(nUARTRST == 1'b0)
    begin
      LstSIRLPCBit0 <= 1'b0;
      iSIRLPC       <= 8'b00000000;
    end
  else
    begin
      LstSIRLPCBit0 <= iSIRLPC[0];
      iSIRLPC       <= NextSIRLPC;
    end
end // p_SIRLPCSeq;

//------------------------------------------------------------------------------
// Detect the counter counting down to one by seeing if the
// counter has reached one and the previous value of the
// LSBit is zero. If ILPR is set to 1, then IrLPBaud16 is pulled high
//------------------------------------------------------------------------------
assign iIrLPBaud16 = (((LstSIRLPCBit0 == 1'b0) && (iSIRLPC == 8'b00000001)) ||
                      ILPR == 8'b00000001);

//------------------------------------------------------------------------------
// Assignment of the local copy to port
//------------------------------------------------------------------------------
assign IrLPBaud16  = iIrLPBaud16;
assign Baud16      = iBaud16;
assign LoadValue   = iLoadValue;

//------------------------------------------------------------------------------
// Abort transmission if
// * 'BRK' bit in the LCRH is asserted
// * zerobaud is asserted
//------------------------------------------------------------------------------
assign Abort  = ((iLCRH[0] == 1'b1) || (iZerobaud == 1'b1));

endmodule

// ========================= End of UartBaudCntr =============================--
