//------------------------------------------------------------------------------
// The confidential and proprietary information contained in this file may
// only be used by a person authorised under and to the extent permitted
// by a subsisting licensing agreement from Arm Limited or its affiliates.
//
//            (C) COPYRIGHT 2019-2021 Arm Limited or its affiliates.
//                ALL RIGHTS RESERVED
//
// This entire notice must be reproduced on all copies of this file
// and copies of this file may only be made by a person if such person is
// permitted to do so under the terms of a subsisting license agreement
// from Arm Limited or its affiliates.
//
//
//      Release Information : SSE710-r0p0-00eac0
//
//------------------------------------------------------------------------------
// Verilog-2001 (IEEE Std 1364-2001)
//------------------------------------------------------------------------------


module secenc_f1_aontop #(
  parameter    [15:0] SEC_ENC_ROM_SIZE          = 16'd32,  
  parameter    [15:0] SEC_ENC_RAM_SIZE          = 16'd128, 
  parameter           CAAON2CA_WIDTH            = 34,      
  parameter           CA2CAAON_WIDTH            = 49,      
  parameter           DEV_PREQ_DLY_SECENC       = 0,       
  parameter           PCSM_PREQ_DLY_SECENC      = 0,       
  parameter           ISO_CLKEN_DLY_CFG_SECENC  = 0,       
  parameter           CLKEN_RST_DLY_CFG_SECENC  = 0,       
  parameter           RST_HWSTAT_DLY_CFG_SECENC = 0,       
  parameter           CLKEN_ISO_DLY_CFG_SECENC  = 0,       
  parameter           ISO_RST_DLY_CFG_SECENC    = 0        
) (
  input  wire         SECENCREFCLK,
  input  wire         SYSPLL,
  input  wire         SYSPLLLOCK,
  input  wire         S32KCLK,

  input  wire         SEPORESETn,

  output wire         SECENCCLK,
  output wire         SECENCDIVCLK,
  output wire         SECENCHINTCLK,
  output wire         S32KCLK_SECENC,

  output wire         SECENCPORESETn,
  output wire         SECENCWARMRESETn,

  input  wire         nUARTCTS,  
  input  wire         nUARTDCD,  
  input  wire         nUARTDSR,  
  input  wire         nUARTRI,   
  input  wire         UARTRXD,   
  output wire         UARTTXD,   
  output wire         nUARTDTR,  
  output wire         nUARTRTS,  
  output wire         nUARTOut1, 
  output wire         nUARTOut2, 

  input  wire  [63:0] EXTIRQ, 
  output wire         SOC_WD_IRQ,
  output wire         UART_IRQ,
  output wire         PPU_IRQ,
  output wire         CO_IRQ,
  input wire          MHU2R_CIRQ,
  input wire          MHU2S_CIRQ,
    input wire          MHU3R_CIRQ,
  input wire          MHU3S_CIRQ,
    input wire          MHU4R_CIRQ,
  input wire          MHU4S_CIRQ,
    input wire          MHU5R_CIRQ,
  input wire          MHU5S_CIRQ,
    input  wire         HOST_FWT_IRQ, 
  input  wire         INT_RTT_IRQ,  
  input  wire         SWD_WS1_IRQ,  
  output wire         HOST_FWT_IRQ_SS, 
  output wire         INT_RTT_IRQ_SS,  
  output wire         SWD_WS1_IRQ_SS,  
   
  
  output wire [127:0] SCB,  
  
  input  wire         CALC,    

  input  wire   [1:0] HOST_RST_ACK,         
  output wire         HOST_CPUWAIT,         
  input  wire   [5:0] CHS_PWR_ST,           
  output wire   [5:0] CHS_PWR_REQ,          
  input  wire   [4:0] SOC_RST_SYN,          
  input  wire   [2:0] SE_RST_SYN,           

  output wire         S32_WDOG_RST_REQ,  
  output wire         SOC_RST_REQ,       
  output wire         HOST_RST_REQ,      
  output wire         CAE_RST_REQ,       
  
  input  wire         AON_APB_ASYNC_REQ,
  input  wire  [55:0] AON_APB_ASYNC_REQ_PAYLOAD,
  output wire  [32:0] AON_APB_ASYNC_RESP_PAYLOAD,
  output wire         AON_APB_ASYNC_ACK,

  input  wire         SOCWD_APB_ASYNC_REQ,
  input  wire  [47:0] SOCWD_APB_ASYNC_REQ_PAYLOAD,
  output wire  [32:0] SOCWD_APB_ASYNC_RESP_PAYLOAD,
  output wire         SOCWD_APB_ASYNC_ACK,  
  
  output wire         DBGD_QREQn,
  input  wire         DBGD_QACCEPTn,
  input  wire         DBGD_QDENY,
  input  wire         DBGD_QACTIVE,
  output wire         MHU0_QREQn,
  input  wire         MHU0_QACCEPTn,
  input  wire         MHU0_QDENY,
  output wire         MHU1_QREQn,
  input  wire         MHU1_QACCEPTn,
  input  wire         MHU1_QDENY,
  output wire         MHU2_QREQn,
  input  wire         MHU2_QACCEPTn,
  input  wire         MHU2_QDENY,
    output wire         MHU3_QREQn,
  input  wire         MHU3_QACCEPTn,
  input  wire         MHU3_QDENY,
    output wire         MHU4_QREQn,
  input  wire         MHU4_QACCEPTn,
  input  wire         MHU4_QDENY,
    output wire         MHU5_QREQn,
  input  wire         MHU5_QACCEPTn,
  input  wire         MHU5_QDENY,
    output wire         CTI_QREQn,
  input  wire         CTI_QACCEPTn,
  input  wire         CTI_QDENY,
  input  wire         CTI_QACTIVE,

  output wire         CM0_QREQn,
  input  wire         CM0_QACCEPTn,
  input  wire         CM0_QDENY,
  input  wire         CM0_QACTIVE,

  output wire         AXIB_QREQn,
  input  wire         AXIB_QACCEPTn,
  input  wire         AXIB_QDENY,
  input  wire         AXIB_QACTIVE,

  output wire         SOCWD_ADB_QREQn,
  input  wire         SOCWD_ADB_QACCEPTn,
  input  wire         SOCWD_ADB_QDENY,
  input  wire         SOCWD_ADB_QACTIVE,

  output wire         AON_ADB_QREQn,
  input  wire         AON_ADB_QACCEPTn,
  input  wire         AON_ADB_QDENY,
  input  wire         AON_ADB_QACTIVE,
  
  input  wire         SYSC_QREQn,
  output wire         SYSC_QACCEPTn,
  output wire         SYSC_QDENY,
  output wire         SYSC_QACTIVE,
  
  input  wire         DBGC_QREQn,
  output wire         DBGC_QACCEPTn,
  output wire         DBGC_QDENY,
  output wire         DBGC_QACTIVE,   

  input  wire         MHU_HSE0_RECWAKEUP_ASYNC,
  input  wire         MHU_HSE1_RECWAKEUP_ASYNC,
  input  wire         MHU_ES0SE0_RECWAKEUP_ASYNC,
    input  wire         MHU_ES0SE1_RECWAKEUP_ASYNC,
    input  wire         MHU_ES1SE0_RECWAKEUP_ASYNC,
    input  wire         MHU_ES1SE1_RECWAKEUP_ASYNC,
     
  input  wire         CDBGPWRUPREQ0,
  output wire         CDBGPWRUPACK0,

  output wire         CLKFORCE,
  output wire [7:0]   ENTRY_DELAY,

  input  wire         M0_HALTED,
  
  output wire   [CAAON2CA_WIDTH-1:0] CAAON2CA,
  input  wire   [CA2CAAON_WIDTH-1:0] CA2CAAON,  

  input  wire         CAE,  
  output wire         CA_ERR_MSK, 

  

  input  wire         DFTDIVSEL,
  input  wire         DFTCLKSELEN,
  input  wire   [1:0] DFTCLKSEL,
  input  wire         DFTDIVBYPASS,
  input  wire   [1:0] DFTRSTDISABLE,
  input  wire         DFTISODISABLE,
  input  wire         DFTRETDISABLE,
  input  wire         DFTPWRUP,
  input  wire         DFTCGEN,
  input  wire         nMBISTRESET,
  input  wire         MBISTREQ,
  input  wire         DFTSE,
  input  wire         DFTTESTMODE
);

  secenc_f1_aon #(
    .SEC_ENC_ROM_SIZE             (SEC_ENC_ROM_SIZE),
    .SEC_ENC_RAM_SIZE             (SEC_ENC_RAM_SIZE),
    .CAAON2CA_WIDTH               (CAAON2CA_WIDTH),
    .CA2CAAON_WIDTH               (CA2CAAON_WIDTH),
    .DEV_PREQ_DLY_SECENC          (DEV_PREQ_DLY_SECENC),
    .PCSM_PREQ_DLY_SECENC         (PCSM_PREQ_DLY_SECENC),
    .ISO_CLKEN_DLY_CFG_SECENC     (ISO_CLKEN_DLY_CFG_SECENC),
    .CLKEN_RST_DLY_CFG_SECENC     (CLKEN_RST_DLY_CFG_SECENC),
    .RST_HWSTAT_DLY_CFG_SECENC    (RST_HWSTAT_DLY_CFG_SECENC),
    .CLKEN_ISO_DLY_CFG_SECENC     (CLKEN_ISO_DLY_CFG_SECENC),
    .ISO_RST_DLY_CFG_SECENC       (ISO_RST_DLY_CFG_SECENC)
  ) u_secenc_f1_aon (             
    .SECENCREFCLK                 (SECENCREFCLK),
    .SYSPLL                       (SYSPLL),
    .SYSPLLLOCK                   (SYSPLLLOCK),
    .S32KCLK                      (S32KCLK),
    .SEPORESETn                   (SEPORESETn),
    .SECENCCLK                  (SECENCCLK),
    .SECENCDIVCLK               (SECENCDIVCLK),
    .SECENCHINTCLK              (SECENCHINTCLK),
    .S32KCLK_SECENC             (S32KCLK_SECENC),
    .SECENCPORESETn             (SECENCPORESETn),
    .SECENCWARMRESETn           (SECENCWARMRESETn),
    .nUARTCTS                     (nUARTCTS),
    .nUARTDCD                     (nUARTDCD),
    .nUARTDSR                     (nUARTDSR),
    .nUARTRI                      (nUARTRI),
    .UARTRXD                      (UARTRXD),
    .UARTTXD                      (UARTTXD),
    .nUARTDTR                     (nUARTDTR),
    .nUARTRTS                     (nUARTRTS),
    .nUARTOut1                    (nUARTOut1),
    .nUARTOut2                    (nUARTOut2),
    .EXTIRQ                       (EXTIRQ),
    .SOC_WD_IRQ                   (SOC_WD_IRQ),
    .UART_IRQ                     (UART_IRQ),
    .PPU_IRQ                      (PPU_IRQ),
    .CO_IRQ                       (CO_IRQ),
 
    .MHU2R_CIRQ (MHU2R_CIRQ),
    .MHU2S_CIRQ (MHU2S_CIRQ),
      .MHU3R_CIRQ (MHU3R_CIRQ),
    .MHU3S_CIRQ (MHU3S_CIRQ),
   
    .MHU4R_CIRQ (MHU4R_CIRQ),
    .MHU4S_CIRQ (MHU4S_CIRQ),
      .MHU5R_CIRQ (MHU5R_CIRQ),
    .MHU5S_CIRQ (MHU5S_CIRQ),
      .HOST_FWT_IRQ                 (HOST_FWT_IRQ),
    .INT_RTT_IRQ                  (INT_RTT_IRQ),
    .SWD_WS1_IRQ                  (SWD_WS1_IRQ),
    .HOST_FWT_IRQ_SS              (HOST_FWT_IRQ_SS),
    .INT_RTT_IRQ_SS               (INT_RTT_IRQ_SS),
    .SWD_WS1_IRQ_SS               (SWD_WS1_IRQ_SS),
    .SCB                          (SCB),
    .CALC                         (CALC),
    .HOST_RST_ACK                 (HOST_RST_ACK),
    .HOST_CPUWAIT                 (HOST_CPUWAIT),
    .CHS_PWR_ST                   (CHS_PWR_ST),
    .CHS_PWR_REQ                  (CHS_PWR_REQ),
    .SOC_RST_SYN                  (SOC_RST_SYN),
    .SE_RST_SYN                   (SE_RST_SYN),
    .S32_WDOG_RST_REQ             (S32_WDOG_RST_REQ),
    .SOC_RST_REQ                  (SOC_RST_REQ),
    .HOST_RST_REQ                 (HOST_RST_REQ),
    .CAE_RST_REQ                  (CAE_RST_REQ),
    .AON_APB_ASYNC_REQ            (AON_APB_ASYNC_REQ),
    .AON_APB_ASYNC_REQ_PAYLOAD    (AON_APB_ASYNC_REQ_PAYLOAD),
    .AON_APB_ASYNC_RESP_PAYLOAD   (AON_APB_ASYNC_RESP_PAYLOAD),
    .AON_APB_ASYNC_ACK            (AON_APB_ASYNC_ACK),
    .SOCWD_APB_ASYNC_REQ          (SOCWD_APB_ASYNC_REQ),
    .SOCWD_APB_ASYNC_REQ_PAYLOAD  (SOCWD_APB_ASYNC_REQ_PAYLOAD),
    .SOCWD_APB_ASYNC_RESP_PAYLOAD (SOCWD_APB_ASYNC_RESP_PAYLOAD),
    .SOCWD_APB_ASYNC_ACK          (SOCWD_APB_ASYNC_ACK),
    .DBGD_QREQn                   (DBGD_QREQn),
    .DBGD_QACCEPTn                (DBGD_QACCEPTn),
    .DBGD_QDENY                   (DBGD_QDENY),
    .DBGD_QACTIVE                 (DBGD_QACTIVE),
    .MHU0_QREQn                   (MHU0_QREQn),
    .MHU0_QACCEPTn                (MHU0_QACCEPTn),
    .MHU0_QDENY                   (MHU0_QDENY),
    .MHU1_QREQn                   (MHU1_QREQn),
    .MHU1_QACCEPTn                (MHU1_QACCEPTn),
    .MHU1_QDENY                   (MHU1_QDENY),
 
    .MHU2_QREQn    (MHU2_QREQn),
    .MHU2_QACCEPTn (MHU2_QACCEPTn),
    .MHU2_QDENY    (MHU2_QDENY),
      .MHU3_QREQn    (MHU3_QREQn),
    .MHU3_QACCEPTn (MHU3_QACCEPTn),
    .MHU3_QDENY    (MHU3_QDENY),
   
    .MHU4_QREQn    (MHU4_QREQn),
    .MHU4_QACCEPTn (MHU4_QACCEPTn),
    .MHU4_QDENY    (MHU4_QDENY),
      .MHU5_QREQn    (MHU5_QREQn),
    .MHU5_QACCEPTn (MHU5_QACCEPTn),
    .MHU5_QDENY    (MHU5_QDENY),
    
    .CM0_QREQn                    (CM0_QREQn),
    .CM0_QACCEPTn                 (CM0_QACCEPTn),
    .CM0_QDENY                    (CM0_QDENY),
    .CM0_QACTIVE                  (CM0_QACTIVE),
    .AXIB_QREQn                   (AXIB_QREQn),
    .AXIB_QACCEPTn                (AXIB_QACCEPTn),
    .AXIB_QDENY                   (AXIB_QDENY),
    .AXIB_QACTIVE                 (AXIB_QACTIVE),
    .SOCWD_ADB_QREQn              (SOCWD_ADB_QREQn),
    .SOCWD_ADB_QACCEPTn           (SOCWD_ADB_QACCEPTn),
    .SOCWD_ADB_QDENY              (SOCWD_ADB_QDENY),
    .SOCWD_ADB_QACTIVE            (SOCWD_ADB_QACTIVE),
    .AON_ADB_QREQn                (AON_ADB_QREQn),
    .AON_ADB_QACCEPTn             (AON_ADB_QACCEPTn),
    .AON_ADB_QDENY                (AON_ADB_QDENY),
    .AON_ADB_QACTIVE              (AON_ADB_QACTIVE),
    .SYSC_QREQn                   (SYSC_QREQn),
    .SYSC_QACCEPTn                (SYSC_QACCEPTn),
    .SYSC_QDENY                   (SYSC_QDENY),
    .SYSC_QACTIVE                 (SYSC_QACTIVE),
    .DBGC_QREQn                   (DBGC_QREQn),
    .DBGC_QACCEPTn                (DBGC_QACCEPTn),
    .DBGC_QDENY                   (DBGC_QDENY),
    .DBGC_QACTIVE                 (DBGC_QACTIVE),
    .CTI_QREQn                    (CTI_QREQn),
    .CTI_QACCEPTn                 (CTI_QACCEPTn),
    .CTI_QDENY                    (CTI_QDENY),
    .CTI_QACTIVE                  (CTI_QACTIVE), 
    .MHU_HSE0_RECWAKEUP_ASYNC     (MHU_HSE0_RECWAKEUP_ASYNC),
    .MHU_HSE1_RECWAKEUP_ASYNC     (MHU_HSE1_RECWAKEUP_ASYNC),
 
    .MHU_ES0SE0_RECWAKEUP_ASYNC   (MHU_ES0SE0_RECWAKEUP_ASYNC),
      .MHU_ES0SE1_RECWAKEUP_ASYNC   (MHU_ES0SE1_RECWAKEUP_ASYNC),
   
    .MHU_ES1SE0_RECWAKEUP_ASYNC   (MHU_ES1SE0_RECWAKEUP_ASYNC),
      .MHU_ES1SE1_RECWAKEUP_ASYNC   (MHU_ES1SE1_RECWAKEUP_ASYNC),
     
    .CDBGPWRUPREQ0                (CDBGPWRUPREQ0),
    .CDBGPWRUPACK0                (CDBGPWRUPACK0),
    .CLKFORCE                     (CLKFORCE),
    .ENTRY_DELAY                  (ENTRY_DELAY),
    .M0_HALTED                    (M0_HALTED),
    .CAAON2CA                     (CAAON2CA),
    .CA2CAAON                     (CA2CAAON),
    .CAE                          (CAE),
    .CA_ERR_MSK                   (CA_ERR_MSK),
    .DFTDIVSEL                    (DFTDIVSEL),
    .DFTCLKSELEN                  (DFTCLKSELEN),
    .DFTCLKSEL                    (DFTCLKSEL),
    .DFTDIVBYPASS                 (DFTDIVBYPASS),
    .DFTRSTDISABLE                (DFTRSTDISABLE),
    .DFTISODISABLE                (DFTISODISABLE),
    .DFTPWRUP                     (DFTPWRUP),
    .DFTRETDISABLE                (DFTRETDISABLE),
    .DFTCGEN                      (DFTCGEN),
    .MBISTREQ                     (MBISTREQ),
    .nMBISTRESET                  (nMBISTRESET),
    .DFTSE                        (DFTSE),
    .DFTTESTMODE                  (DFTTESTMODE)
  );

endmodule
