//------------------------------------------------------------------------------
// The confidential and proprietary information contained in this file may
// only be used by a person authorised under and to the extent permitted
// by a subsisting licensing agreement from Arm Limited or its affiliates.
//
//            (C) COPYRIGHT 2019-2021 Arm Limited or its affiliates.
//                ALL RIGHTS RESERVED
//
// This entire notice must be reproduced on all copies of this file
// and copies of this file may only be made by a person if such person is
// permitted to do so under the terms of a subsisting license agreement
// from Arm Limited or its affiliates.
//
//
//      Release Information : SSE710-r0p0-00eac0
//
//------------------------------------------------------------------------------
// Verilog-2001 (IEEE Std 1364-2001)
//------------------------------------------------------------------------------

module pc_eh_f0_extsysmem #(

    parameter  EXT_SYSX_MEM_ADDR_WIDTH       = 32,
    parameter  EXT_SYSX_MEM_DATA_WIDTH       = 64,
    parameter  EXT_SYSX_MEM_AWID_WIDTH       = 8,
    parameter  EXT_SYSX_MEM_ARID_WIDTH       = 8,
    parameter  EXT_SYSX_MEM_AWUSER_WIDTH     = 0,
    parameter  EXT_SYSX_MEM_WUSER_WIDTH      = 0,
    parameter  EXT_SYSX_MEM_BUSER_WIDTH      = 0,
    parameter  EXT_SYSX_MEM_ARUSER_WIDTH     = 0,
    parameter  EXT_SYSX_MEM_RUSER_WIDTH      = 0,
    parameter  EXT_SYSX_MEM_AW_FIFO_DEPTH    = 4,
    parameter  EXT_SYSX_MEM_W_FIFO_DEPTH     = 6,
    parameter  EXT_SYSX_MEM_B_FIFO_DEPTH     = 2,
    parameter  EXT_SYSX_MEM_AR_FIFO_DEPTH    = 4,
    parameter  EXT_SYSX_MEM_R_FIFO_DEPTH     = 6,
    parameter  EXT_SYSX_MEM_AW_PAYLOAD_WIDTH = 236,
    parameter  EXT_SYSX_MEM_W_PAYLOAD_WIDTH  = 222,
    parameter  EXT_SYSX_MEM_B_PAYLOAD_WIDTH  = 24,
    parameter  EXT_SYSX_MEM_AR_PAYLOAD_WIDTH = 236,
    parameter  EXT_SYSX_MEM_R_PAYLOAD_WIDTH  = 264
  )
  (
    input  wire           extsysx_aclk,

    input  wire           extsysx_aresetn,

    input  wire                                  awakeup_extsysx_mem,
    input  wire [EXT_SYSX_MEM_AWID_WIDTH-1:0]     awid_extsysx_mem,
    input  wire [31:0]                           awaddr_extsysx_mem,
    input  wire [7:0]                            awlen_extsysx_mem,
    input  wire [2:0]                            awsize_extsysx_mem,
    input  wire [1:0]                            awburst_extsysx_mem,
    input  wire                                  awlock_extsysx_mem,
    input  wire [3:0]                            awcache_extsysx_mem,
    input  wire [2:0]                            awprot_extsysx_mem,
    input  wire [3:0]                            awregion_extsysx_mem,
    input  wire                                  awvalid_extsysx_mem,
    output wire                                  awready_extsysx_mem,
    input  wire [(EXT_SYSX_MEM_DATA_WIDTH/8)-1:0] wstrb_extsysx_mem,
    input  wire                                  wlast_extsysx_mem,
    input  wire                                  wvalid_extsysx_mem,
    input  wire [EXT_SYSX_MEM_DATA_WIDTH-1:0]     wdata_extsysx_mem,
    output wire                                  wready_extsysx_mem,
    output wire [EXT_SYSX_MEM_AWID_WIDTH-1:0]     bid_extsysx_mem,
    output wire [1:0]                            bresp_extsysx_mem,
    output wire                                  bvalid_extsysx_mem,
    input  wire                                  bready_extsysx_mem,
    input  wire [EXT_SYSX_MEM_ARID_WIDTH-1:0]     arid_extsysx_mem,
    input  wire [31:0]                           araddr_extsysx_mem,
    input  wire [7:0]                            arlen_extsysx_mem,
    input  wire [2:0]                            arsize_extsysx_mem,
    input  wire [1:0]                            arburst_extsysx_mem,
    input  wire                                  arlock_extsysx_mem,
    input  wire [3:0]                            arcache_extsysx_mem,
    input  wire [2:0]                            arprot_extsysx_mem,
    input  wire [3:0]                            arregion_extsysx_mem,
    input  wire                                  arvalid_extsysx_mem,
    output wire                                  arready_extsysx_mem,
    output wire [EXT_SYSX_MEM_ARID_WIDTH-1:0]     rid_extsysx_mem,
    output wire [1:0]                            rresp_extsysx_mem,
    output wire                                  rlast_extsysx_mem,
    output wire                                  rvalid_extsysx_mem,
    output wire [EXT_SYSX_MEM_DATA_WIDTH-1:0]     rdata_extsysx_mem,
    input  wire                                  rready_extsysx_mem,

    input  wire                          qreqn_extsysx_aclk,
    output wire                          qacceptn_extsysx_aclk,
    output wire                          qdeny_extsysx_aclk,
    output wire                          qactive_extsysx_aclk,

    input  wire                          qreqn_extsysx_mempwr,
    output wire                          qacceptn_extsysx_mempwr,
    output wire                          qdeny_extsysx_mempwr,
    output wire                          qactive_extsysx_mempwr,

    output wire                                     slvmustacceptreqn_async_ehx,
    output wire                                     slvcandenyreqn_async_ehx,
    input  wire                                     slvacceptn_async_ehx,
    input  wire                                     slvdeny_async_ehx,
    output wire                                     si_to_mi_wakeup_async_ehx,
    input  wire                                     mi_to_si_wakeup_async_ehx,
    output wire [EXT_SYSX_MEM_AW_FIFO_DEPTH-1:0]     aw_wr_ptr_async_ehx,
    input  wire [EXT_SYSX_MEM_AW_FIFO_DEPTH-1:0]     aw_rd_ptr_async_ehx,
    output wire [EXT_SYSX_MEM_AW_PAYLOAD_WIDTH-1:0]  aw_payld_async_ehx,
    output wire [EXT_SYSX_MEM_W_FIFO_DEPTH-1:0]      w_wr_ptr_async_ehx,
    input  wire [EXT_SYSX_MEM_W_FIFO_DEPTH-1:0]      w_rd_ptr_async_ehx,
    output wire [EXT_SYSX_MEM_W_PAYLOAD_WIDTH-1:0]   w_payld_async_ehx,
    input  wire [EXT_SYSX_MEM_B_FIFO_DEPTH-1:0]      b_wr_ptr_async_ehx,
    output wire [EXT_SYSX_MEM_B_FIFO_DEPTH-1:0]      b_rd_ptr_async_ehx,
    input  wire [EXT_SYSX_MEM_B_PAYLOAD_WIDTH-1:0]   b_payld_async_ehx,
    output wire [EXT_SYSX_MEM_AR_FIFO_DEPTH-1:0]     ar_wr_ptr_async_ehx,
    input  wire [EXT_SYSX_MEM_AR_FIFO_DEPTH-1:0]     ar_rd_ptr_async_ehx,
    output wire [EXT_SYSX_MEM_AR_PAYLOAD_WIDTH-1:0]  ar_payld_async_ehx,
    input  wire [EXT_SYSX_MEM_R_FIFO_DEPTH-1:0]      r_wr_ptr_async_ehx,
    output wire [EXT_SYSX_MEM_R_FIFO_DEPTH-1:0]      r_rd_ptr_async_ehx,
    input  wire [EXT_SYSX_MEM_R_PAYLOAD_WIDTH-1:0]   r_payld_async_ehx,

    input  wire           dftrstdisable
    );


   sse710_adb400_r3_axi4_slv_wrapper #(
    .ADDR_WIDTH             (EXT_SYSX_MEM_ADDR_WIDTH),
    .DATA_WIDTH             (EXT_SYSX_MEM_DATA_WIDTH),
    .AWID_WIDTH             (EXT_SYSX_MEM_AWID_WIDTH),
    .ARID_WIDTH             (EXT_SYSX_MEM_ARID_WIDTH),
    .AWUSER_WIDTH           (EXT_SYSX_MEM_AWUSER_WIDTH),
    .WUSER_WIDTH            (EXT_SYSX_MEM_WUSER_WIDTH),
    .BUSER_WIDTH            (EXT_SYSX_MEM_BUSER_WIDTH),
    .ARUSER_WIDTH           (EXT_SYSX_MEM_ARUSER_WIDTH),
    .RUSER_WIDTH            (EXT_SYSX_MEM_RUSER_WIDTH),
    .AW_FIFO_DEPTH          (EXT_SYSX_MEM_AW_FIFO_DEPTH),
    .W_FIFO_DEPTH           (EXT_SYSX_MEM_W_FIFO_DEPTH),
    .B_FIFO_DEPTH           (EXT_SYSX_MEM_B_FIFO_DEPTH),
    .AR_FIFO_DEPTH          (EXT_SYSX_MEM_AR_FIFO_DEPTH),
    .R_FIFO_DEPTH           (EXT_SYSX_MEM_R_FIFO_DEPTH),
    .B_OPREG                (1),
    .R_OPREG                (1),
    .SI_SYNC_LEVELS         (2),
    .AW_PAYLOAD_WIDTH       (EXT_SYSX_MEM_AW_PAYLOAD_WIDTH),
    .W_PAYLOAD_WIDTH        (EXT_SYSX_MEM_W_PAYLOAD_WIDTH),
    .B_PAYLOAD_WIDTH        (EXT_SYSX_MEM_B_PAYLOAD_WIDTH),
    .AR_PAYLOAD_WIDTH       (EXT_SYSX_MEM_AR_PAYLOAD_WIDTH),
    .R_PAYLOAD_WIDTH        (EXT_SYSX_MEM_R_PAYLOAD_WIDTH)
  ) u_sse710_adb400_r3_axi4_slv_wrapper (
    .pwrq_permit_deny_sar_i         (1'b1), 
    .aclks                          (extsysx_aclk),
    .aresetns                       (extsysx_aresetn),
    .pwrqreqns_i                    (qreqn_extsysx_mempwr),
    .pwrqacceptns_o                 (qacceptn_extsysx_mempwr),
    .pwrqdenys_o                    (qdeny_extsysx_mempwr),
    .clkqreqns_i                    (qreqn_extsysx_aclk),
    .clkqacceptns_o                 (qacceptn_extsysx_aclk),
    .clkqdenys_o                    (qdeny_extsysx_aclk),
    .clkqactives_o                  (qactive_extsysx_aclk),
    .pwrqactives_o                  (qactive_extsysx_mempwr),
    .wakeups_i                      (awakeup_extsysx_mem),
    .awvalids                       (awvalid_extsysx_mem),
    .awreadys                       (awready_extsysx_mem),
    .awusers                        (1'b0),
    .awids                          (awid_extsysx_mem),
    .awaddrs                        (awaddr_extsysx_mem),
    .awregions                      (awregion_extsysx_mem),
    .awlens                         (awlen_extsysx_mem),
    .awsizes                        (awsize_extsysx_mem),
    .awbursts                       (awburst_extsysx_mem),
    .awlocks                        (awlock_extsysx_mem),
    .awcaches                       (awcache_extsysx_mem),
    .awprots                        (awprot_extsysx_mem),
    .awqoss                         (4'h0),
    .wvalids                        (wvalid_extsysx_mem),
    .wreadys                        (wready_extsysx_mem),
    .wusers                         (1'b0),
    .wdatas                         (wdata_extsysx_mem),
    .wstrbs                         (wstrb_extsysx_mem),
    .wlasts                         (wlast_extsysx_mem),
    .bvalids                        (bvalid_extsysx_mem),
    .breadys                        (bready_extsysx_mem),
    .busers                         (),
    .bids                           (bid_extsysx_mem),
    .bresps                         (bresp_extsysx_mem),
    .arvalids                       (arvalid_extsysx_mem),
    .arreadys                       (arready_extsysx_mem),
    .arusers                        (1'b0),
    .arids                          (arid_extsysx_mem),
    .araddrs                        (araddr_extsysx_mem),
    .arregions                      (arregion_extsysx_mem),
    .arlens                         (arlen_extsysx_mem),
    .arsizes                        (arsize_extsysx_mem),
    .arbursts                       (arburst_extsysx_mem),
    .arlocks                        (arlock_extsysx_mem),
    .arcaches                       (arcache_extsysx_mem),
    .arprots                        (arprot_extsysx_mem),
    .arqoss                         (4'h0),
    .rvalids                        (rvalid_extsysx_mem),
    .rreadys                        (rready_extsysx_mem),
    .rusers                         (),
    .rids                           (rid_extsysx_mem),
    .rdatas                         (rdata_extsysx_mem),
    .rresps                         (rresp_extsysx_mem),
    .rlasts                         (rlast_extsysx_mem),
    .slvmustacceptreqn_async        (slvmustacceptreqn_async_ehx),
    .slvcandenyreqn_async           (slvcandenyreqn_async_ehx),
    .slvacceptn_async               (slvacceptn_async_ehx),
    .slvdeny_async                  (slvdeny_async_ehx),
    .si_to_mi_wakeup_async          (si_to_mi_wakeup_async_ehx),
    .mi_to_si_wakeup_async          (mi_to_si_wakeup_async_ehx),
    .aw_wr_ptr_async                (aw_wr_ptr_async_ehx),
    .aw_rd_ptr_async                (aw_rd_ptr_async_ehx),
    .aw_payld_async                 (aw_payld_async_ehx),
    .w_wr_ptr_async                 (w_wr_ptr_async_ehx),
    .w_rd_ptr_async                 (w_rd_ptr_async_ehx),
    .w_payld_async                  (w_payld_async_ehx),
    .b_wr_ptr_async                 (b_wr_ptr_async_ehx),
    .b_rd_ptr_async                 (b_rd_ptr_async_ehx),
    .b_payld_async                  (b_payld_async_ehx),
    .ar_wr_ptr_async                (ar_wr_ptr_async_ehx),
    .ar_rd_ptr_async                (ar_rd_ptr_async_ehx),
    .ar_payld_async                 (ar_payld_async_ehx),
    .r_wr_ptr_async                 (r_wr_ptr_async_ehx),
    .r_rd_ptr_async                 (r_rd_ptr_async_ehx),
    .r_payld_async                  (r_payld_async_ehx),
    .dftrstdisables                 (dftrstdisable)
    );

endmodule
