//------------------------------------------------------------------------------
// The confidential and proprietary information contained in this file may
// only be used by a person authorised under and to the extent permitted
// by a subsisting licensing agreement from Arm Limited or its affiliates.
//
//            (C) COPYRIGHT 2019-2021 Arm Limited or its affiliates.
//                ALL RIGHTS RESERVED
//
// This entire notice must be reproduced on all copies of this file
// and copies of this file may only be made by a person if such person is
// permitted to do so under the terms of a subsisting license agreement
// from Arm Limited or its affiliates.
//
//
//      Release Information : SSE710-r0p0-00eac0
//
//------------------------------------------------------------------------------
// Verilog-2001 (IEEE Std 1364-2001)
//------------------------------------------------------------------------------


module pd_secenc_f1_top #(

  parameter                  [15:0] SEC_ENC_ROM_SIZE   = 16'd32,  
  parameter                  [15:0] SEC_ENC_RAM_SIZE   = 16'd128, 

  parameter                         MHU_HSE0_NUM_CH    = 7'd1,        
  parameter                         MHU_SEH0_NUM_CH    = 7'd1,        
  parameter                         MHU_HSE1_NUM_CH    = 7'd1,        
  parameter                         MHU_SEH1_NUM_CH    = 7'd1,        
                                                                   

  parameter                         MHU_SEES00_NUM_CH         = 7'd1,     
  parameter                         MHU_ES0SE0_NUM_CH         = 7'd1,     
    parameter                         MHU_SEES01_NUM_CH         = 7'd1,     
  parameter                         MHU_ES0SE1_NUM_CH         = 7'd1,     
  
  
  parameter                         MHU_SEES10_NUM_CH         = 7'd1,     
  parameter                         MHU_ES1SE0_NUM_CH         = 7'd1,     
    parameter                         MHU_SEES11_NUM_CH         = 7'd1,     
  parameter                         MHU_ES1SE1_NUM_CH         = 7'd1,     
  
  
  parameter                         AW_FIFO_DEPTH      = 2,        
  parameter                         W_FIFO_DEPTH       = 2,        
  parameter                         B_FIFO_DEPTH       = 2,        
  parameter                         AR_FIFO_DEPTH      = 2,        
  parameter                         R_FIFO_DEPTH       = 2,        
  parameter                         AW_PAYLOAD_WIDTH   = 148,      
  parameter                         W_PAYLOAD_WIDTH    = 74,       
  parameter                         B_PAYLOAD_WIDTH    = 32,       
  parameter                         AR_PAYLOAD_WIDTH   = 148,      
  parameter                         R_PAYLOAD_WIDTH    = 98,       
  
  parameter                         CAAON2CA_WIDTH     = 34,       
  parameter                         CA2CAAON_WIDTH     = 49,       
  
  parameter                         AHB_SYNC_BRIDGE    = 1         
  
  
) (
  input  wire                       SECENCCLK,
  input  wire                       SECENCDIVCLK,
  input  wire                       SECENCHINTCLK,
  input  wire                       S32KCLK_SECENC,
  input  wire                       SECENCPORESETn,
  input  wire                       SECENCWARMRESETn,
  input  wire                       SECENCCPUWAIT,

  output wire                       M0_HALTED,
  input  wire                       CDBGPWRUPREQ0,
  input  wire                       CLKFORCE,
  input  wire [7:0]                 ENTRY_DELAY,
  

  input  wire                       DEBUG_APB_ASYNC_REQ,
  input  wire                [48:0] DEBUG_APB_ASYNC_REQ_PAYLOAD,
  output wire                [32:0] DEBUG_APB_ASYNC_RESP_PAYLOAD,
  output wire                       DEBUG_APB_ASYNC_ACK,
  
  input  wire                       DP_ABORT_PULSE_REQ,
  output wire                       DP_ABORT_PULSE_ACK,

  input  wire [3:0]                 CTI_CHA_TO_SECENC_PULSE_REQ,
  output wire [3:0]                 CTI_CHA_TO_SECENC_PULSE_ACK,
  input  wire [3:0]                 CTI_SECENC_TO_CHA_PULSE_ACK,
  output wire [3:0]                 CTI_SECENC_TO_CHA_PULSE_REQ,

  output wire                       SLVMUSTACCEPTREQN_ASYNC,
  output wire                       SLVCANDENYREQN_ASYNC,
  input  wire                       SLVACCEPTN_ASYNC,
  input  wire                       SLVDENY_ASYNC,
  output wire                       SI_TO_MI_WAKEUP_ASYNC,
  input  wire                       MI_TO_SI_WAKEUP_ASYNC,

  output wire                 [AW_FIFO_DEPTH-1:0]    AW_WR_PTR_ASYNC,
  input  wire                 [AW_FIFO_DEPTH-1:0]    AW_RD_PTR_ASYNC,
  output wire                 [AW_PAYLOAD_WIDTH-1:0] AW_PAYLD_ASYNC,
  output wire                 [W_FIFO_DEPTH-1:0]     W_WR_PTR_ASYNC,
  input  wire                 [W_FIFO_DEPTH-1:0]     W_RD_PTR_ASYNC,
  output wire                 [W_PAYLOAD_WIDTH-1:0]  W_PAYLD_ASYNC,
  input  wire                 [B_FIFO_DEPTH-1:0]     B_WR_PTR_ASYNC,
  output wire                 [B_FIFO_DEPTH-1:0]     B_RD_PTR_ASYNC,
  input  wire                 [B_PAYLOAD_WIDTH-1:0]  B_PAYLD_ASYNC,
  output wire                 [AR_FIFO_DEPTH-1:0]    AR_WR_PTR_ASYNC,
  input  wire                 [AR_FIFO_DEPTH-1:0]    AR_RD_PTR_ASYNC,
  output wire                 [AR_PAYLOAD_WIDTH-1:0] AR_PAYLD_ASYNC,
  input  wire                 [R_FIFO_DEPTH-1:0]     R_WR_PTR_ASYNC,
  output wire                 [R_FIFO_DEPTH-1:0]     R_RD_PTR_ASYNC,
  input  wire                 [R_PAYLOAD_WIDTH-1:0]  R_PAYLD_ASYNC,

  input  wire                       MHU_HSE0_APB_ASYNC_REQ,
  input  wire                [48:0] MHU_HSE0_APB_ASYNC_REQ_PAYLOAD,
  output wire                [32:0] MHU_HSE0_APB_ASYNC_RESP_PAYLOAD,
  output wire                       MHU_HSE0_APB_ASYNC_ACK,
  output wire [MHU_HSE0_NUM_CH-1:0] MHU_HSE0_EDGE_ASYNC_REQ,
  input  wire [MHU_HSE0_NUM_CH-1:0] MHU_HSE0_EDGE_ASYNC_ACK,
  output wire                       MHU_HSE0_RECAWAKE_ASYNC,
  input  wire                       MHU_HSE0_RECWAKEUP_ASYNC,

  output wire                       MHU_SEH0_APB_ASYNC_REQ,
  output wire                [48:0] MHU_SEH0_APB_ASYNC_REQ_PAYLOAD,
  input  wire                [32:0] MHU_SEH0_APB_ASYNC_RESP_PAYLOAD,
  input  wire                       MHU_SEH0_APB_ASYNC_ACK,
  input  wire [MHU_SEH0_NUM_CH-1:0] MHU_SEH0_EDGE_ASYNC_REQ,
  output wire [MHU_SEH0_NUM_CH-1:0] MHU_SEH0_EDGE_ASYNC_ACK,
  input  wire                       MHU_SEH0_RECAWAKE_ASYNC,
  output wire                       MHU_SEH0_RECWAKEUP_ASYNC,

  input  wire                       MHU_HSE1_APB_ASYNC_REQ,
  input  wire                [48:0] MHU_HSE1_APB_ASYNC_REQ_PAYLOAD,
  output wire                [32:0] MHU_HSE1_APB_ASYNC_RESP_PAYLOAD,
  output wire                       MHU_HSE1_APB_ASYNC_ACK,
  output wire [MHU_HSE1_NUM_CH-1:0] MHU_HSE1_EDGE_ASYNC_REQ,
  input  wire [MHU_HSE1_NUM_CH-1:0] MHU_HSE1_EDGE_ASYNC_ACK,
  output wire                       MHU_HSE1_RECAWAKE_ASYNC,
  input  wire                       MHU_HSE1_RECWAKEUP_ASYNC,

  output wire                       MHU_SEH1_APB_ASYNC_REQ,
  output wire                [48:0] MHU_SEH1_APB_ASYNC_REQ_PAYLOAD,
  input  wire                [32:0] MHU_SEH1_APB_ASYNC_RESP_PAYLOAD,
  input  wire                       MHU_SEH1_APB_ASYNC_ACK,
  input  wire [MHU_SEH1_NUM_CH-1:0] MHU_SEH1_EDGE_ASYNC_REQ,
  output wire [MHU_SEH1_NUM_CH-1:0] MHU_SEH1_EDGE_ASYNC_ACK,
  input  wire                       MHU_SEH1_RECAWAKE_ASYNC,
  output wire                       MHU_SEH1_RECWAKEUP_ASYNC,


  input  wire                                       MHU_ES0SE0_APB_ASYNC_REQ,
  input  wire                                [48:0] MHU_ES0SE0_APB_ASYNC_REQ_PAYLOAD,
  output wire                                [32:0] MHU_ES0SE0_APB_ASYNC_RESP_PAYLOAD,
  output wire                                       MHU_ES0SE0_APB_ASYNC_ACK,
  output wire [MHU_ES0SE0_NUM_CH-1:0] MHU_ES0SE0_EDGE_ASYNC_REQ,
  input  wire [MHU_ES0SE0_NUM_CH-1:0] MHU_ES0SE0_EDGE_ASYNC_ACK,
  output wire                                       MHU_ES0SE0_RECAWAKE_ASYNC,
  input  wire                                       MHU_ES0SE0_RECWAKEUP_ASYNC,

  output wire                                       MHU_SEES00_APB_ASYNC_REQ,
  output wire                                [48:0] MHU_SEES00_APB_ASYNC_REQ_PAYLOAD,
  input  wire                                [32:0] MHU_SEES00_APB_ASYNC_RESP_PAYLOAD,
  input  wire                                       MHU_SEES00_APB_ASYNC_ACK,
  input  wire [MHU_SEES00_NUM_CH-1:0] MHU_SEES00_EDGE_ASYNC_REQ,
  output wire [MHU_SEES00_NUM_CH-1:0] MHU_SEES00_EDGE_ASYNC_ACK,
  input  wire                                       MHU_SEES00_RECAWAKE_ASYNC,
  output wire                                       MHU_SEES00_RECWAKEUP_ASYNC,
  
    
  input  wire                                       MHU_ES0SE1_APB_ASYNC_REQ,
  input  wire                              [48:0]   MHU_ES0SE1_APB_ASYNC_REQ_PAYLOAD,
  output wire                              [32:0]   MHU_ES0SE1_APB_ASYNC_RESP_PAYLOAD,
  output wire                                       MHU_ES0SE1_APB_ASYNC_ACK,
  output wire [MHU_ES0SE1_NUM_CH-1:0] MHU_ES0SE1_EDGE_ASYNC_REQ,
  input  wire [MHU_ES0SE1_NUM_CH-1:0] MHU_ES0SE1_EDGE_ASYNC_ACK,
  output wire                                       MHU_ES0SE1_RECAWAKE_ASYNC,
  input  wire                                       MHU_ES0SE1_RECWAKEUP_ASYNC,

  output wire                                       MHU_SEES01_APB_ASYNC_REQ,
  output wire                [48:0]                 MHU_SEES01_APB_ASYNC_REQ_PAYLOAD,
  input  wire                [32:0]                 MHU_SEES01_APB_ASYNC_RESP_PAYLOAD,
  input  wire                                       MHU_SEES01_APB_ASYNC_ACK,
  input  wire [MHU_SEES01_NUM_CH-1:0] MHU_SEES01_EDGE_ASYNC_REQ,
  output wire [MHU_SEES01_NUM_CH-1:0] MHU_SEES01_EDGE_ASYNC_ACK,
  input  wire                                       MHU_SEES01_RECAWAKE_ASYNC,
  output wire                                       MHU_SEES01_RECWAKEUP_ASYNC,

  
  input  wire                                       MHU_ES1SE0_APB_ASYNC_REQ,
  input  wire                                [48:0] MHU_ES1SE0_APB_ASYNC_REQ_PAYLOAD,
  output wire                                [32:0] MHU_ES1SE0_APB_ASYNC_RESP_PAYLOAD,
  output wire                                       MHU_ES1SE0_APB_ASYNC_ACK,
  output wire [MHU_ES1SE0_NUM_CH-1:0] MHU_ES1SE0_EDGE_ASYNC_REQ,
  input  wire [MHU_ES1SE0_NUM_CH-1:0] MHU_ES1SE0_EDGE_ASYNC_ACK,
  output wire                                       MHU_ES1SE0_RECAWAKE_ASYNC,
  input  wire                                       MHU_ES1SE0_RECWAKEUP_ASYNC,

  output wire                                       MHU_SEES10_APB_ASYNC_REQ,
  output wire                                [48:0] MHU_SEES10_APB_ASYNC_REQ_PAYLOAD,
  input  wire                                [32:0] MHU_SEES10_APB_ASYNC_RESP_PAYLOAD,
  input  wire                                       MHU_SEES10_APB_ASYNC_ACK,
  input  wire [MHU_SEES10_NUM_CH-1:0] MHU_SEES10_EDGE_ASYNC_REQ,
  output wire [MHU_SEES10_NUM_CH-1:0] MHU_SEES10_EDGE_ASYNC_ACK,
  input  wire                                       MHU_SEES10_RECAWAKE_ASYNC,
  output wire                                       MHU_SEES10_RECWAKEUP_ASYNC,
  
    
  input  wire                                       MHU_ES1SE1_APB_ASYNC_REQ,
  input  wire                              [48:0]   MHU_ES1SE1_APB_ASYNC_REQ_PAYLOAD,
  output wire                              [32:0]   MHU_ES1SE1_APB_ASYNC_RESP_PAYLOAD,
  output wire                                       MHU_ES1SE1_APB_ASYNC_ACK,
  output wire [MHU_ES1SE1_NUM_CH-1:0] MHU_ES1SE1_EDGE_ASYNC_REQ,
  input  wire [MHU_ES1SE1_NUM_CH-1:0] MHU_ES1SE1_EDGE_ASYNC_ACK,
  output wire                                       MHU_ES1SE1_RECAWAKE_ASYNC,
  input  wire                                       MHU_ES1SE1_RECWAKEUP_ASYNC,

  output wire                                       MHU_SEES11_APB_ASYNC_REQ,
  output wire                [48:0]                 MHU_SEES11_APB_ASYNC_REQ_PAYLOAD,
  input  wire                [32:0]                 MHU_SEES11_APB_ASYNC_RESP_PAYLOAD,
  input  wire                                       MHU_SEES11_APB_ASYNC_ACK,
  input  wire [MHU_SEES11_NUM_CH-1:0] MHU_SEES11_EDGE_ASYNC_REQ,
  output wire [MHU_SEES11_NUM_CH-1:0] MHU_SEES11_EDGE_ASYNC_ACK,
  input  wire                                       MHU_SEES11_RECAWAKE_ASYNC,
  output wire                                       MHU_SEES11_RECWAKEUP_ASYNC,

    
  
  input  wire                       SOC_WD_IRQ,
  input  wire                       UART_IRQ,
  input  wire                       PPU_IRQ,
  input  wire                       CO_IRQ,
  input  wire                       HOST_FWT_IRQ, 
  input  wire                       INT_RTT_IRQ,  
  input  wire                       SWD_WS1_IRQ,  
  output wire                       MHU2R_CIRQ,
  output wire                       MHU2S_CIRQ,
    output wire                       MHU3R_CIRQ,
  output wire                       MHU3S_CIRQ,
    output wire                       MHU4R_CIRQ,
  output wire                       MHU4S_CIRQ,
    output wire                       MHU5R_CIRQ,
  output wire                       MHU5S_CIRQ,
    
  output wire                       AON_APB_ASYNC_REQ,
  output wire                [55:0] AON_APB_ASYNC_REQ_PAYLOAD,
  input  wire                [32:0] AON_APB_ASYNC_RESP_PAYLOAD,
  input  wire                       AON_APB_ASYNC_ACK,
  
  output wire                       SOCWD_APB_ASYNC_REQ,
  output wire                [47:0] SOCWD_APB_ASYNC_REQ_PAYLOAD,
  input  wire                [32:0] SOCWD_APB_ASYNC_RESP_PAYLOAD,
  input  wire                       SOCWD_APB_ASYNC_ACK,
  
  input  wire                       MHU0_QREQn,
  output wire                       MHU0_QACCEPTn,
  output wire                       MHU0_QDENY,
  input  wire                       MHU1_QREQn,
  output wire                       MHU1_QACCEPTn,
  output wire                       MHU1_QDENY,
  
  input  wire                       MHU2_QREQn,
  output wire                       MHU2_QACCEPTn,
  output wire                       MHU2_QDENY,
    input  wire                       MHU3_QREQn,
  output wire                       MHU3_QACCEPTn,
  output wire                       MHU3_QDENY,
    
  input  wire                       MHU4_QREQn,
  output wire                       MHU4_QACCEPTn,
  output wire                       MHU4_QDENY,
    input  wire                       MHU5_QREQn,
  output wire                       MHU5_QACCEPTn,
  output wire                       MHU5_QDENY,
    input  wire                       CTI_QREQn,
  output wire                       CTI_QACCEPTn,
  output wire                       CTI_QDENY,
  output wire                       CTI_QACTIVE, 
  input  wire                       CM0_QREQn,
  output wire                       CM0_QACCEPTn,
  output wire                       CM0_QDENY,
  output wire                       CM0_QACTIVE,
  input  wire                       AXIB_QREQn,
  output wire                       AXIB_QACCEPTn,
  output wire                       AXIB_QDENY,
  output wire                       AXIB_QACTIVE,
  
  input  wire                       SOCWD_ADB_QREQn,
  output wire                       SOCWD_ADB_QACCEPTn,
  output wire                       SOCWD_ADB_QDENY,
  output wire                       SOCWD_ADB_QACTIVE,

  input  wire                       AON_ADB_QREQn,
  output wire                       AON_ADB_QACCEPTn,
  output wire                       AON_ADB_QDENY,
  output wire                       AON_ADB_QACTIVE,

  output wire                       WDOG_RST_REQ, 
  output wire                       SW_RST_REQ,   

  input  wire                       DBGEN,
  input  wire                       NIDEN,
  input  wire                       CHEN,
  input  wire                       FIREWALL_BYPASS,
  
  input  wire  [CAAON2CA_WIDTH-1:0] CAAON2CA,
  output wire  [CA2CAAON_WIDTH-1:0] CA2CAAON,   
  
  output wire                       CAE,
  input  wire                       CA_ERR_MSK,
  

  
  input  wire                 [1:0] DFTRSTDISABLE,
  input  wire                       DFTRAMHOLD,
  input  wire                       DFTCGEN,
  input  wire                       DFTMCPHOLD,
  input  wire                       MBISTREQ,
  input  wire                       DFTSE,
  input  wire                       DFTTESTMODE
);

  secenc_f1_sepd #(
    .SEC_ENC_ROM_SIZE                    (SEC_ENC_ROM_SIZE),
    .SEC_ENC_RAM_SIZE                    (SEC_ENC_RAM_SIZE),
    .MHU_HSE0_NUM_CH                     (MHU_HSE0_NUM_CH),
    .MHU_SEH0_NUM_CH                     (MHU_SEH0_NUM_CH),
    .MHU_HSE1_NUM_CH                     (MHU_HSE1_NUM_CH),
    .MHU_SEH1_NUM_CH                     (MHU_SEH1_NUM_CH),
    .MHU_SEES00_NUM_CH  (MHU_SEES00_NUM_CH),
    .MHU_ES0SE0_NUM_CH  (MHU_ES0SE0_NUM_CH),
      .MHU_SEES01_NUM_CH  (MHU_SEES01_NUM_CH),
    .MHU_ES0SE1_NUM_CH  (MHU_ES0SE1_NUM_CH),
      .MHU_SEES10_NUM_CH  (MHU_SEES10_NUM_CH),
    .MHU_ES1SE0_NUM_CH  (MHU_ES1SE0_NUM_CH),
      .MHU_SEES11_NUM_CH  (MHU_SEES11_NUM_CH),
    .MHU_ES1SE1_NUM_CH  (MHU_ES1SE1_NUM_CH),
      .AW_FIFO_DEPTH                       (AW_FIFO_DEPTH),  
    .W_FIFO_DEPTH                        (W_FIFO_DEPTH),    
    .B_FIFO_DEPTH                        (B_FIFO_DEPTH),    
    .AR_FIFO_DEPTH                       (AR_FIFO_DEPTH),   
    .R_FIFO_DEPTH                        (R_FIFO_DEPTH),    
    .AW_PAYLOAD_WIDTH                    (AW_PAYLOAD_WIDTH),
    .W_PAYLOAD_WIDTH                     (W_PAYLOAD_WIDTH), 
    .B_PAYLOAD_WIDTH                     (B_PAYLOAD_WIDTH), 
    .AR_PAYLOAD_WIDTH                    (AR_PAYLOAD_WIDTH),
    .R_PAYLOAD_WIDTH                     (R_PAYLOAD_WIDTH),
    .CAAON2CA_WIDTH                      (CAAON2CA_WIDTH),
    .CA2CAAON_WIDTH                      (CA2CAAON_WIDTH),
    .AHB_SYNC_BRIDGE                     (AHB_SYNC_BRIDGE)
  ) u_secenc_f1_sepd (
    .SECENCCLK                           (SECENCCLK),
    .SECENCDIVCLK                        (SECENCDIVCLK),
    .SECENCHINTCLK                       (SECENCHINTCLK),
    .S32KCLK_SECENC                      (S32KCLK_SECENC),
    .SECENCPORESETn                      (SECENCPORESETn),
    .SECENCWARMRESETn                    (SECENCWARMRESETn),
    .SECENCCPUWAIT                       (SECENCCPUWAIT),
    .M0_HALTED                           (M0_HALTED),
    .CDBGPWRUPREQ0                       (CDBGPWRUPREQ0),
    .CLKFORCE                            (CLKFORCE),
    .ENTRY_DELAY                         (ENTRY_DELAY),
    .DEBUG_APB_ASYNC_REQ                 (DEBUG_APB_ASYNC_REQ),
    .DEBUG_APB_ASYNC_REQ_PAYLOAD         (DEBUG_APB_ASYNC_REQ_PAYLOAD),
    .DEBUG_APB_ASYNC_RESP_PAYLOAD        (DEBUG_APB_ASYNC_RESP_PAYLOAD),
    .DEBUG_APB_ASYNC_ACK                 (DEBUG_APB_ASYNC_ACK),
    .DP_ABORT_PULSE_REQ                  (DP_ABORT_PULSE_REQ),
    .DP_ABORT_PULSE_ACK                  (DP_ABORT_PULSE_ACK),
    .CTI_CHA_TO_SECENC_PULSE_REQ         (CTI_CHA_TO_SECENC_PULSE_REQ),
    .CTI_CHA_TO_SECENC_PULSE_ACK         (CTI_CHA_TO_SECENC_PULSE_ACK),
    .CTI_SECENC_TO_CHA_PULSE_ACK         (CTI_SECENC_TO_CHA_PULSE_ACK),
    .CTI_SECENC_TO_CHA_PULSE_REQ         (CTI_SECENC_TO_CHA_PULSE_REQ),    
    .SLVMUSTACCEPTREQN_ASYNC             (SLVMUSTACCEPTREQN_ASYNC),
    .SLVCANDENYREQN_ASYNC                (SLVCANDENYREQN_ASYNC),
    .SLVACCEPTN_ASYNC                    (SLVACCEPTN_ASYNC),
    .SLVDENY_ASYNC                       (SLVDENY_ASYNC),
    .SI_TO_MI_WAKEUP_ASYNC               (SI_TO_MI_WAKEUP_ASYNC),
    .MI_TO_SI_WAKEUP_ASYNC               (MI_TO_SI_WAKEUP_ASYNC),
    .AW_WR_PTR_ASYNC                     (AW_WR_PTR_ASYNC),
    .AW_RD_PTR_ASYNC                     (AW_RD_PTR_ASYNC),
    .AW_PAYLD_ASYNC                      (AW_PAYLD_ASYNC),
    .W_WR_PTR_ASYNC                      (W_WR_PTR_ASYNC),
    .W_RD_PTR_ASYNC                      (W_RD_PTR_ASYNC),
    .W_PAYLD_ASYNC                       (W_PAYLD_ASYNC),
    .B_WR_PTR_ASYNC                      (B_WR_PTR_ASYNC),
    .B_RD_PTR_ASYNC                      (B_RD_PTR_ASYNC),
    .B_PAYLD_ASYNC                       (B_PAYLD_ASYNC),
    .AR_WR_PTR_ASYNC                     (AR_WR_PTR_ASYNC),
    .AR_RD_PTR_ASYNC                     (AR_RD_PTR_ASYNC),
    .AR_PAYLD_ASYNC                      (AR_PAYLD_ASYNC),
    .R_WR_PTR_ASYNC                      (R_WR_PTR_ASYNC),
    .R_RD_PTR_ASYNC                      (R_RD_PTR_ASYNC),
    .R_PAYLD_ASYNC                       (R_PAYLD_ASYNC),
    .MHU_HSE0_APB_ASYNC_REQ              (MHU_HSE0_APB_ASYNC_REQ),
    .MHU_HSE0_APB_ASYNC_REQ_PAYLOAD      (MHU_HSE0_APB_ASYNC_REQ_PAYLOAD),
    .MHU_HSE0_APB_ASYNC_RESP_PAYLOAD     (MHU_HSE0_APB_ASYNC_RESP_PAYLOAD),
    .MHU_HSE0_APB_ASYNC_ACK              (MHU_HSE0_APB_ASYNC_ACK),
    .MHU_HSE0_RECAWAKE_ASYNC             (MHU_HSE0_RECAWAKE_ASYNC),
    .MHU_HSE0_RECWAKEUP_ASYNC            (MHU_HSE0_RECWAKEUP_ASYNC),
    .MHU_HSE0_EDGE_ASYNC_REQ             (MHU_HSE0_EDGE_ASYNC_REQ),
    .MHU_HSE0_EDGE_ASYNC_ACK             (MHU_HSE0_EDGE_ASYNC_ACK),
    .MHU_SEH0_APB_ASYNC_REQ              (MHU_SEH0_APB_ASYNC_REQ),
    .MHU_SEH0_APB_ASYNC_REQ_PAYLOAD      (MHU_SEH0_APB_ASYNC_REQ_PAYLOAD),
    .MHU_SEH0_APB_ASYNC_RESP_PAYLOAD     (MHU_SEH0_APB_ASYNC_RESP_PAYLOAD),
    .MHU_SEH0_APB_ASYNC_ACK              (MHU_SEH0_APB_ASYNC_ACK),
    .MHU_SEH0_RECAWAKE_ASYNC             (MHU_SEH0_RECAWAKE_ASYNC),
    .MHU_SEH0_RECWAKEUP_ASYNC            (MHU_SEH0_RECWAKEUP_ASYNC),
    .MHU_SEH0_EDGE_ASYNC_REQ             (MHU_SEH0_EDGE_ASYNC_REQ),
    .MHU_SEH0_EDGE_ASYNC_ACK             (MHU_SEH0_EDGE_ASYNC_ACK),
    .MHU_HSE1_APB_ASYNC_REQ              (MHU_HSE1_APB_ASYNC_REQ),
    .MHU_HSE1_APB_ASYNC_REQ_PAYLOAD      (MHU_HSE1_APB_ASYNC_REQ_PAYLOAD),
    .MHU_HSE1_APB_ASYNC_RESP_PAYLOAD     (MHU_HSE1_APB_ASYNC_RESP_PAYLOAD),
    .MHU_HSE1_APB_ASYNC_ACK              (MHU_HSE1_APB_ASYNC_ACK),
    .MHU_HSE1_RECAWAKE_ASYNC             (MHU_HSE1_RECAWAKE_ASYNC),
    .MHU_HSE1_RECWAKEUP_ASYNC            (MHU_HSE1_RECWAKEUP_ASYNC),
    .MHU_HSE1_EDGE_ASYNC_REQ             (MHU_HSE1_EDGE_ASYNC_REQ),
    .MHU_HSE1_EDGE_ASYNC_ACK             (MHU_HSE1_EDGE_ASYNC_ACK),
    .MHU_SEH1_APB_ASYNC_REQ              (MHU_SEH1_APB_ASYNC_REQ),
    .MHU_SEH1_APB_ASYNC_REQ_PAYLOAD      (MHU_SEH1_APB_ASYNC_REQ_PAYLOAD),
    .MHU_SEH1_APB_ASYNC_RESP_PAYLOAD     (MHU_SEH1_APB_ASYNC_RESP_PAYLOAD),
    .MHU_SEH1_APB_ASYNC_ACK              (MHU_SEH1_APB_ASYNC_ACK),
    .MHU_SEH1_RECAWAKE_ASYNC             (MHU_SEH1_RECAWAKE_ASYNC),
    .MHU_SEH1_RECWAKEUP_ASYNC            (MHU_SEH1_RECWAKEUP_ASYNC),
    .MHU_SEH1_EDGE_ASYNC_REQ             (MHU_SEH1_EDGE_ASYNC_REQ),
    .MHU_SEH1_EDGE_ASYNC_ACK             (MHU_SEH1_EDGE_ASYNC_ACK),
    .MHU_ES0SE0_APB_ASYNC_REQ            (MHU_ES0SE0_APB_ASYNC_REQ),
    .MHU_ES0SE0_APB_ASYNC_REQ_PAYLOAD    (MHU_ES0SE0_APB_ASYNC_REQ_PAYLOAD),
    .MHU_ES0SE0_APB_ASYNC_RESP_PAYLOAD   (MHU_ES0SE0_APB_ASYNC_RESP_PAYLOAD),
    .MHU_ES0SE0_APB_ASYNC_ACK            (MHU_ES0SE0_APB_ASYNC_ACK),
    .MHU_ES0SE0_RECAWAKE_ASYNC           (MHU_ES0SE0_RECAWAKE_ASYNC),
    .MHU_ES0SE0_RECWAKEUP_ASYNC          (MHU_ES0SE0_RECWAKEUP_ASYNC),
    .MHU_ES0SE0_EDGE_ASYNC_REQ           (MHU_ES0SE0_EDGE_ASYNC_REQ),
    .MHU_ES0SE0_EDGE_ASYNC_ACK           (MHU_ES0SE0_EDGE_ASYNC_ACK),
    .MHU_SEES00_APB_ASYNC_REQ            (MHU_SEES00_APB_ASYNC_REQ),
    .MHU_SEES00_APB_ASYNC_REQ_PAYLOAD    (MHU_SEES00_APB_ASYNC_REQ_PAYLOAD),
    .MHU_SEES00_APB_ASYNC_RESP_PAYLOAD   (MHU_SEES00_APB_ASYNC_RESP_PAYLOAD),
    .MHU_SEES00_APB_ASYNC_ACK            (MHU_SEES00_APB_ASYNC_ACK),
    .MHU_SEES00_RECAWAKE_ASYNC           (MHU_SEES00_RECAWAKE_ASYNC),
    .MHU_SEES00_RECWAKEUP_ASYNC          (MHU_SEES00_RECWAKEUP_ASYNC),
    .MHU_SEES00_EDGE_ASYNC_REQ           (MHU_SEES00_EDGE_ASYNC_REQ),
    .MHU_SEES00_EDGE_ASYNC_ACK           (MHU_SEES00_EDGE_ASYNC_ACK),
      .MHU_ES0SE1_APB_ASYNC_REQ            (MHU_ES0SE1_APB_ASYNC_REQ),
    .MHU_ES0SE1_APB_ASYNC_REQ_PAYLOAD    (MHU_ES0SE1_APB_ASYNC_REQ_PAYLOAD),
    .MHU_ES0SE1_APB_ASYNC_RESP_PAYLOAD   (MHU_ES0SE1_APB_ASYNC_RESP_PAYLOAD),
    .MHU_ES0SE1_APB_ASYNC_ACK            (MHU_ES0SE1_APB_ASYNC_ACK),
    .MHU_ES0SE1_RECAWAKE_ASYNC           (MHU_ES0SE1_RECAWAKE_ASYNC),
    .MHU_ES0SE1_RECWAKEUP_ASYNC          (MHU_ES0SE1_RECWAKEUP_ASYNC),
    .MHU_ES0SE1_EDGE_ASYNC_REQ           (MHU_ES0SE1_EDGE_ASYNC_REQ),
    .MHU_ES0SE1_EDGE_ASYNC_ACK           (MHU_ES0SE1_EDGE_ASYNC_ACK),
    .MHU_SEES01_APB_ASYNC_REQ            (MHU_SEES01_APB_ASYNC_REQ),
    .MHU_SEES01_APB_ASYNC_REQ_PAYLOAD    (MHU_SEES01_APB_ASYNC_REQ_PAYLOAD),
    .MHU_SEES01_APB_ASYNC_RESP_PAYLOAD   (MHU_SEES01_APB_ASYNC_RESP_PAYLOAD),
    .MHU_SEES01_APB_ASYNC_ACK            (MHU_SEES01_APB_ASYNC_ACK),
    .MHU_SEES01_RECAWAKE_ASYNC           (MHU_SEES01_RECAWAKE_ASYNC),
    .MHU_SEES01_RECWAKEUP_ASYNC          (MHU_SEES01_RECWAKEUP_ASYNC),
    .MHU_SEES01_EDGE_ASYNC_REQ           (MHU_SEES01_EDGE_ASYNC_REQ),
    .MHU_SEES01_EDGE_ASYNC_ACK           (MHU_SEES01_EDGE_ASYNC_ACK),
      .MHU_ES1SE0_APB_ASYNC_REQ            (MHU_ES1SE0_APB_ASYNC_REQ),
    .MHU_ES1SE0_APB_ASYNC_REQ_PAYLOAD    (MHU_ES1SE0_APB_ASYNC_REQ_PAYLOAD),
    .MHU_ES1SE0_APB_ASYNC_RESP_PAYLOAD   (MHU_ES1SE0_APB_ASYNC_RESP_PAYLOAD),
    .MHU_ES1SE0_APB_ASYNC_ACK            (MHU_ES1SE0_APB_ASYNC_ACK),
    .MHU_ES1SE0_RECAWAKE_ASYNC           (MHU_ES1SE0_RECAWAKE_ASYNC),
    .MHU_ES1SE0_RECWAKEUP_ASYNC          (MHU_ES1SE0_RECWAKEUP_ASYNC),
    .MHU_ES1SE0_EDGE_ASYNC_REQ           (MHU_ES1SE0_EDGE_ASYNC_REQ),
    .MHU_ES1SE0_EDGE_ASYNC_ACK           (MHU_ES1SE0_EDGE_ASYNC_ACK),
    .MHU_SEES10_APB_ASYNC_REQ            (MHU_SEES10_APB_ASYNC_REQ),
    .MHU_SEES10_APB_ASYNC_REQ_PAYLOAD    (MHU_SEES10_APB_ASYNC_REQ_PAYLOAD),
    .MHU_SEES10_APB_ASYNC_RESP_PAYLOAD   (MHU_SEES10_APB_ASYNC_RESP_PAYLOAD),
    .MHU_SEES10_APB_ASYNC_ACK            (MHU_SEES10_APB_ASYNC_ACK),
    .MHU_SEES10_RECAWAKE_ASYNC           (MHU_SEES10_RECAWAKE_ASYNC),
    .MHU_SEES10_RECWAKEUP_ASYNC          (MHU_SEES10_RECWAKEUP_ASYNC),
    .MHU_SEES10_EDGE_ASYNC_REQ           (MHU_SEES10_EDGE_ASYNC_REQ),
    .MHU_SEES10_EDGE_ASYNC_ACK           (MHU_SEES10_EDGE_ASYNC_ACK),
      .MHU_ES1SE1_APB_ASYNC_REQ            (MHU_ES1SE1_APB_ASYNC_REQ),
    .MHU_ES1SE1_APB_ASYNC_REQ_PAYLOAD    (MHU_ES1SE1_APB_ASYNC_REQ_PAYLOAD),
    .MHU_ES1SE1_APB_ASYNC_RESP_PAYLOAD   (MHU_ES1SE1_APB_ASYNC_RESP_PAYLOAD),
    .MHU_ES1SE1_APB_ASYNC_ACK            (MHU_ES1SE1_APB_ASYNC_ACK),
    .MHU_ES1SE1_RECAWAKE_ASYNC           (MHU_ES1SE1_RECAWAKE_ASYNC),
    .MHU_ES1SE1_RECWAKEUP_ASYNC          (MHU_ES1SE1_RECWAKEUP_ASYNC),
    .MHU_ES1SE1_EDGE_ASYNC_REQ           (MHU_ES1SE1_EDGE_ASYNC_REQ),
    .MHU_ES1SE1_EDGE_ASYNC_ACK           (MHU_ES1SE1_EDGE_ASYNC_ACK),
    .MHU_SEES11_APB_ASYNC_REQ            (MHU_SEES11_APB_ASYNC_REQ),
    .MHU_SEES11_APB_ASYNC_REQ_PAYLOAD    (MHU_SEES11_APB_ASYNC_REQ_PAYLOAD),
    .MHU_SEES11_APB_ASYNC_RESP_PAYLOAD   (MHU_SEES11_APB_ASYNC_RESP_PAYLOAD),
    .MHU_SEES11_APB_ASYNC_ACK            (MHU_SEES11_APB_ASYNC_ACK),
    .MHU_SEES11_RECAWAKE_ASYNC           (MHU_SEES11_RECAWAKE_ASYNC),
    .MHU_SEES11_RECWAKEUP_ASYNC          (MHU_SEES11_RECWAKEUP_ASYNC),
    .MHU_SEES11_EDGE_ASYNC_REQ           (MHU_SEES11_EDGE_ASYNC_REQ),
    .MHU_SEES11_EDGE_ASYNC_ACK           (MHU_SEES11_EDGE_ASYNC_ACK),
        
    .SOC_WD_IRQ                          (SOC_WD_IRQ),
    .UART_IRQ                            (UART_IRQ),
    .PPU_IRQ                             (PPU_IRQ),
    .CO_IRQ                              (CO_IRQ),
       
    .MHU2R_CIRQ    (MHU2R_CIRQ),
    .MHU2S_CIRQ    (MHU2S_CIRQ),
      .MHU3R_CIRQ    (MHU3R_CIRQ),
    .MHU3S_CIRQ    (MHU3S_CIRQ),
         
    .MHU4R_CIRQ    (MHU4R_CIRQ),
    .MHU4S_CIRQ    (MHU4S_CIRQ),
      .MHU5R_CIRQ    (MHU5R_CIRQ),
    .MHU5S_CIRQ    (MHU5S_CIRQ),
      .HOST_FWT_IRQ                        (HOST_FWT_IRQ),
    .INT_RTT_IRQ                         (INT_RTT_IRQ),
    .SWD_WS1_IRQ                         (SWD_WS1_IRQ),
    .AON_APB_ASYNC_REQ                   (AON_APB_ASYNC_REQ),
    .AON_APB_ASYNC_REQ_PAYLOAD           (AON_APB_ASYNC_REQ_PAYLOAD),
    .AON_APB_ASYNC_RESP_PAYLOAD          (AON_APB_ASYNC_RESP_PAYLOAD),
    .AON_APB_ASYNC_ACK                   (AON_APB_ASYNC_ACK),
    .SOCWD_APB_ASYNC_REQ                 (SOCWD_APB_ASYNC_REQ),
    .SOCWD_APB_ASYNC_REQ_PAYLOAD         (SOCWD_APB_ASYNC_REQ_PAYLOAD),
    .SOCWD_APB_ASYNC_RESP_PAYLOAD        (SOCWD_APB_ASYNC_RESP_PAYLOAD),
    .SOCWD_APB_ASYNC_ACK                 (SOCWD_APB_ASYNC_ACK),   
    .MHU0_QREQn                          (MHU0_QREQn),
    .MHU0_QACCEPTn                       (MHU0_QACCEPTn),
    .MHU0_QDENY                          (MHU0_QDENY),
    .MHU1_QREQn                          (MHU1_QREQn),
    .MHU1_QACCEPTn                       (MHU1_QACCEPTn),
    .MHU1_QDENY                          (MHU1_QDENY),
   
    .MHU2_QREQn    (MHU2_QREQn),
    .MHU2_QACCEPTn (MHU2_QACCEPTn),
    .MHU2_QDENY    (MHU2_QDENY),
      .MHU3_QREQn    (MHU3_QREQn),
    .MHU3_QACCEPTn (MHU3_QACCEPTn),
    .MHU3_QDENY    (MHU3_QDENY),
     
    .MHU4_QREQn    (MHU4_QREQn),
    .MHU4_QACCEPTn (MHU4_QACCEPTn),
    .MHU4_QDENY    (MHU4_QDENY),
      .MHU5_QREQn    (MHU5_QREQn),
    .MHU5_QACCEPTn (MHU5_QACCEPTn),
    .MHU5_QDENY    (MHU5_QDENY),
      .CTI_QREQn                           (CTI_QREQn),
    .CTI_QACCEPTn                        (CTI_QACCEPTn),
    .CTI_QDENY                           (CTI_QDENY),
    .CTI_QACTIVE                         (CTI_QACTIVE),    
    .CM0_QREQn                           (CM0_QREQn),
    .CM0_QACCEPTn                        (CM0_QACCEPTn),
    .CM0_QDENY                           (CM0_QDENY),
    .CM0_QACTIVE                         (CM0_QACTIVE),
    .AXIB_QREQn                          (AXIB_QREQn),
    .AXIB_QACCEPTn                       (AXIB_QACCEPTn),
    .AXIB_QDENY                          (AXIB_QDENY),
    .AXIB_QACTIVE                        (AXIB_QACTIVE),
    .SOCWD_ADB_QREQn                     (SOCWD_ADB_QREQn),
    .SOCWD_ADB_QACCEPTn                  (SOCWD_ADB_QACCEPTn),
    .SOCWD_ADB_QDENY                     (SOCWD_ADB_QDENY),
    .SOCWD_ADB_QACTIVE                   (SOCWD_ADB_QACTIVE),
    .AON_ADB_QREQn                       (AON_ADB_QREQn),
    .AON_ADB_QACCEPTn                    (AON_ADB_QACCEPTn),
    .AON_ADB_QDENY                       (AON_ADB_QDENY),
    .AON_ADB_QACTIVE                     (AON_ADB_QACTIVE),
    .SW_RST_REQ                          (SW_RST_REQ),
    .WDOG_RST_REQ                        (WDOG_RST_REQ),
    .DBGEN                               (DBGEN),
    .NIDEN                               (NIDEN),
    .CHEN                                (CHEN),
    .FIREWALL_BYPASS                     (FIREWALL_BYPASS),
    .CAAON2CA                            (CAAON2CA),
    .CA2CAAON                            (CA2CAAON),
    .CAE                                 (CAE),
    .CA_ERR_MSK                          (CA_ERR_MSK),
    .DFTRSTDISABLE                       (DFTRSTDISABLE),
    .DFTRAMHOLD                          (DFTRAMHOLD),
    .DFTCGEN                             (DFTCGEN),
    .DFTMCPHOLD                          (DFTMCPHOLD),
    .MBISTREQ                            (MBISTREQ),
    .DFTSE                               (DFTSE),
    .DFTTESTMODE                         (DFTTESTMODE)
  );

endmodule
