//------------------------------------------------------------------------------
// The confidential and proprietary information contained in this file may
// only be used by a person authorised under and to the extent permitted
// by a subsisting licensing agreement from Arm Limited or its affiliates.
//
//            (C) COPYRIGHT 2019-2021 Arm Limited or its affiliates.
//                ALL RIGHTS RESERVED
//
// This entire notice must be reproduced on all copies of this file
// and copies of this file may only be made by a person if such person is
// permitted to do so under the terms of a subsisting license agreement
// from Arm Limited or its affiliates.
//
//
//      Release Information : SSE710-r0p0-00eac0
//
//------------------------------------------------------------------------------
// Verilog-2001 (IEEE Std 1364-2001)
//------------------------------------------------------------------------------

// Configured verilog auto generated by the IP Catalog.
// The contents of this file reflect the catalog configuration. 
// Generation Date     : 2025-07-04 08:33:49.657786
// IP Catalog  Release : ip-catalog


// //////////////////////////////////////////////////////////////////////
// FIXED FOR SSE710, NOT MODIFIABLE SECTION
// //////////////////////////////////////////////////////////////////////

`ifndef INT_RTR_PARAMS
`define INT_RTR_PARAMS

`define INT_RTR_CFG \
    parameter NUM_SHD_INT = 96, \
    parameter NUM_ICI     = 4

// //////////////////////////////////////////////////////////////////////
// SSE710 CUSTOMER MODIFIABLE SECTION  
// - Configure the default values for SI{x}_IDI_DST - Starting from 32
// - Configure the default values for SI{x}_DEF_ICI - Starting from 32
// //////////////////////////////////////////////////////////////////////

`define SI_DEF_ICI_DST_FROM_32 \
    parameter SI32_ICI_DST = 4'hF, \
    parameter SI33_ICI_DST = 4'hF, \
    parameter SI34_ICI_DST = 4'hF, \
    parameter SI35_ICI_DST = 4'hF, \
    parameter SI36_ICI_DST = 4'hF, \
    parameter SI37_ICI_DST = 4'hF, \
    parameter SI38_ICI_DST = 4'hF, \
    parameter SI39_ICI_DST = 4'hF, \
    parameter SI40_ICI_DST = 4'hF, \
    parameter SI41_ICI_DST = 4'hF, \
    parameter SI42_ICI_DST = 4'hF, \
    parameter SI43_ICI_DST = 4'hF, \
    parameter SI44_ICI_DST = 4'hF, \
    parameter SI45_ICI_DST = 4'hF, \
    parameter SI46_ICI_DST = 4'hF, \
    parameter SI47_ICI_DST = 4'hF, \
    parameter SI48_ICI_DST = 4'hF, \
    parameter SI49_ICI_DST = 4'hF, \
    parameter SI50_ICI_DST = 4'hF, \
    parameter SI51_ICI_DST = 4'hF, \
    parameter SI52_ICI_DST = 4'hF, \
    parameter SI53_ICI_DST = 4'hF, \
    parameter SI54_ICI_DST = 4'hF, \
    parameter SI55_ICI_DST = 4'hF, \
    parameter SI56_ICI_DST = 4'hF, \
    parameter SI57_ICI_DST = 4'hF, \
    parameter SI58_ICI_DST = 4'hF, \
    parameter SI59_ICI_DST = 4'hF, \
    parameter SI60_ICI_DST = 4'hF, \
    parameter SI61_ICI_DST = 4'hF, \
    parameter SI62_ICI_DST = 4'hF, \
    parameter SI63_ICI_DST = 4'hF, \
    parameter SI64_ICI_DST = 4'hF, \
    parameter SI65_ICI_DST = 4'hF, \
    parameter SI66_ICI_DST = 4'hF, \
    parameter SI67_ICI_DST = 4'hF, \
    parameter SI68_ICI_DST = 4'hF, \
    parameter SI69_ICI_DST = 4'hF, \
    parameter SI70_ICI_DST = 4'hF, \
    parameter SI71_ICI_DST = 4'hF, \
    parameter SI72_ICI_DST = 4'hF, \
    parameter SI73_ICI_DST = 4'hF, \
    parameter SI74_ICI_DST = 4'hF, \
    parameter SI75_ICI_DST = 4'hF, \
    parameter SI76_ICI_DST = 4'hF, \
    parameter SI77_ICI_DST = 4'hF, \
    parameter SI78_ICI_DST = 4'hF, \
    parameter SI79_ICI_DST = 4'hF, \
    parameter SI80_ICI_DST = 4'hF, \
    parameter SI81_ICI_DST = 4'hF, \
    parameter SI82_ICI_DST = 4'hF, \
    parameter SI83_ICI_DST = 4'hF, \
    parameter SI84_ICI_DST = 4'hF, \
    parameter SI85_ICI_DST = 4'hF, \
    parameter SI86_ICI_DST = 4'hF, \
    parameter SI87_ICI_DST = 4'hF, \
    parameter SI88_ICI_DST = 4'hF, \
    parameter SI89_ICI_DST = 4'hF, \
    parameter SI90_ICI_DST = 4'hF, \
    parameter SI91_ICI_DST = 4'hF, \
    parameter SI92_ICI_DST = 4'hF, \
    parameter SI93_ICI_DST = 4'hF, \
    parameter SI94_ICI_DST = 4'hF, \
    parameter SI95_ICI_DST = 4'hF, \


`define SI_DEF_ICI_EN_FROM_32 \
    parameter SI32_DEF_ICI = 4'hF, \
    parameter SI33_DEF_ICI = 4'hF, \
    parameter SI34_DEF_ICI = 4'hF, \
    parameter SI35_DEF_ICI = 4'hF, \
    parameter SI36_DEF_ICI = 4'hF, \
    parameter SI37_DEF_ICI = 4'hF, \
    parameter SI38_DEF_ICI = 4'hF, \
    parameter SI39_DEF_ICI = 4'hF, \
    parameter SI40_DEF_ICI = 4'hF, \
    parameter SI41_DEF_ICI = 4'hF, \
    parameter SI42_DEF_ICI = 4'hF, \
    parameter SI43_DEF_ICI = 4'hF, \
    parameter SI44_DEF_ICI = 4'hF, \
    parameter SI45_DEF_ICI = 4'hF, \
    parameter SI46_DEF_ICI = 4'hF, \
    parameter SI47_DEF_ICI = 4'hF, \
    parameter SI48_DEF_ICI = 4'hF, \
    parameter SI49_DEF_ICI = 4'hF, \
    parameter SI50_DEF_ICI = 4'hF, \
    parameter SI51_DEF_ICI = 4'hF, \
    parameter SI52_DEF_ICI = 4'hF, \
    parameter SI53_DEF_ICI = 4'hF, \
    parameter SI54_DEF_ICI = 4'hF, \
    parameter SI55_DEF_ICI = 4'hF, \
    parameter SI56_DEF_ICI = 4'hF, \
    parameter SI57_DEF_ICI = 4'hF, \
    parameter SI58_DEF_ICI = 4'hF, \
    parameter SI59_DEF_ICI = 4'hF, \
    parameter SI60_DEF_ICI = 4'hF, \
    parameter SI61_DEF_ICI = 4'hF, \
    parameter SI62_DEF_ICI = 4'hF, \
    parameter SI63_DEF_ICI = 4'hF, \
    parameter SI64_DEF_ICI = 4'hF, \
    parameter SI65_DEF_ICI = 4'hF, \
    parameter SI66_DEF_ICI = 4'hF, \
    parameter SI67_DEF_ICI = 4'hF, \
    parameter SI68_DEF_ICI = 4'hF, \
    parameter SI69_DEF_ICI = 4'hF, \
    parameter SI70_DEF_ICI = 4'hF, \
    parameter SI71_DEF_ICI = 4'hF, \
    parameter SI72_DEF_ICI = 4'hF, \
    parameter SI73_DEF_ICI = 4'hF, \
    parameter SI74_DEF_ICI = 4'hF, \
    parameter SI75_DEF_ICI = 4'hF, \
    parameter SI76_DEF_ICI = 4'hF, \
    parameter SI77_DEF_ICI = 4'hF, \
    parameter SI78_DEF_ICI = 4'hF, \
    parameter SI79_DEF_ICI = 4'hF, \
    parameter SI80_DEF_ICI = 4'hF, \
    parameter SI81_DEF_ICI = 4'hF, \
    parameter SI82_DEF_ICI = 4'hF, \
    parameter SI83_DEF_ICI = 4'hF, \
    parameter SI84_DEF_ICI = 4'hF, \
    parameter SI85_DEF_ICI = 4'hF, \
    parameter SI86_DEF_ICI = 4'hF, \
    parameter SI87_DEF_ICI = 4'hF, \
    parameter SI88_DEF_ICI = 4'hF, \
    parameter SI89_DEF_ICI = 4'hF, \
    parameter SI90_DEF_ICI = 4'hF, \
    parameter SI91_DEF_ICI = 4'hF, \
    parameter SI92_DEF_ICI = 4'hF, \
    parameter SI93_DEF_ICI = 4'hF, \
    parameter SI94_DEF_ICI = 4'hF, \
    parameter SI95_DEF_ICI = 4'hF, \

// //////////////////////////////////////////////////////////////////////
// FIXED FOR SSE710, NOT MODIFIABLE SECTION 
// //////////////////////////////////////////////////////////////////////


`define ICI_DST_OVERRIDE_FROM_32 \
    .SI32_ICI_DST         (SI32_ICI_DST), \
    .SI33_ICI_DST         (SI33_ICI_DST), \
    .SI34_ICI_DST         (SI34_ICI_DST), \
    .SI35_ICI_DST         (SI35_ICI_DST), \
    .SI36_ICI_DST         (SI36_ICI_DST), \
    .SI37_ICI_DST         (SI37_ICI_DST), \
    .SI38_ICI_DST         (SI38_ICI_DST), \
    .SI39_ICI_DST         (SI39_ICI_DST), \
    .SI40_ICI_DST         (SI40_ICI_DST), \
    .SI41_ICI_DST         (SI41_ICI_DST), \
    .SI42_ICI_DST         (SI42_ICI_DST), \
    .SI43_ICI_DST         (SI43_ICI_DST), \
    .SI44_ICI_DST         (SI44_ICI_DST), \
    .SI45_ICI_DST         (SI45_ICI_DST), \
    .SI46_ICI_DST         (SI46_ICI_DST), \
    .SI47_ICI_DST         (SI47_ICI_DST), \
    .SI48_ICI_DST         (SI48_ICI_DST), \
    .SI49_ICI_DST         (SI49_ICI_DST), \
    .SI50_ICI_DST         (SI50_ICI_DST), \
    .SI51_ICI_DST         (SI51_ICI_DST), \
    .SI52_ICI_DST         (SI52_ICI_DST), \
    .SI53_ICI_DST         (SI53_ICI_DST), \
    .SI54_ICI_DST         (SI54_ICI_DST), \
    .SI55_ICI_DST         (SI55_ICI_DST), \
    .SI56_ICI_DST         (SI56_ICI_DST), \
    .SI57_ICI_DST         (SI57_ICI_DST), \
    .SI58_ICI_DST         (SI58_ICI_DST), \
    .SI59_ICI_DST         (SI59_ICI_DST), \
    .SI60_ICI_DST         (SI60_ICI_DST), \
    .SI61_ICI_DST         (SI61_ICI_DST), \
    .SI62_ICI_DST         (SI62_ICI_DST), \
    .SI63_ICI_DST         (SI63_ICI_DST), \
    .SI64_ICI_DST         (SI64_ICI_DST), \
    .SI65_ICI_DST         (SI65_ICI_DST), \
    .SI66_ICI_DST         (SI66_ICI_DST), \
    .SI67_ICI_DST         (SI67_ICI_DST), \
    .SI68_ICI_DST         (SI68_ICI_DST), \
    .SI69_ICI_DST         (SI69_ICI_DST), \
    .SI70_ICI_DST         (SI70_ICI_DST), \
    .SI71_ICI_DST         (SI71_ICI_DST), \
    .SI72_ICI_DST         (SI72_ICI_DST), \
    .SI73_ICI_DST         (SI73_ICI_DST), \
    .SI74_ICI_DST         (SI74_ICI_DST), \
    .SI75_ICI_DST         (SI75_ICI_DST), \
    .SI76_ICI_DST         (SI76_ICI_DST), \
    .SI77_ICI_DST         (SI77_ICI_DST), \
    .SI78_ICI_DST         (SI78_ICI_DST), \
    .SI79_ICI_DST         (SI79_ICI_DST), \
    .SI80_ICI_DST         (SI80_ICI_DST), \
    .SI81_ICI_DST         (SI81_ICI_DST), \
    .SI82_ICI_DST         (SI82_ICI_DST), \
    .SI83_ICI_DST         (SI83_ICI_DST), \
    .SI84_ICI_DST         (SI84_ICI_DST), \
    .SI85_ICI_DST         (SI85_ICI_DST), \
    .SI86_ICI_DST         (SI86_ICI_DST), \
    .SI87_ICI_DST         (SI87_ICI_DST), \
    .SI88_ICI_DST         (SI88_ICI_DST), \
    .SI89_ICI_DST         (SI89_ICI_DST), \
    .SI90_ICI_DST         (SI90_ICI_DST), \
    .SI91_ICI_DST         (SI91_ICI_DST), \
    .SI92_ICI_DST         (SI92_ICI_DST), \
    .SI93_ICI_DST         (SI93_ICI_DST), \
    .SI94_ICI_DST         (SI94_ICI_DST), \
    .SI95_ICI_DST         (SI95_ICI_DST), \


`define DEF_ICI_OVERRIDE_FROM_32 \
     .SI32_DEF_ICI         (SI32_DEF_ICI), \
     .SI33_DEF_ICI         (SI33_DEF_ICI), \
     .SI34_DEF_ICI         (SI34_DEF_ICI), \
     .SI35_DEF_ICI         (SI35_DEF_ICI), \
     .SI36_DEF_ICI         (SI36_DEF_ICI), \
     .SI37_DEF_ICI         (SI37_DEF_ICI), \
     .SI38_DEF_ICI         (SI38_DEF_ICI), \
     .SI39_DEF_ICI         (SI39_DEF_ICI), \
     .SI40_DEF_ICI         (SI40_DEF_ICI), \
     .SI41_DEF_ICI         (SI41_DEF_ICI), \
     .SI42_DEF_ICI         (SI42_DEF_ICI), \
     .SI43_DEF_ICI         (SI43_DEF_ICI), \
     .SI44_DEF_ICI         (SI44_DEF_ICI), \
     .SI45_DEF_ICI         (SI45_DEF_ICI), \
     .SI46_DEF_ICI         (SI46_DEF_ICI), \
     .SI47_DEF_ICI         (SI47_DEF_ICI), \
     .SI48_DEF_ICI         (SI48_DEF_ICI), \
     .SI49_DEF_ICI         (SI49_DEF_ICI), \
     .SI50_DEF_ICI         (SI50_DEF_ICI), \
     .SI51_DEF_ICI         (SI51_DEF_ICI), \
     .SI52_DEF_ICI         (SI52_DEF_ICI), \
     .SI53_DEF_ICI         (SI53_DEF_ICI), \
     .SI54_DEF_ICI         (SI54_DEF_ICI), \
     .SI55_DEF_ICI         (SI55_DEF_ICI), \
     .SI56_DEF_ICI         (SI56_DEF_ICI), \
     .SI57_DEF_ICI         (SI57_DEF_ICI), \
     .SI58_DEF_ICI         (SI58_DEF_ICI), \
     .SI59_DEF_ICI         (SI59_DEF_ICI), \
     .SI60_DEF_ICI         (SI60_DEF_ICI), \
     .SI61_DEF_ICI         (SI61_DEF_ICI), \
     .SI62_DEF_ICI         (SI62_DEF_ICI), \
     .SI63_DEF_ICI         (SI63_DEF_ICI), \
     .SI64_DEF_ICI         (SI64_DEF_ICI), \
     .SI65_DEF_ICI         (SI65_DEF_ICI), \
     .SI66_DEF_ICI         (SI66_DEF_ICI), \
     .SI67_DEF_ICI         (SI67_DEF_ICI), \
     .SI68_DEF_ICI         (SI68_DEF_ICI), \
     .SI69_DEF_ICI         (SI69_DEF_ICI), \
     .SI70_DEF_ICI         (SI70_DEF_ICI), \
     .SI71_DEF_ICI         (SI71_DEF_ICI), \
     .SI72_DEF_ICI         (SI72_DEF_ICI), \
     .SI73_DEF_ICI         (SI73_DEF_ICI), \
     .SI74_DEF_ICI         (SI74_DEF_ICI), \
     .SI75_DEF_ICI         (SI75_DEF_ICI), \
     .SI76_DEF_ICI         (SI76_DEF_ICI), \
     .SI77_DEF_ICI         (SI77_DEF_ICI), \
     .SI78_DEF_ICI         (SI78_DEF_ICI), \
     .SI79_DEF_ICI         (SI79_DEF_ICI), \
     .SI80_DEF_ICI         (SI80_DEF_ICI), \
     .SI81_DEF_ICI         (SI81_DEF_ICI), \
     .SI82_DEF_ICI         (SI82_DEF_ICI), \
     .SI83_DEF_ICI         (SI83_DEF_ICI), \
     .SI84_DEF_ICI         (SI84_DEF_ICI), \
     .SI85_DEF_ICI         (SI85_DEF_ICI), \
     .SI86_DEF_ICI         (SI86_DEF_ICI), \
     .SI87_DEF_ICI         (SI87_DEF_ICI), \
     .SI88_DEF_ICI         (SI88_DEF_ICI), \
     .SI89_DEF_ICI         (SI89_DEF_ICI), \
     .SI90_DEF_ICI         (SI90_DEF_ICI), \
     .SI91_DEF_ICI         (SI91_DEF_ICI), \
     .SI92_DEF_ICI         (SI92_DEF_ICI), \
     .SI93_DEF_ICI         (SI93_DEF_ICI), \
     .SI94_DEF_ICI         (SI94_DEF_ICI), \
     .SI95_DEF_ICI         (SI95_DEF_ICI), \



`endif
