//------------------------------------------------------------------------------
// The confidential and proprietary information contained in this file may
// only be used by a person authorised under and to the extent permitted
// by a subsisting licensing agreement from Arm Limited or its affiliates.
//
//            (C) COPYRIGHT 2019-2021 Arm Limited or its affiliates.
//                ALL RIGHTS RESERVED
//
// This entire notice must be reproduced on all copies of this file
// and copies of this file may only be made by a person if such person is
// permitted to do so under the terms of a subsisting license agreement
// from Arm Limited or its affiliates.
//
//
//      Release Information : SSE710-r0p0-00eac0
//
//------------------------------------------------------------------------------
// Verilog-2001 (IEEE Std 1364-2001)
//------------------------------------------------------------------------------

// Configured verilog auto generated by the IP Catalog.
// The contents of this file reflect the catalog configuration. 
// Generation Date     : 2025-07-04 08:33:50.319477
// IP Catalog  Release : ip-catalog


// *******************************
// REGION CONFIGURATION PARAMETERS
// *******************************
`include "firewall_f0_comp_sse710_aonperiph.vh"

///////////////////////////////////////////////////////////////////////////////
// CUSTOMER MODIFIABLE PARAMETERS
///////////////////////////////////////////////////////////////////////////////

// AON Expansion 0-15
localparam [22:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN24_BASE_ADDR = 23'h60_0000;
localparam [7:0]  FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN24_SIZE      = 8'h10; 

localparam [22:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN25_BASE_ADDR = 23'h61_0000;
localparam [7:0]  FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN25_SIZE      = 8'h10; 

localparam [22:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN26_BASE_ADDR = 23'h62_0000;
localparam [7:0]  FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN26_SIZE      = 8'h10; 

localparam [22:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN27_BASE_ADDR = 23'h63_0000;
localparam [7:0]  FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN27_SIZE      = 8'h10; 

localparam [22:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN28_BASE_ADDR = 23'h64_0000;
localparam [7:0]  FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN28_SIZE      = 8'h10; 

localparam [22:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN29_BASE_ADDR = 23'h65_0000;
localparam [7:0]  FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN29_SIZE      = 8'h10; 

localparam [22:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN30_BASE_ADDR = 23'h66_0000;
localparam [7:0]  FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN30_SIZE      = 8'h10; 

localparam [22:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN31_BASE_ADDR = 23'h67_0000;
localparam [7:0]  FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN31_SIZE      = 8'h10; 

localparam [22:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN32_BASE_ADDR = 23'h68_0000;
localparam [7:0]  FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN32_SIZE      = 8'h10; 

localparam [22:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN33_BASE_ADDR = 23'h69_0000;
localparam [7:0]  FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN33_SIZE      = 8'h10; 

localparam [22:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN34_BASE_ADDR = 23'h6A_0000;
localparam [7:0]  FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN34_SIZE      = 8'h10; 

localparam [22:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN35_BASE_ADDR = 23'h6B_0000;
localparam [7:0]  FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN35_SIZE      = 8'h10; 

localparam [22:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN36_BASE_ADDR = 23'h6C_0000;
localparam [7:0]  FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN36_SIZE      = 8'h10; 

localparam [22:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN37_BASE_ADDR = 23'h6D_0000;
localparam [7:0]  FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN37_SIZE      = 8'h10; 

localparam [22:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN38_BASE_ADDR = 23'h6E_0000;
localparam [7:0]  FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN38_SIZE      = 8'h10; 

localparam [22:0] FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN39_BASE_ADDR = 23'h6F_0000;
localparam [7:0]  FIREWALL_F0_CFG_SSE710_AONPERIPH_FC_RGN39_SIZE      = 8'h10; 

