//------------------------------------------------------------------------------
// The confidential and proprietary information contained in this file may
// only be used by a person authorised under and to the extent permitted
// by a subsisting licensing agreement from Arm Limited or its affiliates.
//
//            (C) COPYRIGHT 2019-2021 Arm Limited or its affiliates.
//                ALL RIGHTS RESERVED
//
// This entire notice must be reproduced on all copies of this file
// and copies of this file may only be made by a person if such person is
// permitted to do so under the terms of a subsisting license agreement
// from Arm Limited or its affiliates.
//
//
//      Release Information : SSE710-r0p0-00eac0
//
//------------------------------------------------------------------------------
// Verilog-2001 (IEEE Std 1364-2001)
//------------------------------------------------------------------------------

// Configured verilog auto generated by the IP Catalog.
// The contents of this file reflect the catalog configuration. 
// Generation Date     : 2025-07-04 08:33:52.167342
// IP Catalog  Release : ip-catalog


`include "firewall_f0_global_masterid_sse710.vh"
localparam [31:0] FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID1_VAL = 32'hec00ec00;
 
localparam [31:0] FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID5_VAL = 32'hdeaddead; 
 
localparam [31:0] FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID6_VAL = 32'hdeaddead; 

// ********************************************************************
// CUSTOMER MODIFIABLE PARAMETERS
// ********************************************************************

 
localparam  [7:0] FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID7_VAL = 8'd32; 
localparam [31:0] FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID7_VAL = 32'hA5A5_A5A5; 
 
localparam  [7:0] FIREWALL_F0_CFG_GLOBAL_SSE710_FC_MST_ID8_VAL = 8'd33; 
localparam [31:0] FIREWALL_F0_CFG_GLOBAL_SSE710_ERR_RESP_PER_MST_ID8_VAL = 32'hA5A5_A5A5; 
