<?php $cfg = json_decode(file_get_contents($argv[1]), true);
$NUM_EXT_SYS = $cfg['NUM_EXT_SYS'];
$ID_WIDTH    = $cfg['ID_WIDTH'];
?>
<periph>
    <product_version_info major_group="bu" major_revision="1" major_version="00" minor_code="50000" minor_revision="2" minor_version="0" part_quality="rel" product_code="nic400" />
    <validator_version_info major_revision="23" minor_revision="2" />
    <global>
        <address0x0>top</address0x0>
        <aruser_width>10</aruser_width>
        <awuser_width>10</awuser_width>
        <buser_width>0</buser_width>
        <cc_type>sync</cc_type>
        <default_protocol>axi4</default_protocol>
        <dpe_glb_enable>false</dpe_glb_enable>
        <dpe_status>false</dpe_status>
        <dpe_width>5</dpe_width>
        <gen_caps>true</gen_caps>
        <hcg_en>true</hcg_en>
        <license_status>licensed</license_status>
        <periph_id3>0</periph_id3>
        <pl_id_width><?php echo $ID_WIDTH?></pl_id_width>
        <qos_status>false</qos_status>
        <rsb_arch_central_ring>true</rsb_arch_central_ring>
        <ruser_width>0</ruser_width>
        <sas_visible>false</sas_visible>
        <start_iid>0</start_iid>
        <taxonomy>masterslave</taxonomy>
        <thin_links_status>false</thin_links_status>
        <uppercase_ext_sig>false</uppercase_ext_sig>
        <virtual_networks />
        <virtual_networks_status>false</virtual_networks_status>
        <wuser_width>0</wuser_width>
    </global>
    <clocks>
        <domain freq="100">main</domain>
        <domain freq="100">a</domain>
    </clocks>
    <asib>
        <address_ranges>
            <name>default_map</name>
            <range>
                <addr_max>0x1A01FFFF</addr_max>
                <addr_min>0x1A000000</addr_min>
                <remap>
                    <bit>default</bit>
                    <present>true</present>
                    <region>0</region>
                    <target>sysctrl_apb</target>
                </remap>
            </range>
            <range>
                <addr_max>0x1A20FFFF</addr_max>
                <addr_min>0x1A200000</addr_min>
                <remap>
                    <bit>default</bit>
                    <present>true</present>
                    <region>0</region>
                    <target>sysctrl_apb</target>
                </remap>
            </range>
            <range>
                <addr_max>0x1A31FFFF</addr_max>
                <addr_min>0x1A300000</addr_min>
                <remap>
                    <bit>default</bit>
                    <present>true</present>
                    <region>0</region>
                    <target>sysctrl_apb</target>
                </remap>
            </range>
            <range>
                <addr_max>0x1A04FFFF</addr_max>
                <addr_min>0x1A020000</addr_min>
                <remap>
                    <bit>default</bit>
                    <present>true</present>
                    <region>0</region>
                    <target>sysctrl_apb</target>
                </remap>
            </range>
            <range>
                <addr_max>0x1A26FFFF</addr_max>
                <addr_min>0x1A210000</addr_min>
                <remap>
                    <bit>default</bit>
                    <present>true</present>
                    <region>0</region>
                    <target>sysctrl_apb</target>
                </remap>
            </range>
            <range>
                <addr_max>0x1A33FFFF</addr_max>
                <addr_min>0x1A320000</addr_min>
                <remap>
                    <bit>default</bit>
                    <present>true</present>
                    <region>0</region>
                    <target>sysctrl_apb</target>
                </remap>
            </range>
            <range>
                <addr_max>0x1A40FFFF</addr_max>
                <addr_min>0x1A400000</addr_min>
                <remap>
                    <bit>default</bit>
                    <present>true</present>
                    <region>0</region>
                    <target>sysctrl_apb</target>
                </remap>
            </range>
            <range>
                <addr_max>0x1A44FFFF</addr_max>
                <addr_min>0x1A410000</addr_min>
                <remap>
                    <bit>default</bit>
                    <present>true</present>
                    <region>0</region>
                    <target>sysctrl_apb</target>
                </remap>
            </range>
            <range>
                <addr_max>0x1A50FFFF</addr_max>
                <addr_min>0x1A500000</addr_min>
                <remap>
                    <bit>default</bit>
                    <present>true</present>
                    <region>0</region>
                    <target>sysctrl_apb</target>
                </remap>
            </range>
            <range>
                <addr_max>0x1A6FFFFF</addr_max>
                <addr_min>0x1A600000</addr_min>
                <remap>
                    <bit>default</bit>
                    <present>true</present>
                    <region>0</region>
                    <target>sysctrl_apb</target>
                </remap>
            </range>
            <range>
                <addr_max>0x1A510FFF</addr_max>
                <addr_min>0x1A510000</addr_min>
                <remap>
                    <bit>default</bit>
                    <present>true</present>
                    <region>0</region>
                    <target>uart_apb</target>
                </remap>
            </range>
            <range>
                <addr_max>0x1A520FFF</addr_max>
                <addr_min>0x1A520000</addr_min>
                <remap>
                    <bit>default</bit>
                    <present>true</present>
                    <region>0</region>
                    <target>uart_apb</target>
                </remap>
            </range>
        </address_ranges>
        <apb_config>false</apb_config>
        <apb_slave_no>2</apb_slave_no>
        <cds>slaveperid</cds>
        <clock_boundary>none</clock_boundary>
        <clock_domain_name_master_if>a</clock_domain_name_master_if>
        <clock_domain_name_slave_if>a</clock_domain_name_slave_if>
        <master_if_data_width>32</master_if_data_width>
        <multi_ported>false</multi_ported>
        <multi_region>false</multi_region>
        <name>sysctrl_axis</name>
        <protocol>axi4</protocol>
        <qos_config>
            <hard>disable</hard>
            <lqv>disable</lqv>
            <pot>disable</pot>
        </qos_config>
        <qv>
            <type>input</type>
            <value>0</value>
        </qv>
        <reg>
            <impl>present</impl>
            <location>slave_port</location>
            <name>aw</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>present</impl>
            <location>slave_port</location>
            <name>ar</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>present</impl>
            <location>slave_port</location>
            <name>w</name>
            <type>full</type>
        </reg>
        <reg>
            <depth>6</depth>
            <impl>present</impl>
            <location>boundary</location>
            <name>aw</name>
            <type>fifo</type>
        </reg>
        <reg>
            <depth>4</depth>
            <impl>present</impl>
            <location>boundary</location>
            <name>ar</name>
            <type>fifo</type>
        </reg>
        <reg>
            <depth>4</depth>
            <impl>present</impl>
            <location>boundary</location>
            <name>r</name>
            <type>fifo</type>
        </reg>
        <reg>
            <depth>6</depth>
            <impl>present</impl>
            <location>boundary</location>
            <name>w</name>
            <type>fifo</type>
        </reg>
        <reg>
            <depth>6</depth>
            <impl>present</impl>
            <location>boundary</location>
            <name>b</name>
            <type>fifo</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>master_port</location>
            <name>aw</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>master_port</location>
            <name>ar</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>master_port</location>
            <name>r</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>master_port</location>
            <name>w</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>master_port</location>
            <name>b</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>present</impl>
            <location>slave_port</location>
            <name>r</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>present</impl>
            <location>slave_port</location>
            <name>b</name>
            <type>full</type>
        </reg>
        <slave_if_addr_width>32</slave_if_addr_width>
        <slave_if_data_width>32</slave_if_data_width>
        <tide>0</tide>
        <token_prerequest>false</token_prerequest>
        <token_prerequest_bridge>false</token_prerequest_bridge>
        <trustzone>input</trustzone>
        <vid_width><?php echo $ID_WIDTH?></vid_width>
        <vn_external>none</vn_external>
        <vn_external_bridge>none</vn_external_bridge>
        <x>110</x>
        <y>130</y>
        <master_if_port_name>sysctrl_axis_m</master_if_port_name>
        <slave_if_port_name>sysctrl_axis_s</slave_if_port_name>
    </asib>
    <amib>
        <apb_config>false</apb_config>
        <apb_port>
            <clock_domain>a</clock_domain>
            <name>sysctrl_apb</name>
            <trustzone>nsec</trustzone>
            <x>902</x>
            <y>168</y>
        </apb_port>
        <apb_slave_no>65</apb_slave_no>
        <clock_boundary>none</clock_boundary>
        <clock_domain_name_master_if>a</clock_domain_name_master_if>
        <clock_domain_name_slave_if>a</clock_domain_name_slave_if>
        <compress_id>false</compress_id>
        <dest_type>peripheral</dest_type>
        <master_if_addr_width>32</master_if_addr_width>
        <master_if_data_width>32</master_if_data_width>
        <multi_ported>false</multi_ported>
        <multi_region>false</multi_region>
        <name>slave_5</name>
        <protocol>apb</protocol>
        <qv_out>false</qv_out>
        <reg>
            <impl>present</impl>
            <location>master_port</location>
            <name>w</name>
            <type>rev</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>slave_port</location>
            <name>aw</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>slave_port</location>
            <name>ar</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>slave_port</location>
            <name>r</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>slave_port</location>
            <name>w</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>slave_port</location>
            <name>b</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>master_port</location>
            <name>a</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>master_port</location>
            <name>d</name>
            <type>full</type>
        </reg>
        <reg>
            <depth>2</depth>
            <impl>absent</impl>
            <location>boundary</location>
            <name>a</name>
            <type>fifo</type>
        </reg>
        <reg>
            <depth>2</depth>
            <impl>absent</impl>
            <location>boundary</location>
            <name>d</name>
            <type>fifo</type>
        </reg>
        <reg>
            <depth>2</depth>
            <impl>absent</impl>
            <location>boundary</location>
            <name>w</name>
            <type>fifo</type>
        </reg>
        <slave_if_data_width>32</slave_if_data_width>
        <token_prerequest>false</token_prerequest>
        <token_prerequest_bridge>false</token_prerequest_bridge>
        <trustzone>nsec</trustzone>
        <vn_external>none</vn_external>
        <vn_external_bridge>none</vn_external_bridge>
        <x>890</x>
        <y>130</y>
        <master_if_port_name>sysctrl_apb</master_if_port_name>
        <slave_if_port_name>slave_5_s</slave_if_port_name>
    </amib>
    <amib>
        <apb_config>false</apb_config>
        <apb_port>
            <clock_domain>a</clock_domain>
            <name>uart_apb</name>
            <trustzone>nsec</trustzone>
            <x>902</x>
            <y>80</y>
        </apb_port>
        <apb_slave_no>64</apb_slave_no>
        <clock_boundary>none</clock_boundary>
        <clock_domain_name_master_if>a</clock_domain_name_master_if>
        <clock_domain_name_slave_if>a</clock_domain_name_slave_if>
        <compress_id>false</compress_id>
        <dest_type>peripheral</dest_type>
        <master_if_addr_width>32</master_if_addr_width>
        <master_if_data_width>32</master_if_data_width>
        <multi_ported>false</multi_ported>
        <multi_region>false</multi_region>
        <name>slave_2</name>
        <protocol>apb</protocol>
        <qv_out>false</qv_out>
        <reg>
            <impl>present</impl>
            <location>master_port</location>
            <name>w</name>
            <type>rev</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>slave_port</location>
            <name>aw</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>slave_port</location>
            <name>ar</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>slave_port</location>
            <name>r</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>slave_port</location>
            <name>w</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>slave_port</location>
            <name>b</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>master_port</location>
            <name>a</name>
            <type>full</type>
        </reg>
        <reg>
            <impl>absent</impl>
            <location>master_port</location>
            <name>d</name>
            <type>full</type>
        </reg>
        <reg>
            <depth>2</depth>
            <impl>absent</impl>
            <location>boundary</location>
            <name>a</name>
            <type>fifo</type>
        </reg>
        <reg>
            <depth>2</depth>
            <impl>absent</impl>
            <location>boundary</location>
            <name>d</name>
            <type>fifo</type>
        </reg>
        <reg>
            <depth>2</depth>
            <impl>absent</impl>
            <location>boundary</location>
            <name>w</name>
            <type>fifo</type>
        </reg>
        <slave_if_data_width>32</slave_if_data_width>
        <token_prerequest>false</token_prerequest>
        <token_prerequest_bridge>false</token_prerequest_bridge>
        <trustzone>nsec</trustzone>
        <vn_external>none</vn_external>
        <vn_external_bridge>none</vn_external_bridge>
        <x>890</x>
        <y>80</y>
        <master_if_port_name>uart_apb</master_if_port_name>
        <slave_if_port_name>slave_2_s</slave_if_port_name>
    </amib>
    <inter>
        <clock_domain>a</clock_domain>
        <data_width>32</data_width>
        <expanded>true</expanded>
        <height>237</height>
        <impl>singlelayer</impl>
        <master_if>
            <name>axi_m_0</name>
            <post_arb_reg>absent</post_arb_reg>
            <x>528</x>
            <y>130</y>
        </master_if>
        <master_if>
            <name>axi_m_2</name>
            <post_arb_reg>absent</post_arb_reg>
            <x>528</x>
            <y>80</y>
        </master_if>
        <master_if>
            <name>axi_m_1</name>
            <post_arb_reg>absent</post_arb_reg>
            <x>528</x>
            <y>102</y>
        </master_if>
        <name>switch1</name>
        <protocol>axi4</protocol>
        <slave_if>
            <name>axi_s_0</name>
            <x>332</x>
            <y>120</y>
        </slave_if>
        <sparse>
            <cds>slaveperid</cds>
            <sas>false</sas>
            <slave_if_port>axi_s_0</slave_if_port>
            <master_if_port>
                <name>axi_m_2</name>
                <reg>
                    <impl>absent</impl>
                    <name>aw</name>
                    <type>full</type>
                </reg>
                <reg>
                    <impl>absent</impl>
                    <name>ar</name>
                    <type>full</type>
                </reg>
                <reg>
                    <impl>absent</impl>
                    <name>r</name>
                    <type>full</type>
                </reg>
                <reg>
                    <impl>absent</impl>
                    <name>w</name>
                    <type>full</type>
                </reg>
                <reg>
                    <impl>absent</impl>
                    <name>b</name>
                    <type>full</type>
                </reg>
            </master_if_port>
            <master_if_port>
                <name>axi_m_0</name>
                <reg>
                    <impl>absent</impl>
                    <name>aw</name>
                    <type>full</type>
                </reg>
                <reg>
                    <impl>absent</impl>
                    <name>ar</name>
                    <type>full</type>
                </reg>
                <reg>
                    <impl>absent</impl>
                    <name>r</name>
                    <type>full</type>
                </reg>
                <reg>
                    <impl>absent</impl>
                    <name>w</name>
                    <type>full</type>
                </reg>
                <reg>
                    <impl>absent</impl>
                    <name>b</name>
                    <type>full</type>
                </reg>
            </master_if_port>
            <master_if_port>
                <name>axi_m_1</name>
                <reg>
                    <impl>absent</impl>
                    <name>aw</name>
                    <type>full</type>
                </reg>
                <reg>
                    <impl>absent</impl>
                    <name>ar</name>
                    <type>full</type>
                </reg>
                <reg>
                    <impl>absent</impl>
                    <name>r</name>
                    <type>full</type>
                </reg>
                <reg>
                    <impl>absent</impl>
                    <name>w</name>
                    <type>full</type>
                </reg>
                <reg>
                    <impl>absent</impl>
                    <name>b</name>
                    <type>full</type>
                </reg>
            </master_if_port>
        </sparse>
        <type>busmatrix</type>
        <width>197</width>
        <x>430</x>
        <y>140</y>
        <master_if_port_name>axi_m_0,axi_m_2,axi_m_1</master_if_port_name>
        <slave_if_port_name>axi_s_0</slave_if_port_name>
    </inter>
    <inter>
        <name>ds_0</name>
        <slave_if>
            <name>axi_s_0</name>
            <x>544</x>
            <y>102</y>
        </slave_if>
        <type>default_slave</type>
        <x>558</x>
        <y>102</y>
        <master_if_port_name />
        <slave_if_port_name>axi_s_0</slave_if_port_name>
    </inter>
    <connect>
        <dest>slave_5</dest>
        <dest_port>slave_5_s</dest_port>
        <lock>false</lock>
        <out_reads>1</out_reads>
        <out_trans>2</out_trans>
        <out_writes>1</out_writes>
        <protocol>axi4</protocol>
        <src>switch1</src>
        <src_port>axi_m_0</src_port>
    </connect>
    <connect>
        <dest>slave_2</dest>
        <dest_port>slave_2_s</dest_port>
        <lock>false</lock>
        <out_reads>1</out_reads>
        <out_trans>2</out_trans>
        <out_writes>1</out_writes>
        <protocol>axi4</protocol>
        <src>switch1</src>
        <src_port>axi_m_2</src_port>
    </connect>
    <connect>
        <dest>switch1</dest>
        <dest_port>axi_s_0</dest_port>
        <lock>false</lock>
        <out_reads def="true">4</out_reads>
        <out_trans>10</out_trans>
        <out_writes def="true">6</out_writes>
        <protocol>axi4</protocol>
        <src>sysctrl_axis</src>
        <src_port>sysctrl_axis_m</src_port>
    </connect>
    <connect>
        <dest>ds_0</dest>
        <dest_port>axi_s_0</dest_port>
        <lock>false</lock>
        <out_reads>1</out_reads>
        <out_trans>2</out_trans>
        <out_writes>1</out_writes>
        <protocol>axi4</protocol>
        <src>switch1</src>
        <src_port>axi_m_1</src_port>
    </connect>
    <connect>
        <aruser>true</aruser>
        <awuser>true</awuser>
        <buser>false</buser>
        <dest>sysctrl_axis</dest>
        <dest_port>sysctrl_axis_s</dest_port>
        <lock>false</lock>
        <out_reads>4</out_reads>
        <out_trans>10</out_trans>
        <out_writes>6</out_writes>
        <protocol>axi4</protocol>
        <ruser>false</ruser>
        <src>external</src>
        <src_port>sysctrl_axis</src_port>
        <wuser>false</wuser>
    </connect>
    <connect>
        <aruser>false</aruser>
        <awuser>false</awuser>
        <buser>false</buser>
        <dest>external</dest>
        <dest_port>sysctrl_apb</dest_port>
        <lock>false</lock>
        <out_reads>1</out_reads>
        <out_trans>1</out_trans>
        <out_writes>1</out_writes>
        <protocol>apb4</protocol>
        <ruser>false</ruser>
        <src>slave_5</src>
        <src_port>sysctrl_apb</src_port>
        <wuser>false</wuser>
    </connect>
    <connect>
        <aruser>false</aruser>
        <awuser>false</awuser>
        <buser>false</buser>
        <dest>external</dest>
        <dest_port>uart_apb</dest_port>
        <lock>false</lock>
        <out_reads>1</out_reads>
        <out_trans>1</out_trans>
        <out_writes>1</out_writes>
        <protocol>apb4</protocol>
        <ruser>false</ruser>
        <src>slave_2</src>
        <src_port>uart_apb</src_port>
        <wuser>false</wuser>
    </connect>
    <architecture>
        <link>
            <slave_if>
                <name>sysctrl_axis</name>
                <master_if>slave_5</master_if>
                <master_if>sysctrl_apb<parent>slave_5</parent>
                </master_if>
                <master_if>uart_apb<parent>slave_2</parent>
                </master_if>
                <master_if>slave_2</master_if>
            </slave_if>
        </link>
    </architecture>
</periph>
