//----------------------------------------------------------------------------
//   The confidential and proprietary information contained in this file may
//   only be used by a person authorised under and to the extent permitted
//   by a subsisting licensing agreement from Arm Limited or its affiliates.
//
//          (C) COPYRIGHT 2016-2017 Arm Limited or its affiliates.
//              ALL RIGHTS RESERVED
//
//   This entire notice must be reproduced on all copies of this file
//   and copies of this file may only be made by a person if such person is
//   permitted to do so under the terms of a subsisting license agreement
//   from Arm Limited or its affiliates.
//----------------------------------------------------------------------------
//   Release information : TM200-MN-22110-r4p1-00rel0
//
//----------------------------------------------------------------------------
//   Description :
//   Parameters for css600_apbic
//
//----------------------------------------------------------------------------


  FF_SYNC_DEPTH          = 2,
  NUM_APB_SLAVES         = 1,
  APB_SLAVE_ADDR_WIDTH   = 13,
  NUM_APB_MASTERS        = 64,
  NUM_EXPANDERS          = 1,

  M0_BASE_ADDR           = 0,
  M0_ADDR_WIDTH          = 12,
  M0_GROUP               = 0,
  M1_BASE_ADDR           = 0,
  M1_ADDR_WIDTH          = 12,
  M1_GROUP               = 0,
  M2_BASE_ADDR           = 0,
  M2_ADDR_WIDTH          = 12,
  M2_GROUP               = 0,
  M3_BASE_ADDR           = 0,
  M3_ADDR_WIDTH          = 12,
  M3_GROUP               = 0,
  M4_BASE_ADDR           = 0,
  M4_ADDR_WIDTH          = 12,
  M4_GROUP               = 0,
  M5_BASE_ADDR           = 0,
  M5_ADDR_WIDTH          = 12,
  M5_GROUP               = 0,
  M6_BASE_ADDR           = 0,
  M6_ADDR_WIDTH          = 12,
  M6_GROUP               = 0,
  M7_BASE_ADDR           = 0,
  M7_ADDR_WIDTH          = 12,
  M7_GROUP               = 0,
  M8_BASE_ADDR           = 0,
  M8_ADDR_WIDTH          = 12,
  M8_GROUP               = 0,
  M9_BASE_ADDR           = 0,
  M9_ADDR_WIDTH          = 12,
  M9_GROUP               = 0,
  M10_BASE_ADDR          = 0,
  M10_ADDR_WIDTH         = 12,
  M10_GROUP              = 0,
  M11_BASE_ADDR          = 0,
  M11_ADDR_WIDTH         = 12,
  M11_GROUP              = 0,
  M12_BASE_ADDR          = 0,
  M12_ADDR_WIDTH         = 12,
  M12_GROUP              = 0,
  M13_BASE_ADDR          = 0,
  M13_ADDR_WIDTH         = 12,
  M13_GROUP              = 0,
  M14_BASE_ADDR          = 0,
  M14_ADDR_WIDTH         = 12,
  M14_GROUP              = 0,
  M15_BASE_ADDR          = 0,
  M15_ADDR_WIDTH         = 12,
  M15_GROUP              = 0,
  M16_BASE_ADDR          = 0,
  M16_ADDR_WIDTH         = 12,
  M16_GROUP              = 0,
  M17_BASE_ADDR          = 0,
  M17_ADDR_WIDTH         = 12,
  M17_GROUP              = 0,
  M18_BASE_ADDR          = 0,
  M18_ADDR_WIDTH         = 12,
  M18_GROUP              = 0,
  M19_BASE_ADDR          = 0,
  M19_ADDR_WIDTH         = 12,
  M19_GROUP              = 0,
  M20_BASE_ADDR          = 0,
  M20_ADDR_WIDTH         = 12,
  M20_GROUP              = 0,
  M21_BASE_ADDR          = 0,
  M21_ADDR_WIDTH         = 12,
  M21_GROUP              = 0,
  M22_BASE_ADDR          = 0,
  M22_ADDR_WIDTH         = 12,
  M22_GROUP              = 0,
  M23_BASE_ADDR          = 0,
  M23_ADDR_WIDTH         = 12,
  M23_GROUP              = 0,
  M24_BASE_ADDR          = 0,
  M24_ADDR_WIDTH         = 12,
  M24_GROUP              = 0,
  M25_BASE_ADDR          = 0,
  M25_ADDR_WIDTH         = 12,
  M25_GROUP              = 0,
  M26_BASE_ADDR          = 0,
  M26_ADDR_WIDTH         = 12,
  M26_GROUP              = 0,
  M27_BASE_ADDR          = 0,
  M27_ADDR_WIDTH         = 12,
  M27_GROUP              = 0,
  M28_BASE_ADDR          = 0,
  M28_ADDR_WIDTH         = 12,
  M28_GROUP              = 0,
  M29_BASE_ADDR          = 0,
  M29_ADDR_WIDTH         = 12,
  M29_GROUP              = 0,
  M30_BASE_ADDR          = 0,
  M30_ADDR_WIDTH         = 12,
  M30_GROUP              = 0,
  M31_BASE_ADDR          = 0,
  M31_ADDR_WIDTH         = 12,
  M31_GROUP              = 0,
  M32_BASE_ADDR          = 0,
  M32_ADDR_WIDTH         = 12,
  M32_GROUP              = 0,
  M33_BASE_ADDR          = 0,
  M33_ADDR_WIDTH         = 12,
  M33_GROUP              = 0,
  M34_BASE_ADDR          = 0,
  M34_ADDR_WIDTH         = 12,
  M34_GROUP              = 0,
  M35_BASE_ADDR          = 0,
  M35_ADDR_WIDTH         = 12,
  M35_GROUP              = 0,
  M36_BASE_ADDR          = 0,
  M36_ADDR_WIDTH         = 12,
  M36_GROUP              = 0,
  M37_BASE_ADDR          = 0,
  M37_ADDR_WIDTH         = 12,
  M37_GROUP              = 0,
  M38_BASE_ADDR          = 0,
  M38_ADDR_WIDTH         = 12,
  M38_GROUP              = 0,
  M39_BASE_ADDR          = 0,
  M39_ADDR_WIDTH         = 12,
  M39_GROUP              = 0,
  M40_BASE_ADDR          = 0,
  M40_ADDR_WIDTH         = 12,
  M40_GROUP              = 0,
  M41_BASE_ADDR          = 0,
  M41_ADDR_WIDTH         = 12,
  M41_GROUP              = 0,
  M42_BASE_ADDR          = 0,
  M42_ADDR_WIDTH         = 12,
  M42_GROUP              = 0,
  M43_BASE_ADDR          = 0,
  M43_ADDR_WIDTH         = 12,
  M43_GROUP              = 0,
  M44_BASE_ADDR          = 0,
  M44_ADDR_WIDTH         = 12,
  M44_GROUP              = 0,
  M45_BASE_ADDR          = 0,
  M45_ADDR_WIDTH         = 12,
  M45_GROUP              = 0,
  M46_BASE_ADDR          = 0,
  M46_ADDR_WIDTH         = 12,
  M46_GROUP              = 0,
  M47_BASE_ADDR          = 0,
  M47_ADDR_WIDTH         = 12,
  M47_GROUP              = 0,
  M48_BASE_ADDR          = 0,
  M48_ADDR_WIDTH         = 12,
  M48_GROUP              = 0,
  M49_BASE_ADDR          = 0,
  M49_ADDR_WIDTH         = 12,
  M49_GROUP              = 0,
  M50_BASE_ADDR          = 0,
  M50_ADDR_WIDTH         = 12,
  M50_GROUP              = 0,
  M51_BASE_ADDR          = 0,
  M51_ADDR_WIDTH         = 12,
  M51_GROUP              = 0,
  M52_BASE_ADDR          = 0,
  M52_ADDR_WIDTH         = 12,
  M52_GROUP              = 0,
  M53_BASE_ADDR          = 0,
  M53_ADDR_WIDTH         = 12,
  M53_GROUP              = 0,
  M54_BASE_ADDR          = 0,
  M54_ADDR_WIDTH         = 12,
  M54_GROUP              = 0,
  M55_BASE_ADDR          = 0,
  M55_ADDR_WIDTH         = 12,
  M55_GROUP              = 0,
  M56_BASE_ADDR          = 0,
  M56_ADDR_WIDTH         = 12,
  M56_GROUP              = 0,
  M57_BASE_ADDR          = 0,
  M57_ADDR_WIDTH         = 12,
  M57_GROUP              = 0,
  M58_BASE_ADDR          = 0,
  M58_ADDR_WIDTH         = 12,
  M58_GROUP              = 0,
  M59_BASE_ADDR          = 0,
  M59_ADDR_WIDTH         = 12,
  M59_GROUP              = 0,
  M60_BASE_ADDR          = 0,
  M60_ADDR_WIDTH         = 12,
  M60_GROUP              = 0,
  M61_BASE_ADDR          = 0,
  M61_ADDR_WIDTH         = 12,
  M61_GROUP              = 0,
  M62_BASE_ADDR          = 0,
  M62_ADDR_WIDTH         = 12,
  M62_GROUP              = 0,
  M63_BASE_ADDR          = 0,
  M63_ADDR_WIDTH         = 12,
  M63_GROUP              = 0
